---
permalink: a1k/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff a1k, pre-shutdown checks for onboard encryption keys 
summary: Prima di spegnere il controller compromesso e controllare lo stato delle chiavi di crittografia integrate, è necessario controllare lo stato del controller compromesso, disattivare il giveback automatico e verificare la versione di ONTAP in esecuzione nel sistema. 
---
= Controllare le chiavi di crittografia integrate - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di spegnere il controller compromesso e controllare lo stato delle chiavi di crittografia integrate, è necessario controllare lo stato del controller compromesso, disattivare il giveback automatico e verificare la versione di ONTAP in esecuzione.

Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].



== Controllare NVE o NSE nei sistemi che eseguono ONTAP 9.15 e versioni successive

Prima di arrestare il controller danneggiato, è necessario verificare se il sistema ha attivato il gestore delle chiavi di sicurezza o dischi crittografati.



== Verificare la configurazione del gestore delle chiavi di protezione

.Fasi
. Determe se Key Manager è attivo con il comando _Security key-manager keystore show_. Per ulteriori informazioni, consultare la https://docs.netapp.com/us-en/ontap-cli/security-key-manager-keystore-show.html["Security key-manager keystore mostra pagina MAN"^]
+

NOTE: È possibile che si disponga di altri tipi di gestore delle chiavi. I tipi sono `KMIP`, , `AKV`e `GCP`. Il processo di conferma di questi tipi è lo stesso dei tipi di gestore delle chiavi o di conferma `external` `onboard` .

+
** Se non viene visualizzata alcuna uscita, andare a link:bootmedia-shutdown.html["spegnere il controller danneggiato"] per arrestare il nodo danneggiato.
** Se il comando visualizza output, il sistema è `security key-manager` attivo ed è necessario visualizzare il tipo e lo `Key Manager` stato.


. Visualizzare le informazioni per l'attivo `Key Manager` utilizzando il comando _Security key-manager key query_.
+
** Se `Key Manager` viene visualizzato il tipo `external` e la `Restored` colonna visualizza `true`, è possibile spegnere il controller danneggiato in tutta sicurezza.
** Se viene visualizzato il `Key Manager` tipo `onboard` e la `Restored` colonna viene visualizzata `true`, è necessario completare alcuni passaggi aggiuntivi.
** Se il `Key Manager` tipo viene visualizzato `external` e la `Restored` colonna visualizza qualcosa di diverso da `true`, è necessario completare alcuni passaggi aggiuntivi.
** Se il `Key Manager` tipo viene visualizzato `onboard` e la `Restored` colonna visualizza qualcosa di diverso da `true`, è necessario completare alcuni passaggi aggiuntivi.


. Se viene visualizzato il `Key Manager` tipo `onboard` e viene visualizzata la `Restored` colonna `true`, eseguire manualmente il backup delle informazioni OKM:
+
.. Immettere `y` quando viene richiesto di continuare: `set -priv advanced`
.. Immettere il comando per visualizzare le informazioni sulla gestione delle chiavi: _Security key-manager onboard show-backup_
.. Copiare il contenuto delle informazioni di backup in un file separato o nel file di log. Sarà necessario in situazioni di emergenza in cui potrebbe essere necessario ripristinare manualmente OKM.
.. È possibile arrestare il controller danneggiato in modo sicuro.


. Se il `Key Manager` tipo viene visualizzato `onboard` e la `Restored` colonna visualizza qualcosa di diverso da `true`:
+
.. Immettere il comando di sincronizzazione del gestore delle chiavi di sicurezza integrato: _Security key-manager onboard Sync_
+

NOTE: Immettere la passphrase di gestione della chiave integrata alfanumerica di 32 caratteri al prompt. Se non è possibile fornire la passphrase, contattare l'assistenza NetApp. http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. Verificare che venga visualizzata la `Restored` colonna `true` per tutte le chiavi di autenticazione: `security key-manager key query`
.. Verificare che il `Key Manager` tipo sia visualizzato `onboard`, quindi eseguire manualmente il backup delle informazioni OKM.
.. Immettere il comando per visualizzare le informazioni di backup della gestione delle chiavi: _Security key-manager onboard show-backup_
.. Copiare il contenuto delle informazioni di backup in un file separato o nel file di log. Sarà necessario in situazioni di emergenza in cui potrebbe essere necessario ripristinare manualmente OKM.
.. È possibile spegnere il controller in modo sicuro.


. Se il `Key Manager` tipo viene visualizzato `external` e la `Restored` colonna visualizza qualcosa di diverso da `true`:
+
.. Ripristinare le chiavi di autenticazione per la gestione delle chiavi esterne in tutti i nodi del cluster: `security key-manager external restore`
+
Se il comando non riesce, contattare l'assistenza NetApp all'indirizzo http://mysupport.netapp.com/["mysupport.netapp.com"^].

.. Verificare che venga visualizzata la `Restored` colonna `true` per tutte le chiavi di autenticazione: _Security key-manager key query_
.. È possibile arrestare il controller danneggiato in modo sicuro.



