---
permalink: a1k/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a1k,  verify and set HA state, complete the replacement process 
summary: Riavviare il controller, verificare lo stato del sistema e restituire la parte guasta a NetApp per completare il passaggio finale della procedura di sostituzione dello chassis AFF A1K . 
---
= Completa la sostituzione dello chassis per un sistema AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Riavvia il controller, verifica lo stato del sistema e restituisci il componente guasto a NetApp per completare la fase finale della sostituzione dello chassis del tuo sistema AFF A1K.



[[step-1-boot-the-controllers-and-verify-system-health]]
== Passaggio 1: avviare i controller e verificare lo stato del sistema

Dopo il riavvio dei controller, avvia ONTAP, restituisci i controller e verifica lo stato del sistema.

.Fasi
. Controllare l'output della console:
+
.. Se il controller viene avviato al prompt Loader, riavviarlo con il `boot_ontap` comando.
.. Se la console viene visualizzata `waiting for giveback` dopo il riavvio, accedere al controller partner e verificare che il controller sostituito sia pronto per il giveback con il `storage failover show` comando.


. Eseguire lo sconto:
+
.. Collegare il cavo della console al controller partner.
.. Riportare la centralina guasta al normale funzionamento restituendo la memoria: `storage failover giveback -ofnode _impaired_node_name_`
.. Se la restituzione automatica è stata disabilitata, riabilitarla: `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`
.. Se AutoSupport è attivato, ripristinare/riattivare la creazione automatica dei casi: `system node autosupport invoke -node * -type all -message MAINT=END`


. Dopo aver completato la restituzione, esegui https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] per verificare lo stato del sistema di archiviazione e correggere eventuali problemi riscontrati.




[[step-2-return-the-failed-part-to-netapp]]
== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
