---
sidebar: sidebar 
permalink: a1k/install-requirements.html 
keywords: a1k, install, setup, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per la piattaforma e i ripiani.' 
---
= Requisiti di installazione - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esaminare l'attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage AFF A1K e gli shelf di storage.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Graffetta o penna a sfera con punta stretta per l'impostazione di NS224 ID scaffali
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi e gli shelf di storage sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Peso del sistema di storage

Prendere le precauzioni necessarie durante lo spostamento o il sollevamento del sistema di stoccaggio.

Un sistema di stoccaggio A1K può pesare fino a 28,5 kg (62,83 lb). Per sollevare l'impianto di stoccaggio, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Icona di avvertenza sollevamento AFF A1K]



=== Peso del ripiano

Prendere le precauzioni necessarie quando si sposta o si solleva il ripiano.

Un ripiano NS224 può pesare fino a 30,29 kg (66,78 lb). Per sollevare il ripiano, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^] :a1k!:


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti hardware, si link:install-prepare.html["Preparazione dell'installazione del sistema di storage AFF A1K"].
