---
permalink: a1k/io-module-overview.html 
sidebar: sidebar 
keywords: aff a1k, replace io module 
summary: 'Il sistema AFF A1K offre flessibilità nell"espansione o nella sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L"aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.' 
---
= Panoramica su aggiunta e sostituzione di un modulo i/o - AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema AFF A1K offre flessibilità nell'espansione o nella sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L'aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.

È possibile sostituire un modulo i/o guasto nel sistema storage AFF A1K con uno stesso tipo di modulo i/o o o con un altro tipo di modulo i/O. È inoltre possibile aggiungere un modulo i/o in un sistema con slot vuoti.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di moduli aggiuntivi può migliorare la ridondanza, contribuendo a garantire che il sistema rimanga operativo anche in caso di guasto di un modulo.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema allo stato operativo ottimale.



.Numerazione degli slot i/O.
Gli slot i/o sul controller AFF A1K sono numerati da 1 a 11, come illustrato nella figura seguente.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numerazione degli slot su un controller AFF A1K]
