---
permalink: a400/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: aff a400, aff, a400, shut, down, impair, controller, check, status, onboard, encryption, keys, status, disable, automatic, giveback, version, ontap, system, run, pre-shutdown, check, pre-shutdown checks for onboard encryption keys 
summary: Prima di spegnere il controller compromesso e controllare lo stato delle chiavi di crittografia integrate, è necessario controllare lo stato del controller compromesso, disattivare il giveback automatico e verificare la versione di ONTAP in esecuzione nel sistema. 
---
= Verificare il supporto e lo stato della chiave di crittografia - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di spegnere il controller danneggiato, verifica che la tua versione di ONTAP supporti la crittografia dei volumi NetApp (NVE) e che il tuo sistema di gestione delle chiavi sia configurato correttamente.



== Passaggio 1: Verificare se la versione di ONTAP in uso supporta la crittografia

Verifica se la versione di ONTAP in uso supporta la crittografia dei volumi di NetApp (NVE). Queste informazioni sono fondamentali per scaricare l'immagine ONTAP corretta.

. Per determinare se la versione di ONTAP in uso supporta la crittografia, eseguire il seguente comando:
+
`version -v`

+
Se l'output include `1Ono-DARE`, NVE non è supportato nella versione del cluster.

. In base al supporto di NVE sul tuo sistema, esegui una delle seguenti azioni:
+
** Se NVE è supportato, scarica l'immagine ONTAP con crittografia dei volumi di NetApp.
** Se NVE non è supportato, scaricare l'immagine ONTAP *senza* crittografia del volume NetApp.






== Fase 2: Determinare se è possibile arrestare il controller in modo sicuro

Per arrestare in modo sicuro un controller, identificare prima se il gestore delle chiavi integrato (OKM) o il gestore delle chiavi esterno (EKM) è attivo. Quindi, verificare il gestore delle chiavi in uso, visualizzare le informazioni sulla chiave appropriate ed eseguire le azioni necessarie in base allo stato delle chiavi di autenticazione.

. Determinare quale gestore delle chiavi è abilitato sul proprio sistema:
+
[cols="1a,2a"]
|===
| Tipo di gestore delle chiavi | Attenersi alla procedura descritta di seguito... 


 a| 
Gestore chiavi esterno (EKM)
 a| 
Determinare se EKM è abilitato sul proprio sistema eseguendo il seguente comando:

`security key-manager show key store`

Se EKM è abilitato, `external` viene elencato nell'output.



 a| 
Onboard Key Manager (OKM)
 a| 
Determinare se OKM è abilitato nel sistema eseguendo uno dei seguenti comandi in base alla versione di ONTAP in esecuzione nel nodo.

** Per ONTAP 9.14,1 o versione successiva, immettere il seguente comando:
+
`security key-manager keystore show`

+
Se OKM è attivato, `OKM` viene elencato nell'output del comando.

** Per ONTAP 9.13,1 o versioni precedenti, immettere il seguente comando:
+
`security key-manager show-key-store`

+
Se OKM è attivato, `onboard` viene elencato nell'output del comando.



|===
. Immettere il seguente comando di query per visualizzare lo stato delle chiavi di autenticazione nel gestore delle chiavi:
+
`security key-manager key query`

. Controllare l'output per il valore nella `Restored` colonna per il gestore delle chiavi.
+
Questa colonna indica se le chiavi di autenticazione per il gestore delle chiavi (EKM o OKM) sono state ripristinate correttamente.

+
** Se il valore nella colonna ripristinata è vero, i tasti vengono ripristinati correttamente ed è sicuro procedere con lo spegnimento del controller.
** Se il valore è diverso da true, le chiavi non sono state ripristinate e sarà necessario eseguire ulteriori operazioni (ripristino o sincronizzazione delle chiavi) a seconda che si utilizzi EKM o OKM.


. A seconda che si stia utilizzando EKM o OKM, selezionare una delle seguenti opzioni e seguire la procedura appropriata a seconda del valore di output visualizzato nella `Restored` colonna.
+
[role="tabbed-block"]
====
.EKM
--
A seconda del valore di output visualizzato nella `Restored` colonna, seguire la procedura appropriata.

[cols="1a,2a"]
|===
| Valore di output in `Restored` colonna | Attenersi alla procedura descritta di seguito... 


 a| 
`true`
 a| 
È possibile arrestare il controller danneggiato in modo sicuro. Andare a link:bootmedia-shutdown.html["spegnere il controller danneggiato"].



 a| 
Altro `true`
 a| 
.. Ripristinare le chiavi di autenticazione della gestione delle chiavi esterne in tutti i nodi del cluster utilizzando il seguente comando:
+
`security key-manager external restore`

+
Se il comando non riesce, contattare http://mysupport.netapp.com/["Supporto NetApp"^].

.. Verificare che la `Restored` colonna visualizzata `true` per tutte le chiavi di autenticazione immettendo il  `_security key-manager key query_`comando.
+
Se tutte le chiavi di autenticazione sono `true`, è possibile arrestare il controller danneggiato in modo sicuro. Andare a link:bootmedia-shutdown.html["spegnere il controller danneggiato"].



|===
--
.OKM
--
A seconda del valore di output visualizzato nella `Restored` colonna, seguire la procedura appropriata.

[cols="1a,2a"]
|===
| Valore di output in `Restored` colonna | Attenersi alla procedura descritta di seguito... 


 a| 
`true`
 a| 
Eseguire manualmente il backup delle informazioni OKM.

.. Accedere alla modalità avanzata immettendo `set -priv advanced` e quindi immettere `Y` quando richiesto.
.. Immettere il seguente comando per visualizzare le informazioni sulla gestione delle chiavi:
+
`security key-manager onboard show-backup`

.. Copiare il contenuto delle informazioni di backup in un file separato o nel file di log.
+
Sarà necessario in situazioni di emergenza in cui potrebbe essere necessario ripristinare manualmente OKM.

.. È possibile arrestare il controller danneggiato in modo sicuro. Andare a link:bootmedia-shutdown.html["spegnere il controller danneggiato"].




 a| 
Altro `true`
 a| 
.. Immettere il comando di sincronizzazione del gestore delle chiavi di sicurezza integrato:
+
`security key-manager onboard sync`

.. Immettere la passphrase di gestione della chiave integrata alfanumerica di 32 caratteri quando richiesto.
+
Se non è possibile fornire la passphrase, contattare http://mysupport.netapp.com/["Supporto NetApp"^].

.. Verificare che venga visualizzata la `Restored` colonna `true` per tutte le chiavi di autenticazione:
+
`security key-manager key query`

.. Verificare che il `Key Manager` tipo sia visualizzato `onboard`, quindi eseguire manualmente il backup delle informazioni OKM.
.. Immettere il comando per visualizzare le informazioni di backup per la gestione delle chiavi:
+
`security key-manager onboard show-backup`

.. Copiare il contenuto delle informazioni di backup in un file separato o nel file di log.
+
Sarà necessario in situazioni di emergenza in cui potrebbe essere necessario ripristinare manualmente OKM.

.. È possibile arrestare il controller danneggiato in modo sicuro. Andare a link:bootmedia-shutdown.html["spegnere il controller danneggiato"].


|===
--
====

