---
permalink: a400/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff a400, aff, a400, component, system, function, properly, contact, technical, support, replace, chassis, shut, down, controller, replacing, remove, module, fan, equipment, rack, cabinet, ha, state, switch, back, aggregate, two-node, metrocluster, configuration, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, verify and set the ha state of the chassis, switch back aggregates in a two-node metrocluster configuration, complete the replacement process 
summary: 'Spostare le ventole, i dischi rigidi e il modulo controller o i moduli dallo chassis guasto al nuovo chassis, quindi sostituire lo chassis compromesso dal rack dell"apparecchiatura o dall"armadietto del sistema con il nuovo chassis dello stesso modello dello chassis compromesso.' 
---
= Sostituire l'hardware - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Spostare le ventole, i dischi rigidi e il modulo controller dallo chassis compromesso al nuovo chassis e sostituire lo chassis compromesso con quello nuovo dello stesso modello dello chassis compromesso.



== Fase 1: Rimuovere i moduli controller

Per sostituire lo chassis, è necessario rimuovere i moduli controller dal vecchio chassis.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Rilasciare i fermi dei cavi di alimentazione, quindi scollegare i cavi dagli alimentatori.
. Allentare il gancio e la fascetta che fissano i cavi al dispositivo di gestione dei cavi, quindi scollegare i cavi di sistema e gli SFP (se necessario) dal modulo controller, tenendo traccia del punto in cui sono stati collegati i cavi.
+
Lasciare i cavi nel dispositivo di gestione dei cavi in modo che quando si reinstalla il dispositivo di gestione dei cavi, i cavi siano organizzati.

. Rimuovere e mettere da parte i dispositivi di gestione dei cavi dai lati sinistro e destro del modulo controller.
. Premere verso il basso entrambi i fermi di bloccaggio, quindi ruotare entrambi i fermi verso il basso contemporaneamente.
+
Il modulo controller si sposta leggermente fuori dallo chassis.

. Estrarre il modulo controller dal telaio.
+
Assicurarsi di sostenere la parte inferiore del modulo controller mentre lo si sposta fuori dallo chassis.

. Mettere da parte il modulo controller in un luogo sicuro e ripetere questa procedura per l'altro modulo controller nello chassis.




== Fase 2: Spostare le ventole

Per spostare i moduli delle ventole nello chassis sostitutivo durante la sostituzione dello chassis, è necessario eseguire una sequenza specifica di attività.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Rimuovere il pannello (se necessario) con due mani, afferrando le aperture su ciascun lato del pannello, quindi tirandolo verso di sé fino a quando non si sgancia dai perni sferici sul telaio.
. Premere verso il basso il fermo di rilascio sulla maniglia della camma del modulo ventola, quindi ruotare la maniglia della camma verso il basso.
+
Il modulo della ventola si allontana leggermente dallo chassis.

. Estrarre il modulo della ventola dal telaio, assicurandosi di sostenerlo con la mano libera in modo che non ruoti fuori dal telaio.
+

CAUTION: I moduli della ventola sono corti. Sostenere sempre la parte inferiore del modulo della ventola con la mano libera in modo che non cada improvvisamente dal telaio e non causi lesioni.

. Mettere da parte il modulo della ventola.
. Ripetere i passaggi precedenti per tutti i moduli ventola rimanenti.
. Inserire il modulo della ventola nel telaio sostitutivo allineandolo con l'apertura e facendolo scorrere nel telaio.
. Spingere con decisione la maniglia della camma del modulo della ventola in modo che sia inserita completamente nel telaio.
+
La maniglia della camma si solleva leggermente quando il modulo della ventola è completamente inserito.

. Ruotare la maniglia della camma verso l'alto nella posizione di chiusura, assicurandosi che il fermo di rilascio della maniglia della camma scatti nella posizione di blocco.
. Ripetere questa procedura per i moduli ventola rimanenti.




== Fase 3: Sostituire uno chassis all'interno del rack dell'apparecchiatura o dell'armadietto del sistema

Prima di installare lo chassis sostitutivo, è necessario rimuovere lo chassis esistente dal rack dell'apparecchiatura o dall'armadietto del sistema.

. Rimuovere le viti dai punti di montaggio del telaio.
. Con due persone, far scorrere il vecchio chassis dalle guide del rack in un cabinet di sistema o in un rack dell'apparecchiatura, quindi metterlo da parte.
. Se non si è già collegati a terra, mettere a terra l'utente.
. Con l'aiuto di due persone, installare lo chassis sostitutivo nel rack dell'apparecchiatura o nell'armadietto del sistema guidandolo sulle guide del rack in un cabinet del sistema o in un rack dell'apparecchiatura.
. Far scorrere lo chassis completamente nel rack dell'apparecchiatura o nell'armadietto del sistema.
. Fissare la parte anteriore dello chassis al rack dell'apparecchiatura o all'armadietto del sistema, utilizzando le viti rimosse dal vecchio chassis.
. Se non è già stato fatto, installare il pannello.




== Fase 4: Installare i moduli controller

Dopo aver installato i moduli controller nel nuovo chassis, è necessario avviarlo.

Per le coppie ha con due moduli controller nello stesso chassis, la sequenza in cui si installa il modulo controller è particolarmente importante perché tenta di riavviarsi non appena lo si installa completamente nello chassis.

. Allineare l'estremità del modulo controller con l'apertura dello chassis, quindi spingere delicatamente il modulo controller a metà nel sistema.
+

NOTE: Non inserire completamente il modulo controller nel telaio fino a quando non viene richiesto.

. Collegare nuovamente la console al modulo controller, quindi ricollegare la porta di gestione.
. Completare l'installazione del modulo controller:
+
.. Collegare il cavo di alimentazione all'alimentatore, reinstallare il collare di bloccaggio del cavo di alimentazione, quindi collegare l'alimentatore alla fonte di alimentazione.
.. Utilizzando i fermi di bloccaggio, spingere con decisione il modulo controller nel telaio fino a quando i fermi di bloccaggio non iniziano a sollevarsi.
+

NOTE: Non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel telaio per evitare di danneggiare i connettori.

.. Inserire completamente il modulo controller nel telaio ruotando i fermi di bloccaggio verso l'alto, inclinandoli in modo da liberare i perni di bloccaggio, spingere delicatamente il controller fino in fondo, quindi abbassare i fermi di bloccaggio in posizione di blocco.
+
Il modulo controller inizia ad avviarsi non appena viene inserito completamente nello chassis. Prepararsi ad interrompere il processo di avvio.

.. Se non è già stato fatto, reinstallare il dispositivo di gestione dei cavi.
.. Interrompere il normale processo di avvio e avviare IL CARICATORE premendo `Ctrl-C`.
+

NOTE: Se il sistema si arresta nel menu di avvio, selezionare l'opzione per avviare IL CARICATORE.

.. Al prompt DEL CARICATORE, immettere `bye` Per reinizializzare le schede PCIe e altri componenti.
.. Interrompere il processo di avvio e avviare il CARICATORE premendo `Ctrl-C`.
+
Se il sistema si arresta nel menu di avvio, selezionare l'opzione per avviare IL CARICATORE.



. Ripetere i passi precedenti per installare il secondo controller nel nuovo chassis.

