---
permalink: a400/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a400, verify and set HA state, run diagnostics, complete the replacement process 
summary: Verificare lo stato ha dello chassis, eseguire la diagnostica e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Completare il processo di ripristino e sostituzione - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare lo stato ha dello chassis, eseguire la diagnostica e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit.



== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _HA-state_`
+
Il valore per _ha-state_ può essere uno dei seguenti:

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.
. Reinstallare il pannello anteriore del sistema.




== Fase 2: Eseguire la diagnostica

Dopo aver sostituito un componente del sistema, è necessario eseguire test diagnostici su tale componente.

Il sistema deve essere al prompt DEL CARICATORE per avviare la diagnostica.

Tutti i comandi delle procedure diagnostiche vengono emessi dal nodo in cui viene sostituito il componente.

. Se il nodo da sottoporre a manutenzione non viene visualizzato al prompt DEL CARICATORE, riavviare il nodo: `system node halt -node node_name`
+
Dopo aver eseguito il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

. Al prompt DEL CARICATORE, accedere ai driver speciali progettati appositamente per la diagnostica a livello di sistema per funzionare correttamente: `boot_diags`
. Selezionare *Scan System* (sistema di scansione) dal menu visualizzato per abilitare l'esecuzione dei test di diagnostica.
. Selezionare *Test system* dal menu visualizzato per eseguire i test di diagnostica.
. Selezionare il test o la serie di test dai vari sottomenu.
. Procedere in base al risultato del passaggio precedente:
+
** Se il test non ha avuto esito positivo, correggerlo ed eseguire nuovamente il test.
** Se il test non ha rilevato errori, selezionare Reboot (Riavvia) dal menu per riavviare il sistema.






== Fase 3: Switch back aggregates in una configurazione MetroCluster a due nodi

Una volta completata la sostituzione dell'unità FRU in una configurazione MetroCluster a due nodi, è possibile eseguire l'operazione di switchback dell'unità MetroCluster. In questo modo, la configurazione torna al suo normale stato operativo, con le macchine virtuali dello storage di origine sincronizzata (SVM) sul sito precedentemente compromesso ora attive e che forniscono i dati dai pool di dischi locali.

Questa attività si applica solo alle configurazioni MetroCluster a due nodi.

.Fasi
. Verificare che tutti i nodi si trovino in `enabled` stato: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Verificare che la risincronizzazione sia completa su tutte le SVM: `metrocluster vserver show`
. Verificare che tutte le migrazioni LIF automatiche eseguite dalle operazioni di riparazione siano state completate correttamente: `metrocluster check lif show`
. Eseguire lo switchback utilizzando `metrocluster switchback` comando da qualsiasi nodo del cluster esistente.
. Verificare che l'operazione di switchback sia stata completata: `metrocluster show`
+
L'operazione di switchback è ancora in esecuzione quando un cluster si trova in `waiting-for-switchback` stato:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
L'operazione di switchback è completa quando i cluster si trovano in `normal` stato:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Se il completamento di uno switchback richiede molto tempo, è possibile verificare lo stato delle linee di base in corso utilizzando `metrocluster config-replication resync-status show` comando.

. Ripristinare le configurazioni SnapMirror o SnapVault.




== Fase 4: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
