---
permalink: a400/power-supply-replace.html 
sidebar: sidebar 
keywords: aff a400, aff, a400, replace, replacing, power, supply, psu, disconnect, target, psu, unplug, power, cable, removing, remove, replacement, source, replace a power supply 
summary: 'La sostituzione di un alimentatore comporta lo scollegamento dell"alimentatore di destinazione dalla fonte di alimentazione, lo scollegamento del cavo di alimentazione, la rimozione dell"alimentatore precedente e l"installazione dell"alimentatore sostitutivo, quindi il ricollegamento dell"alimentatore sostitutivo alla fonte di alimentazione.' 
---
= Sostituzione di un alimentatore - AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sostituzione di un alimentatore comporta lo scollegamento dell'alimentatore di destinazione dalla fonte di alimentazione, lo scollegamento del cavo di alimentazione, la rimozione dell'alimentatore precedente e l'installazione dell'alimentatore sostitutivo, quindi il ricollegamento dell'alimentatore sostitutivo alla fonte di alimentazione.

* Gli alimentatori sono ridondanti e sostituibili a caldo.
* Questa procedura è stata scritta per la sostituzione di un alimentatore alla volta.
+

NOTE: Si consiglia di sostituire l'alimentatore entro due minuti dalla rimozione dallo chassis. Il sistema continua a funzionare, ma ONTAP invia messaggi alla console sull'alimentatore danneggiato fino alla sostituzione dell'alimentatore.

+

IMPORTANT: Non combinare PSU con diversi indici di efficienza. Sostituire sempre come per come.



Per sostituire l'alimentatore, utilizzare la seguente illustrazione con la procedura scritta.

image::../media/drw_c400_psu_IEOPS-1237.svg[DRW C400 psu IEOPS 1237]

. Se non si è già collegati a terra, mettere a terra l'utente.
. Identificare l'alimentatore che si desidera sostituire, in base ai messaggi di errore della console o tramite i LED degli alimentatori.
. Scollegare l'alimentatore:
+
.. Aprire il fermo del cavo di alimentazione, quindi scollegare il cavo di alimentazione dall'alimentatore.
.. Scollegare il cavo di alimentazione dalla fonte di alimentazione.


. Rimuovere l'alimentatore:
+
.. Ruotare la maniglia della camma in modo che possa essere utilizzata per estrarre l'alimentatore dallo chassis.
.. Premere la linguetta blu di blocco per rilasciare l'alimentatore dallo chassis.
.. Con entrambe le mani, estrarre l'alimentatore dal telaio e metterlo da parte.


. Con entrambe le mani, sostenere e allineare i bordi dell'alimentatore con l'apertura nel modulo controller, quindi spingere delicatamente l'alimentatore nel modulo controller fino a quando la linguetta di blocco non scatta in posizione.
+
Gli alimentatori si innestano correttamente solo con il connettore interno e si bloccano in un modo.

+

NOTE: Per evitare di danneggiare il connettore interno, non esercitare una forza eccessiva quando si inserisce l'alimentatore nel sistema.

. Ruotare la maniglia della camma in modo che sia a filo con l'alimentatore.
. Ricollegare il cablaggio dell'alimentatore:
+
.. Ricollegare il cavo di alimentazione all'alimentatore e alla fonte di alimentazione.
.. Fissare il cavo di alimentazione all'alimentatore utilizzando il fermo del cavo di alimentazione.


+
Una volta ripristinata l'alimentazione, il LED di stato deve essere verde.

. Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"^] per ulteriori informazioni.

