---
permalink: a70-90/aff-a-series-affa70-overview.html 
sidebar: sidebar 
keywords: AFF A70 specifications, AFF A70 specs, NetApp AFF A70, AFF A70 hardware 
summary: Specifiche chiave per il sistema di archiviazione AFF A70 
---
= Specifiche chiave per AFF A70
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' AFF A70.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche AFF A70 .  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per AFF A70

Configurazione della piattaforma: coppia HA a telaio singolo AFF A70

Capacità massima grezza: 6,6096 PB

Memoria: 256.0000 GB

Fattore di forma: chassis 4U con 2 controller HA e 48 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 18

Versione minima ONTAP : ONTAP 9.15.1RC2



=== Massimi di scalabilità

* NAS: 12 coppie HA, capacità raw 79,3 PB / 70,4 PiB, memoria massima 3072 GB
* SAN: 6 coppie HA, capacità raw 39,7 PB / 35,2 PiB, memoria massima 1536 GB
* Coppia HA: capacità grezza 6,6 PB / 5,9 PiB, memoria massima 256,0000 GB




=== Io



==== IO di bordo

Nessun dato IO a bordo.



==== IO totale

* Ethernet 200 Gbps: 24 porte
* Ethernet 100 Gbps: 36 porte
* Ethernet 25 Gbps: 56 porte
* Ethernet 10 Gbps: 56 porte
* FC 64 Gbps: 56 porte
* NVMe/FC 64 Gbps: 56 porte
* SAS 12 Gbps: 56 porte




==== Porte di gestione

* Ethernet 1 Gbps: 2 porte
* RS-232 115 Kbps: 4 porte
* USB 600 Mbps: 2 porte




=== Rete di archiviazione supportata

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 6938 BTU/ora
* Potenza nel caso peggiore: 9089 BTU/ora
* Peso: 118,0 libbre/53,5 kg
* Altezza: 4U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 34,5" (36,6" con staffa per la gestione dei cavi)
* Temperatura/altitudine/umidità di esercizio: da 10°C a 35°C (da 50°F a 95°F) a 3048 m (da 10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi)<br/>Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 8,6;br/Pressione sonora (LpAm) (posizioni degli astanti): 71,6 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo; Gestione in banda SAS su connessioni SAS per ripiani esterni; [//] 2025-10-15 ontap-systems-internal/issues/1357
