---
permalink: a70-90/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, a90, replace the boot media 
summary: 'Prima di sostituire il supporto di avvio nel sistema AFF A70 o AFF A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. È necessario assicurarsi di disporre di un"unità flash USB con la quantità di spazio di archiviazione appropriata e verificare di disporre della periferica di avvio sostitutiva corretta.' 
---
= Requisiti per il ripristino manuale dei supporti di avvio - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema AFF A70 o AFF A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. È necessario assicurarsi di disporre di un'unità flash USB con la quantità di spazio di archiviazione appropriata e verificare di disporre della periferica di avvio sostitutiva corretta.

.Chiavetta USB
* Assicurati di avere una chiavetta USB formattata in FAT32.
* La chiavetta USB deve avere una capacità di archiviazione sufficiente per contenere il  `image_xxx.tgz` file.


.Preparazione del file
Copia il  `image_xxx.tgz` file sull'unità flash USB. Questo file verrà utilizzato quando si trasferisce l'immagine ONTAP tramite l'unità flash USB.

.Sostituzione dei componenti
Sostituire il componente guasto con il componente sostitutivo fornito da NetApp.

.Identificazione del controllore
Quando si sostituisce il supporto di avvio danneggiato, è fondamentale applicare i comandi al controller corretto:

* Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
* Il _controllore sano_ è il partner HA del controllore compromesso.


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti per sostituire il supporto di avvio, è necessario link:bootmedia-encryption-preshutdown-checks.html["controllare il supporto e lo stato della chiave di crittografia sul supporto di avvio"].
