---
permalink: a70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: Prima di sostituire il supporto di avvio nel sistema di archiviazione AFF A70 o AFF A90 , rivedere i requisiti. 
---
= Requisiti per il ripristino automatico dei supporti di avvio - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema di archiviazione AFF A70 o AFF A90 , rivedere i requisiti, tra cui la funzionalità della porta del cluster, la configurazione del gestore delle chiavi e la compatibilità della versione ONTAP .

Il processo di ripristino automatico del supporto di avvio richiede ONTAP 9.17.1 o versione successiva.  Se il sistema di archiviazione esegue una versione precedente di ONTAP, utilizzarelink:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .

Esaminare i seguenti requisiti.

* È necessario sostituire il supporto di avvio guasto con un supporto di avvio sostitutivo ricevuto da NetApp.
* Le porte del cluster vengono utilizzate per comunicare tra i due controller durante il processo di ripristino automatico dell'avvio. Assicurarsi che le porte del cluster sul controller danneggiato funzionino correttamente.
* Per OKM, è necessaria la passphrase dell'intero cluster e anche i dati di backup.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* Comprendere la terminologia del controller utilizzata in questa procedura:
+
** Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
** Il _controllore sano_ è il partner HA del controllore compromesso.




.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, si link:bootmedia-shutdown-bmr.html["spegnere il controller"].
