---
permalink: a70-90/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, a90, replace the boot media 
summary: 'Prima di sostituire il supporto di avvio nel sistema AFF A70 o AFF A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. È necessario assicurarsi di disporre di un"unità flash USB con la quantità di spazio di archiviazione appropriata e verificare di disporre della periferica di avvio sostitutiva corretta.' 
---
= Requisiti per il ripristino manuale dei supporti di avvio - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema AFF A70 o AFF A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. È necessario assicurarsi di disporre di un'unità flash USB con la quantità di spazio di archiviazione appropriata e verificare di disporre della periferica di avvio sostitutiva corretta.

Se il sistema è in esecuzione in ONTAP 9.17.1 e versioni successive, utilizzare link:bootmedia-replace-workflow-bmr.html["procedura di ripristino automatico dell'avvio"] .

[NOTE]
====
NetApp raccomanda vivamente di abilitare la registrazione della console sui dispositivi con cui si sta lavorando e di adottare le seguenti misure durante l'esecuzione di questa procedura:

* Lascia AutoSupport abilitato durante la manutenzione. Questo consente al supporto NetApp di ricevere informazioni diagnostiche in caso di problemi.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI. Questo crea una registrazione completa di tutti i comandi e dell'output di sistema durante l'attività di manutenzione. Per istruzioni su come abilitare la registrazione delle sessioni, vedere  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^].


====
.Chiavetta USB
* Assicurati di avere una chiavetta USB formattata in FAT32.
* La chiavetta USB deve avere una capacità di archiviazione sufficiente per contenere il  `image_xxx.tgz` file.


.Preparazione del file
Copia il  `image_xxx.tgz` file sull'unità flash USB. Questo file verrà utilizzato quando si trasferisce l'immagine ONTAP tramite l'unità flash USB.

Dall'immagine ONTAP estratta, copia la  `EFI` cartella nella directory principale dell'unità flash USB.

.Sostituzione dei componenti
Sostituire il componente guasto con il componente sostitutivo fornito da NetApp.

.Identificazione del controllore
Quando si sostituisce il supporto di avvio danneggiato, è fondamentale applicare i comandi al controller corretto:

* Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
* Il _controllore sano_ è il partner HA del controllore compromesso.


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti per sostituire il supporto di avvio, è necessario link:bootmedia-encryption-preshutdown-checks.html["controllare il supporto e lo stato della chiave di crittografia sul supporto di avvio"].
