---
permalink: a70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a70, aff a90,  verify and set HA state, complete the replacement process 
summary: Riavviare i controller, verificare lo stato del sistema e restituire il componente guasto a NetApp per completare la fase finale della procedura di sostituzione dello chassis AFF A70 e AFF A90. 
---
= Completare la sostituzione del telaio - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Riavviare i controller, verificare lo stato del sistema e restituire il componente guasto a NetApp per completare la fase finale della procedura di sostituzione dello chassis AFF A70 e AFF A90.



== Passaggio 1: avviare i controller ed eseguire il giveback

Avviare ONTAP sui controller ed eseguire il giveback del controller per ripristinare la proprietà dello storage.

.Fasi
. Controllare l'output della console:
+
.. Se il controller viene avviato al prompt Loader, riavviarlo con il `boot_ontap` comando.
.. Se la console viene visualizzata `waiting for giveback` dopo il riavvio, accedere al controller partner e verificare che il controller sostituito sia pronto per il giveback con il `storage failover show` comando.


. Eseguire lo sconto:
+
.. Collegare il cavo della console al controller partner.
.. Restituire il controller con il `storage failover giveback -fromnode local` comando.






== Fase 2: Verifica dello stato del sistema di archiviazione

Dopo aver completato la restituzione del controller, verificare lo stato del sistema utilizzando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .  Risolvere eventuali problemi riscontrati.



== Fase 3: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
