---
permalink: a70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a70, aff a90, how to recable the system, teboot the system 
summary: È necessario eseguire nuovamente il riavvio dello storage del controller. 
---
= Possibilità di recuperare e restituire il controller - AFF A70, AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Recuperare le connessioni di storage e di rete, quindi restituire il controller.



== Fase 1: Ricable del sistema

Possibilità di ricable le connessioni di rete e di storage del modulo controller.

.Fasi
. Possibilità di recuperare il modulo controller per le connessioni di storage e di rete.
. Verificare che il cablaggio sia corretto utilizzando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].
+
.. Scaricare e installare Config Advisor.
.. Inserire le informazioni relative al sistema di destinazione, quindi fare clic su Collect Data (Raccogli dati).
.. Fare clic sulla scheda Cabling (cablaggio), quindi esaminare l'output. Assicurarsi che tutti gli shelf di dischi siano visualizzati e che tutti i dischi appaiano nell'output, correggendo eventuali problemi di cablaggio rilevati.
.. Controllare gli altri cavi facendo clic sulla scheda appropriata, quindi esaminare l'output di Config Advisor.






== Fase 2: Restituire il controller

. Se il sistema di archiviazione ha configurato la crittografia, è necessario ripristinare la funzionalità di archiviazione o crittografia dei volumi utilizzando la seguente procedura per riavviare il sistema:
+
.. Avviare il menu ed eseguire l'opzione 10
.. Inserire la passphrase e eseguire il backup dei dati, quindi eseguire l'avvio normale vedere https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys["Ripristinare le chiavi di crittografia integrate per la gestione delle chiavi"].
.. Esegui uno sconto solo per CFO
.. Eseguire Onboard Sync e verificare che SVM-KEK sia impostato su true vedere https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement["Giveback dopo la sostituzione della MB fallisce - l'operazione è stata messa al veto dal keymanager"]
.. OFS Giveback (senza forza)


. Se nel sistema non è configurata la crittografia, completare la seguente procedura per riavviare il sistema:
+
.. Avviare il menu ed eseguire l'opzione 1.
.. Restituire il controller:
.. Dal controller integro, restituire lo storage del controller sostituito: `storage failover giveback -ofnode _replacement_node_name_`
+
Il controller _replacement_ riprende lo storage e completa l'avvio.

+

NOTE: Se il giveback viene vetoed, puoi prendere in considerazione la possibilità di ignorare i veti.

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["Trova il contenuto della configurazione ad alta disponibilità per la tua versione di ONTAP 9"]

.. Una volta completato il giveback, verificare che la coppia ha sia in buone condizioni e che sia possibile effettuare il takeover: `storage failover show`


. Se il sistema si trova in una configurazione MetroCluster, monitorare lo stato del controller: `metrocluster node show`
+
La configurazione MetroCluster impiega alcuni minuti dopo la sostituzione per tornare a uno stato normale, in cui ogni controller mostra uno stato configurato, con mirroring DR abilitato e una modalità normale. Il `metrocluster node show -fields node-systemid` L'output del comando visualizza il vecchio ID di sistema fino a quando la configurazione MetroCluster non torna allo stato normale.

. Se il controller si trova in una configurazione MetroCluster, a seconda dello stato MetroCluster, verificare che il campo DR home ID (ID origine DR) indichi il proprietario originale del disco se il proprietario originale è un controller nel sito di emergenza.
+
Ciò è necessario se si verificano entrambe le seguenti condizioni:

+
** La configurazione MetroCluster è in uno stato di switchover.
** Il controller _replacement_ è l'attuale proprietario dei dischi nel sito di disastro.
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["La proprietà del disco cambia durante il takeover ha e lo switchover MetroCluster in una configurazione MetroCluster a quattro nodi"]



. Se il sistema si trova in una configurazione MetroCluster, verificare che ciascun controller sia configurato: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Verificare che i volumi previsti siano presenti per ciascun controller: `vol show -node node-name`
. Se al riavvio è stato disattivato il Takeover automatico, attivarlo dal controller integro: `storage failover modify -node replacement-node-name -onreboot true`

