---
permalink: a70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: aff a70, aff a90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Verificare che le interfacce logiche riportino la porta home, eseguire un controllo dello stato di salute del cluster e restituire il componente guasto a NetApp per completare l"ultima fase della procedura di sostituzione dei controller AFF A70 e AFF A90.' 
---
= Sostituzione completa della centralina - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per completare la sostituzione del controller per il tuo sistema AFF A70 o AFF A90, ripristina innanzitutto la configurazione di NetApp Storage Encryption (se necessario). Quindi, conferma che le interfacce logiche (LIF) stanno eseguendo un reporting sulle rispettive porte home ed esegui un controllo dello stato di salute del cluster. Infine, restituisci il componente guasto a NetApp.



== Fase 1: Verifica delle LIF e verifica dello stato del cluster

Prima di riportare in servizio il nodo sostitutivo, verifica che le interfacce logiche siano sulle porte home, verifica lo stato del cluster e ripristina il giveback automatico.

.Fasi
. Verificare che le interfacce logiche stiano segnalando al server principale e alle porte: `network interface show -is-home false`
+
Se alcune interfacce logiche sono elencate come false, riportarle alle porte principali: `network interface revert -vserver * -lif *`

. Controllare lo stato di salute del cluster. Per ulteriori informazioni, consultare l' https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Come eseguire un controllo dello stato del cluster con uno script in ONTAP"^] articolo della KB.
. Se il giveback automatico è stato disattivato, riabilitarlo: `storage failover modify -node local -auto-giveback true`




== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
