---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per la piattaforma e i ripiani.' 
---
= Requisiti di installazione - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esaminare l'attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage e i shelf di storage AFF A70 o AFF A90.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi e gli shelf di storage sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Peso del sistema di storage

Prendere le precauzioni necessarie durante lo spostamento o il sollevamento del sistema di stoccaggio.

Il sistema di stoccaggio può pesare fino a 68,8 kg (151,68 lb). Per sollevare l'impianto di stoccaggio, utilizzare quattro persone o un sollevatore idraulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Icona di attenzione peso AFF A90 AFF A70 e C80]



=== Peso del ripiano

Prendere le precauzioni necessarie quando si sposta o si solleva il ripiano.

Un ripiano NS224 può pesare fino a 30,29 kg (66,78 lb). Per sollevare il ripiano, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100 attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti hardware, si link:install-prepare.html["Preparazione dell'installazione del sistema di storage AFF A70 o AFF A90"].
