---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per la piattaforma e i ripiani.' 
---
= Requisiti di installazione - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esaminare l'attrezzatura necessaria e le precauzioni di sollevamento per il sistema di storage e i shelf di storage AFF A70 o AFF A90.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage AFF A70 o AFF A90 sono necessari le seguenti attrezzature e strumenti.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Graffetta o penna a sfera con punta stretta per l'impostazione di NS224 ID scaffali
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi storage AFF A70 e AFF A90 e gli shelf di storage NS224 sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Sistemi storage AFF A70 e AFF A90

Un sistema storage AFF A70 o AFF A90 può pesare fino a 68,8 kg (151,68 libbre). Per sollevare l'impianto, utilizzare quattro persone o un sollevatore idraulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90]



=== NS224 ripiano

Un ripiano di stoccaggio NS224 può pesare fino a 30,29 kg (66,78 lb). Per sollevare il ripiano portaoggetti, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano portaoggetti (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti hardware, si link:install-prepare.html["Preparazione dell'installazione del sistema di storage AFF A70 o AFF A90"].
