---
permalink: a70-90/install-prepare.html 
sidebar: sidebar 
keywords: aff a70-90k, prepare installation 
summary: 'Preparare l"installazione della piattaforma AFF A70 e AFF A90.' 
---
= Preparazione all'installazione - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Preparare l'installazione del sistema di storage AFF A70 o AFF A90 preparando il sito, disimballando le confezioni e confrontando il contenuto delle confezioni con il documento di trasporto, quindi registrare il sistema per accedere ai vantaggi del supporto.



== Fase 1: Preparare il sito

Per installare il sistema di archiviazione, verificare che il sito e il cabinet o il rack che si intende utilizzare soddisfino le specifiche per la configurazione.

.Fasi
. Utilizzare https://hwu.netapp.com["NetApp Hardware Universe"^] per verificare che il sito soddisfi i requisiti ambientali ed elettrici del sistema di archiviazione.
. Assicurarsi di disporre di uno spazio rack adeguato:
+
** 4U in una configurazione ha per la piattaforma
** 2U TB per ogni shelf storage NS224


+
*NOTA:* vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^] per i requisiti di spazio rack per altri shelf di archiviazione supportati.

. Installare gli switch di rete necessari.
+
Per le istruzioni di installazione e per informazioni sulla compatibilità, consultare la https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentazione dello switch"^] link:https://hwu.netapp.com["NetApp Hardware Universe"^] .





== Fase 2: Disimballare le scatole

Dopo aver verificato che il sito e il cabinet o il rack che si intende utilizzare per il sistema di archiviazione soddisfino le specifiche richieste, disimballare tutte le confezioni e confrontare il contenuto con gli articoli presenti sul documento di trasporto.

.Fasi
. Aprire con attenzione tutte le scatole e disporre il contenuto in modo organizzato.
. Confrontare il contenuto della confezione con l'elenco riportato sul documento di trasporto.
+

NOTE: È possibile ottenere la distinta di imballaggio eseguendo la scansione del codice QR sul lato del cartone di spedizione.

+
I seguenti elementi sono alcuni dei contenuti che potrebbero essere visualizzati nelle caselle.

+
Assicurarsi che tutto ciò che è contenuto nelle confezioni corrisponda all'elenco riportato sul documento di trasporto. In caso di discrepanze, annotarle per ulteriori azioni.

+
[cols="12,9,4"]
|===


| *Hardware* | *Cavi* |  


 a| 
** Pannello
** Dispositivo di gestione dei cavi
** Piattaforma
** Kit guide con istruzioni (opzionale)
** Shelf di storage

 a| 
** Cavi Ethernet di gestione (cavi RJ-45)
** Cavi di rete
** Cavi di alimentazione
** Cavi di stoccaggio (se è stato ordinato ulteriore spazio di archiviazione)
** Cavo della porta seriale USB-C.

|  
|===




== Fase 3: Registrare il sistema di archiviazione

Dopo aver verificato che il sito soddisfi i requisiti per le specifiche del sistema di storage e aver verificato di disporre di tutte le parti ordinate, è necessario registrare il sistema.

.Fasi
. Individua il numero di serie del tuo sistema storage.
+
Il numero è riportato sul documento di trasporto, nell'e-mail di conferma o sul modulo Gestione sistema del controller dopo averlo disimballato.

+
image::../media/drw_ssn_label.svg[Esempio di numero di serie del sistema]

. Andare a http://mysupport.netapp.com/["Sito di supporto NetApp"^].
. Stabilire se è necessario registrare il sistema storage:
+
[cols="1a,2a"]
|===
| Se sei un... | Attenersi alla procedura descritta di seguito... 


 a| 
Cliente NetApp esistente
 a| 
.. Accedi con il tuo nome utente e la password.
.. Selezionare *sistemi* > *i miei sistemi*.
.. Verificare che il nuovo numero di serie sia elencato.
.. In caso contrario, seguire le istruzioni per i nuovi clienti NetApp.




 a| 
Nuovo cliente NetApp
 a| 
.. Fare clic su *Registrati ora* e creare un account.
.. Selezionare *sistemi* > *Registra sistemi*.
.. Inserisci il numero di serie del sistema storage e i dettagli richiesti.


Una volta approvata la registrazione, è possibile scaricare il software richiesto. Il processo di approvazione potrebbe richiedere fino a 24 ore.

|===


.Quali sono le prossime novità?
Dopo aver completato l'installazione dell'hardware AFF A70 o AFF A90, eseguire le operazioni link:install-hardware.html["Installazione dell'hardware per il sistema di storage AFF A70 o AFF A90"]descritte di seguito.
