---
permalink: a70-90/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: È possibile sostituire un modulo i/o guasto nel sistema storage AFF A70 o AFF A90 con uno stesso tipo di modulo i/o o o con un altro tipo di modulo i/O. È inoltre possibile aggiungere un modulo i/o in un sistema con slot vuoti. 
---
= Panoramica su aggiunta e sostituzione di un modulo i/o - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi AFF A70 e AFF A90 offrono la massima flessibilità nell'espansione o sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L'aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.

È possibile sostituire un modulo i/o guasto nel sistema storage AFF A70 o AFF A90 con uno stesso tipo di modulo i/o o o con un altro tipo di modulo i/O. È inoltre possibile aggiungere un modulo i/o in un sistema con slot vuoti.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di moduli aggiuntivi può migliorare la ridondanza, contribuendo a garantire che il sistema rimanga operativo anche in caso di guasto di un modulo.

* link:io-module-hotswap.html["Eseguire lo swap a caldo di un modulo I/O"]
+
È possibile eseguire lo swap a caldo di determinati moduli I/O con un modulo I/O equivalente per ripristinare il sistema storage al suo stato operativo ottimale. Lo swap a caldo viene eseguito senza dover eseguire un takeover manuale.



Per utilizzare questa procedura, il sistema storage deve eseguire ONTAP 9.18.1 o versioni successive.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema allo stato operativo ottimale.



.Numerazione degli slot i/O.
Gli slot i/o sui controller AFF A70 e AFF A90 sono numerati da 1 a 11, come illustrato nella figura seguente.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numerazione degli slot sui controller AFF A70 e AFF A90]
