---
permalink: a70-90/maintain-overview.html 
sidebar: sidebar 
keywords: aff a70 aff a90 maintenance, maintenance, repairing aff a70 aff a90, repairing a70 aff a90, replace a70 aff a90 components 
summary: 'Mantieni l"hardware dei tuoi sistemi storage AFF A70 e AFF A90 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.' 
---
= Panoramica delle procedure di manutenzione - AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantieni l'hardware dei tuoi sistemi storage AFF A70 e AFF A90 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.

Le procedure di manutenzione presumono che i sistemi AFF A70 e AFF A90 siano già stati implementati come nodo storage nell'ambiente ONTAP.



== Componenti del sistema

Per i sistemi di storage AFF A70 e AFF A90, è possibile eseguire le procedure di manutenzione sui seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["Supporto di boot"]
 a| 
Il supporto di avvio memorizza una serie primaria e secondaria di file di immagine ONTAP che il sistema utilizza all'avvio.



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla le unità ed esegue il software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un modulo DIMM (Dual in-line Memory Module) è un tipo di memoria per computer. Vengono installati per aggiungere memoria di sistema a una scheda madre del controller.



 a| 
link:drive-replace.html["Disco"]
 a| 
Un'unità è un dispositivo che fornisce l'archiviazione fisica necessaria per i dati.



 a| 
link:fan-swap-out.html["Ventola"]
 a| 
Una ventola raffredda la centralina.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
La NVRAM (non-volatile Random Access Memory) è un modulo che consente al controller di proteggere e salvare i dati in-flight in caso di interruzione dell'alimentazione del sistema. L'ID di sistema risiede nel modulo NVRAM. Una volta sostituito, il controller presuppone il nuovo ID di sistema dal modulo NVRAM sostitutivo.



 a| 
link:nvdimm-battery-replace.html["Batteria NV"]
 a| 
La batteria NV è responsabile dell'alimentazione al modulo NVRAM mentre i dati in-flight vengono trasferiti alla memoria flash dopo un'interruzione dell'alimentazione.



 a| 
link:io-module-overview.html["Modulo i/O."]
 a| 
Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



 a| 
link:power-supply-replace.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc-battery-replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria dell'orologio in tempo reale conserva le informazioni relative alla data e all'ora del sistema se l'alimentazione è spenta.



 a| 
link:system-management-replace.html["Modulo di gestione del sistema"]
 a| 
Il modulo di gestione del sistema fornisce l'interfaccia tra il controller e una console o un laptop per scopi di manutenzione del controller o del sistema. Il modulo di gestione del sistema contiene il supporto di avvio e memorizza il numero di serie del sistema (SSN).

|===