---
permalink: a70-90/maintain-overview.html 
sidebar: sidebar 
keywords: aff a70 aff a90 maintenance, maintenance, repairing aff a70 aff a90, repairing a70 aff a90, replace a70 aff a90 components 
summary: 'Eseguire la manutenzione dell"hardware AFF A70 e AFF A90' 
---
= Manutenzione dell'hardware AFF A70 e AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per i sistemi di archiviazione AFF A70 e AFF A90, è possibile eseguire le procedure di manutenzione sui seguenti componenti.



== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



== Disco

Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



== Ventola

La ventola raffredda il controller.



== NVRAM

La NVRAM (non-volatile Random Access Memory) è un modulo che consente al controller di proteggere e salvare i dati in-flight in caso di interruzione dell'alimentazione del sistema. L'ID di sistema risiede nel modulo NVRAM. Una volta sostituito, il controller presuppone il nuovo ID di sistema dal modulo NVRAM sostitutivo.



== Batteria NV

La batteria NVRAM alimenta il modulo NVRAM mentre i dati in-flight vengono trasferiti nella memoria flash in seguito a un'interruzione dell'alimentazione.



== Modulo i/O.

Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.



== Modulo di gestione del sistema

Il modulo di gestione del sistema fornisce l'interfaccia tra il controller e una console o un laptop per scopi di manutenzione del controller o del sistema. Il modulo di gestione del sistema contiene il supporto di avvio e memorizza il numero di serie del sistema (SSN).
