---
permalink: afx-2k/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, replace the chassis 
summary: Prima di sostituire lo chassis nel tuo sistema storage AFX 2K, assicurati di soddisfare i requisiti necessari per una sostituzione riuscita. Questo include la verifica che tutti gli altri componenti del sistema funzionino correttamente, che tu abbia le credenziali di amministratore locale per ONTAP, lo chassis di ricambio corretto e gli strumenti necessari. 
---
= Verifica i requisiti prima di sostituire il tuo chassis AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire lo chassis nel tuo sistema storage AFX 2K, assicurati di soddisfare i requisiti necessari per una sostituzione riuscita. Questo include la verifica che tutti gli altri componenti del sistema funzionino correttamente, che tu abbia le credenziali di amministratore locale per ONTAP, lo chassis di ricambio corretto e gli strumenti necessari.

Lo chassis è il telaio fisico che ospita tutti i componenti del sistema, come ventole, unità controller/CPU, NVRAM12, modulo di gestione del sistema, schede I/O e moduli di oscuramento, nonché alimentatori.

Esaminare i seguenti requisiti.

* Verificare che tutti gli altri componenti del sistema funzionino correttamente; in caso contrario, contattare per assistenza. http://mysupport.netapp.com/["Supporto NetApp"^]
* Ottenere le credenziali di amministratore locale per ONTAP se non si dispone di tali credenziali.
* Assicurarsi di disporre degli strumenti e delle attrezzature necessarie per la sostituzione.
* È possibile utilizzare la procedura di sostituzione dello chassis con tutte le versioni di ONTAP supportate dal sistema.
* La procedura di sostituzione dello chassis è scritta partendo dal presupposto che si stiano spostando la cornice, le ventole, il modulo controller, la NVRAM12, il modulo di gestione del sistema, le schede I/O e i moduli di oscuramento, nonché gli alimentatori nel nuovo chassis e che lo chassis sostitutivo sia un nuovo componente di NetApp.


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti,link:chassis-replace-prepare.html["preparati a sostituire il telaio"] .
