---
permalink: afx-2k/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: afx 2k, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Verifica che la configurazione HA del controller sia attiva e funzioni correttamente nel tuo sistema storage afx 2k e conferma che gli adattatori di sistema elenchino tutti i percorsi ai dischi. 
---
= Ripristina e verifica la configurazione di sistema - AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica che la configurazione HA del controller sia attiva e funzioni correttamente nel tuo sistema storage AFX 2K e conferma che gli adattatori del sistema elenchino tutti i percorsi ai dischi.



[[step-1-verify-ha-config-settings]]
== Fase 1: Verificare le impostazioni di configurazione ha

Verificare `HA` stato del modulo controller e, se necessario, aggiornare lo stato in modo che corrisponda alla configurazione del sistema.

. Avvio in modalità di manutenzione: `boot_ontap maint`
+
.. Immettere `y` quando viene visualizzato _continuare con boot?_.
+
Se viene visualizzato il messaggio di avviso _System ID mismatch_, immettere `y`.



. Immettere `sysconfig -v` e acquisire il contenuto del display.
+

NOTE: Se viene visualizzato _PERSONALITY MISMATCH_, contattare l'assistenza clienti.

. Dall' `sysconfig -v`uscita, confrontare le informazioni della scheda adattatore con le schede e le posizioni nella centralina sostitutiva.




[[step-2-verify-disk-list]]
== Passo 2: Verifica dell'elenco dei dischi

. Verificare che la scheda di rete elenchi i percorsi per tutti i dischi:
+
`storage show disk -p`

+
In caso di problemi, controllare il cablaggio e riposizionare i cavi.

. Uscire dalla modalità di manutenzione:
+
`halt`



.Quali sono le prossime novità?
Dopo aver ripristinato e verificato la configurazione del sistema storage AFX 2K, link:controller-replace-recable-reassign-disks.html["restituire il controller"].
