---
permalink: afx-2k/controller-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 2k, shut down the impaired controller 
summary: Arresta il controller nel tuo sistema storage afx 2k quando è guasto. Prima di eseguire manutenzione o sostituzione di componenti, è fondamentale arrestare il controller in modo sicuro per prevenire la perdita di dati e garantire la stabilità del sistema. 
---
= Spegni il controller guasto - AFX 2K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arresta il controller guasto nel tuo sistema storage AFX 2K per evitare la perdita di dati e garantire la stabilità del sistema quando sostituisci il controller.

Arrestare il modulo controller utilizzando una delle seguenti opzioni.

Prendere il controllo e arrestare il controller non funzionante in modo che il controller funzionante continui a fornire dati dalla memoria del controller non funzionante. Per fare questo, si sopprime la creazione automatica dei casi in AutoSupport, si disabilita il giveback automatico e si porta il controller non funzionante al prompt LOADER. Il prompt LOADER è lo stato di arresto sicuro da cui è possibile sostituire la FRU.

.A proposito di questa attività
* Se si dispone di un cluster con più di quattro nodi, è necessario che sia raggiunto il quorum.  Per visualizzare le informazioni del cluster sui nodi, utilizzare `cluster show` comando.  Per maggiori informazioni sul `cluster show` comando, vederelink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Visualizza i dettagli a livello di nodo in un cluster ONTAP"^] .
* Se il cluster non è in quorum o se lo stato di integrità o l'idoneità di un qualsiasi controller (diverso dal controller non funzionante) risulta falso, è necessario correggere il problema prima di arrestare il controller non funzionante. Vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^] .


.Fasi
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattivare il ritorno automatico dalla console del controllore non abilitato:
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Quando vedi _Vuoi disattivare la restituzione automatica?_, inserisci `y` .

. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Passare alla fase successiva.



 a| 
Prompt di sistema o prompt della password
 a| 
Prendere il controllo o interrompere il controllo del controllore sano da parte del controllore compromesso:
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Il parametro _-halt true_ porta il nodo danneggiato al prompt LOADER.

|===


.Quali sono le prossime novità?
Dopo aver spento il controller,link:controller-replace-move-hardware.html["sostituire la centralina"] .
