---
permalink: a900/chassis_replace_complete_system_restore_rma.html 
sidebar: sidebar 
keywords: aff a900, verify and set HA state, run diagnostics, complete the replacement process 
summary: Verificare lo stato ha dello chassis, eseguire la diagnostica e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Ripristinare e verificare la configurazione - AFF A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per completare la sostituzione dello chassis, è necessario completare attività specifiche.



== Fase 1: Verifica e impostazione dello stato ha dello chassis

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _ha-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** ha
*** non ha




. Verificare che l'impostazione sia stata modificata: `ha-config show`
. Se non lo si è già fatto, recuperare il resto del sistema.




== Fase 2: Richiamare il sistema

. In caso contrario, ricollegare i cavi di alimentazione alle PSU.
. Accendere le PSU portando il selettore su *ON* e attendere che i controller si accendano completamente.
. Dopo l'accensione, controllare la parte anteriore e posteriore dello chassis e dei controller per verificare l'eventuale presenza di spie di guasto.
. Connettersi all'indirizzo IP SP o BMC dei nodi tramite SSH. Questo sarà lo stesso indirizzo utilizzato per arrestare i nodi.
. Eseguire ulteriori controlli dello stato di salute come descritto in https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["How_to_Perform_a_cluster_Health_check_with_a_script_in_ONTAP"^]
. Riattivare AutoSupport (terminare il messaggio della finestra di manutenzione):
`system node autosupport invoke -node * -type all -message MAINT=end`


[]
====

NOTE: Come Best practice, devi effettuare le seguenti operazioni:

* Risolvere qualsiasi https://activeiq.netapp.com/["Avvisi e rischi relativi al benessere Active IQ"^] (Active IQ richiederà tempo per elaborare i servizi di assistenza automatica post-accensione - prevedendo un ritardo nei risultati)
* Eseguire https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* Controllare lo stato del sistema utilizzando https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["How_to_Perform_a_cluster_Health_check_with_a_script_in_ONTAP"^]


====


== Fase 3: Eseguire la diagnostica a livello di sistema

Dopo aver installato un nuovo chassis, eseguire la diagnostica di interconnessione.

.Prima di iniziare
Per avviare la diagnostica a livello di sistema, il sistema deve essere al prompt DEL CARICATORE.

Tutti i comandi delle procedure diagnostiche vengono emessi dalla centralina in cui viene sostituito il componente.

. Se il controller da sottoporre a manutenzione non viene visualizzato al prompt DEL CARICATORE, attenersi alla seguente procedura:
+
.. Selezionare l'opzione Maintenance mode (modalità manutenzione) dal menu visualizzato.
.. Una volta avviato il controller in modalità di manutenzione, arrestare il controller: `halt`
+
Dopo aver eseguito il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

+

NOTE: Durante il processo di avvio, è possibile rispondere in modo sicuro `y` a prompt:



. Ripetere il passaggio precedente sul secondo controller se si è in una configurazione ha.
+

NOTE: Per eseguire il test di interconnessione, entrambi i controller devono essere in modalità di manutenzione.

. Al prompt DEL CARICATORE, accedere ai driver speciali progettati appositamente per la diagnostica a livello di sistema per funzionare correttamente: `boot_diags`
+
Durante il processo di avvio, è possibile rispondere in modo sicuro `y` Fino a visualizzare il prompt della modalità di manutenzione (*>).

. Attivare i test di diagnostica di interconnessione dal prompt della modalità di manutenzione: `sldiag device modify -dev interconnect -sel enable`
+
I test di interconnessione sono disattivati per impostazione predefinita e devono essere attivati per essere eseguiti separatamente.

. Eseguire il test di diagnostica di interconnessione dal prompt della modalità di manutenzione: `sldiag device run -dev interconnect`
+
È sufficiente eseguire il test di interconnessione da un solo controller.

. Verificare che non vi siano problemi hardware dovuti alla sostituzione dello chassis: `sldiag device status -dev interconnect -long -state failed`
+
La diagnostica a livello di sistema riporta al prompt se non ci sono errori di test o elenca lo stato completo degli errori risultanti dal test del componente.

. Procedere in base al risultato del passaggio precedente.


|===
| Se il test di diagnostica a livello di sistema... | Quindi... 


 a| 
Sono stati completati senza guasti
 a| 
. Cancellare i registri di stato: `sldiag device clearstatus`
. Verificare che il registro sia stato cancellato: `sldiag device status`
+
Viene visualizzata la seguente risposta predefinita:

+
[listing]
----
SLDIAG: No log messages are present.
----
. Uscire dalla modalità di manutenzione su entrambi i controller: `halt`
+
Il sistema visualizza il prompt DEL CARICATORE.

+

NOTE: Prima di procedere, uscire dalla modalità di manutenzione su entrambi i controller.

. Immettere il seguente comando su entrambi i controller al prompt DEL CARICATORE: `bye`
. Ripristinare il normale funzionamento del controller.


|===
|===
| Se sul sistema è in esecuzione ONTAP... | Quindi... 


 a| 
Con due nodi nel cluster
 a| 
Eseguire questi comandi: `node::> cluster ha modify -configured true``node::> storage failover modify -node node0 -enabled true`



 a| 
Con più di due nodi nel cluster
 a| 
Eseguire questo comando:``node::> storage failover modify -node node0 -enabled true``



 a| 
In una configurazione standalone
 a| 
Non hai ulteriori passaggi in questa specifica attività. La diagnostica a livello di sistema è stata completata.



 a| 
Ha causato alcuni errori di test
 a| 
Determinare la causa del problema.

. Uscire dalla modalità di manutenzione: `halt`
. Eseguire un arresto pulito, quindi scollegare gli alimentatori.
. Verificare di aver osservato tutte le considerazioni identificate per l'esecuzione della diagnostica a livello di sistema, che i cavi siano collegati saldamente e che i componenti hardware siano installati correttamente nel sistema di storage.
. Ricollegare gli alimentatori, quindi accendere il sistema storage.
. Eseguire nuovamente il test di diagnostica a livello di sistema. + se il test di diagnostica a livello di sistema non riesce di nuovo, contattare link:http://mysupport.netapp.com/["mysupport.netapp.com"^].


|===


== Fase 4: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
