---
permalink: asa800/install-videos.html 
sidebar: sidebar 
keywords: asa a800, hardware installation and cabling video, perform end-to-end software configuration video 
summary: 'Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.' 
---
= Video - ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.



== Video uno di due: Installazione hardware e cablaggio

Il seguente video mostra come installare e collegare il nuovo sistema.

."Animazione - Installazione e configurazione di un AFF A800
video::2a61ed74-a0ce-46c3-86d2-ab4b013c0030[panopto]

NOTE: Il sistema ASA A800 utilizza la stessa procedura di installazione del sistema AFF A800.



== Video due di due: Esecuzione della configurazione software end-to-end

Il seguente video mostra la configurazione software end-to-end per i sistemi che eseguono ONTAP 9.2 e versioni successive.

video::WAE0afWhj1c?[youtube]