---
permalink: asa800/overview.html 
sidebar: sidebar 
keywords: ASA A800 specifications, ASA A800 specs, NetApp ASA A800, ASA A800 hardware 
summary: Specifiche principali per il sistema di archiviazione ASA A800 
---
= Specifiche chiave per ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' ASA A800.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche ASA A800 .  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per ASA A800

Configurazione della piattaforma: coppia HA a telaio singolo ASA A800

Capacità massima grezza: 6,6096 PB

Memoria: 1280.0000 GB

Fattore di forma: chassis 4U con 2 controller HA e 48 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 10

Versione minima ONTAP : ONTAP 9.13.1



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS |  |  |  


| SAN | 6 | 39,7 PB / 35,2 PiB | 7680 GB 


| Coppia HA |  | 6,6 PB / 5,9 PiB | 1280,0000 
|===


=== Io



==== IO di bordo

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 4 
|===


==== IO totale

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 20 


| Ethernet 25 Gbps | 16 


| Ethernet 10 Gbps | 32 


| FC 32 Gbps | 32 


| NVMe/FC 32 Gbps | 32 


|  | 0 


|  | 0 


| SAS 12 Gbps | 32 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rete di archiviazione supportata

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== Specifiche dell'ambiente di sistema

Nessun dato ambientale disponibile.



=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo; Gestione in banda SAS su connessioni SAS per ripiani esterni; [//] 2025-10-15 ontap-systems-internal/issues/1357
