---
permalink: a200/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a200, shut down the controller, manual, manual boot recovery 
summary: Arresta il controller nel tuo sistema storage AFF A200 per evitare la perdita di dati e mantenere la stabilità del sistema durante il processo di ripristino manuale del supporto di boot. 
---
= Spegni il controller in un sistema AFF A200 durante il processo di ripristino manuale dell'avvio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arresta il controller nel tuo sistema storage AFF A200 per evitare la perdita di dati e mantenere la stabilità del sistema durante il processo di ripristino manuale del supporto di boot.

Completare l'arresto del controller danneggiato arrestandolo al prompt LOADER e acquisendo le variabili di ambiente di avvio. Il prompt LOADER è lo stato di arresto sicuro da cui è possibile sostituire il supporto di avvio.

.Fasi
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
`Waiting for giveback...`
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode impaired_node_name`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===
. Dal prompt DEL CARICATORE, immettere: `printenv` per acquisire tutte le variabili ambientali di avvio. Salvare l'output nel file di log.
+

NOTE: Questo comando potrebbe non funzionare se il dispositivo di boot è corrotto o non funzionante.


