---
permalink: a200/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a200, shut down the controller, manual, manual boot recovery 
summary: 'Dopo aver completato le attività NVE o NSE, è necessario completare l"arresto del controller danneggiato. Il sistema AFF A200 supporta solo procedure di ripristino manuale tramite supporti di avvio.' 
---
= Spegnere il controller non utilizzato - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Spegnere il controller danneggiato utilizzando la procedura appropriata per la configurazione in uso. Il sistema AFF A200 supporta solo procedure di ripristino manuale tramite supporti di avvio. Il ripristino automatico del supporto di avvio non è supportato.

Dopo aver completato le attività NVE o NSE, è necessario completare l'arresto del controller compromesso.

.Fasi
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
`Waiting for giveback...`
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode impaired_node_name`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===
. Dal prompt DEL CARICATORE, immettere: `printenv` per acquisire tutte le variabili ambientali di avvio. Salvare l'output nel file di log.
+

NOTE: Questo comando potrebbe non funzionare se il dispositivo di boot è corrotto o non funzionante.


