---
permalink: a200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, replace the chassis 
summary: Il nuovo telaio dello stesso modello del telaio compromesso viene sostituito da un telaio non valido. 
---
= Esamina i requisiti per la sostituzione di uno chassis in un sistema AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire lo chassis nel tuo sistema AFF A200, verifica i requisiti per una sostituzione riuscita. La procedura di sostituzione dello chassis prevede lo spostamento di tutti gli alimentatori, le unità e i moduli controller dallo chassis guasto a quello di ricambio ed è un'operazione che comporta interruzioni.

.Prima di iniziare
Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

.A proposito di questa attività
* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura si basa sul presupposto che si stiano spostando tutti i dischi e i moduli controller nel nuovo chassis e che lo chassis sia un nuovo componente di NetApp.
* Questa procedura ha un'interruzione. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

