---
permalink: a200/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a200, verify and set HA state,  complete the replacement process 
summary: Verificare lo stato ha del telaio e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Ripristinare e verificare la configurazione - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== Fase 1: Verificare e impostare lo stato ha del telaio

[role="lead"]
È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

.Fasi
. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _HA-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** `ha`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.




== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
