---
permalink: a200/controller-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, prerequisite, replace the controller module 
summary: È necessario esaminare i prerequisiti per la procedura di sostituzione e selezionare quello corretto per la versione del sistema operativo ONTAP in uso. 
---
= Panoramica della sostituzione del modulo controller - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario esaminare i prerequisiti per la procedura di sostituzione e selezionare quello corretto per la versione del sistema operativo ONTAP in uso.

.Di cosa hai bisogno
* Tutti gli shelf di dischi devono funzionare correttamente.
* Se il sistema si trova in una coppia ha, il controller integro deve essere in grado di assumere il controllo che viene sostituito (indicato in questa procedura come "`nodo alterato`").


.A proposito di questa attività
* È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.
* È necessario sostituire un modulo controller con un modulo controller dello stesso tipo di modello. Non è possibile aggiornare il sistema semplicemente sostituendo il modulo controller.
* Non è possibile modificare dischi o shelf di dischi come parte di questa procedura.
* In questa procedura, il dispositivo di boot viene spostato dal controller guasto al nodo _replacement_ in modo che il nodo _replacement_ si avvii nella stessa versione di ONTAP del vecchio modulo controller.
* È importante applicare i comandi descritti di seguito ai sistemi corretti:
+
** Il nodo _alterato_ è il controller che viene sostituito.
** Il nodo _replacement_ è il nuovo controller che sostituisce il controller compromesso.
** Il nodo _healthy_ è il controller sopravvissuto.


* È sempre necessario acquisire l'output della console del controller in un file di testo.
+
In questo modo è possibile registrare la procedura per risolvere eventuali problemi riscontrati durante il processo di sostituzione.


