---
permalink: a220/maintain-overview.html 
sidebar: sidebar 
keywords: aff 220 maintenance, maintenance, repairing 220, repairing asa 220, replace aff 220 components, replace aff 220 components 
summary: 'Manutenzione dell"hardware AFF A220' 
---
= Scopri come effettuare la manutenzione del tuo sistema storage AFF A220
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema storage AFF A220, è possibile eseguire le procedure di manutenzione dei seguenti componenti.



[[boot-media]]
== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



[[chassis]]
== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



[[controller]]
== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



[[dimm]]
== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



[[drive]]
== Disco

Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



[[nvem-battery]]
== Batteria NVEM

Una batteria è inclusa in un controller e conserva i dati memorizzati nella cache in caso di interruzione dell'alimentazione CA.



[[power-supply]]
== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



[[real-time-clock-battery]]
== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
