---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione sui sistemi hardware ONTAP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità per i sistemi hardware ONTAP
      url: "/whats-new.html"
    - title: Compatibilità hardware e software ONTAP
      url: "/supported-platforms.html"
    - title: Fine supporto
      url: "/eoa-hardware.html"
  - title: Avvio rapido
    url: "/get-up-and-run.html"
  - title: Sistemi AFF
    url: "/aff-landing/index.html"
    entries:
    - title: Sistemi a-Series
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: Sistemi C-Series
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
  - title: Sistemi AFX
    url: "/afx/index.html"
    entries:
    - title: Installazione e configurazione
      url: "/afx/afx-install-setup.html"
    - title: Mantenere
      pdf-filename: AFX Mantieni
      url: "/afx-landing-maintain/index.html"
      entries:
      - title: Panoramica della manutenzione
        url: "/afx-1k/maintain-overview.html"
      - title: Supporto di boot
        pdf-filename: Supporto di avvio AFX 1K
        entries:
        - title: Flusso di lavoro per la sostituzione dei supporti di avvio
          url: "/afx-1k/bootmedia-replace-workflow.html"
        - title: Verifica dei requisiti
          url: "/afx-1k/bootmedia-replace-requirements.html"
        - title: Arrestare il controller
          url: "/afx-1k/bootmedia-shutdown.html"
        - title: Sostituire il supporto di avvio
          url: "/afx-1k/bootmedia-replace.html"
        - title: Ripristinare il supporto di avvio
          url: "/afx-1k/bootmedia-recovery-image-boot.html"
        - title: Restituire la parte guasta a NetApp
          url: "/afx-1k/bootmedia-complete-rma.html"
      - title: Chassis
        pdf-filename: Telaio AFX A1K
        entries:
        - title: Flusso di lavoro per la sostituzione dello chassis
          url: "/afx-1k/chassis-replace-workflow.html"
        - title: Verifica dei requisiti
          url: "/afx-1k/chassis-replace-requirements.html"
        - title: Prepararsi alla sostituzione
          url: "/afx-1k/chassis-replace-prepare.html"
        - title: Arrestare il controller
          url: "/afx-1k/chassis-replace-shutdown.html"
        - title: Sostituire il telaio
          url: "/afx-1k/chassis-replace-move-hardware.html"
        - title: Sostituzione completa dello chassis
          url: "/afx-1k/chassis-replace-complete-system-restore-rma.html"
      - title: Controller
        pdf-filename: Controller AFX 1K
        entries:
        - title: Workflow di sostituzione del controller
          url: "/afx-1k/controller-replace-workflow.html"
        - title: Verifica dei requisiti
          url: "/afx-1k/controller-replace-requirements.html"
        - title: Spegnere il controller compromesso
          url: "/afx-1k/controller-replace-shutdown.html"
        - title: Sostituire il controller
          url: "/afx-1k/controller-replace-move-hardware.html"
        - title: Ripristinare la configurazione del sistema
          url: "/afx-1k/controller-replace-system-config-restore-and-verify.html"
        - title: Restituire il controller
          url: "/afx-1k/controller-replace-recable-reassign-disks.html"
        - title: Sostituzione completa del controller
          url: "/afx-1k/controller-replace-restore-system-rma.html"
      - title: DIMM
        url: "/afx-1k/dimm-replace.html"
      - title: Ventola
        url: "/afx-1k/fan-replace.html"
      - title: NVRAM
        url: "/afx-1k/nvram-replace.html"
      - title: Batteria NV
        url: "/afx-1k/nvdimm-battery-replace.html"
      - title: Modulo i/O.
        pdf-filename: Modulo AFX 1K IO
        entries:
        - title: Panoramica del modulo di i/O.
          url: "/afx-1k/io-module-overview.html"
        - title: Aggiungere il modulo i/O.
          url: "/afx-1k/io-module-add.html"
        - title: Modulo I/O swap a caldo
          url: "/afx-1k/io-module-hotswap.html"
        - title: Sostituire il modulo i/O.
          url: "/afx-1k/io-module-replace.html"
      - title: Alimentatore
        url: "/afx-1k/power-supply-replace.html"
      - title: Batteria con orologio in tempo reale
        url: "/afx-1k/rtc-battery-replace.html"
      - title: Modulo di gestione del sistema
        url: "/afx-1k/system-management-replace.html"
  - title: Sistemi ASA
    url: "/allsan-landing/index.html"
    entries:
    - section: asa150
    - section: asa250
    - section: asa400
    - section: asa800
    - section: asa900
  - title: Sistemi ASA r2
    url: "/asa-r2/index.html"
    entries:
    - title: Installazione e configurazione
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: Mantenere
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
      - section: asa-r2-a20-30-50-maintain
      - section: asa-r2-c30-maintain
    - section: asa-r2-key-specifications
  - title: Sistemi FAS
    url: "/fas/index.html"
    entries:
    - section: fas50
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: Sistemi di fine disponibilità
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: asa-c250
    - section: asa-c400
    - section: asa-c800
    - section: c190
    - section: c800
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: Altri modelli
      url: "/other/other-models.html"
  - title: Shelf di dischi
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: nx224
    - section: sas3
  - title: Cabinet e kit di guide
    entries:
    - title: Kit SuperRail
      url: "/platform-supplemental/superrail-install.html"
    - title: Kit guide a due montanti AFF A700/FAS9000
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: Cabinet di sistema 42U da 1280 mm
      entries:
      - title: Preparazione per l'installazione del cabinet
        entries:
        - title: Caratteristiche del cabinet
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: Strumenti/apparecchiature necessari
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: Requisiti di spazio e dimensioni del cabinet
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: Specifiche e tipi di PDU supportati
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: Disimballare l'armadietto del sistema
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: Installare l'armadio
        entries:
        - title: Panoramica
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: Installare il kit di interconnessione del cabinet
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: Installare il kit di bulloni
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: Installare le guide di supporto
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: Installare l'apparecchiatura
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: Accendere l'armadio
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: Sostituire le PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: Sportello anteriore dell'armadio inverso
        entries:
        - title: Di cosa hai bisogno
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: Rimuovere il logo illuminato
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: Rimuovere lo sportello del cabinet
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: Spostare l'alimentatore e il cablaggio del badge
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: Invertire la cerniera dello sportello e il fermo di blocco
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: Reinstallare lo sportello e il logo illuminato
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: Procedure di sostituzione per componente
    url: "/fru-reference/index.html"
    entries:
    - title: Supporto di boot
      url: "/fru-reference/bootmedia-fru-links.html"
    - title: Modulo di caching
      url: "/fru-reference/caching-module-fru-links.html"
    - title: Chassis
      url: "/fru-reference/chassis-fru-links.html"
    - title: Controller
      url: "/fru-reference/controller-fru-links.html"
    - title: Modulo di potenza DCPM
      url: "/fru-reference/dcpm-power-fru-links.html"
    - title: DIMM
      url: "/fru-reference/dimm-fru-links.html"
    - title: Disco
      url: "/fru-reference/drive-fru-links.html"
    - title: Ventola
      url: "/fru-reference/fan-fru-links.html"
    - title: Modulo i/O.
      url: "/fru-reference/io-module-fru-links.html"
    - title: modulo LED
      url: "/fru-reference/led-module-fru-links.html"
    - title: Mezzanino
      url: "/fru-reference/mezzanine-fru-links.html"
    - title: NVDIMM
      url: "/fru-reference/nvdimm-fru-links.html"
    - title: Batteria NVMEM/ NVRAM
      url: "/fru-reference/nvmem-battery-fru-links.html"
    - title: Modulo NVRAM
      url: "/fru-reference/nvram-module-fru-links.html"
    - title: NSM
      url: "/fru-reference/nsm-fru-links.html"
    - title: Schede PCI e riser
      url: "/fru-reference/pci-cards-fru-links.html"
    - title: Alimentatore
      url: "/fru-reference/power-supply-fru-links.html"
    - title: Batteria RTC
      url: "/fru-reference/rtc-battery-fru-links.html"
    - title: Modulo di gestione del sistema
      url: "/fru-reference/system-management-fru-links.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
