---
permalink: a200/replace_internal_drive.html 
sidebar: sidebar 
keywords: AFF A200 
summary: Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso. 
---
= Sostituire il disco guasto - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario sostituire un modulo DIMM nel modulo controller quando il sistema registra un numero crescente di codici di correzione degli errori correggibili (ECC); in caso contrario, si verifica un errore di sistema.

.Prima di iniziare
* La procedura consigliata consiste nell'installare la versione corrente del Disk Qualification Package (DQP) prima di sostituire a caldo un disco.
* Identificare il disco guasto eseguendo il `storage disk show -broken` dalla console di sistema. Il disco guasto viene visualizzato nell'elenco dei dischi guasti. In caso contrario, attendere ed eseguire nuovamente il comando.
* La modalità di sostituzione a caldo del disco dipende dal modo in cui viene utilizzato il disco. Se l'autenticazione SED è attivata, è necessario utilizzare le istruzioni per la sostituzione SED contenute in https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["Guida alla potenza della crittografia NetApp per ONTAP 9"]. Le presenti istruzioni descrivono i passaggi aggiuntivi da eseguire prima e dopo la sostituzione di un SED.
* L'unità sostitutiva deve essere supportata dalla piattaforma. Vedere https://hwu.netapp.com["NetApp Hardware Universe"].
* Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.


.A proposito di questa attività
Il firmware del disco viene aggiornato automaticamente (senza interruzioni) sui nuovi dischi con versioni firmware non correnti.

Quando si sostituiscono più dischi, è necessario attendere un minuto tra la rimozione di ciascun disco guasto e l'inserimento dell'unità disco sostitutiva per consentire al sistema di storage di riconoscere l'esistenza di ciascun nuovo disco.

[role="tabbed-block"]
====
.Opzione 1: Sostituire l'SSD
--
Direttiva irrisolta in <stdin> - include:../_include/drive_hotswap_sas.adoc[]

--
.Opzione 2: Sostituire il disco rigido
--
Direttiva irrisolta in <stdin> - include:../_include/drive_hotswap_sas.ado.ado[]

--
====