---
sidebar: sidebar 
permalink: supported-platforms.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Scopri la versione supportata di ONTAP per la tua piattaforma o shelf. 
---
= Compatibilità hardware e software ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
I sistemi di storage ONTAP sono compatibili con diverse versioni del software ONTAP. Scopri le versioni di ONTAP supportate dai tuoi sistemi storage e dagli shelf di dischi.

Il supporto completo della configurazione e le limitazioni per i sistemi hardware ONTAP sono disponibili in  https://hwu.netapp.com["NetApp Hardware Universe"]. I dettagli sui problemi noti, le limitazioni e le precauzioni per l'aggiornamento nel software ONTAP 9 sono disponibili nella https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"] .

[role="tabbed-block"]
====
.Sistemi AFF
--
I sistemi AFF A-Series e AFF C-Series offrono una piattaforma scale-out efficace e adatta ad ambienti virtualizzati. Possono essere implementati come sistemi standalone o come Tier dalle performance elevate nelle configurazioni NetApp ONTAP. Ulteriori informazioni su link:https://www.netapp.com/aff-a-series/["Sistemi AFF A-Series"] e link:https://www.netapp.com/aff-c-series/["Sistemi AFF C-Series"].

I sistemi AFF serie A e AFF C-Series sono supportati A partire dalle seguenti versioni di ONTAP.

ONTAP 9.16.1::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15.1::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10.1::
+
--
* AFF A900


--
ONTAP 9.8::
+
--
* AFF A250


--
ONTAP 9.7::
+
--
* AFF A400
* AFF A800


--


--
.Sistemi AFX
--
I sistemi AFX forniscono una soluzione disaggregata progettata per soddisfare i rigorosi requisiti dei carichi di lavoro NAS e S3 ad alte prestazioni, comprese le applicazioni AI/ML. link:https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["Scopri di più sul sistema AFX"^] .

I sistemi AFX sono supportati a partire dalla versione ONTAP successiva.

ONTAP 9.17.1::
+
--
* AFX 1K


--


--
.Sistemi ASA r2
--
I sistemi ASA r2 offrono una soluzione hardware e software unificata che crea un'esperienza semplificata specifica per le esigenze dei clienti SAN-only. link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Ulteriori informazioni sui sistemi ASA R2"^] .

I sistemi ASA R2 sono supportati a partire dalle seguenti versioni di ONTAP.

ONTAP 9.16.1::
+
--
* ASA A20
* ASA A30
* ASA A50
* ASA C30


--
ONTAP 9.16.0::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.Sistemi ASA
--
I sistemi ASA A-Series e ASA C-Series offrono un'esperienza SAN semplificata e dedicata che fornisce una disponibilità continua dei dati per database Enterprise mission-critical e altri carichi di lavoro SAN utilizzando il protocollo FCP o iSCSI. link:https://www.netapp.com/asa/["Ulteriori informazioni sui sistemi ASA"].

I sistemi ASA sono supportati a partire dalle seguenti versioni di ONTAP.

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9.8::
+
--
* ASA AFF A250
* ASA AFF A800


--
ONTAP 9.7::
+
--
* ASA AFF A400


--


--
.Sistemi FAS
--
I sistemi FAS offrono uno storage secondario efficiente e sicuro, la soluzione definitiva per tiering, backup e disaster recovery. link:https://www.netapp.com/data-storage/fas/["Scopri di più sui sistemi FAS"].

I sistemi FAS sono supportati a partire dalle seguenti versioni di ONTAP.

ONTAP 9.16.1::
+
--
* FAS50


--
ONTAP 9.15.1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1::
+
--
* FAS2820


--
ONTAP 9.11.1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9.7::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.Shelf di dischi
--
Gli scaffali delle unità sono progettati specificamente per i sistemi NetApp AFF, AFX, ASA e FAS e contribuiscono a fornire le prestazioni, la resilienza e la flessibilità di cui la tua trasformazione digitale ha bisogno.

Gli shelf di dischi sono disponibili a partire dalle seguenti release di ONTAP.

ONTAP 9.17.1::
+
--
* Mensola NSX224 per sistemi AFX


--
ONTAP 9.16.1::
+
--
* DCM3 per ripiani SAS-3
* NS224 con NSM100B moduli


--
ONTAP 9.6:: NS224 shelf con NSM100 moduli


--
====