---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, fas, aff systems 
summary: Scopri le nuove funzionalità dei sistemi FAS e AFF. 
---
= Novità per i sistemi FAS e AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità dei sistemi FAS e AFF.



== Nuovo supporto adattatore

[cols="4*"]
|===
| Numero di parte dell'adattatore | Descrizione | Categoria | Inizio disponibile 


 a| 
https://hwu.netapp.com/adapter/index["X91148A"]
 a| 
RoCE QSFP28 da 100 GbE a 2 porte
 a| 
* Storage
* Networking
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X91122A"]
 a| 
RoCE QSFP28 a 2 porte da 25 GbE
 a| 
* Networking
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X9170A"]
 a| 
Modulo SSD NVMe (1 TB)
 a| 
Dispositivo core dump
 a| 
ONTAP 9.8

|===


== Nuovo supporto switch

[cols="25h,~,~"]
|===
| Switch | Descrizione | Inizio disponibile 


 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 36 porte (X190200)"]
 a| 
Supporta un'infrastruttura condivisa (cluster, ha e storage collegato a switch) sulla stessa coppia di switch Cisco Nexus 9336C-FX2, incluso il supporto per le configurazioni IP MetroCluster.
 a| 
ONTAP 9.9.1



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 36 porte (X190200 e X190210)"]
 a| 
Switch di interconnessione cluster e storage switch Cisco Nexus 9336C-FX2 per controller AFF/FAS e connettività dati front-end.
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Supporto di switch di interconnessione cluster Broadcom BES-53248 per controller AFF/FAS con porte 40/100GbE.
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 36 porte (X190200)"] https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 32 porte (X190100 e X190100R)"]
 a| 
Lo switch Cisco Nexus 100 GbE può essere utilizzato come switch storage dedicato per collegare gli shelf di dischi NS224 NVMe alle seguenti piattaforme:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Supporto di switch di interconnessione cluster Broadcom BES-53248 per controller AFF/FAS con porte 10 GbE.
 a| 
ONTAP 9.5P8

|===


== Supporto di una nuova piattaforma

[cols="2*"]
|===
| Piattaforme (con link alle schede tecniche) | Inizio disponibile 


 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS9500"]
 a| 
ONTAP 9.10.1P3 e 9.11.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/us/media/ds-3989.pdf["AFF C190"]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===


== Nuovo supporto per gli shelf

[cols="2*"]
|===
| Shelf | Inizio disponibile 


 a| 
NS224
 a| 
ONTAP 9.6

|===


== Nuovi aggiornamenti hardware

[cols="25h,~,~"]
|===
| Funzionalità | Descrizione e dove saperne di più | Inizio disponibile 


 a| 
Supporto esteso della piattaforma per shelf di dischi NS224
 a| 
Le seguenti piattaforme supportano gli shelf di dischi NS224:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A250/AFF ASA A250
* FAS500f

 a| 
ONTAP 9.8



 a| 
Aggiunta a caldo di shelf SAS da 12 GB a stack di storage SAS da 6 GB
 a| 
È ora supportata una transizione a velocità singola da 6 GB a 12 GB in uno stack di storage SAS. Ciò consente l'espansione dello storage degli stack da 6 GB esistenti con shelf da 12 GB.

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Shelf hot-adding con moduli IOM12 a uno stack di shelf con moduli IOM6"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===


== Nuovi miglioramenti per l'aggiornamento dell'hardware

Le procedure di aggiornamento dell'hardware sono state semplificate in ONTAP 9.8 con l'introduzione della funzione di posizionamento automatico delle porte. Quando si esegue l'aggiornamento di un sistema con ONTAP 9.8, è necessario utilizzare la procedura corretta per tenere conto della funzione di posizionamento delle porte.

Consultare la seguente tabella per consultare le procedure di aggiornamento disponibili. Per ulteriori dettagli, consultare ciascuna guida per determinare se la procedura è appropriata.

Per ulteriori procedure specifiche di MetroCluster, vedere https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["Scelta di un metodo di aggiornamento o refresh"].

[cols="4*"]
|===
| Versione di ONTAP | Posizione | Senza interruzioni | Supporta MetroCluster 


 a| 
da 9.8 a 9.0.x
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-decide-to-use-this-guide.html["Guida rapida all'aggiornamento dell'hardware del controller"] (Spostamento dello storage fisico esistente)
 a| 
No
 a| 
No



 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-decide-to-use-this-guide.html["Guida rapida all'aggiornamento dell'hardware del controller"] (Spostamento dei volumi in un nuovo storage)
 a| 
Sì
 a| 
No



 a| 
9.8
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-decide-to-use-this-guide.html["Utilizzare i comandi "`sSystem controller replace`" per aggiornare l'hardware del controller con ONTAP 9.8"]
 a| 
Sì
 a| 
Sì (FC)



 a| 
9.8
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/index.html["Utilizzare il trasferimento aggregato per aggiornare manualmente l'hardware del controller con ONTAP 9.8 o versione successiva"]
 a| 
Sì
 a| 
Sì (FC)



 a| 
da 9.7 a 9.5
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/index.html["Utilizzare i comandi "`sSystem controller replace`" per aggiornare l'hardware del controller che esegue ONTAP 9.5 a ONTAP 9.7"]
 a| 
Sì
 a| 
Sì (FC)



 a| 
9.7 e versioni precedenti
 a| 
https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/index.html["Aggiornamento dei controller con trasferimento aggregato per aggiornare manualmente l'hardware del controller con ONTAP 9.7 e versioni precedenti"]
 a| 
Sì
 a| 
Sì (FC)

|===