---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: Scopri le nuove piattaforme per i sistemi hardware ONTAP. 
---
= Novità dei sistemi hardware ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le novità dei sistemi hardware ONTAP.



== Dicembre 2024



=== AFF A20, AFF A30 e AFF A50

I nuovi sistemi hardware AFF A20, A30 e A50 estendono funzioni di gestione dei dati complete, intelligenti e dalle performance elevate per un numero maggiore di clienti e carichi di lavoro.

I sistemi offrono il rilevamento del ransomware basato su ML in real-time, un'integrazione del cloud perfetta e performance senza pari per carichi di lavoro mission-critical tra cui ai, VMware, database e analytics, con supporto per storage a blocchi, file e oggetti.

link:https://www.netapp.com/data-storage/aff-a-series/["Ulteriori informazioni sui sistemi AFF A-Series"].



=== AFF C30, AFF C60 e AFF C80

I nuovi sistemi hardware AFF C30, AFF C60 e AFF C80 rendono più accessibili alle aziende i vantaggi in termini di performance ed efficienza della tecnologia flash, offrendo 1,5PB PB di capacità dello storage leader di settore in implementazioni a due rack.

La soluzione offre densità eccezionale con dischi da 60TB TB, maggiori performance e una maggiore flessibilità i/O.

link:https://www.netapp.com/data-storage/aff-c-series/["Ulteriori informazioni sui sistemi AFF C-Series"].



=== Shelf di dischi NS224 con moduli shelf NSM100B

Migliora le funzionalità dei tuoi data center con NS224 e il nuovo modulo di espansione dello storage NSM100B NVMe. Progettato come sostituto diretto del modulo NSM100, il nuovo modulo NSM100B si integra perfettamente nella configurazione esistente. Supporta sia configurazioni a collegamento diretto che a collegamento switch di NS224 shelf, offrendo una flessibilità eccezionale per ottimizzare l'efficienza e la scalabilità del tuo sistema storage.



== Settembre 2024



=== Sistemi ASA r2

I nuovi sistemi hardware ASA R2 (ASA A1K, ASA A70 e ASA A90) forniscono una soluzione hardware e software unificata che crea un'esperienza semplificata specifica per le esigenze dei clienti che utilizzano solo SAN.

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Ulteriori informazioni sui sistemi ASA R2"].



=== FAS70 e FAS90

I nuovi sistemi hardware FAS70 ed FAS90 offrono uno storage di backup conveniente ma con performance elevate, consentendo un vault informatico sicuro per il recovery dagli attacchi ransomware.

link:https://www.netapp.com/data-storage/fas/["Scopri di più sui sistemi FAS"].
