---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features,aff, asa,  fas, legacy, end-of-support 
summary: 'Scopri le nuove funzionalità dei sistemi AFF, ASA e FAS e l"hardware legacy non più supportato.' 
---
= Novità dei sistemi AFF, ASA e FAS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le nuove funzionalità dei sistemi AFF, ASA e FAS.

Per informazioni dettagliate su problemi noti, limitazioni e avvisi di aggiornamento nelle versioni di ONTAP 9, fare riferimento alla https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Note sulla versione di ONTAP 9"]. Per accedere alle Note di rilascio, è necessario accedere con l'account NetApp o creare un account.



== Supporto di una nuova piattaforma

[cols="2*"]
|===
| Piattaforme (con link alle schede tecniche) | Inizio disponibile 


 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C250"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C400"]
 a| 
ONTAP 9.13.1P1



 a| 
https://www.netapp.com/data-storage/all-flash-san-storage-array/["ASA C800"]
 a| 
ONTAP 9,13.P11



 a| 
https://hwu.netapp.com/ProductSpecs/Index["FAS2820"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A150"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A250"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A400"]
 a| 
ONTAP 9.13.1



 a| 
https://www.netapp.com/pdf.html?item=/media/85736-DS-4254-NetApp-ASA.pdf["ASA A900"]
 a| 
ONTAP 9.13.1



 a| 
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C250"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C400"]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf["AFF C800"]

 a| 
ONTAP 9.12.1P1

ONTAP 9.13.1 GA e versioni successive di ONTAP

[NOTE]
====
Queste piattaforme non sono supportate con ONTAP 9.13.1 RC1.

====


 a| 
https://www.netapp.com/pdf.html?item=/media/7828-DS-3582-AFF-A-Series.pdf["AFF A150"]

[NOTE]
====
Non tentare di installare o avviare il sistema di archiviazione AFF A150 con una versione non supportata di ONTAP. Se si tenta di installare o avviare il sistema con una versione non supportata di ONTAP, ONTAP lo consentirà (ONTAP non bloccherà il tentativo). Di conseguenza, il sistema di storage AFF A150 diventerà un sistema di storage FAS2750.

==== a| 
ONTAP 9.13.1 e versioni successive di ONTAP

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS9500"]
 a| 
ONTAP 9.11.1

ONTAP 9.10.1P3



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A900"]
 a| 
ONTAP 9.10.1



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A250/AFF ASA A250"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS500f"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A800"]
 a| 
ONTAP 9.8



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8300"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FAS8700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF A400"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF ASA A220"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/pdf.html?item=/media/7828-ds-3582.pdf["AFF ASA A700"]
 a| 
ONTAP 9.7



 a| 
https://www.netapp.com/us/media/ds-3989.pdf["AFF C190"]
 a| 
ONTAP 9.6



 a| 
https://www.netapp.com/pdf.html?item=/media/17190-na-382.pdf["AFF A320"]
 a| 
ONTAP 9.6

|===


== Nuovo supporto switch

[cols="20,65,15"]
|===
| Switch | Descrizione | Inizio disponibile 


 a| 
https://hwu.netapp.com/Switch/Index["SWITCH NVIDIA IP SN2100"]
 a| 
Lo switch di storage NVIDIA IP SN2100 è supportato nelle configurazioni MetroCluster IP che utilizzano le piattaforme A900/FAS9500.
 a| 
ONTAP 9.12.1



 a| 
https://hwu.netapp.com/Switch/Index["SWITCH NVIDIA IP SN2100 (X190006)"]
 a| 
Lo switch di storage NVIDIA IP SN2100 è supportato nelle configurazioni IP di MetroCluster che utilizzano le seguenti piattaforme:

* FAS500f/AFF A250
* FAS8300/AFF A400
* FAS8700
* FAS9000/AFF A700
* AFF A800

 a| 
ONTAP 9.10.1P3



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 36 porte (X190200)"]
 a| 
Supporta un'infrastruttura condivisa (cluster, ha e storage collegato a switch) sulla stessa coppia di switch Cisco Nexus 9336C-FX2, incluso il supporto per le configurazioni IP MetroCluster.
 a| 
ONTAP 9.9.1



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 36 porte (X190200 e X190210)"]
 a| 
Switch di interconnessione cluster e storage switch Cisco Nexus 9336C-FX2 per controller AFF/FAS e connettività dati front-end.
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Supporto di switch di interconnessione cluster Broadcom BES-53248 per controller AFF/FAS con porte 40/100GbE.
 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 36 porte (X190200)"] https://hwu.netapp.com/Switch/Index["Switch Cisco 100 GbE a 32 porte (X190100 e X190100R)"]
 a| 
Lo switch Cisco Nexus 100 GbE può essere utilizzato come switch storage dedicato per collegare gli shelf di dischi NS224 NVMe alle seguenti piattaforme:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A400/AFF ASA A400
* AFF A320

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/Switch/Index["Switch Broadcom BES-53248 (X190005 e X190005R)"]
 a| 
Supporto di switch di interconnessione cluster Broadcom BES-53248 per controller AFF/FAS con porte 10 GbE.
 a| 
ONTAP 9.5P8

|===


== Nuovo supporto adattatore

[cols="4*"]
|===
| Numero di parte dell'adattatore | Descrizione | Categoria | Inizio disponibile 


 a| 
https://hwu.netapp.com/adapter/index["X91148A"]
 a| 
RoCE QSFP28 da 100 GbE a 2 porte
 a| 
* Storage
* Networking
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X91122A"]
 a| 
RoCE QSFP28 a 2 porte da 25 GbE
 a| 
* Networking
* HA/MetroCluster

 a| 
ONTAP 9.8



 a| 
https://hwu.netapp.com/adapter/index["X9170A"]
 a| 
Modulo SSD NVMe (1 TB)
 a| 
Dispositivo core dump
 a| 
ONTAP 9.8

|===


== Nuovo supporto per gli shelf

[cols="2*"]
|===
| Shelf | Inizio disponibile 


 a| 
NS224
 a| 
ONTAP 9.6

|===


== Nuovi aggiornamenti hardware

[cols="25h,~,~"]
|===
| Funzionalità | Descrizione e dove saperne di più | Inizio disponibile 


 a| 
Supporto esteso della piattaforma per shelf di dischi NS224
 a| 
Le seguenti piattaforme supportano gli shelf di dischi NS224:

* AFF A800/AFF ASA A800
* AFF A700/AFF ASA A700
* AFF A250/AFF ASA A250
* FAS500f

 a| 
ONTAP 9.8



 a| 
Aggiunta a caldo di shelf SAS da 12 GB a stack di storage SAS da 6 GB
 a| 
È ora supportata una transizione a velocità singola da 6 GB a 12 GB in uno stack di storage SAS. Ciò consente l'espansione dello storage degli stack da 6 GB esistenti con shelf da 12 GB.

https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html["Shelf hot-adding con moduli IOM12 a uno stack di shelf con moduli IOM6"]
 a| 
ONTAP 9.7P4

ONTAP 9.6P9

ONTAP 9.5P14

|===