---
permalink: asa400/install-videos.html 
sidebar: sidebar 
keywords: asa a400, asa, a400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.' 
---
= Video - ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.



== Video uno di due: Installazione hardware e cablaggio

Il seguente video mostra come installare e collegare il nuovo sistema.

.Animazione - istruzioni per l'installazione e la configurazione di AFF A400
video::6cbbcb96-fe92-4040-a004-ab2001624dd7[panopto]

NOTE: Il sistema ASA A400 utilizza la stessa procedura di installazione del sistema AFF A400.



== Video due di due: Esecuzione della configurazione software end-to-end

Il seguente video mostra la configurazione software end-to-end per i sistemi che eseguono ONTAP 9.2 e versioni successive.

video::WAE0afWhj1c?[youtube]