---
permalink: asa400/overview.html 
sidebar: sidebar 
keywords: ASA A400 specifications, ASA A400 specs, NetApp ASA A400, ASA A400 hardware 
summary: Specifiche chiave per il sistema di archiviazione ASA A400 
---
= Specifiche chiave per ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' ASA A400.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche ASA A400 .  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per ASA A400

Configurazione della piattaforma: coppia HA a chassis singolo ASA A400 , bundle Ethernet

Capacità massima grezza: 14,6880 PB

Memoria: 256.0000 GB

Fattore di forma: chassis 4U con 2 controller HA

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 10

Versione minima ONTAP : ONTAP 9.13.1



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS |  |  |  


| SAN | 6 | 88,1 PB / 78,3 PiB | 1536 GB 


| Coppia HA |  | 14,7 PB / 13,0 PiB | 256,0000 
|===


=== Io



==== IO di bordo

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 4 


| Ethernet 25 Gbps | 12 


| SAS 12 Gbps | 8 
|===


==== IO totale

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 20 


| Ethernet 25 Gbps | 24 


| Ethernet 10 Gbps | 32 


| FC 32 Gbps | 24 


| NVMe/FC 32 Gbps | 24 


|  | 0 


| SAS 12 Gbps | 32 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rete di archiviazione supportata

FC; iSCSI; NVMe/FC ; NVMe/TCP;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 4209 BTU/ora
* Potenza nel caso peggiore: 5212 BTU/ora
* Peso: 110,0 libbre 49,9 kg
* Altezza: 4U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 32,6" (34,7" con staffa di gestione dei cavi)
* Temperatura/altitudine/umidità di funzionamento: da 10°C a 35°C (da 50°F a 95°F) fino a 3048 m (10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: potenza sonora dichiarata (LwAd): 8,5; pressione sonora (LpAm) (posizioni degli astanti): 67,2 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo; Gestione in banda SAS tramite connessioni SAS;
