---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: Specifiche chiave per il sistema di archiviazione AFF C80 
---
= Specifiche chiave per AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' AFF C80.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche AFF C80.  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per AFF C80

Configurazione della piattaforma: coppia HA a telaio singolo AFF C80

Capacità massima grezza: 14,7360 PB

Memoria: 512.0000 GB

Fattore di forma: chassis 4U con 2 controller HA e 48 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 18

Versione minima ONTAP : ONTAP 9.16.1RC1



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS | 12 | 176,8 PB / 157,0 PiB | 6144 GB 


| SAN | 6 | 88,4 PB / 78,5 PiB | 3072 GB 


| Coppia HA |  | 14,7 PB / 13,1 PiB | 512,0000 
|===


=== Io



==== IO di bordo

Nessun dato IO a bordo.



==== IO totale

|===


| Protocollo | porti 


| Ethernet 200 Gbps | 24 


| Ethernet 100 Gbps | 36 


| Ethernet 25 Gbps | 56 


| Ethernet 10 Gbps | 56 


| FC 64 Gbps | 56 


| NVMe/FC 64 Gbps | 56 


|  | 0 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Rete di archiviazione supportata

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

Nessun dato ambientale disponibile.



=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo;
