---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: 'Prima di sostituire il supporto di avvio nel sistema AFF C80, accertarsi di disporre del dispositivo di avvio sostitutivo corretto, dell"accesso al firmware di sistema e al software ONTAP e di un backup dei dati di configurazione essenziali.' 
---
= Requisiti di sostituzione dei supporti di avvio - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema AFF C80, accertarsi di disporre del dispositivo di avvio sostitutivo corretto, dell'accesso al firmware di sistema e al software ONTAP e di un backup dei dati di configurazione essenziali.

Esaminare i seguenti requisiti.

* È necessario disporre di un'unità flash USB, formattata in FAT32, con la quantità di storage appropriata per contenere `image_xxx.tgz` file.
* È necessario copiare il `image_xxx.tgz` file nell'unità flash USB per utilizzarlo successivamente in questa procedura.
* È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.
* È importante applicare i comandi descritti di seguito al controller corretto:
+
** Il controller _alterato_ è il controller su cui si esegue la manutenzione.
** Il controller _healthy_ è il partner ha del controller compromesso.



