---
permalink: c80/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: c80, verify and set HA state, complete the replacement process 
summary: Riavviare i controller, verificare lo stato del sistema e restituire la parte guasta a NetApp per completare la fase finale del flusso di lavoro di sostituzione dello chassis di AFF C80. 
---
= Sostituzione completa dello chassis - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Riavviare i controller, verificare lo stato del sistema e restituire la parte guasta a NetApp per completare la fase finale del flusso di lavoro di sostituzione dello chassis di AFF C80.



== Fase 1: Avviare i controller e restituirli

Dopo il riavvio dei controller, avviare ONTAP e restituire i controller.

. Controllare l'output della console:
+
.. Se il controller viene avviato al prompt Loader, riavviarlo con il `boot_ontap` comando.
.. Se la console viene visualizzata `waiting for giveback` dopo il riavvio, accedere al controller partner e verificare che il controller sostituito sia pronto per il giveback con il `storage failover show` comando.


. Eseguire lo sconto:
+
.. Collegare il cavo della console al controller partner.
.. Restituire il controller con il `storage failover giveback -fromnode local` comando.






== Fase 2: Verifica dello stato del sistema di archiviazione

Dopo che il controller ha restituito lo spazio di archiviazione, è necessario controllare lo stato generale con https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"].

. Una volta completato il giveback, eseguire Active IQ Config Advisor per verificare lo stato di salute del sistema storage.
. Correggere eventuali problemi riscontrati.




== Fase 3: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
