---
permalink: c80/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: c80, shutdown the controllers 
summary: Arrestare i controller del sistema storage AFF C80 quando è necessario sostituire lo chassis. Prima di eseguire la manutenzione o la sostituzione dei componenti, è fondamentale spegnere il controller in modo sicuro per evitare perdite di dati e garantire la stabilità del sistema. 
---
= Spegnere le centraline - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrestare i controller del sistema storage AFF C80 quando è necessario sostituire lo chassis. Prima di eseguire la manutenzione o la sostituzione dei componenti, è fondamentale spegnere il controller in modo sicuro per evitare perdite di dati e garantire la stabilità del sistema.

Questa procedura si applica ai sistemi con configurazioni a due nodi. Per ulteriori informazioni sull'arresto regolare durante la manutenzione di un cluster, vedere https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["Shutdown anomalo e accendere il sistema storage System Resolution Guide - NetApp Knowledge base"].

.Prima di iniziare
* Assicurarsi di disporre delle autorizzazioni e delle credenziali necessarie:
+
** Credenziali dell'amministratore locale per ONTAP.
** Accessibilità BMC per ciascun controller.


* Assicurarsi di disporre degli strumenti e delle attrezzature necessarie per la sostituzione.
* Come Best practice prima dello spegnimento, è necessario:
+
** Eseguire ulteriori operazioni https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["controlli dello stato del sistema"].
** Aggiornare ONTAP a una versione consigliata per il sistema.
** Risolvere qualsiasi https://activeiq.netapp.com/["Avvisi e rischi relativi al benessere Active IQ"]. Annotare eventuali guasti presenti nel sistema, ad esempio i LED sui componenti del sistema.




.Fasi
. Accedere al cluster tramite SSH o da qualsiasi nodo del cluster utilizzando un cavo della console locale e un laptop/console.
. Impedire a tutti i client/host di accedere ai dati sul sistema NetApp.
. Sospendere i processi di backup esterni.
. Se AutoSupport è abilitato, sospendere la creazione di casi e indicare per quanto tempo si prevede che il sistema sia offline:
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. Identificare l'indirizzo SP/BMC di tutti i nodi del cluster:
+
`system service-processor show -node * -fields address`

. Uscire dalla shell del cluster:
+
`exit`

. Accedere a SP/BMC tramite SSH utilizzando l'indirizzo IP di uno dei nodi elencati nell'output del passaggio precedente per monitorare l'avanzamento.
+
Se stai utilizzando una console/laptop, accedi al controller usando le stesse credenziali di amministratore del cluster.

. Arrestare i due nodi situati nel telaio danneggiato:
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Per i cluster che utilizzano SnapMirror Synchronous che operano in modalità StrictSync: `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Immettere *y* per ciascun controller nel cluster quando viene visualizzato:
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. Attendere che ogni controller si arresti e visualizzi il prompt DEL CARICATORE.


.Quali sono le prossime novità?
Dopo aver spento i controller, è necessario link:chassis-replace-move-hardware.html["sostituire il telaio"].
