---
permalink: c80/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: c80, replace the chassis 
summary: Si sostituisce un telaio danneggiato con il nuovo telaio dello stesso modello del telaio danneggiato. 
---
= Requisiti per la sostituzione del telaio - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.

Prima di sostituire il telaio, verificare i seguenti requisiti.

* Verificare che tutti gli altri componenti del sistema funzionino correttamente; in caso contrario, contattare il supporto tecnico.
* È possibile utilizzare la procedura di sostituzione dello chassis con tutte le versioni di ONTAP supportate dal sistema.
* La procedura di sostituzione dello chassis viene scritta presupponendo che il pannello, i dischi NVMe e i moduli controller vengano spostati nel nuovo chassis e che lo chassis di ricambio sia un nuovo componente di NetApp.
* *La procedura di sostituzione del telaio non funziona.* Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

