---
permalink: c80/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: c80, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: Verifica che le interfacce logiche stiano segnalando alla porta home, esegui un controllo dello stato di salute del cluster e restituisci il componente guasto a NetApp per completare la fase finale della procedura di sostituzione del controller AFF C80. 
---
= Sostituzione completa della centralina - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per completare la sostituzione del controller del sistema AFF C80, ripristinare innanzitutto la configurazione di NetApp Storage Encryption (se necessario). Quindi, conferma che le interfacce logiche (LIF) stanno eseguendo un reporting sulle rispettive porte home ed esegui un controllo dello stato di salute del cluster. Infine, restituire il componente guasto a NetApp.



== Fase 1: Verifica delle LIF e verifica dello stato del cluster

Prima di riportare in servizio il nodo sostitutivo, verifica che le interfacce logiche siano sulle porte home, verifica lo stato del cluster e ripristina il giveback automatico.

.Fasi
. Verificare che le interfacce logiche segnalino il proprio server di origine e le porte:
+
`network interface show -is-home false`

+
Se alcune interfacce logiche sono elencate come false, ripristinarle alle rispettive porte home:

+
`network interface revert -vserver * -lif *`

. Controlla lo stato del tuo cluster.  Vedi il https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Come eseguire un controllo dello stato del cluster con uno script in ONTAP"^] Articolo della Knowledge Base.
. Se il giveback automatico è stato disattivato, riabilitarlo:
+
`storage failover modify -node local -auto-giveback true`





== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
