---
permalink: c80/overview.html 
sidebar: sidebar 
summary: Specifiche chiave per il gruppo piattaforma C80 
---
= Specifiche chiave per AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione AFF C80 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche chiave per AFF C80

* Configurazione della piattaforma: coppia HA a telaio singolo AFF C80
* Capacità massima grezza: 14,7360 PB
* Memoria: 512.0000 GB
* Fattore di forma: chassis 4U con 2 controller HA e 48 slot per unità
* Versione ONTAP : ONTAP: 9.16.1P2
* Slot di espansione PCIe: 18
* Versione minima ONTAP : ONTAP 9.16.1RC1 == Massimi di scalabilità
* Tipo: NAS; Coppie HA: 12; Capacità raw: 176,8 PB / 157,0 PiB; Memoria massima: 6144 GB
* Tipo: SAN; Coppie HA: 6; Capacità grezza: 88,4 PB / 78,5 PiB; Memoria massima: 3072 GB
* Tipo: coppia HA; capacità grezza: 14,7 PB / 13,1 PiB; memoria massima: 512.0000




== I/O



=== I/O integrato

Nessun dato I/O integrato.



=== Totale I/O

* Protocollo: Ethernet 200 Gbps; Porte: 24
* Protocollo: Ethernet 100 Gbps; Porte: 36
* Protocollo: Ethernet 25 Gbps; Porte: 56
* Protocollo: Ethernet 10 Gbps; Porte: 56
* Protocollo: FC 64 Gbps; Porte: 56
* Protocollo: NVMe/FC 64 Gbps; Porte: 56
* Porte: 0




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 600 Mbps; Porte: 2




== Rete di archiviazione supportata

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NFSv3/RDMA
* NFSv4/RDMA
* NVMe/FC
* NVMe/TCP
* S3
* S3 con NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1 == Specifiche dell'ambiente di sistema Nessun dato sull'ambiente disponibile.




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo

