---
permalink: fas2700/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas2700, aff a220, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Per sostituire lo chassis, è necessario spegnere i controller. 
---
= Spegnere i controller - FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrestare o sostituire il controller con problemi utilizzando la procedura appropriata per la configurazione.



== Opzione 1: La maggior parte delle configurazioni

Spegnere i controller per eseguire la manutenzione dello chassis.

Questa procedura si applica ai sistemi con configurazioni a due nodi. Se si dispone di un sistema con più di due nodi, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["Come eseguire un arresto e un'accensione regolari di una coppia ha in un cluster a quattro nodi"^].

.Prima di iniziare
* Impedire a tutti i client/host di accedere ai dati sul sistema NetApp.
* Sospendere i processi di backup esterni.
* Assicurarsi di disporre delle autorizzazioni e delle credenziali necessarie:
+
** Credenziali dell'amministratore locale per ONTAP.
** Passphrase per la gestione delle chiavi integrata di NetApp (OKM) a livello del cluster se si utilizza la crittografia storage o NVE/NAE.
** Accessibilità BMC per ciascun controller.


* Assicurarsi di disporre degli strumenti e delle attrezzature necessarie per la sostituzione.
* Come Best practice prima dello spegnimento, è necessario:
+
** Eseguire ulteriori operazioni https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["controlli dello stato del sistema"].
** Aggiornare ONTAP a una versione consigliata per il sistema.
** Risolvere qualsiasi https://activeiq.netapp.com/["Avvisi e rischi relativi al benessere Active IQ"]. Annotare eventuali guasti presenti nel sistema, ad esempio i LED sui componenti del sistema.




.Fasi
. Accedere al cluster tramite SSH o da qualsiasi nodo del cluster utilizzando un cavo della console locale e un laptop/console.
. Disattivare AutoSupport e indicare per quanto tempo si prevede che il sistema non sia in linea:
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. Identificare l'indirizzo SP/BMC di tutti i nodi:
+
`system service-processor show -node * -fields address`

. Uscire dalla shell del cluster: `exit`
. Accedere a SP/BMC tramite SSH utilizzando l'indirizzo IP di uno qualsiasi dei nodi elencati nell'output del passaggio precedente.
+
Se stai utilizzando una console/laptop, accedi al controller usando le stesse credenziali di amministratore del cluster.

+

NOTE: Aprire una sessione SSH per ogni connessione SP/BMC in modo da poter monitorare l'avanzamento.

. Arrestare i due nodi situati nel telaio danneggiato:
+
`system node halt -node <node>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: Per i cluster che utilizzano SnapMirror Synchronous che operano in modalità StrictSync: `system node halt -node <node>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. Immettere *y* per ogni controller nel cluster quando viene visualizzato `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. Attendere che ogni controller si arresti e visualizzi il prompt DEL CARICATORE.




== Opzione 2: Il controller è in una configurazione MetroCluster


NOTE: Non utilizzare questa procedura se il sistema si trova in una configurazione MetroCluster a due nodi.

Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso.

* Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].
* Se si dispone di una configurazione MetroCluster, è necessario confermare che lo stato di configurazione MetroCluster è configurato e che i nodi sono in uno stato abilitato e normale (`metrocluster node show`).


.Fasi
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattivare il giveback automatico dalla console del controller integro: `storage failover modify –node local -auto-giveback false`
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Passare alla fase successiva.



 a| 
In attesa di un giveback...
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode _impaired_node_name_`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===

