---
permalink: fas2700/maintain-overview.html 
sidebar: sidebar 
keywords: fas2700 maintenance, maintenance, repairing, repairing fas2700, replace fas2700 components, replace fas2700 components 
summary: 'Manutenzione dell"hardware ASA C800' 
---
= Manutenzione dell'hardware FAS2700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema storage FAS2700, è possibile eseguire le procedure di manutenzione dei seguenti componenti.



[[boot-media]]
== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



[[caching-module]]
== Modulo di caching

È necessario sostituire il modulo di caching del controller quando il sistema registra un singolo messaggio ASUP (AutoSupport) che indica che il modulo è offline.



[[chassis]]
== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



[[controller]]
== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



[[dimm]]
== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



[[drive]]
== Disco

Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



[[nvmem-battery]]
== Batteria NVMEM

Una batteria è inclusa nel controller e conserva i dati memorizzati nella cache in caso di interruzione dell'alimentazione CA.



[[power-supply]]
== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



[[real-time-clock-battery]]
== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
