---
permalink: fas2700/overview.html 
sidebar: sidebar 
summary: Specifiche chiave per il gruppo di piattaforme FAS2700 
---
= Specifiche chiave per FAS2750
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione FAS2750 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche chiave per FAS2750

* Configurazione della piattaforma: FAS2750 UTA2 Single Chassis HA Pair
* Capacità massima grezza: 2,6832 PB
* Memoria: 64.0000 GB
* Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità
* Versione ONTAP : ONTAP: 9.16.1P2
* Slot di espansione PCIe: 2
* Versione minima ONTAP : ONTAP 9.4RC1 == Massimi di scalabilità
* Tipo: NAS; Coppie HA: 12; Capacità raw: 32,2 PB / 28,6 PiB; Memoria massima: 768 GB
* Tipo: SAN; Coppie HA: 6; Capacità grezza: 16,1 PB / 14,3 PiB; Memoria massima: 384 GB
* Tipo: coppia HA; capacità grezza: 2,7 PB / 2,4 PiB; memoria massima: 64.0000




== I/O



=== I/O integrato

* Protocollo: Ethernet 10 Gbps; Porte: 12
* Protocollo: FC 16 Gbps; Porte: 8
* Protocollo: SAS 12 Gbps; Porte: 4




=== Totale I/O

* Protocollo: Ethernet 10 Gbps; Porte: 12
* Protocollo: FC 16 Gbps; Porte: 8
* Protocollo: SAS 12 Gbps; Porte: 4




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 12 Mbps; Porte: 2




== Rete di archiviazione supportata

* CIFS
* FC
* FCoE
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NVMe/TCP
* S3
* S3 con NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1 == Specifiche dell'ambiente di sistema
* Potenza tipica: 1209 BTU/ora
* Potenza nel caso peggiore: 1676 BTU/ora
* Peso: 60,8 libbre 27,6 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 19,0" (24,1" con staffa per la gestione dei cavi)
* Temperatura/altitudine/umidità di esercizio: da 5°C a 45°C (da 41°F a 113°F) a <= 3048 m <= 10000 piedi) di altitudine; umidità relativa dall'8% al 90%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 6,9 Pressione sonora (LpAm) (posizioni degli astanti): 51,0 dB




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo
* Gestione in banda SAS su connessioni SAS per scaffali esterni

