---
sidebar: sidebar 
permalink: fru-reference/io-module-fru-links.html 
keywords: I/O module, field replaceable units, FRU, I/O module replacement 
summary: Trova le procedure di sostituzione dei moduli I/O per il tuo sistema di storage NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione dei moduli I/O per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico. 
---
= Procedure di sostituzione dei moduli I/O per famiglia di piattaforme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trova le procedure di sostituzione dei moduli I/O per il tuo sistema di storage NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione dei moduli I/O per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico.

[role="tabbed-block"]
====
.Sistemi AFF
--
* link:../a1k/io-module-replace.html["AFF A1K"]
* link:../a20-30-50/io-module-replace.html["AFF A20/30/50"]
* link:../a70-90/io-module-replace.html["AFF A70/90"]
* link:../c30-60/io-module-replace.html["AFF C30/60"]
* link:../c80/io-module-replace.html["AFF C80"]


--
.Sistemi ASA
--
* link:../asa-r2-a1k/io-module-replace.html["ASA A1K"]
* link:../asa-r2-a20-30-50/io-module-replace.html["ASA A20/30/50"]
* link:../asa-r2-70-90/io-module-replace.html["ASA 70/90"]
* link:../asa-r2-c30/io-module-replace.html["ASA C30"]


--
.Sistemi FAS
--
* link:../fas50/io-module-replace.html["FAS50"]
* link:../fas-70-90/io-module-replace.html["FAS70/90"]


--
====