---
sidebar: sidebar 
permalink: fru-reference/nvdimm-fru-links.html 
keywords: NVDIMM, field replaceable units, FRU, NVDIMM replacement 
summary: Trova le procedure di sostituzione NVDIMM per il tuo sistema di archiviazione NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione di NVDIMM per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico. 
---
= Procedure di sostituzione NVDIMM per famiglia di piattaforme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trova le procedure di sostituzione NVDIMM per il tuo sistema di archiviazione NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione di NVDIMM per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico.

[role="tabbed-block"]
====
.Sistemi AFF
--
* link:../a320/nvdimm-replace.html["AFF A320"]
* link:../a400/nvdimm-replace.html["AFF A400"]
* link:../a800/nvdimm-replace.html["AFF A800"]
* link:../c400/nvdimm-replace.html["AFF C400"]
* link:../c800/nvdimm-replace.html["AFF C800"]


--
.Sistemi ASA
--
* link:../asa400/nvdimm-replace.html["ASA A400"]
* link:../asa800/nvdimm-replace.html["ASA A800"]
* link:../asa-c400/nvdimm-replace.html["ASA C400"]
* link:../asa-c800/nvdimm-replace.html["ASA C800"]


--
.Sistemi FAS
--
* link:../fas8300/nvdimm-replace.html["FAS8300"]


--
====