---
sidebar: sidebar 
permalink: fru-reference/nvram-module-fru-links.html 
keywords: NVRAM module, field replaceable units, FRU, NVRAM module replacement 
summary: Trova le procedure di sostituzione dei moduli NVRAM per il tuo sistema di storage NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione dei moduli NVRAM per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico. 
---
= Procedure di sostituzione del modulo NVRAM per famiglia di piattaforme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trova le procedure di sostituzione dei moduli NVRAM per il tuo sistema di storage NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione dei moduli NVRAM per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico.

[role="tabbed-block"]
====
.Sistemi AFF
--
* link:../a1k/nvram-replace.html["AFF A1K"]
* link:../a70-90/nvram-replace.html["AFF A70/90"]
* link:../a700/nvram-module-or-nvram-dimm-replacement.html["AFF A700"]
* link:../a700s/nvram-or-nvram-dimm-replacement.html["AFF A700"]
* link:../a900/nvram_module_or_nvram_dimm_replacement.html["AFF A900"]
* link:../c80/nvram-replace.html["AFF C80"]


--
.Sistemi AFX
--
* link:../afx-1k/nvram-replace.html["AFX A1K"]


--
.Sistemi ASA
--
* link:../asa900/nvram_module_or_nvram_dimm_replacement.html["ASA A900"]
* link:../asa-r2-a1k/nvram-replace.html["ASA A1K"]
* link:../asa-r2-70-90/nvram-replace.html["ASA 70/90"]


--
.Sistemi FAS
--
* link:../fas-70-90/nvram-replace.html["FAS70/90"]
* link:../fas9000/nvram-module-or-nvram-dimm-replacement.html["FAS9000"]
* link:../fas9500/nvram_module_or_nvram_dimm_replacement.html["FAS9500"]


--
====