---
sidebar: sidebar 
permalink: fru-reference/pci-cards-fru-links.html 
keywords: PCI cards, risers, field replaceable units, FRU, PCI replacement 
summary: Scopri le procedure di sostituzione delle schede PCI e dei riser per il tuo sistema di storage NetApp , organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti a flussi di lavoro passo passo per la sostituzione di schede PCI e riser per sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico. 
---
= Procedure di sostituzione delle schede PCI e dei riser per famiglia di piattaforme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le procedure di sostituzione delle schede PCI e dei riser per il tuo sistema di storage NetApp , organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti a flussi di lavoro passo passo per la sostituzione di schede PCI e riser per sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico.

[role="tabbed-block"]
====
.Sistemi AFF
--
* link:../a300/pci-cards-and-risers-replace.html["AFF A300"]
* link:../a320/pci-cards-and-risers-replace.html["AFF A320"]
* link:../a400/pci-cards-and-risers-replace.html["AFF A400"]
* link:../a700/pci-cards-and-risers-replace.html["AFF A700"]
* link:../a700s/pci-cards-and-risers-replace.html["AFF A700"]
* link:../a800/pci-cards-and-risers-replace.html["AFF A800"]
* link:../c400/pci-cards-and-risers-replace.html["AFF C400"]
* link:../c800/pci-cards-and-risers-replace.html["AFF C800"]


--
.Sistemi ASA
--
* link:../asa400/pci-cards-and-risers-replace.html["ASA A400"]
* link:../asa800/pci-cards-and-risers-replace.html["ASA A800"]
* link:../asa-c400/pci-cards-and-risers-replace.html["ASA C400"]
* link:../asa-c800/pci-cards-and-risers-replace.html["ASA C800"]


--
.Sistemi FAS
--
* link:../fas2800/pci-cards-and-risers-replace.html["FAS2800"]
* link:../fas8200/pci-cards-and-risers-replace.html["FAS8200"]
* link:../fas8300/pci-cards-and-risers-replace.html["FAS8300"]
* link:../fas9000/pci-cards-and-risers-replace.html["FAS9000"]


--
====