---
sidebar: sidebar 
permalink: fru-reference/system-management-fru-links.html 
keywords: system management module, field replaceable units, FRU, system management replacement 
summary: Trova le procedure di sostituzione dei moduli di gestione del sistema per il tuo sistema di storage NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione dei moduli di gestione del sistema per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico. 
---
= Procedure di sostituzione del modulo di gestione del sistema per famiglia di piattaforme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trova le procedure di sostituzione dei moduli di gestione del sistema per il tuo sistema di storage NetApp organizzate per famiglia di piattaforme.  Questo riferimento fornisce collegamenti diretti ai flussi di lavoro passo passo per la sostituzione dei moduli di gestione del sistema per i sistemi AFF, ASA e FAS , per aiutarti a individuare rapidamente la procedura corretta per il tuo modello specifico.

[role="tabbed-block"]
====
.Sistemi AFF
--
* link:../a1k/system-management-replace.html["AFF A1K"]
* link:../a70-90/system-management-replace.html["AFF A70/90"]
* link:../c80/system-management-replace.html["AFF C80"]


--
.Sistemi ASA
--
* link:../asa-r2-a1k/system-management-replace.html["ASA A1K"]
* link:../asa-r2-70-90/system-management-replace.html["ASA 70/90"]


--
.Sistemi FAS
--
* link:../fas-70-90/system-management-replace.html["FAS70/90"]


--
====