---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: 'L"armadio del sistema è costituito da pannelli laterali, sportelli anteriori e posteriori, un kit opzionale imbullonato, un kit di interconnessione opzionale, PDU per l"apparecchiatura e un sistema di gestione dei cavi integrato.' 
---
= Caratteristiche dell'armadio di sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'armadio del sistema è costituito da pannelli laterali, sportelli anteriori e posteriori, un kit opzionale imbullonato, un kit di interconnessione opzionale, PDU per l'apparecchiatura e un sistema di gestione dei cavi integrato.

[cols="1,2"]
|===
| Funzione | Descrizione 


 a| 
Pannelli laterali
 a| 
Gli armadi del sistema sono dotati di pannelli laterali bloccabili, rimovibili e intercambiabili.



 a| 
Sportelli anteriori e posteriori perforati
 a| 
Gli armadi del sistema sono dotati di sportelli anteriori e posteriori rimovibili con un meccanismo di sgancio rapido. La porta anteriore è reversibile e le porte posteriori sono separate. Entrambi gli sportelli sono forati per il raffreddamento.



 a| 
Chiave comune
 a| 
Questa chiave consente di sbloccare gli sportelli anteriori, posteriori e i pannelli laterali.



 a| 
Kit di ricambio
 a| 
Questo kit si trova all'interno dell'armadio del sistema, collegato allo sportello dell'armadio. Contiene i seguenti componenti:

* Quattro viti Phillips da 10-32 x 0.75 pollici
* Quattro dadi a gabbia da 10-32
* Un utensile per l'inserimento di dadi a gabbia
* Due copie della chiave master




 a| 
Accesso via cavo
 a| 
I cavi passanti sono integrati nella parte superiore e inferiore dell'armadio, oltre che tra la parte inferiore dello sportello posteriore e il telaio.



 a| 
Gestione dei cavi
 a| 
Il gancio di gestione dei cavi e le cinghie ad anello sono collegati al telaio dell'armadio del sistema a intervalli uguali.



 a| 
Guide di supporto
 a| 
Il numero di guide di supporto ricevute dipende dalla configurazione. L'armadio vuoto del sistema viene spedito senza guide di supporto installate.

* Per gli armadi del sistema configurati, viene fornito un kit di guide fisse con l'armadio del sistema per supportare le staffe di fissaggio posteriori 80xx, FAS8200 e DS4486.
* Gli armadi del sistema Quick-Ship non includono il kit aggiuntivo per guide fisse.




 a| 
Pannelli ciechi
 a| 
Il numero e la dimensione dei pannelli ciechi ricevuti dipende dalla configurazione. L'armadio vuoto del sistema viene spedito senza pannelli ciechi installati.



 a| 
Kit imbullonato
 a| 
Questo kit opzionale consente di fissare il cabinet di sistema al data center. Il kit non è destinato alla stabilità sismica.

* Quattro staffe imbullonate
* Quattro staffe distanziatrici
* Sei bulloni a testa esagonale M8x20 mm e rondelle




 a| 
Kit di interconnessione
 a| 
Questo kit opzionale consente di collegare tra loro più cabinet di sistema.

* Staffe di interconnessione
+
** Un set di quattro staffe di interconnessione per il collegamento degli armadi del sistema con i pannelli laterali
** Un set di quattro staffe di interconnessione per il collegamento degli armadi del sistema con i pannelli laterali spenti


* Quattro viti Torx-30 M12x20 utilizzate nell'armadio del sistema con pannelli laterali accesi.
* Otto viti Torx-30 a testa svasata M6x10 utilizzate nell'armadio del sistema con i pannelli laterali spenti.




 a| 
Kit di guide di supporto
 a| 
Se sono state ordinate guide di supporto aggiuntive con l'armadietto del sistema, ciascun kit contiene una guida di supporto sinistra e una destra.


NOTE: Le guide di supporto e il kit sono progettati per adattarsi solo al cabinet di sistema da 1280 mm di NetApp 42U. Non utilizzare guide o kit di guide di altri cabinet di sistema perché non sono progettati per l'uso nell'armadio di sistema 42U da 1280 mm.

* Una guida di supporto sinistra e destra
* Due viti per guida per fissare la guida al telaio dell'armadio del sistema




 a| 
Chiave a mezzaluna
 a| 
La chiave a mezzaluna viene utilizzata per rimuovere le staffe di fissaggio sul pallet di imballaggio, regolare i piedini di livellamento dell'armadio del sistema e installare le staffe del kit imbullonate, se ordinate.

|===