---
permalink: platform-supplemental/42u-1280mm-remove-door.html 
sidebar: sidebar 
keywords: remove, system, cabinet, door, side, panel, illuminate, badge, component, reverse, door, remove the system cabinet door 
summary: 'È necessario rimuovere lo sportello e i pannelli laterali dell"armadio di sistema per spostare il badge illuminato e i componenti e per invertire lo sportello.' 
---
= Rimuovere lo sportello del cabinet di sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario rimuovere lo sportello e i pannelli laterali dell'armadio di sistema per spostare il badge illuminato e i componenti e per invertire lo sportello.

. Aprire lo sportello del cabinet di sistema, se non è già aperto.
. Eseguire l'azione appropriata a seconda che gli armadi siano collegati con il kit di interconnessione.
+
[cols="1,2"]
|===
| Se il cabinet di sistema è... | Quindi... 


 a| 
Non collegato a un altro cabinet di sistema
 a| 
Passare alla fase successiva.



 a| 
Collegato a un altro cabinet di sistema con un kit di interconnessione
 a| 
Rimuovere tutte e quattro le staffe del kit di interconnessione e posizionare le staffe e le viti in un luogo sicuro.

|===
. Sbloccare entrambi i pannelli laterali, scollegare i cavi di messa a terra dai pannelli laterali, quindi rimuoverli e metterli da parte.
. Scollegare il cavo di messa a terra dal connettore situato nella parte superiore dello sportello.
. Svitare l'aletta di messa a terra e il gruppo di cavi dal telaio dell'armadietto del sistema e metterli da parte.
. Svitare il gruppo di fissaggio per la messa a terra dallo sportello dell'armadietto del sistema e metterlo da parte.
. Sollevare il perno del cardine superiore fino a liberare la parte inferiore del cardine.
. Inclinare delicatamente la parte superiore dello sportello per allontanarla dal telaio del cabinet di sistema, quindi rilasciare il perno del cardine.
. Sollevare lo sportello dal cardine inferiore e metterlo da parte.

