---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: È necessario collegare i componenti del sistema alle PDU, instradare i cavi PDU alle fonti di alimentazione CA, collegarli alle fonti di alimentazione e accendere il sistema. 
---
= Accendere l'armadio di sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario collegare i componenti del sistema alle PDU, instradare i cavi PDU alle fonti di alimentazione CA, collegarli alle fonti di alimentazione e accendere il sistema.

È necessario disporre di circuiti di alimentazione separati per ciascuna PDU nell'armadio del sistema.

. Collegare l'apparecchiatura alle PDU, assicurandosi di collegare gli alimentatori di ciascun componente a una PDU sui lati opposti dell'armadio del sistema.
. Inserire i cavi di alimentazione della PDU attraverso un'apertura nell'armadio del sistema.
+
Utilizzare una delle seguenti aperture:

+
** Nella parte superiore dell'armadietto del sistema
** Tra la parte inferiore dello sportello posteriore e il telaio dell'armadietto del sistema
** Attraverso l'apertura a pavimento e sotto l'armadietto del sistema


. Spegnere gli interruttori di alimentazione o gli interruttori automatici delle PDU.
. Collegare ciascun cavo di alimentazione PDU a singole fonti di alimentazione CA che si trovano su circuiti CA separati.
. Accendere gli interruttori di alimentazione o gli interruttori di circuito delle PDU.
. Accendere i componenti e avviare il sistema.
. Chiudere e bloccare gli sportelli del cabinet di sistema.

