---
permalink: platform-supplemental/sldiag-introduction.html 
sidebar: sidebar 
keywords: system-level, diagnostic, command-line, interface, test, search, hardware, problem, storage, system, component, operating, identify, faulty, component, introduction, introduction to system-level diagnostic 
summary: 'La diagnostica a livello di sistema fornisce un"interfaccia a riga di comando per i test che cercano e determinano i problemi hardware sui sistemi storage supportati. Si utilizza la diagnostica a livello di sistema per confermare il corretto funzionamento di un componente specifico o per identificare i componenti guasti.' 
---
= Introduzione alla diagnostica a livello di sistema‑
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La diagnostica a livello di sistema fornisce un'interfaccia a riga di comando per i test che cercano e determinano i problemi hardware sui sistemi storage supportati. Si utilizza la diagnostica a livello di sistema per confermare il corretto funzionamento di un componente specifico o per identificare i componenti guasti.

La diagnostica a livello di sistema è disponibile solo per i sistemi storage supportati. L'accesso alla diagnostica a livello di sistema dall'interfaccia della riga di comando dei sistemi di storage non supportati genera un messaggio di errore.

La diagnostica a livello di sistema viene eseguita dopo una delle seguenti situazioni comuni di risoluzione dei problemi:

* Installazione iniziale del sistema
* Aggiunta o sostituzione di componenti hardware
* Panico di sistema causato da un guasto hardware non identificato
* L'accesso a un dispositivo specifico diventa intermittente o il dispositivo non è più disponibile
* I tempi di risposta del sistema diventano rallentati


Per eseguire la diagnostica a livello di sistema, è necessario che Data ONTAP sia già in esecuzione perché è necessario accedere all'opzione *modalità di manutenzione boot* in Data ONTAP. Esistono diversi approcci per ottenere questa opzione, ma questo è l'approccio consigliato nelle procedure documentate in questa guida. Alcuni componenti hardware del sistema potrebbero richiedere un approccio specifico, documentato nel volantino FRU (Field Replaceable Unit) applicabile. Questa guida non fornisce definizioni dettagliate di comandi, sottocomandi, test o condizioni specifici.

Una volta immesso il comando, i test vengono eseguiti in background e il risultato dei test superato o non superato viene registrato nel log interno basato sulla memoria, che ha una dimensione fissa. Alcuni test sono utility e indicano semplicemente Completed (completato) piuttosto che Passed (superato) o FAILED (non superato). Dopo aver eseguito i test appropriati, le procedure documentate in questa guida consentono di generare un report sullo stato. Una volta che i risultati del test mostrano il completamento della diagnostica a livello di sistema, si consiglia di cancellare il registro.

In caso di errori di test, i report di stato aiuteranno il supporto tecnico a fornire consigli appropriati. Il guasto può essere risolto reinstallando la FRU, verificando che i cavi siano collegati o attivando test specifici raccomandati dal supporto tecnico e rieseguendo i test. Se il guasto non può essere risolto, si è verificato un guasto hardware e l'hardware interessato deve essere sostituito.

Non ci sono messaggi di errore che richiedono ulteriori definizioni o spiegazioni.
