---
permalink: platform-supplemental/sldiag-requirements.html 
sidebar: sidebar 
keywords: system-level, diagnostic, test, run, time, system, requirement, system, memory, general, nic, sas, fc-al, cna, interconnect, requirement for running system-level diagnostic 
summary: A seconda dei test di diagnostica a livello di sistema in esecuzione, è necessario conoscere i requisiti di tempo e hardware di sistema. 
---
= Requisiti per l'esecuzione della diagnostica a livello di sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A seconda dei test di diagnostica a livello di sistema in esecuzione, è necessario conoscere i requisiti di tempo e hardware di sistema.

Ogni attività documentata presenta lievi differenze; utilizzare la procedura consigliata per l'attività.

Quando si esegue la diagnostica a livello di sistema, devono essere soddisfatti i seguenti requisiti; in caso contrario, parti dei test non riescono e vengono visualizzati messaggi di errore nel report di stato:



== Requisiti generali

* Ogni sistema sottoposto a test deve trovarsi su una rete separata.
+
Il test dell'interfaccia di rete assegna indirizzi IP statici univoci, a partire da 172.25.150.23, a tutte le interfacce di rete disponibili su un sistema di storage. Ciò comporta l'assegnazione dello stesso indirizzo IP alle porte di interfaccia di rete su diversi controller di storage. Se tutti i sistemi sottoposti a test si trovano sulla stessa rete, sulle console collegate vengono visualizzati messaggi di avviso di indirizzo ip duplicati. Questi messaggi di avviso non influiscono sui risultati del test.





== Requisiti di memoria di sistema

* È necessario mettere da parte il tempo necessario per eseguire i test della memoria; maggiore è la capacità di memoria del sistema storage, maggiore sarà il tempo necessario.




== Requisiti NIC

* Tutte le porte di interfaccia di rete adiacenti sul sistema devono essere collegate per ottenere le migliori prestazioni utilizzando un cavo Ethernet standard.
+
Esempi di porte adiacenti sono e0a e e0b o e2c e e2d.

+

NOTE: Le porte e0M e e0P non possono essere collegate tra loro a causa di una connessione interna dello switch. Nei sistemi con porte e0M e e0P, gli abbinamenti più efficienti sono e0M con e0a e e0P con e0b.

* Se nel sistema sono presenti diverse porte di interfaccia di rete, potrebbe essere necessario eseguire il test diagnostico a livello di sistema della scheda NIC diverse volte, limitando ogni esecuzione a non più di due coppie ogni volta.




== Requisiti SAS

* Quando si eseguono i test di diagnostica a livello di sistema SAS, è necessario collegare le porte SAS adiacenti per ottenere le migliori prestazioni; gli shelf di storage devono essere scollegati dalle porte.
+

NOTE: Le connessioni tra porte SAS adiacenti non sono più un requisito per i sistemi che eseguono Data ONTAP 8.2; tuttavia, solo il test di loopback interno verrà eseguito per i sistemi con porte SAS non connesse.





== Requisiti FC-al

* Quando si eseguono i test diagnostici a livello di sistema FC-al, è necessario disporre di cappe di loopback sulle interfacce FC-al sulla scheda madre o sugli adattatori di espansione per ottenere le migliori prestazioni; tutti gli altri cavi per lo storage o le reti Fibre Channel devono essere scollegati dalle porte.
+

NOTE: Anche se l'utilizzo delle cappe di loopback sulle interfacce FC-al non è più necessario per i sistemi che eseguono Data ONTAP 8.2, l'ambito della copertura di test sull'interfaccia è ridotto.





== Requisiti CNA

* L'utilizzo di cappe di loopback non è un requisito per l'esecuzione di test di diagnostica a livello di sistema CNA.




== Requisiti di interconnessione

* Per eseguire il test diagnostico a livello di sistema di interconnessione, entrambi i moduli controller della piattaforma in un sistema a controller doppio devono essere in modalità di manutenzione.
+

NOTE: Se si tenta di eseguire il test di diagnostica a livello di sistema di interconnessione con altri test di diagnostica a livello di sistema, viene visualizzato un messaggio di avviso.


