---
permalink: a320/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, diagnostic, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, run diagnostics, complete the replacement process 
summary: Il nuovo telaio dello stesso modello del telaio compromesso viene sostituito da un telaio non valido. 
---
= Panoramica della sostituzione dello chassis - AFF A320
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sostituire lo chassis, è necessario spostare le ventole e i moduli controller dallo chassis compromesso al nuovo chassis dello stesso modello dello chassis compromesso.

Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura si basa sul presupposto che si stiano spostando i moduli controller nel nuovo chassis e che lo chassis sia un nuovo componente di NetApp.
* Questa procedura ha un'interruzione. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

