---
permalink: c400/install-videos.html 
sidebar: sidebar 
keywords: aff c400, aff, c400, video, rack, cable, system, manager, guide, setup, initial, configuration, hardware, installation, cabling, perform, end-to-end, software, configuration, hardware installation and cabling, perform end-to-end software configuration 
summary: 'Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.' 
---
= Video - AFF C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.

Se si dispone di una configurazione MetroCluster, utilizzare il contenuto dell'installazione di MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentazione MetroCluster"^]



== Video uno di due: Installazione hardware e cablaggio

Il seguente video mostra come installare e collegare il nuovo sistema.

.Animazione - istruzioni per l'installazione e la configurazione di AFF C400
video::8e392453-beac-4db7-8088-aff1005e1f90[panopto]


== Video due di due: Esecuzione della configurazione software end-to-end

Il seguente video mostra la configurazione software end-to-end per i sistemi che eseguono ONTAP 9.2 e versioni successive.

video::WAE0afWhj1c?[youtube]