---
permalink: a800/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: aff a800, post boot media replacement steps for okm, nse, and nve 
summary: 'Una volta controllate le variabili di ambiente, è necessario completare i passaggi specifici per i sistemi che hanno attivato Onboard Key Manager (OKM), NetApp Storage Encryption (NSE) o NetApp Volume Encryption (NVE).' 
---
= Ripristinare la crittografia - AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ripristinare la crittografia sul supporto di avvio sostitutivo del sistema AFF A800 per garantire una protezione continua dei dati. Il processo di sostituzione prevede la verifica della disponibilità della chiave, la riapplicazione delle impostazioni di crittografia e la conferma dell'accesso sicuro ai dati.

Se il sistema di archiviazione esegue ONTAP 9.17.1 o versione successiva, utilizzarelink:bootmedia-replace-workflow-bmr.html["procedura di ripristino automatico dell'avvio"] .  Se il sistema esegue una versione precedente di ONTAP, è necessario utilizzare la procedura di ripristino manuale all'avvio.

Completare i passaggi appropriati per ripristinare la crittografia sul sistema in base al tipo di gestore delle chiavi.  Se non sei sicuro del gestore chiavi utilizzato dal tuo sistema, controlla le impostazioni acquisite all'inizio della procedura di sostituzione del supporto di avvio.

[role="tabbed-block"]
====
.Onboard Key Manager (OKM)
--
Ripristinare la configurazione di Onboard Key Manager (OKM) dal menu di avvio di ONTAP.

.Prima di iniziare
Assicurati di avere a disposizione le seguenti informazioni:

* Passphrase a livello di cluster inserita durante https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["abilitazione della gestione delle chiavi di bordo"]
* https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Informazioni di backup per il Key Manager integrato"]
* Verifica di avere la passphrase corretta e i dati di backup utilizzando https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["Come verificare il backup della gestione delle chiavi integrata e la passphrase a livello del cluster"] procedura


.Fasi
*Sul controller non autorizzato:*

. Collegare il cavo della console al controller non funzionante.
. Dal menu di avvio ONTAP , selezionare l'opzione appropriata:
+
[cols="1a,2a"]
|===
| Versione di ONTAP | Selezionare questa opzione 


 a| 
ONTAP 9.8 o versione successiva
 a| 
Selezionare l'opzione 10.

.Mostra un esempio di menu di avvio
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
=====


 a| 
ONTAP 9.7 e versioni precedenti
 a| 
Selezionare l'opzione nascosta `recover_onboard_keymanager`

.Mostra un esempio di menu di avvio
[%collapsible]
=====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
=====
|===
. Quando richiesto, conferma di voler continuare il processo di ripristino:
+
.Mostra prompt di esempio
[%collapsible]
=====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

=====
. Inserire due volte la passphrase a livello di cluster.
+
Durante l'inserimento della passphrase, la console non mostra alcun input.

+
.Mostra prompt di esempio
[%collapsible]
=====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

=====
. Inserisci le informazioni di backup:
+
.. Incollare l'intero contenuto dalla riga BEGIN BACKUP alla riga END BACKUP, inclusi i trattini.
+
.Mostra prompt di esempio
[%collapsible]
=====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
=====
.. Premere Invio due volte alla fine dell'input.
+
Il processo di ripristino viene completato e viene visualizzato il seguente messaggio:

+
`Successfully recovered keymanager secrets.`

+
.Mostra prompt di esempio
[%collapsible]
=====
....

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
=====
+

WARNING: Non procedere se l'output visualizzato è diverso da `Successfully recovered keymanager secrets` .  Eseguire la risoluzione dei problemi per correggere l'errore.



. Seleziona l'opzione `1` dal menu di avvio per continuare l'avvio in ONTAP.
+
.Mostra prompt di esempio
[%collapsible]
=====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====
. Verificare che la console del controller visualizzi il seguente messaggio:
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

+
*Sul controller del partner:*

. Restituire il controller non funzionante:
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`

+
*Sul controller non autorizzato:*

. Dopo aver avviato solo con l'aggregato CFO, sincronizzare il gestore delle chiavi:
+
`security key-manager onboard sync`

. Quando richiesto, immettere la passphrase dell'intero cluster per Onboard Key Manager.
+
.Mostra prompt di esempio
[%collapsible]
=====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
=====
+

NOTE: Se la sincronizzazione ha esito positivo, viene restituito il prompt del cluster senza messaggi aggiuntivi.  Se la sincronizzazione fallisce, viene visualizzato un messaggio di errore prima di tornare al prompt del cluster.  Non continuare finché l'errore non sarà stato corretto e la sincronizzazione non sarà stata eseguita correttamente.

. Verificare che tutte le chiavi siano sincronizzate:
+
`security key-manager key query -restored false`

+
Il comando non dovrebbe restituire alcun risultato.  Se vengono visualizzati dei risultati, ripetere il comando sync finché non vengono restituiti più risultati.

+
*Sul controller del partner:*

. Restituire il controller non funzionante:
+
`storage failover giveback -fromnode local`

. Ripristinare lo sconto automatico se è stato disattivato:
+
`storage failover modify -node local -auto-giveback true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.Gestore chiavi esterno (EKM)
--
Ripristinare la configurazione del gestore chiavi esterno dal menu di avvio di ONTAP.

.Prima di iniziare
Raccogli i seguenti file da un altro nodo del cluster o dal tuo backup:

* `/cfcard/kmip/servers.cfg`file o l'indirizzo e la porta del server KMIP
* `/cfcard/kmip/certs/client.crt`file (certificato client)
* `/cfcard/kmip/certs/client.key`file (chiave client)
* `/cfcard/kmip/certs/CA.pem`file (certificati CA del server KMIP)


.Fasi
*Sul controller non autorizzato:*

. Collegare il cavo della console al controller non funzionante.
. Seleziona l'opzione `11` dal menu di avvio di ONTAP .
+
.Mostra un esempio di menu di avvio
[%collapsible]
=====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
=====
. Quando richiesto, conferma di aver raccolto le informazioni richieste:
+
.Mostra prompt di esempio
[%collapsible]
=====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
=====
. Quando richiesto, immettere le informazioni sul client e sul server:
+
.. Immettere il contenuto del file del certificato client (client.crt), comprese le righe BEGIN e END.
.. Immettere il contenuto del file della chiave client (client.key), comprese le righe BEGIN e END.
.. Immettere il contenuto del file CA(s) del server KMIP (CA.pem), comprese le righe BEGIN e END.
.. Immettere l'indirizzo IP del server KMIP.
.. Immettere la porta del server KMIP (premere Invio per utilizzare la porta predefinita 5696).
+
.Mostra esempio
[%collapsible]
=====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
=====
+
Il processo di ripristino viene completato e viene visualizzato il seguente messaggio:

+
`Successfully recovered keymanager secrets.`

+
.Mostra esempio
[%collapsible]
=====
....
System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.
....
=====


. Seleziona l'opzione `1` dal menu di avvio per continuare l'avvio in ONTAP.
+
.Mostra prompt di esempio
[%collapsible]
=====
....

***************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***************************************************************************

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
=====
. Ripristinare lo sconto automatico se è stato disattivato:
+
`storage failover modify -node local -auto-giveback true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====
.Quali sono le prossime novità?
Dopo aver ripristinato la crittografia sul supporto di avvio, è necessario link:bootmedia-complete-rma.html["Restituire la parte guasta a NetApp"].
