---
permalink: a800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a800, verify and set HA state, complete the replacement process 
summary: Verificare lo stato ha del telaio e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Completare il processo di ripristino e sostituzione - AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Riavviare i controller, verificare lo stato del sistema e restituire la parte guasta a NetApp per completare il passaggio finale della procedura di sostituzione dello chassis AFF A800 .



== Fase 1: Verificare e impostare lo stato ha del telaio

.Fasi
. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _HA-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.
. Reinstallare il pannello anteriore del sistema.




== Fase 2: Verifica dello stato del sistema di archiviazione

Dopo aver completato la restituzione del controller, verificare lo stato del sistema utilizzando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] .  Risolvere eventuali problemi riscontrati.



== Fase 3: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
