---
permalink: a800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a800, verify and set HA state, run diagnostics, complete the replacement process 
summary: Verificare lo stato ha dello chassis, eseguire la diagnostica e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Completare il processo di ripristino e sostituzione - AFF A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare lo stato ha dello chassis, eseguire la diagnostica e restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit.



== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _HA-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** `ha`
*** `mcc`
*** `mccip`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.
. Reinstallare il pannello anteriore del sistema.




== Fase 2: Eseguire la diagnostica

Dopo aver sostituito un componente del sistema, è necessario eseguire test diagnostici su tale componente.

Il sistema deve essere al prompt DEL CARICATORE per avviare la diagnostica.

Tutti i comandi delle procedure diagnostiche vengono emessi dalla centralina in cui viene sostituito il componente.

.Fasi
. Se il controller da sottoporre a manutenzione non viene visualizzato al prompt DEL CARICATORE, riavviare il controller: `system node halt -node node_name`
+
Dopo aver eseguito il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

. Al prompt DEL CARICATORE, accedere ai driver speciali progettati appositamente per la diagnostica a livello di sistema per funzionare correttamente: `boot_diags`
. Selezionare *Scan System* (sistema di scansione) dal menu visualizzato per abilitare l'esecuzione dei test di diagnostica.
. Selezionare *Test Memory* dal menu visualizzato.
. Procedere in base al risultato del passaggio precedente:
+
** Se il test non ha avuto esito positivo, correggerlo ed eseguire nuovamente il test.
** Se il test non ha rilevato errori, selezionare Reboot (Riavvia) dal menu per riavviare il sistema.






== Fase 3: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
