---
permalink: asa-c800/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c800, replace the boot media 
summary: Prima di sostituire il supporto di avvio nel vostro ASA C800, assicuratevi di soddisfare i requisiti necessari per una sostituzione corretta. Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma che la porta e0S o e0M wrench sul controller danneggiato non sia difettosa e la determinazione se Onboard Key Manager o External Key Manager sono abilitati. 
---
= Requisiti per il ripristino automatico dei supporti di avvio - ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel tuo ASA C800, assicurati di soddisfare i requisiti necessari per una sostituzione riuscita.  Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma che la porta e0S (chiave e0M) sul controller danneggiato non sia difettosa e la determinazione se Onboard Key Manager (OKM) o External Key Manager (EKM) è abilitato.

Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .

[NOTE]
====
NetApp raccomanda vivamente di abilitare la registrazione della console sui dispositivi con cui si sta lavorando e di adottare le seguenti misure durante l'esecuzione di questa procedura:

* Lascia AutoSupport abilitato durante la manutenzione. Questo consente al supporto NetApp di ricevere informazioni diagnostiche in caso di problemi.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI. Questo crea una registrazione completa di tutti i comandi e dell'output di sistema durante l'attività di manutenzione. Per istruzioni su come abilitare la registrazione delle sessioni, vedere  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^].


====
* È necessario sostituire il componente guasto con un componente FRU sostitutivo della stessa capacità ricevuta da NetApp.
* Verificare che l'interfaccia e0S (porta chiave e0M) sul controller difettoso non sia guasta.
+
La porta e0M viene utilizzata per comunicare tra i due controller durante il processo di ripristino automatico dell'avvio.

* Per OKM, è necessaria la passphrase dell'intero cluster e anche i dati di backup.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** file /cfcard/kmip/servers.cfg.
** file /cfcard/kmip/certs/client.crt.
** file /cfcard/kmip/certs/client.key.
** File /cfcard/kmip/certs/CA.pem.


* Quando si sostituisce il supporto di avvio danneggiato, è fondamentale applicare i comandi al controller corretto:
+
** Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
** Il _controllore sano_ è il partner HA del controllore compromesso.




.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, si link:bootmedia-shutdown-bmr.html["spegnere il controller"].
