---
permalink: asa-c800/install-setup.html 
sidebar: sidebar 
keywords: asa c800, initial configuration options 
summary: Scegli il metodo di installazione più adatto alle tue esigenze per configurare un sistema ASA C800, utilizzando istruzioni grafiche rapide, video tutorial o guide dettagliate passo passo. 
---
= Flusso di lavoro per l'installazione e la configurazione di ASA C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scegli il metodo di installazione più adatto alle tue esigenze per configurare un sistema ASA C800, utilizzando istruzioni grafiche rapide, video tutorial o guide dettagliate passo passo.

* link:../asa-c800/install-quick-guide.html["Passaggi rapidi"]
+
Un PDF stampabile con istruzioni dettagliate con collegamenti in tempo reale a contenuti aggiuntivi.

* link:../asa-c800/install-videos.html["Video fasi"]
+
Video istruzioni dettagliate.

* link:../asa-c800/install-detailed-guide.html["Passaggi dettagliati"]
+
Istruzioni passo-passo online con collegamenti in tempo reale a contenuti aggiuntivi.



Se il sistema si trova in una configurazione MetroCluster IP, consultare https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installare la configurazione IP di MetroCluster"^] istruzioni.
