---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: 'Prima di sostituire il supporto di avvio nel sistema di archiviazione ASA C30, accertarsi di soddisfare i requisiti e le considerazioni necessari per una sostituzione riuscita.  Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma che la porta e0M (chiave inglese) sul controller danneggiato funzioni correttamente e la determinazione se Onboard Key Manager (OKM) o External Key Manager (EKM) è abilitato.' 
---
= Requisiti per sostituire i supporti di avvio - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema di archiviazione ASA C30, accertarsi di soddisfare i requisiti e le considerazioni necessari per una sostituzione riuscita.  Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma che la porta e0M (chiave inglese) sul controller danneggiato funzioni correttamente e la determinazione se Onboard Key Manager (OKM) o External Key Manager (EKM) è abilitato.

* È necessario sostituire il componente guasto con un componente FRU sostitutivo della stessa capacità ricevuta da NetApp.
* Verificare che la porta e0M (chiave inglese) sul controller danneggiato sia collegata e non sia difettosa.
+
La porta e0M viene utilizzata per comunicare tra i due controller durante il processo di ripristino automatico dell'avvio.

* Per OKM, è necessaria la passphrase dell'intero cluster e anche i dati di backup.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** file /cfcard/kmip/servers.cfg.
** file /cfcard/kmip/certs/client.crt.
** file /cfcard/kmip/certs/client.key.
** File /cfcard/kmip/certs/CA.pem.


* Quando si sostituisce il supporto di avvio danneggiato, è fondamentale applicare i comandi al controller corretto:
+
** Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
** Il _controllore sano_ è il partner HA del controllore compromesso.




.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, si link:bootmedia-shutdown-bmr.html["spegnere il controller"].
