---
permalink: asa-r2-c30/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: asa c30, replace the chassis 
summary: Prima di sostituire il telaio del sistema di archiviazione ASA C30, accertarsi di soddisfare i requisiti necessari per una sostituzione riuscita. Ciò comprende la verifica del corretto funzionamento di tutti gli altri componenti del sistema, la verifica della correttezza del telaio di ricambio e degli strumenti necessari. 
---
= Requisiti per la sostituzione del telaio - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il telaio del sistema di archiviazione ASA C30, accertarsi di soddisfare i requisiti necessari per una sostituzione riuscita. Ciò comprende la verifica del corretto funzionamento di tutti gli altri componenti del sistema, la verifica della correttezza del telaio di ricambio e degli strumenti necessari.

Esaminare i seguenti requisiti e considerazioni.



== Requisiti

* Il telaio di ricambio deve essere dello stesso modello del telaio danneggiato. Questa procedura si riferisce a una sostituzione simile a quella di un prodotto, non a un aggiornamento.
* Tutti gli altri componenti del sistema di stoccaggio devono funzionare correttamente; in caso contrario, contattare https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] prima di continuare con questa procedura.




== Considerazioni

* La procedura di sostituzione dello chassis provoca interruzioni. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.
* Puoi utilizzare la procedura di sostituzione dello chassis con tutte le versioni di ONTAP supportate dal tuo sistema storage.
* La procedura di sostituzione dello chassis viene scritta presupponendo che il pannello, le unità, gli eventuali alloggiamenti e i controller vengano spostati nel nuovo chassis.


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti per la sostituzione del telaio, è necessario link:chassis-replace-shutdown.html["spegnere i controller"]
