---
permalink: asa-r2-c30/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module 
summary: 'Il sistema di storage ASA C30 offre flessibilità nell"espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni della rete. L"aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.' 
---
= Panoramica su aggiunta e sostituzione di un modulo i/o - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema di storage ASA C30 offre flessibilità nell'espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni della rete. L'aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di ulteriori moduli di i/o può migliorare la ridondanza, contribuendo a garantire che il sistema di storage rimanga operativo anche in caso di guasto di un modulo di i/O.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema di storage allo stato operativo ottimale.


