---
permalink: asa-r2-c30/maintain-overview.html 
sidebar: sidebar 
keywords: asa c30, maintenance, maintenance 
summary: 'Conserva l"hardware del tuo sistema storage ASA C30 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.' 
---
= Panoramica della manutenzione hardware - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conserva l'hardware del tuo sistema storage ASA C30 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.

Le procedure descritte in questa sezione presuppongono che il sistema di archiviazione ASA C30 sia già stato distribuito come nodo di archiviazione nell'ambiente ONTAP.



== Componenti del sistema

Per il sistema di archiviazione ASA C30, è possibile eseguire le procedure di manutenzione sui seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Supporto di avvio - ripristino automatico"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio.  Durante il ripristino automatico, il sistema recupera l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione di menu di avvio appropriata per installare l'immagine sul supporto di avvio sostitutivo.

Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .



 a| 
link:bootmedia-replace-workflow.html["Supporto di avvio - ripristino manuale"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per avviare l'immagine da un'unità USB e ripristinare la configurazione dal nodo partner



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla le unità ed esegue il software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un modulo DIMM (Dual in-line Memory Module) è un tipo di memoria per computer. Vengono installati per aggiungere memoria di sistema a una scheda madre del controller.



 a| 
link:drive-replace.html["Disco"]
 a| 
Un'unità è un dispositivo che fornisce l'archiviazione fisica necessaria per i dati.



 a| 
link:fan-replace.html["Ventola"]
 a| 
Una ventola raffredda il controller e le unità.



 a| 
link:io-module-overview.html["Modulo i/O."]
 a| 
Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



 a| 
link:nvdimm-battery-replace.html["Batteria NV"]
 a| 
La batteria della memoria non volatile (NV) è responsabile della fornitura di alimentazione ai componenti NVMEM mentre i dati in volo vengono trasferiti nella memoria flash dopo un'interruzione dell'alimentazione.



 a| 
link:power-supply-replace.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc-battery-replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria dell'orologio in tempo reale conserva le informazioni relative alla data e all'ora del sistema se l'alimentazione è spenta.

|===