---
permalink: a250/overview.html 
sidebar: sidebar 
keywords: AFF A250 specifications, AFF A250 specs, NetApp AFF A250, AFF A250 hardware 
summary: Specifiche chiave per il sistema di archiviazione AFF A250 
---
= Specifiche chiave per AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' AFF A250.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche AFF A250 .  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per AFF A250

Configurazione della piattaforma: coppia HA a telaio singolo AFF A250

Capacità massima grezza: 1,1016 PB

Memoria: 128.0000 GB

Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 4

Versione minima ONTAP : ONTAP 9.8RC1



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS | 12 | 13,2 PB / 11,7 PiB | 1536 GB 


| SAN | 6 | 6,6 PB / 5,9 PiB | 768 GB 


| Coppia HA |  | 1,1 PB / 1,0 PiB | 128,0000 
|===


=== Io



==== IO di bordo

|===


| Protocollo | porti 


| Ethernet 25 Gbps | 4 


| Ethernet 10 Gbps | 4 
|===


==== IO totale

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 4 


| Ethernet 25 Gbps | 20 


| Ethernet 10 Gbps | 4 


| FC 32 Gbps | 16 


| NVMe/FC 32 Gbps | 16 


|  | 0 


| SAS 12 Gbps | 8 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rete di archiviazione supportata

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 2642 BTU/ora
* Potenza nel caso peggiore: 3476 BTU/ora
* Peso: 54,3 libbre 24,6 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità:
* Temperatura/altitudine/umidità di funzionamento: da 10°C a 35°C (da 50°F a 95°F) fino a 3048 m (10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: potenza sonora dichiarata (LwAd): 7,2; pressione sonora (LpAm) (posizioni degli astanti): 69,1 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda base (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo; Gestione in banda SAS tramite connessioni SAS per ripiani esterni;
