---
permalink: fas8200/chassis-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, replace the chassis 
summary: 'Prima di sostituire lo chassis in un sistema FAS8200, verifica che tutti gli altri componenti funzionino correttamente e che lo chassis di ricambio sia un componente nuovo di NetApp dello stesso modello. La procedura richiede di spostare gli alimentatori, le ventole e i moduli controller nel nuovo chassis ed è di tipo disruptive, causando un"interruzione completa del servizio in un cluster a due controller o un"interruzione parziale in un cluster multinodo.' 
---
= Verifica i requisiti prima di sostituire lo chassis in un sistema FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire lo chassis in un sistema FAS8200, verifica che tutti gli altri componenti funzionino correttamente e che lo chassis di ricambio sia un componente nuovo di NetApp dello stesso modello. La procedura richiede di spostare gli alimentatori, le ventole e i moduli controller nel nuovo chassis ed è di tipo disruptive, causando un'interruzione completa del servizio in un cluster a due controller o un'interruzione parziale in un cluster multinodo.

Tutti gli altri componenti del sistema devono funzionare correttamente. Se non è così, contatta il supporto tecnico.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura si basa sul presupposto che il modulo controller o i moduli vengano trasferiti nel nuovo chassis e che lo chassis sia un nuovo componente di NetApp.
* Questa procedura è invasiva. Per un cluster a due controller, si verifica un'interruzione completa del servizio e un'interruzione parziale in un cluster multi-nodo.

