---
permalink: afx-1k/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shut down the controller 
summary: Arrestare il controller danneggiato nel sistema di archiviazione AFX 1K per evitare la perdita di dati e garantire la stabilità del sistema durante la sostituzione del supporto di avvio. 
---
= Spegnere il controller per sostituire il supporto di avvio - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arrestare il controller danneggiato nel sistema di archiviazione AFX 1K per evitare la perdita di dati e garantire la stabilità del sistema durante la sostituzione del supporto di avvio.

Per arrestare il controller danneggiato, è necessario determinarne lo stato e, se necessario, eseguire un failover di archiviazione del controller in modo che il controller funzionante continui a elaborare i dati dall'archiviazione del controller danneggiato.

.A proposito di questa attività
* Se si dispone di un cluster con più di quattro nodi, è necessario che sia raggiunto il quorum.  Per visualizzare le informazioni del cluster sui nodi, utilizzare `cluster show` comando.  Per maggiori informazioni sul `cluster show` comando, vederelink:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["Visualizza i dettagli a livello di nodo in un cluster ONTAP"^] .
* Se il cluster non è in quorum o se lo stato di integrità o l'idoneità di un qualsiasi controller (diverso dal controller non funzionante) risulta falso, è necessario correggere il problema prima di arrestare il controller non funzionante. Vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^] .


.Fasi
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore:

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattivare il ritorno automatico dalla console del controllore non abilitato:
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: Quando vedi _Vuoi disattivare la restituzione automatica?_, inserisci `y` .

+
.. Se si utilizza ONTAP versione 9.17.1 e il controller non funzionante non può essere avviato o è già stato preso in carico, è necessario disattivare il collegamento di interconnessione HA dal controller funzionante prima di avviare il controller non funzionante.  Ciò impedisce al controllore compromesso di eseguire la restituzione automatica.
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`

+

NOTE: Se non si utilizza la versione 9.17.1 ONTAP , saltare il passaggio precedente e andare al passaggio 3.



. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Passare alla fase successiva.



 a| 
Prompt di sistema o prompt della password
 a| 
Prendere il controllo o interrompere il controllo del controllore sano da parte del controllore compromesso:
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

Il parametro _-halt true_ porta il nodo danneggiato al prompt LOADER.

|===


.Quali sono le prossime novità?
Dopo aver spento il controller,link:bootmedia-replace.html["cambiare il supporto di avvio"] .
