---
permalink: asa150/install-setup.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, install, setup, initial configuration 
summary: Installare e configurare il sistema. 
---
= Inizia qui: Scegli la tua esperienza di installazione e configurazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la maggior parte delle configurazioni, è possibile scegliere tra diversi formati di contenuto.

* link:../asa150/install-quick-guide.html["Passaggi rapidi"]
+
Un PDF stampabile con istruzioni dettagliate con collegamenti in tempo reale a contenuti aggiuntivi.

* link:../asa150/install-videos.html["Video fasi"]
+
Video istruzioni dettagliate.

* link:../asa150/install-detailed-guide.html["Passaggi dettagliati"]
+
Istruzioni passo-passo online con collegamenti in tempo reale a contenuti aggiuntivi.



Se il sistema si trova in una configurazione MetroCluster IP, consultare https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installare la configurazione IP di MetroCluster"] istruzioni.

*Attenzione:* se il sistema viene installato con ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 o ONTAP 9.15,1 - 9.15.1P2 e il sistema contiene 10 o più unità a stato solido interne, è necessario eseguire ulteriori operazioni per preparare il sistema all'installazione. Vedere il numero  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173 - ADP non lascia una partizione root di riserva su un AFF A150 con 10 o più dischi interni"^].
