---
permalink: asa150/install-videos.html 
sidebar: sidebar 
keywords: asa a150, a150, asa, asa a220, video, rack, cable, system, manager, guided, setup, configuration 
summary: 'Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.' 
---
= Fasi video - ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizza i seguenti video per scoprire come collegare in rack e cablare il sistema ed eseguire la configurazione iniziale del sistema.

Se si dispone di una configurazione MetroCluster, utilizzare https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentazione MetroCluster"^].

*Attenzione:* se il sistema viene installato con ONTAP 9.13.1P8 - 9.13.1P11, ONTAP 9.14.1P1 - 9.14.1P7 o ONTAP 9.15,1 - 9.15.1P2 e il sistema contiene 10 o più unità a stato solido interne, è necessario eseguire ulteriori operazioni per preparare il sistema all'installazione. Vedere il numero  https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-285173["CONTAP-285173 - ADP non lascia una partizione root di riserva su un AFF A150 con 10 o più dischi interni"^].

Installazione e cablaggio dell'hardware:: Il video seguente mostra come installare e collegare il sistema.


.Animazione - Installazione e configurazione di un AFF A150
video::561d941a-f387-4eb9-a10a-afb30029eb36[panopto]

NOTE: Il sistema ASA A150 utilizza la stessa procedura di installazione del sistema AFF A150.
