---
permalink: asa150/overview.html 
sidebar: sidebar 
summary: Specifiche chiave per il gruppo di piattaforme ASA150 
---
= Specifiche chiave per ASA A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione ASA A150 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche chiave per ASA A150

* Configurazione della piattaforma: ASA A150 UTA2 Single Chassis HA Pair
* Capacità massima grezza: 0,5472 PB
* Memoria: 64.0000 GB
* Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità
* Versione ONTAP : ONTAP: 9.16.1P2
* Versione minima ONTAP : ONTAP 9.13.1 == Massimi di scalabilità
* Tipo: NAS
* Tipo: SAN; Coppie HA: 6; Capacità grezza: 3,3 PB / 2,9 PiB; Memoria massima: 384 GB
* Tipo: coppia HA; capacità grezza: 0,5 PB / 0,5 PiB; memoria massima: 64.0000




== I/O



=== I/O integrato

* Protocollo: Ethernet 10 Gbps; Porte: 12
* Protocollo: FC 16 Gbps; Porte: 8
* Protocollo: SAS 12 Gbps; Porte: 4




=== Totale I/O

* Protocollo: Ethernet 10 Gbps; Porte: 12
* Protocollo: FC 16 Gbps; Porte: 8
* Protocollo: SAS 12 Gbps; Porte: 4




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 12 Mbps; Porte: 2




== Rete di archiviazione supportata

* FC
* iSCSI
* NVMe/TCP == Specifiche dell'ambiente di sistema Nessun dato sull'ambiente disponibile.




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo
* Gestione in banda SAS su connessioni SAS

