---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: 'Prima di sostituire il controller nel sistema di storage FAS50, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ciò include la verifica del corretto funzionamento di tutti gli altri componenti del sistema, la verifica della corretta sostituzione del controller e il salvataggio dell"output della console del controller in un file di registro di testo.' 
---
= Requisiti per sostituire la centralina - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il controller nel sistema di storage FAS50, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ciò include la verifica del corretto funzionamento di tutti gli altri componenti del sistema, la verifica della corretta sostituzione del controller e il salvataggio dell'output della console del controller in un file di registro di testo.

Esaminare i requisiti e le considerazioni per la procedura di sostituzione della centralina.

[NOTE]
====
NetApp raccomanda vivamente di abilitare la registrazione della console sui dispositivi con cui si sta lavorando e di adottare le seguenti misure durante l'esecuzione di questa procedura:

* Lascia AutoSupport abilitato durante la manutenzione. Questo consente al supporto NetApp di ricevere informazioni diagnostiche in caso di problemi.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI. Questo crea una registrazione completa di tutti i comandi e dell'output di sistema durante l'attività di manutenzione. Per istruzioni su come abilitare la registrazione delle sessioni, vedere  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^].


====


== Requisiti

* Tutti i ripiani devono funzionare correttamente.
* Il controller integro deve essere in grado di assumere il controllo del controller da sostituire (indicato in questa procedura come "`controller alterato`").
* Se il sistema si trova in una configurazione MetroCluster, consultare la sezione https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Scelta della procedura di ripristino corretta"] per determinare se utilizzare questa procedura.
* È necessario sostituire un controller con un controller dello stesso tipo di modello. Non è possibile aggiornare il sistema semplicemente sostituendo il controller.
* Non è possibile sostituire dischi o shelf nell'ambito di questa procedura.




== Considerazioni

È importante applicare i comandi di questa procedura al controller corretto:

* Il controller _alterato_ è il controller che viene sostituito.
* Il controller _replacement_ è il nuovo controller che sostituisce il controller compromesso.
* Il controller _healthy_ è il controller sopravvissuto.


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti per sostituire il controller danneggiato, è necessario link:controller-replace-shutdown.html["spegnere il controller danneggiato"].
