---
sidebar: sidebar 
permalink: fas50/install-requirements.html 
keywords: fas50, install, setup, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per la piattaforma e i ripiani.' 
---
= Requisiti di installazione - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica i requisiti del tuo sistema storage FAS50.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi e gli shelf di storage sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Peso del sistema di storage

Prendere le precauzioni necessarie durante lo spostamento o il sollevamento del sistema di stoccaggio.

Il sistema di stoccaggio può pesare fino a 24,4 kg (53,8 lb). Per sollevare l'impianto di stoccaggio, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[FAS50 icona di attenzione del peso]



=== Peso del ripiano

Prendere le precauzioni necessarie quando si sposta o si solleva il ripiano.

Un ripiano DS460C può pesare fino a 181,1 kg (260,4 lb). Per sollevare il ripiano, potrebbero essere necessarie fino a cinque persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460C attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti di installazione e le considerazioni relative al sistema di archiviazione, è possibile link:install-prepare.html["prima dell'installazione"].
