---
permalink: fas50/install-hardware.html 
sidebar: sidebar 
keywords: fas50, install hardware, telco rack 
summary: 'Dopo aver preparato l"installazione del sistema di storage FAS50, installare l"hardware per il sistema di storage. Per prima cosa, montare i kit guide. Quindi, installare e proteggere il sistema di archiviazione in un cabinet o in un rack per telecomunicazioni.' 
---
= Montare la bulloneria - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver preparato l'installazione del sistema di storage FAS50, installare l'hardware per il sistema di storage. Per prima cosa, montare i kit guide. Quindi, installare e proteggere il sistema di archiviazione in un cabinet o in un rack per telecomunicazioni.

Saltare questo passaggio se il sistema di archiviazione è stato installato in un cabinet.

.Prima di iniziare
* Assicurarsi di avere le istruzioni fornite con il kit guida.
* Prestare attenzione ai problemi di sicurezza associati al peso del sistema di stoccaggio e dello scaffale.
* Tenere presente che il flusso d'aria attraverso il sistema di storage entra dalla parte anteriore dove sono installati il pannello o i cappucci terminali e fuoriesce dalla parte posteriore dove si trovano le porte.


.Fasi
. Installare i kit guide per il sistema di archiviazione e gli scaffali secondo necessità, seguendo le istruzioni fornite con i kit.
. Installare e fissare il sistema di archiviazione nell'armadietto o nel rack per telecomunicazioni:
+
.. Posizionare il sistema di stoccaggio sulle guide al centro del cabinet o del rack per telecomunicazioni, quindi sostenere il sistema di archiviazione dal basso e farlo scorrere in posizione.
.. Assicurarsi che i perni di guida del cabinet o del rack per telecomunicazioni siano fissati negli slot della guida del telaio.
.. Fissare il sistema di archiviazione all'armadietto o al rack per telecomunicazioni utilizzando le viti di montaggio incluse.


. Fissare il frontalino alla parte anteriore del sistema di archiviazione.
. Installare e fissare il ripiano secondo necessità.
+
.. Posizionare la parte posteriore del ripiano sulle guide, quindi sostenere il ripiano dal basso e farlo scorrere nell'armadietto o nel rack per telecomunicazioni.
+
Se si installano più shelf, posizionare il primo shelf direttamente sopra i controller. Posizionare il secondo ripiano direttamente sotto i controller. Ripetere questo modello per tutti i ripiani aggiuntivi.

.. Fissare il ripiano all'armadietto o al rack per telecomunicazioni utilizzando le viti di montaggio incluse.
+
.Quali sono le prossime novità?
Dopo aver installato l'hardware per il sistema di archiviazione, si link:install-cable.html["collegare la bulloneria"].




