---
permalink: fas50/maintain-overview.html 
sidebar: sidebar 
keywords: fas50 maintenance, maintenance, repairing fas50, replace fas50 components 
summary: 'Mantenete l"hardware del vostro sistema di storage FAS50 per garantire affidabilità a lungo termine e prestazioni ottimali. Eseguite regolarmente attività di manutenzione, come la sostituzione di componenti difettosi, per prevenire tempi di inattività e perdite di dati.' 
---
= Panoramica della manutenzione hardware - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantenete l'hardware del vostro sistema di storage FAS50 per garantire affidabilità a lungo termine e prestazioni ottimali. Eseguite regolarmente attività di manutenzione, come la sostituzione di componenti difettosi, per prevenire tempi di inattività e perdite di dati.

Le procedure di manutenzione presuppongono che il sistema di archiviazione FAS50 sia già stato distribuito come nodo di archiviazione nell'ambiente ONTAP .



== Componenti del sistema

Per i sistemi di archiviazione FAS50, è possibile eseguire le procedure di manutenzione sui seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Supporto di avvio - ripristino automatico"]
 a| 
Il supporto di avvio memorizza un set primario e uno secondario di file immagine ONTAP che il sistema di storage utilizza per avviare l'immagine dal nodo partner ed eseguire automaticamente l'opzione appropriata del menu di avvio per installare l'immagine di avvio sul supporto di avvio sostitutivo. Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .



 a| 
link:bootmedia-replace-workflow.html["Supporto di avvio - ripristino manuale"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per avviare l'immagine da un'unità USB e ripristinare la configurazione dal nodo partner.



 a| 
link:caching-module-hot-swap.html["Modulo di caching"]
 a| 
Un modulo di caching (modulo Flash cache) utilizza gli SSD ad alta velocità per memorizzare i dati a cui si accede più frequentemente per un recupero più rapido.



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla le unità ed esegue il software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un modulo DIMM (Dual in-line Memory Module) è un tipo di memoria per computer. Vengono installati per aggiungere memoria di sistema a una scheda madre del controller.



 a| 
link:fan-replace.html["Ventola"]
 a| 
Una ventola raffredda il controller e le unità.



 a| 
link:io-module-overview.html["Modulo i/O."]
 a| 
Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



 a| 
link:nvdimm-battery-replace.html["Batteria NV"]
 a| 
La batteria della memoria non volatile (NV) è responsabile della fornitura di alimentazione ai componenti NVMEM mentre i dati in volo vengono trasferiti nella memoria flash dopo un'interruzione dell'alimentazione.



 a| 
link:power-supply-replace.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc-battery-replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria dell'orologio in tempo reale conserva le informazioni relative alla data e all'ora del sistema se l'alimentazione è spenta.

|===