---
permalink: fas9500/bootmedia-recovery-image-boot-bmr.html 
sidebar: sidebar 
keywords: fas9500, boot the recovery image 
summary: Dopo aver installato il nuovo dispositivo di supporto di avvio nel sistema FAS9500 , è possibile avviare il processo di ripristino automatico del supporto di avvio per ripristinare la configurazione dal nodo partner. 
---
= Ripristino automatico del supporto di avvio dal nodo partner - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver installato il nuovo dispositivo di supporto di avvio nel sistema FAS9500 , è possibile avviare il processo di ripristino automatico del supporto di avvio per ripristinare la configurazione dal nodo partner. Durante il processo di ripristino, il sistema verifica se la crittografia è abilitata e determina il tipo di crittografia a chiave in uso. Se la crittografia a chiave è abilitata, il sistema guida l'utente attraverso i passaggi appropriati per ripristinarla.

Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .

.Prima di iniziare
* Determina il tipo di gestore delle chiavi:
+
** Onboard Key Manager (OKM): richiede passphrase e dati di backup per l'intero cluster
** External Key Manager (EKM): richiede i seguenti file dal nodo partner:
+
*** `/cfcard/kmip/servers.cfg`
*** `/cfcard/kmip/certs/client.crt`
*** `/cfcard/kmip/certs/client.key`
*** `/cfcard/kmip/certs/CA.pem`






.Fasi
. Dal prompt LOADER, avviare il processo di ripristino del supporto di avvio:
+
`boot_recovery -partner`

+
Sullo schermo viene visualizzato il seguente messaggio:

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Monitorare il processo di ripristino dell'installazione dei supporti di avvio.
+
Il processo viene completato e viene visualizzato il `Installation complete` messaggio.

. Il sistema verifica la crittografia e visualizza uno dei seguenti messaggi:
+
[cols="1,2"]
|===
| Se viene visualizzato questo messaggio... | Eseguire questa operazione... 


 a| 
`key manager is not configured. Exiting.`
 a| 
La crittografia non è installata sul sistema.

.. Attendi che venga visualizzato il prompt di accesso.
.. Accedi al nodo e restituisci lo storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. Vai a <<reenable-auto-giveback,riattivazione della restituzione automatica>> se fosse disabilitato.




 a| 
`key manager is configured.`
 a| 
La crittografia è installata. Vai a<<restore-key-manager,ripristino del gestore delle chiavi>> .

|===
+

NOTE: Se il sistema non riesce a identificare la configurazione del gestore delle chiavi, visualizza un messaggio di errore e chiede di confermare se il gestore delle chiavi è configurato e di che tipo (integrato o esterno).  Rispondi alle richieste per procedere.

. [[restore-key-manager]] Ripristina il key manager utilizzando la procedura appropriata per la tua configurazione:
+
[role="tabbed-block"]
====
.Onboard Key Manager (OKM)
--
Il sistema visualizza il seguente messaggio e inizia a eseguire l'opzione BootMenu 10:

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. Entra `y` alla richiesta di conferma di voler avviare il processo di ripristino OKM.
.. Quando richiesto, immettere la passphrase per la gestione delle chiavi integrate.
.. Quando richiesto, immettere nuovamente la passphrase per confermare.
.. Quando richiesto, immettere i dati di backup per il gestore delle chiavi integrato.
+
.Mostra un esempio di richiesta di passphrase e dati di backup
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END BACKUP-----
....
=====
.. Monitorare il processo di ripristino mentre ripristina i file appropriati dal nodo partner.
+
Una volta completato il processo di ripristino, il nodo si riavvia.  I seguenti messaggi indicano un ripristino riuscito:

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.

Successfully recovered keymanager secrets.
....
.. Dopo il riavvio del nodo, verificare che il sistema sia di nuovo online e operativo.
.. Riportare la centralina guasta al normale funzionamento restituendo la memoria:
+
`storage failover giveback -ofnode _impaired_node_name_`

.. Dopo che il nodo partner è completamente attivo e fornisce dati, sincronizzare le chiavi OKM nel cluster:
+
`security key-manager onboard sync`

+
Vai a <<reenable-auto-giveback,riattivazione della restituzione automatica>> se fosse disabilitato.



--
.Gestore chiavi esterno (EKM)
--
Il sistema visualizza il seguente messaggio e inizia a eseguire l'opzione BootMenu 11:

....
key manager is configured.
Entering Bootmenu Option 11...
....
.. Quando richiesto, immettere le impostazioni di configurazione EKM:
+
... Immettere il contenuto del certificato client da `/cfcard/kmip/certs/client.crt` file:
+
.Mostra un esempio di contenuto del certificato client
[%collapsible]
=====
....
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
....
=====
... Immettere il contenuto del file chiave client da `/cfcard/kmip/certs/client.key` file:
+
.Mostra un esempio di contenuto del file della chiave client
[%collapsible]
=====
....
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----
....
=====
... Immettere il contenuto del file CA del server KMIP da `/cfcard/kmip/certs/CA.pem` file:
+
.Mostra un esempio del contenuto del file del server KMIP
[%collapsible]
=====
....
-----BEGIN CERTIFICATE-----
<KMIP_certificate_CA_value>
-----END CERTIFICATE-----
....
=====
... Immettere il contenuto del file di configurazione del server da `/cfcard/kmip/servers.cfg` file:
+
.Mostra un esempio del contenuto del file di configurazione del server
[%collapsible]
=====
....
xxx.xxx.xxx.xxx:5696.host=xxx.xxx.xxx.xxx
xxx.xxx.xxx.xxx:5696.port=5696
xxx.xxx.xxx.xxx:5696.trusted_file=/cfcard/kmip/certs/CA.pem
xxx.xxx.xxx.xxx:5696.protocol=KMIP1_4
1xxx.xxx.xxx.xxx:5696.timeout=25
xxx.xxx.xxx.xxx:5696.nbio=1
xxx.xxx.xxx.xxx:5696.cert_file=/cfcard/kmip/certs/client.crt
xxx.xxx.xxx.xxx:5696.key_file=/cfcard/kmip/certs/client.key
xxx.xxx.xxx.xxx:5696.ciphers="TLSv1.2:kRSA:!CAMELLIA:!IDEA:!RC2:!RC4:!SEED:!eNULL:!aNULL"
xxx.xxx.xxx.xxx:5696.verify=true
xxx.xxx.xxx.xxx:5696.netapp_keystore_uuid=<id_value>
....
=====
... Se richiesto, immettere l'UUID del cluster ONTAP dal nodo partner.  È possibile controllare l'UUID del cluster dal nodo partner utilizzando `cluster identify show` comando.
+
.Mostra un esempio di prompt UUID del cluster ONTAP
[%collapsible]
=====
....
Notice: bootarg.mgwd.cluster_uuid is not set or is empty.
Do you know the ONTAP Cluster UUID? {y/n} y
Enter the ONTAP Cluster UUID: <cluster_uuid_value>


System is ready to utilize external key manager(s).
....
=====
... Se richiesto, immettere l'interfaccia di rete temporanea e le impostazioni per il nodo:
+
**** L'indirizzo IP per la porta
**** La netmask per la porta
**** L'indirizzo IP del gateway predefinito
+
.Mostra un esempio di richieste di impostazione di rete temporanee
[%collapsible]
=====
....
In order to recover key information, a temporary network interface needs to be
configured.

Select the network port you want to use (for example, 'e0a')
e0M

Enter the IP address for port : xxx.xxx.xxx.xxx
Enter the netmask for port : xxx.xxx.xxx.xxx
Enter IP address of default gateway: xxx.xxx.xxx.xxx
Trying to recover keys from key servers....
[discover_versions]
[status=SUCCESS reason= message=]
....
=====




.. Verificare lo stato di ripristino della chiave:
+
*** Se vedi `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696` nell'output, la configurazione EKM è stata ripristinata correttamente.  Il processo ripristina i file appropriati dal nodo partner e riavvia il nodo.  Procedere al passaggio successivo.
*** Se il ripristino della chiave non riesce, il sistema si blocca e visualizza messaggi di errore e di avviso.  Eseguire nuovamente il processo di ripristino dal prompt LOADER: `boot_recovery -partner`
+
.Mostrare un esempio di messaggi di errore e di avvertenza relativi al ripristino della chiave
[%collapsible]
=====
....
ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>
....
=====


.. Dopo il riavvio del nodo, verificare che il sistema sia di nuovo online e operativo.
.. Riportare il controller al funzionamento normale restituendo lo storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
Vai a <<reenable-auto-giveback,riattivazione della restituzione automatica>> se fosse disabilitato.



--
====


. [[reenable-auto-giveback]]Se il giveback automatico è stato disabilitato, riabilitalo:
+
`storage failover modify -node local -auto-giveback true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi:
+
`system node autosupport invoke -node * -type all -message MAINT=END`



.Cosa succederà
Dopo aver ripristinato l'immagine ONTAP e dopo aver attivato e distribuito i dati, si link:bootmedia-complete-rma-bmr.html["Restituire la parte guasta a NetApp"].
