---
permalink: fas9500/dimm_replace.html 
sidebar: sidebar 
keywords:  
summary: 'È necessario sostituire un modulo DIMM nel modulo controller quando il sistema registra un numero crescente di codici di correzione degli errori correggibili (ECC); in caso contrario, si verifica un errore di sistema.' 
---
= Sostituire un DIMM - FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario sostituire un modulo DIMM nel modulo controller quando il sistema registra un numero crescente di codici di correzione degli errori correggibili (ECC); in caso contrario, si verifica un errore di sistema.

.Prima di iniziare
Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.



== Fase 1: Spegnere il nodo compromesso

Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso.

.A proposito di questa attività
* Se si utilizza NetApp Storage Encryption, è necessario reimpostare il MSID seguendo le istruzioni riportate in link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Ripristino dei SED in modalità non protetta"].
* Se si dispone di un sistema SAN, è necessario controllare i messaggi di evento  `cluster kernel-service show`) Per blade SCSI del controller deteriorati. Il `cluster kernel-service show` command visualizza il nome del nodo, lo stato del quorum di quel nodo, lo stato di disponibilità di quel nodo e lo stato operativo di quel nodo.
+
Ogni processo SCSI-blade deve essere in quorum con gli altri nodi del cluster. Eventuali problemi devono essere risolti prima di procedere con la sostituzione.

* Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].


.Fasi
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattivare il giveback automatico dalla console del controller integro: `storage failover modify –node local -auto-giveback false`
+

NOTE: Quando viene visualizzato _Vuoi disattivare il giveback automatico?_, inserisci `y`.

. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
In attesa di un giveback...
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode _impaired_node_name_`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===




== Fase 2: Rimuovere il modulo controller

Per accedere ai componenti all'interno del controller, rimuovere prima il modulo controller dal sistema, quindi rimuovere il coperchio sul modulo controller.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Scollegare i cavi dal modulo controller guasto e tenere traccia del punto in cui sono stati collegati i cavi.
. Far scorrere verso il basso il pulsante terra cotta sulla maniglia della camma fino a sbloccarla.
+
.Animazione - rimuovere il controller
video::5e029a19-8acc-4fa1-be5d-ae78004b365a[panopto]
+
image::../media/drw_9500_remove_PCM.svg[Drw 9500 rimuovere il PCM]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Pulsante di rilascio della maniglia della camma



 a| 
image::../media/legend_icon_02.svg[icona legenda 02]
 a| 
Maniglia CAM

|===
. Ruotare la maniglia della camma in modo da disimpegnare completamente il modulo controller dal telaio, quindi estrarre il modulo controller dal telaio.
+
Assicurarsi di sostenere la parte inferiore del modulo controller mentre lo si sposta fuori dallo chassis.

. Posizionare il coperchio del modulo controller con il lato rivolto verso l'alto su una superficie stabile e piana, premere il pulsante blu sul coperchio, far scorrere il coperchio sul retro del modulo controller, quindi sollevare il coperchio ed estrarlo dal modulo controller.
+
image::../media/drw_9500_PCM_open.svg[Drw 9500 PCM aperto]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Pulsante di bloccaggio del coperchio del modulo controller

|===




== Fase 3: Sostituire i DIMM

Per sostituire i moduli DIMM, individuarli all'interno del controller e seguire la sequenza di passaggi specifica.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Individuare i DIMM sul modulo controller.
+
image::../media/drw_9500_DIMM_map.svg[Mappa DIMM drw 9500]

. Estrarre il modulo DIMM dal relativo slot spingendo lentamente verso l'esterno le due linguette di espulsione dei moduli DIMM su entrambi i lati del modulo, quindi estrarre il modulo DIMM dallo slot.
+

IMPORTANT: Tenere il modulo DIMM per i bordi in modo da evitare di esercitare pressione sui componenti della scheda a circuiti stampati del modulo DIMM.

+
.Animazione - sostituire i DIMM
video::d62a4c7c-8296-4d60-9981-ae78004b36f7[panopto]
+
image::../media/drw_9500_replace_PCM_dimms.svg[Drw 9500 sostituire i moduli dimm PCM]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Schede di espulsione DIMM



 a| 
image::../media/legend_icon_02.svg[icona legenda 02]
 a| 
DIMM

|===
. Rimuovere il modulo DIMM di ricambio dalla confezione antistatica, tenerlo per gli angoli e allinearlo allo slot.
+
La tacca tra i pin del DIMM deve allinearsi con la linguetta dello zoccolo.

. Assicurarsi che le linguette di espulsione del modulo DIMM sul connettore siano aperte, quindi inserire il modulo DIMM correttamente nello slot.
+
Il DIMM si inserisce saldamente nello slot, ma dovrebbe essere inserito facilmente. In caso contrario, riallineare il DIMM con lo slot e reinserirlo.

+

IMPORTANT: Esaminare visivamente il DIMM per verificare che sia allineato in modo uniforme e inserito completamente nello slot.

. Spingere con cautela, ma con decisione, il bordo superiore del DIMM fino a quando le linguette dell'espulsore non scattano in posizione sulle tacche alle estremità del DIMM.
. Chiudere il coperchio del modulo controller.




== Fase 4: Installare il controller

Dopo aver installato i componenti nel modulo controller, è necessario installare nuovamente il modulo controller nel telaio del sistema e avviare il sistema operativo.

Per le coppie ha con due moduli controller nello stesso chassis, la sequenza in cui si installa il modulo controller è particolarmente importante perché tenta di riavviarsi non appena lo si installa completamente nello chassis.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Se non è già stato fatto, riposizionare il coperchio sul modulo controller.
+
image::../media/drw_9500_PCM_open.svg[Drw 9500 PCM aperto]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Pulsante di bloccaggio del coperchio del modulo controller

|===
. Allineare l'estremità del modulo controller con l'apertura dello chassis, quindi spingere delicatamente il modulo controller a metà nel sistema.
+
.Animazione - Installazione del controller
video::f2aa14b4-0d95-4109-b410-ae78004b35c9[panopto]
+
image::../media/drw_9500_remove_PCM.svg[Drw 9500 rimuovere il PCM]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Pulsante di rilascio della maniglia della camma



 a| 
image::../media/legend_icon_02.svg[icona legenda 02]
 a| 
Maniglia CAM

|===
+

NOTE: Non inserire completamente il modulo controller nel telaio fino a quando non viene richiesto.

. Cablare solo le porte di gestione e console, in modo da poter accedere al sistema per eseguire le attività descritte nelle sezioni seguenti.
+

NOTE: I cavi rimanenti verranno collegati al modulo controller più avanti in questa procedura.

. Completare la reinstallazione del modulo controller:
+
.. Se non è già stato fatto, reinstallare il dispositivo di gestione dei cavi.
.. Spingere con decisione il modulo controller nello chassis fino a quando non raggiunge la scheda intermedia e non è completamente inserito.
+
I fermi di bloccaggio si sollevano quando il modulo controller è completamente inserito.

+

IMPORTANT: Non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel telaio per evitare di danneggiare i connettori.

+
Il modulo controller inizia ad avviarsi non appena viene inserito completamente nello chassis. Prepararsi ad interrompere il processo di avvio.

.. Ruotare i fermi di bloccaggio verso l'alto, inclinandoli in modo da liberare i perni di bloccaggio, quindi abbassarli in posizione di blocco.
.. Interrompere il processo di avvio premendo `Ctrl-C` Quando viene visualizzato, premere Ctrl-C per il menu di avvio.
.. Selezionare l'opzione per avviare la modalità di manutenzione dal menu visualizzato.






== Fase 5: Eseguire la diagnostica a livello di sistema

Dopo aver installato un nuovo DIMM, eseguire la diagnostica.

Per avviare la diagnostica a livello di sistema, il sistema deve essere al prompt DEL CARICATORE.

Tutti i comandi delle procedure diagnostiche vengono emessi dal nodo in cui viene sostituito il componente.

. Se il nodo da sottoporre a manutenzione non si trova al prompt DEL CARICATORE, attenersi alla seguente procedura:
+
.. Selezionare l'opzione Maintenance mode (modalità manutenzione) dal menu visualizzato.
.. Una volta avviato il nodo in modalità Maintenance, arrestare il nodo: `halt`
+
Dopo aver eseguito il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

+

IMPORTANT: Durante il processo di avvio, è possibile rispondere in modo sicuro `y` a prompt.

+
*** Se viene visualizzato un messaggio che avvisa che quando si accede alla modalità di manutenzione in una configurazione ha, è necessario assicurarsi che il nodo integro rimanga inattivo.




. Al prompt DEL CARICATORE, accedere ai driver speciali progettati appositamente per la diagnostica a livello di sistema per funzionare correttamente: `boot_diags`
+
Durante il processo di avvio, è possibile rispondere in modo sicuro `y` Fino a visualizzare il prompt della modalità di manutenzione (*>).

. Eseguire la diagnostica sulla memoria di sistema: `sldiag device run -dev mem`
. Verificare che la sostituzione dei DIMM non abbia causato problemi hardware: `sldiag device status -dev mem -long -state failed`
+
La diagnostica a livello di sistema riporta al prompt se non ci sono errori di test o elenca lo stato completo degli errori risultanti dal test del componente.

. Procedere in base al risultato del passaggio precedente:
+
[cols="1,2"]
|===
| Se il test di diagnostica a livello di sistema... | Quindi... 


 a| 
Sono stati completati senza guasti
 a| 
.. Cancellare i registri di stato: `sldiag device clearstatus`
.. Verificare che il registro sia stato cancellato: `sldiag device status`
+
Viene visualizzata la seguente risposta predefinita:

+
SLDIAG: Nessun messaggio di log presente.

.. Uscire dalla modalità di manutenzione: `halt`
+
Il nodo visualizza il prompt DEL CARICATORE.

.. Avviare il nodo dal prompt DEL CARICATORE: `bye`
.. Ripristinare il funzionamento normale del nodo:


|===
+
[cols="1,2"]
|===
| Se il nodo si trova in... | Quindi... 


 a| 
Una coppia ha
 a| 
Eseguire un give back: `storage failover giveback -ofnode replacement_node_name`


NOTE: Se il giveback automatico è stato disattivato, riattivarlo con il comando di modifica del failover dello storage.



 a| 
Ha causato alcuni errori di test
 a| 
Determinare la causa del problema:

.. Uscire dalla modalità di manutenzione: `halt`
+
Dopo aver inviato il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

.. Verificare di aver osservato tutte le considerazioni identificate per l'esecuzione della diagnostica a livello di sistema, che i cavi siano collegati saldamente e che i componenti hardware siano installati correttamente nel sistema di storage.
.. Avviare il modulo controller che si sta eseguendo la manutenzione, interrompendo l'avvio premendo `Ctrl-C` Quando viene richiesto di accedere al menu di avvio:
+
*** Se nello chassis sono presenti due moduli controller, inserire completamente il modulo controller che si sta eseguendo la manutenzione nello chassis.
+
Il modulo controller si avvia quando è completamente inserito.

*** Se si dispone di un modulo controller nello chassis, collegare gli alimentatori e accenderli.


.. Selezionare Boot to maintenance mode (Avvia alla modalità di manutenzione) dal menu.
.. Uscire dalla modalità di manutenzione immettendo il seguente comando: `halt`
+
Dopo aver inviato il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

.. Eseguire nuovamente il test diagnostico a livello di sistema.


|===




== Fase 6: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
