---
permalink: fas2800/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: fas2820, shut, down, impaired, controller, take, over 
summary: Arresta il controller nel tuo sistema storage FAS2820 per evitare la perdita di dati e mantenere la stabilità del sistema durante il processo di ripristino manuale del supporto di avvio. 
---
= Spegni il controller in un sistema FAS2820 durante il processo di ripristino manuale dell'avvio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Arresta il controller nel tuo sistema storage FAS2820 per evitare la perdita di dati e mantenere la stabilità del sistema durante il processo di ripristino manuale del supporto di avvio.

Se il sistema di archiviazione esegue ONTAP 9.17.1 o versione successiva, utilizzarelink:bootmedia-replace-workflow-bmr.html["procedura di ripristino automatico dell'avvio"] .  Se il sistema esegue una versione precedente di ONTAP, è necessario utilizzare la procedura di ripristino manuale all'avvio.

Completare l'arresto del controller danneggiato arrestandolo al prompt LOADER e acquisendo le variabili di ambiente di avvio. Il prompt LOADER è lo stato di arresto sicuro da cui è possibile sostituire il supporto di avvio.

.Fasi
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
`Waiting for giveback...`
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode impaired_node_name`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===
. Dal prompt DEL CARICATORE, immettere: `printenv` per acquisire tutte le variabili ambientali di avvio. Salvare l'output nel file di log.
+

NOTE: Questo comando potrebbe non funzionare se il dispositivo di boot è corrotto o non funzionante.



.Quali sono le prossime novità?
Dopo aver spento il controller, è necessario link:bootmedia-replace.html["sostituire il supporto di avvio"].
