---
permalink: fas2800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas2820, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: Devi verificare lo stato HA dello chassis, ripristinare gli aggregati e restituire la parte guasta a NetApp per completare la sostituzione dello chassis del tuo sistema FAS2820, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Completa la sostituzione dello chassis per un sistema FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica lo stato HA dello chassis, ripristina gli aggregati e restituisci la parte guasta a NetApp per completare la sostituzione dello chassis del tuo sistema FAS2820, come descritto nelle istruzioni RMA fornite con il kit.



[[step-1-verify-and-set-the-ha-state-of-the-chassis]]
== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis in base alla configurazione esistente del sistema: `ha-config modify chassis _ha-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** `ha`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.
. Uscire dalla modalità di manutenzione: `halt`.    Viene visualizzato il prompt DEL CARICATORE.
. Avviare i moduli controller.




[[step-2-bring-up-the-system]]
== Fase 2: Richiamare il sistema

. In caso contrario, ricollegare i cavi di alimentazione alle PSU.
. Accendi gli alimentatori spostando l'interruttore a bilanciere su *ON* e aspetta che i controller si avviino completamente.
. Dopo l'accensione, controllare la parte anteriore e posteriore dello chassis e dei controller per verificare l'eventuale presenza di spie di guasto.
. Connettiti all'indirizzo IP dello SP o del BMC dei nodi tramite SSH. Questo è lo stesso indirizzo utilizzato per arrestare i nodi.
. Eseguire ulteriori controlli dello stato di salute come descritto in https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["How_to_Perform_a_cluster_Health_check_with_a_script_in_ONTAP"^]
. Se è stata attivata una finestra di manutenzione AutoSupport, terminarla utilizzando `system node autosupport invoke -node * -type all -message MAINT=END` comando.


[]
====

NOTE: Come Best practice, devi effettuare le seguenti operazioni:

* Risolvere qualsiasi https://activeiq.netapp.com/["Avvisi e rischi relativi al benessere Active IQ"^] (Active IQ richiederà tempo per elaborare i servizi di assistenza automatica post-accensione - prevedendo un ritardo nei risultati)
* Eseguire https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* Controllare lo stato del sistema utilizzando https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["How_to_Perform_a_cluster_Health_check_with_a_script_in_ONTAP"^]


====


[[step-3-return-the-failed-part-to-netapp]]
== Fase 3: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
