---
permalink: fas2800/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 'Spostare gli alimentatori, i dischi rigidi e i moduli controller dallo chassis guasto allo chassis sostitutivo, quindi sostituire lo chassis guasto dal rack dell"apparecchiatura o dall"armadietto del sistema con lo chassis sostitutivo dello stesso modello dello chassis guasto.' 
---
= Spostare e sostituire l'hardware - FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Spostare gli alimentatori, i dischi rigidi e i moduli controller dallo chassis guasto allo chassis sostitutivo, quindi sostituire lo chassis guasto dal rack dell'apparecchiatura o dall'armadietto del sistema con lo chassis sostitutivo dello stesso modello dello chassis guasto.



== Fase 1: Spostare un alimentatore

Lo spostamento di un alimentatore durante la sostituzione di uno chassis comporta lo spegnimento, lo scollegamento e la rimozione dell'alimentatore dallo chassis difettoso e l'installazione e il collegamento dello stesso sullo chassis sostitutivo.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Spegnere l'alimentatore e scollegare i cavi di alimentazione:
+
.. Spegnere l'interruttore di alimentazione dell'alimentatore.
.. Aprire il fermo del cavo di alimentazione, quindi scollegare il cavo di alimentazione dall'alimentatore.
.. Scollegare il cavo di alimentazione dalla fonte di alimentazione.


. Premere il fermo sulla maniglia della camma dell'alimentatore, quindi aprire la maniglia della camma per rilasciare completamente l'alimentatore dal piano intermedio.
. Utilizzare la maniglia della camma per estrarre l'alimentatore dal sistema.
+

CAUTION: Quando si rimuove un alimentatore, utilizzare sempre due mani per sostenerne il peso.

. Ripetere i passi precedenti per tutti gli alimentatori rimanenti.
. Con entrambe le mani, sostenere e allineare i bordi dell'alimentatore con l'apertura nello chassis del sistema, quindi spingere delicatamente l'alimentatore nello chassis utilizzando la maniglia della camma.
+
Gli alimentatori sono dotati di chiavi e possono essere installati in un solo modo.

+

NOTE: Non esercitare una forza eccessiva quando si inserisce l'alimentatore nel sistema. Il connettore potrebbe danneggiarsi.

. Chiudere la maniglia della camma in modo che il fermo scatti in posizione di blocco e l'alimentatore sia inserito completamente.
. Ricollegare il cavo di alimentazione e fissarlo all'alimentatore utilizzando il meccanismo di blocco del cavo di alimentazione.
+

NOTE: Collegare solo il cavo di alimentazione all'alimentatore. Non collegare il cavo di alimentazione a una fonte di alimentazione.





== Fase 2: Rimuovere il modulo controller

Rimuovere il modulo controller o i moduli dal telaio guasto.

. Allentare il gancio e la fascetta che fissano i cavi al dispositivo di gestione dei cavi, quindi scollegare i cavi di sistema e gli SFP (se necessario) dal modulo controller, tenendo traccia del punto in cui sono stati collegati i cavi.
+
Lasciare i cavi nel dispositivo di gestione dei cavi in modo che quando si reinstalla il dispositivo di gestione dei cavi, i cavi siano organizzati.

. Rimuovere e mettere da parte i dispositivi di gestione dei cavi dai lati sinistro e destro del modulo controller.
. Premere il dispositivo di chiusura sulla maniglia della camma fino al rilascio, aprire completamente la maniglia della camma per rilasciare il modulo controller dalla scheda intermedia, quindi estrarre il modulo controller dallo chassis con due mani.
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[Drw 2850 pcm Remove install IEOPS 694]

. Mettere da parte il modulo controller in un luogo sicuro.
. Ripetere questa procedura per il secondo modulo controller nello chassis.




== Fase 3: Spostare le unità nello chassis sostitutivo

Spostare le unità da ciascuna apertura dell'alloggiamento del disco nello chassis non utilizzato allo stesso alloggiamento dello chassis sostitutivo.

. Rimuovere delicatamente il pannello frontale dal sistema.
. Rimuovere i dischi:
+
.. Premere il pulsante di rilascio sul lato opposto dei LED.
.. Tirare la maniglia della camma in posizione completamente aperta per estrarre l'unità dalla scheda intermedia, quindi estrarre delicatamente l'unità dal telaio.
+
L'unità deve disinnestarsi dallo chassis, in modo che possa scorrere liberamente dallo chassis.

+

NOTE: Quando si rimuove un disco, utilizzare sempre due mani per sostenerne il peso.

+

NOTE: I dischi sono fragili. Maneggiarli il meno possibile per evitare di danneggiarli.



. Allineare l'unità dallo chassis compromesso con la stessa apertura dello chassis sostitutivo.
. Spingere delicatamente l'unità nel telaio fino in fondo.
+
La maniglia della camma si innesta e inizia a ruotare in posizione chiusa.

. Spingere con decisione l'unità fino in fondo nel telaio, quindi bloccare la maniglia della camma spingendola contro il supporto dell'unità.
+
Chiudere lentamente la maniglia della camma in modo che sia allineata correttamente con la parte anteriore del supporto dell'unità. Fa clic quando è sicuro.

. Ripetere la procedura per i dischi rimanenti nel sistema.




== Fase 4: Sostituire uno chassis all'interno del rack dell'apparecchiatura o dell'armadietto del sistema

Rimuovere lo chassis esistente dal rack dell'apparecchiatura o dall'armadietto del sistema e installarlo nel rack dell'apparecchiatura o nell'armadietto del sistema.

. Rimuovere le viti dai punti di montaggio del telaio.
. Con l'aiuto di due o tre persone, far scorrere lo chassis compromesso dalle guide del rack in un cabinet di sistema o dalle staffe _L_ in un rack dell'apparecchiatura, quindi metterlo da parte.
. Se non si è già collegati a terra, mettere a terra l'utente.
. Utilizzando due o tre persone, installare lo chassis sostitutivo nel rack dell'apparecchiatura o nell'armadietto del sistema guidandolo sulle guide del rack in un cabinet del sistema o sulle staffe _L_ in un rack dell'apparecchiatura.
. Far scorrere lo chassis completamente nel rack dell'apparecchiatura o nell'armadietto del sistema.
. Fissare la parte anteriore dello chassis al rack dell'apparecchiatura o all'armadietto del sistema, utilizzando le viti rimosse dallo chassis compromesso.
. Se non è già stato fatto, installare il pannello.




== Fase 5: Installare il controller

Installare il modulo controller e gli altri componenti nel telaio sostitutivo, avviarlo in modalità manutenzione.

Per le coppie ha con due moduli controller nello stesso chassis, la sequenza in cui si installa il modulo controller è particolarmente importante perché tenta di riavviarsi non appena lo si installa completamente nello chassis.

. Allineare l'estremità del modulo controller con l'apertura dello chassis, quindi spingere delicatamente il modulo controller a metà nel sistema.
+

NOTE: Non inserire completamente il modulo controller nel telaio fino a quando non viene richiesto.

. Collegare nuovamente la console al modulo controller, quindi ricollegare la porta di gestione.
. Ripetere i passi precedenti per il secondo controller nello chassis sostitutivo.
. Completare l'installazione del modulo controller:
+
.. Con la maniglia della camma in posizione aperta, spingere con decisione il modulo controller fino a quando non raggiunge la scheda intermedia e non è completamente inserito, quindi chiudere la maniglia della camma in posizione di blocco.
+

NOTE: Non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel telaio per evitare di danneggiare i connettori.

.. Se non è già stato fatto, reinstallare il dispositivo di gestione dei cavi.
.. Collegare i cavi al dispositivo di gestione dei cavi con il gancio e la fascetta.
.. Ripetere i passi precedenti per il secondo modulo controller nel telaio sostitutivo.


. Collegare e accendere gli alimentatori a diverse fonti di alimentazione.
. Avviare ciascun controller in modalità di manutenzione:
+
.. Quando ciascun controller avvia l'avvio, premere `Ctrl-C` per interrompere il processo di avvio quando viene visualizzato il messaggio `Press Ctrl-C for Boot Menu`.
+

NOTE: Se il prompt non viene visualizzato e i moduli controller avviano ONTAP, immettere `halt`, Quindi, al prompt DEL CARICATORE, immettere `boot_ontap`, premere `Ctrl-C` quando richiesto, quindi ripetere questo passaggio.

.. Dal menu di avvio, selezionare l'opzione per la modalità di manutenzione.



