---
permalink: fas2800/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: fas2800, restore and verify the system configuration, verify and set the ha state of the controller module, run system-level diagnostics 
summary: 'Dopo aver sostituito l"hardware e avviato la modalità di manutenzione, verificare la configurazione di sistema di basso livello del controller sostitutivo e riconfigurare le impostazioni di sistema secondo necessità.' 
---
= Ripristinare e verificare la configurazione di sistema - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver sostituito l'hardware e avviato il controller sostitutivo, verificare la configurazione di sistema di basso livello del controller sostitutivo e riconfigurare le impostazioni di sistema secondo necessità.



== Fase 1: Impostare e verificare l'ora di sistema dopo la sostituzione del controller

È necessario controllare l'ora e la data sul modulo controller sostitutivo rispetto al modulo controller integro in una coppia ha o rispetto a un server di riferimento orario affidabile in una configurazione standalone. Se l'ora e la data non corrispondono, è necessario ripristinarli sul modulo controller sostitutivo per evitare possibili interruzioni dei client dovute a differenze di tempo.

.A proposito di questa attività
È importante applicare i comandi descritti nei passaggi sui sistemi corretti:

* Il nodo _replacement_ è il nuovo nodo che ha sostituito il nodo compromesso come parte di questa procedura.
* Il nodo _healthy_ è il partner ha del nodo _replacement_.


.Fasi
. Se il nodo _replacement_ non si trova al prompt DEL CARICATORE, arrestare il sistema al prompt DEL CARICATORE.
. Sul nodo _healthy_, controllare l'ora di sistema: `cluster date show`
+
La data e l'ora si basano sul fuso orario configurato.

. Al prompt DEL CARICATORE, controllare la data e l'ora nel nodo _replacement_: `show date`
+
La data e l'ora sono indicate in GMT.

. Se necessario, impostare la data in GMT sul nodo sostitutivo: `set date _mm/dd/yyyy_`
. Se necessario, impostare l'ora in GMT sul nodo sostitutivo: `set time _hh:mm:ss_`
. Al prompt DEL CARICATORE, confermare la data e l'ora nel nodo _replacement_: `date`
+
La data e l'ora sono indicate in GMT.





== Fase 2: Verificare e impostare lo stato ha del modulo controller

Verificare `HA` stato del modulo controller e, se necessario, aggiornare lo stato in modo che corrisponda alla configurazione del sistema.

. In modalità manutenzione dal nuovo modulo controller, verificare che tutti i componenti siano visualizzati allo stesso modo `HA` stato: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per il controller non corrisponde alla configurazione del sistema, impostare lo stato ha per il modulo controller sostitutivo: `ha-config modify controller _HA-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
** `ha`
** `mcc`
** `mcc-2n`
** `mccip`
+
... Verificare che l'impostazione sia stata modificata: `ha-config show`




. Riavviare il modulo controller.
+

NOTE: Durante il processo di avvio, potrebbero essere visualizzati i seguenti prompt:

+
** Viene visualizzato un messaggio di avviso che indica una mancata corrispondenza dell'ID di sistema e chiede di ignorare l'ID di sistema.
** Un avviso che avvisa che quando si accede alla modalità di manutenzione in una configurazione ha, è necessario assicurarsi che il controller integro rimanga inattivo. Puoi rispondere in tutta sicurezza `y` a questi prompt.



