---
permalink: fas2800/controller-replace-overview.html 
sidebar: sidebar 
keywords: fas2820, prerequisite, replace the controller module 
summary: Prima di sostituire il controller nel tuo sistema FAS2820, devi verificare i prerequisiti per la procedura di sostituzione e selezionare quella corretta per la tua versione di ONTAP. 
---
= Verifica i requisiti prima di sostituire il controller in un sistema FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il controller nel tuo sistema FAS2820, devi verificare i prerequisiti per la procedura di sostituzione e selezionare quella corretta per la tua versione di ONTAP.

[NOTE]
====
NetApp raccomanda vivamente di abilitare la registrazione della console sui dispositivi con cui si sta lavorando e di adottare le seguenti misure durante l'esecuzione di questa procedura:

* Lascia AutoSupport abilitato durante la manutenzione. Questo consente al supporto NetApp di ricevere informazioni diagnostiche in caso di problemi.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI. Questo crea una registrazione completa di tutti i comandi e dell'output di sistema durante l'attività di manutenzione. Per istruzioni su come abilitare la registrazione delle sessioni, vedere  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^].


====
* Tutti gli shelf di dischi devono funzionare correttamente.
* Se il sistema si trova in una coppia ha, il controller integro deve essere in grado di assumere il controllo che viene sostituito (indicato in questa procedura come "`controller alterato`").
* Questa procedura include i passaggi per riassegnare automaticamente o manualmente i dischi al controller _replacement_, a seconda della configurazione del sistema.
+
Eseguire la riassegnazione del disco come indicato nella procedura.

* È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.
* Devi sostituire il modulo controller con un modulo controller dello stesso modello. Non puoi aggiornare il sistema semplicemente sostituendo il modulo controller.
* Non è possibile modificare dischi o shelf di dischi come parte di questa procedura.
* In questa procedura, il dispositivo di boot viene spostato dal controller danneggiato al controller _sostitutivo_ in modo che il controller _sostitutivo_ si avvii con la stessa versione di ONTAP del vecchio modulo controller.
* È importante applicare i comandi descritti di seguito ai sistemi corretti:
+
** Il controller _alterato_ è il controller che viene sostituito.
** Il controller _replacement_ è il nuovo controller che sostituisce il controller compromesso.
** Il controller _healthy_ è il controller sopravvissuto.



