---
permalink: fas2800/maintain-overview.html 
sidebar: sidebar 
keywords: fas2800 maintenance, maintenance, repairing, repairing fas2700, replace fas2800 components, replace fas2800 components 
summary: 'Eseguire la manutenzione dell"hardware FAS2800' 
---
= Manutenzione dell'hardware FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema di archiviazione FAS2800, è possibile eseguire le procedure di manutenzione sui seguenti componenti.



== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



== Modulo di caching

È necessario sostituire il modulo di caching del controller quando il sistema registra un singolo messaggio ASUP (AutoSupport) che indica che il modulo è offline.



== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



== Disco

Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



== Batteria NVMEM

Una batteria è inclusa nel controller e conserva i dati memorizzati nella cache in caso di interruzione dell'alimentazione CA.



== Scheda mezzanino

Una scheda Mezzanine è una scheda di espansione progettata per essere inserita in uno slot specializzato sulla scheda madre.



== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
