---
permalink: fas2800/maintain-overview.html 
sidebar: sidebar 
keywords: fas2800 maintenance, maintenance, repairing, repairing fas2800, replace fas2800 components, replace fas2800 components 
summary: 'Eseguire la manutenzione dell"hardware FAS2820' 
---
= Manutenzione dell'hardware FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantenete l'hardware del vostro sistema di storage FAS2820 per garantire affidabilità a lungo termine e prestazioni ottimali. Eseguite regolarmente attività di manutenzione, come la sostituzione di componenti difettosi, per prevenire tempi di inattività e perdite di dati.

Le procedure di manutenzione presuppongono che il sistema di archiviazione FAS2820 sia già stato distribuito come nodo di archiviazione nell'ambiente ONTAP .



== Componenti del sistema

Per il sistema di archiviazione FAS2820, è possibile eseguire le procedure di manutenzione sui seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Supporto di avvio - ripristino automatico"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio.  Durante il ripristino automatico, il sistema recupera l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione di menu di avvio appropriata per installare l'immagine sul supporto di avvio sostitutivo. Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .



 a| 
link:bootmedia-replace-workflow.html["Supporto di avvio - ripristino manuale"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio. Durante il ripristino manuale, si avvia il sistema di archiviazione da un'unità USB e si ripristina manualmente l'immagine e la configurazione del file system.  Se il sistema di archiviazione esegue ONTAP 9.17.1 e versioni successive, utilizzarelink:bootmedia-replace-workflow-bmr.html["procedura di ripristino automatico dell'avvio"] .



 a| 
link:caching-module-replace.html["Modulo di caching"]
 a| 
È necessario sostituire il modulo di caching del controller quando il sistema registra un singolo messaggio ASUP (AutoSupport) che indica che il modulo è offline.



 a| 
link:chassis-replace-overview.html["Chassis"]
 a| 
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



 a| 
link:controller-replace-overview.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



 a| 
link:drive-replace.html["Disco"]
 a| 
Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



 a| 
link:nvmem-nvram-battery-replace.html["Batteria NVMEM"]
 a| 
Una batteria è inclusa nel controller e conserva i dati memorizzati nella cache in caso di interruzione dell'alimentazione CA.



 a| 
link:pci-cards-and-risers-replace.html["Scheda mezzanino"]
 a| 
Una scheda Mezzanine è una scheda di espansione progettata per essere inserita in uno slot specializzato sulla scheda madre e contiene le schede I/O.



 a| 
link:power-supply-swap-out.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc-battery-replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.

|===