---
permalink: fas2800/nvmem-nvram-battery-replace.html 
sidebar: sidebar 
keywords: fas2800, replace, nvmem, battery, shut, down, impaired, controller, controller, system, aggregates, metrocluster, configuration, reinstall 
summary: Per sostituire una batteria NVMEM nel sistema, è necessario rimuovere il modulo controller dal sistema, aprirlo, sostituire la batteria, chiudere e sostituire il modulo controller. 
---
= Sostituire la batteria NVMEM - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sostituire una batteria NVMEM nel sistema, è necessario rimuovere il modulo controller dal sistema, aprirlo, sostituire la batteria, chiudere e sostituire il modulo controller.

Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.



== Fase 1: Spegnere il controller compromesso

Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso.

Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].

.Fasi
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=_number_of_hours_down_h`
+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Se il controller non funzionante fa parte di una coppia ha, disattivare il giveback automatico dalla console del controller integro: `storage failover modify -node local -auto-giveback false`
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
In attesa di un giveback...
 a| 
Premere Ctrl-C, quindi rispondere `y`.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode _impaired_node_name_`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===




== Fase 2: Rimuovere e aprire il modulo controller

Rimuovere e aprire il modulo controller.

.Fasi
. Se non si è già collegati a terra, mettere a terra l'utente.
. Allentare il gancio e la fascetta che fissano i cavi al dispositivo di gestione dei cavi, quindi scollegare i cavi di sistema e gli SFP (se necessario) dal modulo controller, tenendo traccia del punto in cui sono stati collegati i cavi.
+
Lasciare i cavi nel dispositivo di gestione dei cavi in modo che quando si reinstalla il dispositivo di gestione dei cavi, i cavi siano organizzati.

. Rimuovere e mettere da parte i dispositivi di gestione dei cavi dai lati sinistro e destro del modulo controller.
. Premere il dispositivo di chiusura sulla maniglia della camma fino al rilascio, aprire completamente la maniglia della camma per rilasciare il modulo controller dalla scheda intermedia, quindi estrarre il modulo controller dallo chassis con due mani.
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[Drw 2850 pcm Remove install IEOPS 694]

. Capovolgere il modulo controller e posizionarlo su una superficie piana e stabile.
. Aprire il coperchio premendo i pulsanti blu sui lati del modulo controller per rilasciare il coperchio, quindi ruotare il coperchio verso l'alto e verso l'esterno del modulo controller.
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[Drw 2850 coperchio aperto del modulo controller IEOPS 695]





== Fase 3: Sostituire la batteria NVMEM

Rimuovere la batteria NVMEM guasta dal sistema e sostituirla con una nuova.

.Fasi
. Se non si è già collegati a terra, mettere a terra l'utente.
. Controllare il LED NVMEM:
+
** Se il sistema si trova in una configurazione ha, passare alla fase successiva.
** Se il sistema si trova in una configurazione standalone, spegnere completamente il modulo controller, quindi controllare il LED NVRAM identificato dall'icona NV.
+
image::../media/drw_hw_nvram_icon.svg[icona nvram drw hw]

+

NOTE: Il LED NVRAM lampeggia durante il trasferimento dei contenuti nella memoria flash quando si arresta il sistema. Una volta completata la destage, il LED si spegne.

+
*** In caso di interruzione dell'alimentazione senza un arresto completo, il LED NVMEM lampeggia fino al completamento della destage, quindi il LED si spegne.
*** Se il LED è acceso e l'alimentazione è accesa, i dati non scritti vengono memorizzati su NVMEM.
+
Questo si verifica in genere durante un arresto non controllato dopo l'avvio di ONTAP.





. Individuare la batteria NVMEM nel modulo del controller.
+
.Animazione - sostituire la batteria NV
video::592217fb-4868-4294-a559-af4701725598[panopto]
+
image::../media/drw_2850_replace_nvbattery_IEOPS-715.svg[Drw 2850 sostituire Nvbattery IEOPS 715]

+
[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Linguetta di rilascio della batteria



 a| 
image::../media/legend_icon_02.svg[icona legenda 02]
 a| 
Connettore di alimentazione della batteria

|===
. Rimuovere la batteria guasta dal modulo controller:
+
.. Premere il pulsante blu sul lato del modulo controller.
.. Far scorrere la batteria verso l'alto fino a liberare le staffe di supporto, quindi estrarre la batteria dal modulo controller.
.. Scollegare la batteria dal modulo controller


. Rimuovere la batteria sostitutiva dalla confezione.
Installare la batteria sostitutiva:
+
.. Ricollegare la spina della batteria alla presa del modulo controller.
+
Assicurarsi che la spina sia bloccata nella presa della batteria sulla scheda madre.

.. Allineamento della batteria con le staffe di supporto sulla parete laterale in lamiera.
.. Far scorrere la batteria verso il basso fino a quando il dispositivo di chiusura della batteria non si aggancia e scatta nell'apertura sulla parete laterale.


. Reinstallare il coperchio del modulo controller e bloccarlo in posizione.




== Fase 4: Reinstallare il modulo controller

Dopo aver sostituito i componenti del modulo controller, reinstallarlo nel telaio.

.Fasi
. Se non si è già collegati a terra, mettere a terra l'utente.
. Se non è già stato fatto, riposizionare il coperchio sul modulo controller.
. Capovolgere il modulo controller e allineare l'estremità con l'apertura dello chassis.
. Allineare l'estremità del modulo controller con l'apertura dello chassis, quindi spingere delicatamente il modulo controller a metà nel sistema.
+

NOTE: Non inserire completamente il modulo controller nel telaio fino a quando non viene richiesto.

. Ricable il sistema, come necessario.
+
Se sono stati rimossi i convertitori multimediali (QSFP o SFP), ricordarsi di reinstallarli se si utilizzano cavi in fibra ottica.

. Completare la reinstallazione del modulo controller:
+
.. Con la maniglia della camma in posizione aperta, spingere con decisione il modulo controller fino a quando non raggiunge la scheda intermedia e non è completamente inserito, quindi chiudere la maniglia della camma in posizione di blocco.
+

NOTE: Non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel telaio per evitare di danneggiare i connettori.

+
Il controller inizia ad avviarsi non appena viene inserito nello chassis.

.. Se non è già stato fatto, reinstallare il dispositivo di gestione dei cavi.
.. Collegare i cavi al dispositivo di gestione dei cavi con il gancio e la fascetta.


. Riavviare il modulo controller.
+

NOTE: Durante il processo di avvio, potrebbero essere visualizzati i seguenti prompt:

+
** Viene visualizzato un messaggio di avviso che indica una mancata corrispondenza dell'ID di sistema e chiede di ignorare l'ID di sistema.
** Un avviso che avvisa che quando si accede alla modalità di manutenzione in una configurazione ha, è necessario assicurarsi che il controller integro rimanga inattivo. Puoi rispondere in tutta sicurezza `y` a questi prompt.






== Fase 5: Ripristino del giveback automatico e del supporto automatico

Ripristina giveback automatico e AutoSupport se sono stati disattivati.

. Ripristinare il giveback automatico utilizzando `storage failover modify -node local -auto-giveback true` comando.
. Se è stata attivata una finestra di manutenzione AutoSupport, terminarla utilizzando `system node autosupport invoke -node * -type all -message MAINT=END` comando.




== Fase 6: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
