---
permalink: fas2800/overview.html 
sidebar: sidebar 
keywords: FAS2800 specifications, FAS2800 specs, NetApp FAS2800, FAS2800 hardware 
summary: Specifiche chiave per il gruppo di piattaforme FAS2800 
---
= Specifiche chiave per FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione FAS2820 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche chiave per FAS2820

* Configurazione della piattaforma: coppia HA a chassis singolo FAS2820
* Capacità massima grezza: 3,1680 PB
* Memoria: 128.0000 GB
* Fattore di forma: chassis 2U con 2 controller HA e 12 slot per unità
* Versione ONTAP : ONTAP: 9.16.1P2
* Slot di espansione PCIe: 4
* Versione minima ONTAP : ONTAP 9.13.1RC1 == Massimi di scalabilità
* Tipo: NAS; Coppie HA: 12; Capacità raw: 38,0 PB / 33,8 PiB; Memoria massima: 1536 GB
* Tipo: SAN; Coppie HA: 6; Capacità grezza: 19,0 PB / 16,9 PiB; Memoria massima: 768 GB
* Tipo: coppia HA; capacità grezza: 3,2 PB / 2,8 PiB; memoria massima: 128.0000




== I/O



=== I/O integrato

* Protocollo: Ethernet 25 Gbps; Porte: 4
* Protocollo: SAS 12 Gbps; Porte: 4




=== Totale I/O

* Protocollo: Ethernet 25 Gbps; Porte: 12
* Protocollo: Ethernet 10 Gbps; Porte: 8
* Protocollo: FC 32 Gbps; Porte: 8
* Protocollo: NVMe/FC 32 Gbps; Porte: 8
* Porte: 0
* Protocollo: SAS 12 Gbps; Porte: 4




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 600 Mbps; Porte: 2




== Rete di archiviazione supportata

* CIFS
* FC
* FCoE
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NVMe/TCP
* S3
* S3 con NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1 == Specifiche dell'ambiente di sistema
* Potenza tipica: 1815 BTU/ora
* Potenza nel caso peggiore: 2339 BTU/ora
* Peso: 57,2 libbre 25,9 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 20,0" (25,1" con staffa di gestione dei cavi)
* Temperatura/altitudine/umidità di esercizio: da 10°C a 35°C (da 50°F a 95°F) a = 3048 m = 10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 7,8 Pressione sonora (LpAm) (posizioni degli astanti): 68,4 dB




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo
* Gestione in banda SAS su connessioni SAS per scaffali esterni [//] 2025-10-15 ontap-systems-internal/issues/1357

