---
permalink: fas2800/pci-cards-and-risers-replace.html 
sidebar: sidebar 
keywords: fas2800, fas2800, replace, pcie, mezzanine, card, disconnect, cable, sfp, qsfp, module, fail, mezzanine, shut, down, impair, controller, pcie, switch, aggregate, two-node, metrocluster, complete, replacement, process, replace a pcie or mezzanine card, shut down the impaired controller, remove the controller module, replace a pcie card, replace the mezzanine card, install the controller module, switch back aggregates in a two-node metrocluster configuration, restore the controller module to operation after running diagnostics, complete the replacement process 
summary: Per sostituire una scheda PCIe o mezzanino, scollegare i cavi e i moduli SFP e QSFP dalle schede, sostituire la scheda PCIe o mezzanino guasta e quindi rieseguire le schede. 
---
= Sostituire una scheda mezzanine - FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sostituire la scheda mezzanine scollegando i cavi e i moduli SFP e QSFP dalla scheda, sostituire la scheda mezzanine guasta, quindi riposizionarla.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema
* Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.


.Animazione - sostituire la scheda mezzanino
video::a8ec891d-f6f6-4479-9ca2-af47017254ff[panopto]


== Fase 1: Spegnere il controller compromesso

Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso.

Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].

.Fasi
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=_number_of_hours_down_h`
+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore: `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. Se il controller non funzionante fa parte di una coppia ha, disattivare il giveback automatico dalla console del controller integro: `storage failover modify -node local -auto-giveback false`
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
In attesa di un giveback...
 a| 
Premere Ctrl-C, quindi rispondere `y`.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode _impaired_node_name_`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===




== Fase 2: Rimuovere il modulo controller

Rimuovere il modulo controller dal sistema, quindi rimuovere il coperchio sul modulo controller.

.Fasi
. Se non si è già collegati a terra, mettere a terra l'utente.
. Allentare il gancio e la fascetta che fissano i cavi al dispositivo di gestione dei cavi, quindi scollegare i cavi di sistema e gli SFP (se necessario) dal modulo controller, tenendo traccia del punto in cui sono stati collegati i cavi.
+
Lasciare i cavi nel dispositivo di gestione dei cavi in modo che quando si reinstalla il dispositivo di gestione dei cavi, i cavi siano organizzati.

. Rimuovere e mettere da parte i dispositivi di gestione dei cavi dai lati sinistro e destro del modulo controller.
. Premere il dispositivo di chiusura sulla maniglia della camma fino al rilascio, aprire completamente la maniglia della camma per rilasciare il modulo controller dalla scheda intermedia, quindi estrarre il modulo controller dallo chassis con due mani.
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[Drw 2850 pcm Remove install IEOPS 694]

. Capovolgere il modulo controller e posizionarlo su una superficie piana e stabile.
. Aprire il coperchio premendo i pulsanti blu sui lati del modulo controller per rilasciare il coperchio, quindi ruotare il coperchio verso l'alto e verso l'esterno del modulo controller.
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[Drw 2850 coperchio aperto del modulo controller IEOPS 695]



[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Pulsante di rilascio del coperchio del modulo controller

|===


== Fase 3: Sostituire la scheda mezzanine

Sostituire la scheda mezzanine.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Rimuovere la scheda mezzanine utilizzando la seguente illustrazione o la mappa FRU sul modulo controller:
+
image::../media/drw_2850_replace_HIC_IEOPS-700.svg[Drw 2850 sostituire HIC IEOPS 700]

+
[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[icona legenda 01]
 a| 
Pannello di montaggio



 a| 
image::../media/legend_icon_02.svg[icona legenda 02]
 a| 
Scheda mezzanine PCIe

|===
+
.. Rimuovere il pannello della scheda mezzanine facendolo scorrere verso l'esterno dal modulo controller.
.. Allentare le viti a testa zigrinata sulla scheda mezzanine e sollevare la scheda mezzanine.
+

NOTE: È possibile allentare le viti a testa zigrinata con le dita o con un cacciavite. Se si utilizzano le dita, potrebbe essere necessario ruotare la batteria NV verso l'alto per un migliore acquisto con le dita sulla vite a testa zigrinata accanto ad essa.



. Reinstallare la scheda mezzanine:
+
.. Allineare lo zoccolo della spina della scheda mezzanine sostitutiva con lo zoccolo della scheda madre, quindi inserire delicatamente la scheda nello zoccolo.
.. Serrare le tre viti a testa zigrinata sulla scheda mezzanino.
.. Reinstallare il pannello del mezzanino.


. Reinstallare il coperchio del modulo controller e bloccarlo in posizione.




== Fase 4: Installare il modulo controller

Reinstallare il modulo controller.

.Fasi
. Se non si è già collegati a terra, mettere a terra l'utente.
. Se non è già stato fatto, riposizionare il coperchio sul modulo controller.
. Capovolgere il modulo controller e allineare l'estremità con l'apertura dello chassis.
. Spingere delicatamente il modulo controller a metà nel sistema.allineare l'estremità del modulo controller con l'apertura nel telaio, quindi spingere delicatamente il modulo controller a metà nel sistema.
+

NOTE: Non inserire completamente il modulo controller nel telaio fino a quando non viene richiesto.

. Ricable il sistema, come necessario.
+
Se sono stati rimossi i convertitori multimediali (QSFP o SFP), ricordarsi di reinstallarli se si utilizzano cavi in fibra ottica.

. Completare la reinstallazione del modulo controller:
+
.. Con la maniglia della camma in posizione aperta, spingere con decisione il modulo controller fino a quando non raggiunge la scheda intermedia e non è completamente inserito, quindi chiudere la maniglia della camma in posizione di blocco.
+

NOTE: Non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel telaio per evitare di danneggiare i connettori.

+
Il controller inizia ad avviarsi non appena viene inserito nello chassis.

.. Se non è già stato fatto, reinstallare il dispositivo di gestione dei cavi.
.. Collegare i cavi al dispositivo di gestione dei cavi con il gancio e la fascetta.


. Riportare il controller al funzionamento normale restituendo lo storage: `storage failover giveback -ofnode _impaired_node_name_`
. Ripristinare il giveback automatico utilizzando `storage failover modify -node local -auto-giveback true` comando.
. Se è stata attivata una finestra di manutenzione AutoSupport, terminarla utilizzando `system node autosupport invoke -node * -type all -message MAINT=END` comando.




== Fase 5: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
