---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2820, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: 'La sostituzione a caldo di un alimentatore nel tuo sistema FAS2820 prevede lo spegnimento, la disconnessione e la rimozione dell"alimentatore guasto, e l"installazione, il collegamento e l"accensione dell"alimentatore sostitutivo.' 
---
= Esegui lo swap a caldo di un alimentatore nel tuo sistema FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi sostituire a caldo un alimentatore nel tuo sistema FAS2820 in caso di guasto o degrado, senza interrompere il funzionamento del sistema. Questa procedura prevede lo spegnimento e la rimozione dell'alimentatore guasto, quindi l'installazione e l'accensione di quello sostitutivo.

Se altri componenti del sistema non funzionano correttamente, contatta il supporto tecnico.

* Gli alimentatori sono ridondanti e sostituibili a caldo.
* Questa procedura è stata scritta per la sostituzione di un alimentatore alla volta.
+

NOTE: Sostituisci l'alimentatore entro due minuti dalla sua rimozione dallo chassis. Il sistema continua a funzionare, ma ONTAP invia messaggi alla console relativi all'alimentatore degradato finché l'alimentatore non viene sostituito.

* Gli alimentatori sono a portata automatica.


.Animazione - sostituire l'alimentatore
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.Fasi
. Identificare l'alimentatore che si desidera sostituire, in base ai messaggi di errore della console o tramite i LED degli alimentatori.
. Se non si è già collegati a terra, mettere a terra l'utente.
. Spegnere l'alimentatore e scollegare i cavi di alimentazione:
+
.. Spegnere l'interruttore di alimentazione dell'alimentatore.
.. Aprire il fermo del cavo di alimentazione, quindi scollegare il cavo di alimentazione dall'alimentatore.
.. Scollegare il cavo di alimentazione dalla fonte di alimentazione.


. Premere il fermo sulla maniglia della camma dell'alimentatore, quindi aprire la maniglia della camma per rilasciare completamente l'alimentatore dal piano intermedio.
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[Sostituire l'alimentatore]

. Utilizzare la maniglia della camma per estrarre l'alimentatore dal sistema.
+

CAUTION: Quando si rimuove un alimentatore, utilizzare sempre due mani per sostenerne il peso.

. Assicurarsi che l'interruttore on/off del nuovo alimentatore sia in posizione off.
. Sostieni e allinea i bordi dell'alimentatore con l'apertura nello chassis usando entrambe le mani, quindi spingi delicatamente l'alimentatore nello chassis utilizzando la maniglia a camma.
+
Gli alimentatori sono dotati di chiavi e possono essere installati in un solo modo.

+

NOTE: Non esercitare una forza eccessiva quando si inserisce l'alimentatore nel sistema. Il connettore potrebbe danneggiarsi.

. Chiudere la maniglia della camma in modo che il fermo scatti in posizione di blocco e l'alimentatore sia inserito completamente.
. Ricollegare il cablaggio dell'alimentatore:
+
.. Ricollegare il cavo di alimentazione all'alimentatore e alla fonte di alimentazione.
.. Fissare il cavo di alimentazione all'alimentatore utilizzando il fermo del cavo di alimentazione.


+
Dopo che l'alimentazione è stata ripristinata all'alimentatore, il LED di stato dovrebbe essere verde.

. Accendere il nuovo alimentatore, quindi verificare il funzionamento dei LED di attività dell'alimentatore.
+
I LED dell'alimentatore sono accesi quando l'alimentatore è in linea.

. Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"^] pagina per ulteriori informazioni.

