---
permalink: asa-c-400/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: asa c400, asa, c400, boot, media, store, primary, secondary, set, system, boot, image, file, replace, replace the boot media 
summary: 'Il supporto di avvio memorizza un set primario e secondario di file di sistema (immagine di avvio) che il sistema utilizza al momento dell"avvio.' 
---
= Panoramica sulla sostituzione dei supporti di avvio - ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il supporto di avvio memorizza un set primario e secondario di file di sistema (immagine di avvio) che il sistema utilizza al momento dell'avvio. A seconda della configurazione di rete, è possibile eseguire una sostituzione senza interruzioni o senza interruzioni.

È necessario disporre di un'unità flash USB, formattata in FAT32, con la quantità di storage appropriata per contenere `image_xxx.tgz` file.

È inoltre necessario copiare il `image_xxx.tgz` Sul disco flash USB per utilizzarlo successivamente in questa procedura.

* I metodi senza interruzioni e senza interruzioni per la sostituzione di un supporto di avvio richiedono entrambi il ripristino di `var` file system:
+
** Per la sostituzione senza interruzioni, la coppia ha deve essere connessa a una rete per ripristinare `var` file system.
** Per la sostituzione delle interruzioni, non è necessaria una connessione di rete per ripristinare `var` file system, ma il processo richiede due riavvii.


* È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.
* È importante applicare i comandi di questi passaggi al nodo corretto:
+
** Il nodo _alterato_ è il nodo su cui si esegue la manutenzione.
** Il _nodo sano_ è il partner ha del nodo compromesso.



