---
permalink: asa-c-400/maintain-overview.html 
sidebar: sidebar 
keywords: asa C400 maintenance, maintenance, repairing C400, repairing asa C400, replace asa C400 components, replace asa C400 components 
summary: 'Manutenzione dell"hardware ASA C400' 
---
= Gestire l'hardware ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema di archiviazione ASA C400, è possibile eseguire le procedure di manutenzione sui seguenti componenti.



== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



== Ventola

La ventola raffredda il controller.



== Batteria NVDIMM

La batteria NVDIMM mantiene l'alimentazione del modulo NVDIMM.



== NVDIMM

 The NVDIMM (non-volatile dual in-line memory module) manages the data transfer from the volatile memory to the non-volatile storage, and maintains data integrity in the event of a power loss or system shutdown.


== Scheda PCIe o Mezzanine

Una scheda PCIe (Peripheral Component Interconnect Express) è una scheda di espansione che si inserisce nello slot PCIe della scheda madre.

Una scheda Mezzanine è una scheda di espansione progettata per essere inserita in uno slot specializzato sulla scheda madre.



== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
