---
permalink: c60-key-specifications.html 
sidebar: sidebar 
summary: Specifiche chiave per AFF C60 
---
= Specifiche chiave per AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione AFF C60 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche AFF C60 in sintesi

* Configurazione della piattaforma: coppia HA a telaio singolo AFF C60
* Capacità massima grezza: 7,3680 PB
* Memoria: 128.0000 GB
* Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità
* Versione ONTAP : ONTAP: 9.16.1P2
* Slot di espansione PCIe: 8
* Versione minima ONTAP : ONTAP 9.16.1RC1 == Massimi di scalabilità
* Tipo: NAS; Coppie HA: 4; Capacità raw: 29,5 PB / 26,2 PiB; Memoria massima: 512 GB
* Tipo: SAN; Coppie HA: 4; Capacità grezza: 29,5 PB / 26,2 PiB; Memoria massima: 512 GB
* Tipo: coppia HA; capacità grezza: 7,4 PB / 6,5 PiB; memoria massima: 128.0000




== I/O



=== I/O integrato

Nessun dato I/O integrato.



=== Totale I/O

* Protocollo: Ethernet 100 Gbps; Porte: 16
* Protocollo: Ethernet 25 Gbps; Porte: 24
* Protocollo: Ethernet 10 Gbps; Porte: 24
* Protocollo: FC 64 Gbps; Porte: 24
* Protocollo: NVMe/FC 64 Gbps; Porte: 24
* Porte: 0




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 600 Mbps; Porte: 2




== Rete di archiviazione supportata

* CIFS
* FC
* iSCSI
* NFS v3
* NFS v4.0
* NFS v4.1
* NFS v4.2
* NVMe/FC
* NVMe/TCP
* S3
* S3 con NAS
* SMB 2.0
* SMB 2.1
* SMB 2.x
* SMB 3.0
* SMB 3.1
* SMB 3.1.1 == Specifiche dell'ambiente di sistema
* Potenza tipica: 2892 BTU/ora
* Potenza nel caso peggiore: 4445 BTU/ora
* Peso: 60,7 libbre 27,5 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità:
* Temperatura/altitudine/umidità di esercizio: da 10°C a 35°C (da 50°F a 95°F) a = 3048 m = 10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 8,0 Pressione sonora (LpAm) (posizioni degli astanti): 70,5 dB




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo

