---
permalink: c30-60/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff c30, aff c60, verify and set HA state, complete the replacement process 
summary: Verificare lo stato ha del telaio, quindi restituire il componente guasto a NetApp per completare la fase finale della procedura di sostituzione del telaio AFF C30 e AFF C60. 
---
= Sostituzione completa del telaio - AFF C30 e AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare lo stato ha del telaio, quindi restituire il componente guasto a NetApp per completare la fase finale della procedura di sostituzione del telaio AFF C30 e AFF C60.



== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornare lo stato in modo che corrisponda alla configurazione del sistema di storage.

. In modalità di manutenzione, da uno dei controller, viene visualizzato lo stato ha del controller locale e dello chassis:
+
`ha-config show`

+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema di archiviazione:
+
.. Impostare lo stato ha per lo chassis:
+
`ha-config modify chassis _HA-state_`

+
Il valore per ha-state deve essere _ha_.

.. Verificare che l'impostazione sia stata modificata:
+
`ha-config show`



. Se non l'hai ancora fatto, puoi recuperare il resto del tuo sistema storage.




== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
