---
permalink: c30-60/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff c30, aff c60, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Verificare che la configurazione ha del controller sia attiva e funzioni correttamente nel sistema di storage AFF C30 o AFF C60 e verificare che gli adattatori del sistema elencino tutti i percorsi dei dischi. 
---
= Ripristinare e verificare la configurazione di sistema - AFF C30 e AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verificare che la configurazione ha del controller sia attiva e funzioni correttamente nel sistema di storage AFF C30 o AFF C60 e verificare che gli adattatori del sistema elencino tutti i percorsi dei dischi.



== Fase 1: Verificare le impostazioni di configurazione ha

È necessario verificare `HA` lo stato del controller e, se necessario, aggiornare lo stato in modo che corrisponda alla configurazione del sistema di archiviazione.

. Avvio in modalità di manutenzione:
+
`boot_ontap maint`

+
.. Immettere `y` quando viene visualizzato _continuare con boot?_.
+
Se viene visualizzato il messaggio di avviso _System ID mismatch_, immettere `y`.



. Immettere `sysconfig -v` e acquisire il contenuto del display.
+

NOTE: Se viene visualizzato _PERSONALITY MISMATCH_, contattare l'assistenza clienti.

. Dall' `sysconfig -v`uscita, confrontare le informazioni della scheda adattatore con le schede e le posizioni nella centralina sostitutiva.
. Verificare che tutti i componenti visualizzino lo stesso `HA` stato:
+
`ha-config show`

+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato del controller non corrisponde alla configurazione del sistema di archiviazione, impostare lo `HA` stato per il controller:
+
`ha-config modify controller ha-state`

+
Il valore dello stato ha può essere uno dei seguenti:

+
** `ha`
** `non-ha` (non supportato)


. Verificare che l'impostazione sia stata modificata:
+
`ha-config show`





== Passo 2: Verifica dell'elenco dei dischi

. Verificare che la scheda di rete elenchi i percorsi per tutti i dischi:
+
`storage show disk -p`

+
In caso di problemi, controllare il cablaggio e riposizionare i cavi.

. Uscire dalla modalità di manutenzione:
+
`halt`



.Quali sono le prossime novità?
Dopo aver ripristinato e verificato la configurazione di sistema per il sistema AFF C30 o AFF C60, è necessario link:controller-replace-recable-reassign-disks.html["restituire il controller"].
