---
sidebar: sidebar 
permalink: c30-60/install-requirements.html 
keywords: aff c30, aff c60, install, setup, cautions 
summary: 'Esaminare l"attrezzatura necessaria e le precauzioni di sollevamento per la piattaforma e i ripiani.' 
---
= Requisiti di installazione - AFF C30 e AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Analizza i requisiti del tuo sistema storage AFF C30 o AFF C60.



== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Graffetta o penna a sfera con punta stretta per l'impostazione di NS224 ID scaffali
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi e gli shelf di storage sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Peso del sistema di storage

Prendere le precauzioni necessarie durante lo spostamento o il sollevamento del sistema di stoccaggio.

Il sistema di stoccaggio può pesare fino a 27,9 kg (61,5 lb). Per sollevare l'impianto di stoccaggio, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20,A30,A50 and C30 and C60 weight caution icon]



=== Peso del ripiano

Prendere le precauzioni necessarie quando si sposta o si solleva il ripiano.

Uno shelf NS224 con NSM100B moduli può pesare fino a 25,8 kg (56,8 lb). Per sollevare il ripiano, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NS224 con NSM100b attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti di installazione e le considerazioni relative al sistema di archiviazione, è possibile link:install-prepare.html["prima dell'installazione"].
