---
permalink: c30-60/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module 
summary: 'I sistemi di storage AFF C30 e AFF C60 offrono flessibilità nell"espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L"aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O sono essenziali per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.' 
---
= Scopri come aggiungere e sostituire i moduli I/O in un sistema AFF C30 o AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi di storage AFF C30 e AFF C60 offrono flessibilità nell'espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L'aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O sono essenziali per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.

Puoi sostituire un modulo I/O guasto nel tuo sistema storage con un modulo I/O dello stesso tipo o di tipo diverso. Puoi sostituire a caldo un modulo I/O di cluster e HA quando il tuo sistema storage soddisfa requisiti specifici. Puoi anche aggiungere un modulo I/O a un sistema storage con slot disponibili.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di ulteriori moduli di i/o può migliorare la ridondanza, contribuendo a garantire che il sistema di storage rimanga operativo anche in caso di guasto di un modulo di i/O.

* link:io-module-hotswap.html["Eseguire lo swap a caldo di un modulo I/O"]
+
La sostituzione a caldo di determinati moduli I/O con moduli equivalenti può ripristinare il sistema storage al suo stato operativo ottimale. La sostituzione a caldo viene eseguita senza la necessità di un takeover.

+
Per utilizzare questa procedura, il sistema di archiviazione deve eseguire ONTAP 9.17.1 o versione successiva e soddisfare requisiti di sistema specifici.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema di storage allo stato operativo ottimale.


