---
permalink: c30-60/overview.html 
sidebar: sidebar 
keywords: AFF C30 C60 specifications, AFF C30 C60 specs, AFF C30 C60 capacity, AFF C30 C60 memory, AFF C30 C60 I/O, AFF C30 C60 compliance 
summary: Specifiche chiave per il gruppo di piattaforme C30-60 
---
= Specifiche chiave per il gruppo di piattaforme C30-60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per il gruppo di piattaforme C30-60.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche.  Questa pagina riflette una singola coppia ad alta disponibilità.



== AFF C60



=== Specifiche chiave per AFF C60

Configurazione della piattaforma: coppia HA a telaio singolo AFF C60

Capacità massima grezza: 7,3680 PB

Memoria: 128.0000 GB

Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 8

Versione minima ONTAP : ONTAP 9.16.1RC1



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS | 4 | 29,5 PB / 26,2 PiB | 512 GB 


| SAN | 4 | 29,5 PB / 26,2 PiB | 512 GB 


| Coppia HA |  | 7,4 PB / 6,5 PiB | 128,0000 
|===


=== Io



==== IO di bordo

Nessun dato IO a bordo.



==== IO totale

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 16 


| Ethernet 25 Gbps | 24 


| Ethernet 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Rete di archiviazione supportata

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 2892 BTU/ora
* Potenza nel caso peggiore: 4445 BTU/ora
* Peso: 60,7 libbre 27,5 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità:
* Temperatura/altitudine/umidità di funzionamento: da 10°C a 35°C (da 50°F a 95°F) fino a 3048 m (10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: potenza sonora dichiarata (LwAd): 8,0; pressione sonora (LpAm) (posizioni degli astanti): 70,5 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo;



== AFF C30



=== Specifiche chiave per AFF C30

Configurazione della piattaforma: coppia HA a telaio singolo AFF C30

Capacità massima grezza: 2,2104 PB

Memoria: 128.0000 GB

Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 8

Versione minima ONTAP : ONTAP 9.16.1RC1



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS | 4 | 8,8 PB / 7,9 PiB | 512 GB 


| SAN | 4 | 8,8 PB / 7,9 PiB | 512 GB 


| Coppia HA |  | 2,2 PB / 2,0 PiB | 128,0000 
|===


=== Io



==== IO di bordo

Nessun dato IO a bordo.



==== IO totale

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 16 


| Ethernet 25 Gbps | 24 


| Ethernet 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2 
|===


=== Rete di archiviazione supportata

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 2892 BTU/ora
* Potenza nel caso peggiore: 4445 BTU/ora
* Peso: 60,7 libbre 27,5 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità:
* Temperatura/altitudine/umidità di funzionamento: da 10°C a 35°C (da 50°F a 95°F) fino a 3048 m (10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: potenza sonora dichiarata (LwAd): 8,0; pressione sonora (LpAm) (posizioni degli astanti): 70,5 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo;
