---
permalink: a20-30-50/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: 'Prima di sostituire il supporto di avvio nel sistema di archiviazione AFF A20, AFF A30 o AFF A50, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ciò include l"accertarsi di disporre di un"unità flash USB con la quantità di spazio di archiviazione adeguata e di verificare di disporre del dispositivo di avvio sostitutivo corretto.' 
---
= Requisiti per il ripristino manuale dei supporti di avvio: AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema di archiviazione AFF A20, AFF A30 o AFF A50, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ciò include l'accertarsi di disporre di un'unità flash USB con la quantità di spazio di archiviazione adeguata e di verificare di disporre del dispositivo di avvio sostitutivo corretto.

.Chiavetta USB
* Assicurati di avere una chiavetta USB formattata in FAT32.
* La chiavetta USB deve avere una capacità di archiviazione sufficiente per contenere il  `image_xxx.tgz` file.


.Preparazione del file
Copia il  `image_xxx.tgz` file sull'unità flash USB. Questo file verrà utilizzato quando si trasferisce l'immagine ONTAP tramite l'unità flash USB.

.Sostituzione dei componenti
Sostituire il componente guasto con il componente sostitutivo fornito da NetApp.

.Identificazione del controllore
Quando si sostituisce il supporto di avvio danneggiato, è fondamentale applicare i comandi al controller corretto:

* Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
* Il _controllore sano_ è il partner HA del controllore compromesso.


.Quali sono le prossime novità?
Dopo aver esaminato i requisiti per sostituire il supporto di avvio, è necessario link:bootmedia-encryption-preshutdown-checks.html["controllare il supporto e lo stato della chiave di crittografia sul supporto di avvio"].
