---
permalink: a20-30-50/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: Informazioni sui requisiti per la sostituzione dei supporti di avvio. 
---
= Requisiti per la sostituzione dei supporti di avvio - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio, verificare i seguenti requisiti e considerazioni.



== Requisiti

* È necessario disporre di un'unità flash USB, formattata in FAT32, con la quantità di storage appropriata per contenere `image_xxx.tgz`.
* È necessario copiare il `image_xxx.tgz` file nell'unità flash USB per utilizzarlo successivamente in questa procedura.
* È necessario sostituire il componente guasto con un componente FRU sostitutivo della stessa capacità ricevuta dal provider.




== Considerazioni

* È importante applicare i comandi descritti di seguito al controller corretto:
+
** Il controller _alterato_ è il controller su cui si esegue la manutenzione.
** Il controller _healthy_ è il partner ha del controller compromesso.


* Se necessario, è possibile attivare i LED di posizione del telaio della piattaforma (blu) per facilitare l'individuazione fisica della piattaforma interessata. Accedere a BMC utilizzando SSH e immettere il `system location-led _on_` comando.
+
Un telaio della piattaforma ha tre LED di posizione: Uno sul pannello del display dell'operatore e uno su ogni controller. I LED di posizione rimangono accesi per 30 minuti.

+
È possibile disattivarle immettendo il `system location-led _off_` comando. Se non si è certi che i LED siano accesi o spenti, è possibile controllarne lo stato digitando il `system location-led show` comando.


