---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A90, AFF A70, replace io module 
summary: 'I sistemi AFF A20, AFF A30 e AFF A50 offrono flessibilità nell"espansione o nella sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L"aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.' 
---
= Panoramica su aggiunta e sostituzione di un modulo i/o - AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi AFF A20, AFF A30 e AFF A50 offrono flessibilità nell'espansione o nella sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L'aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.

È possibile sostituire un modulo i/o guasto nel sistema storage con uno stesso tipo di modulo i/o o o con un altro tipo di modulo i/O. È inoltre possibile aggiungere un modulo i/o a un sistema di archiviazione con gli slot disponibili.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di ulteriori moduli di i/o può migliorare la ridondanza, contribuendo a garantire che il sistema di storage rimanga operativo anche in caso di guasto di un modulo di i/O.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema di storage allo stato operativo ottimale.


