---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: 'I sistemi di storage AFF A20, AFF A30 e AFF A50 offrono flessibilità nell"espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L"aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O è essenziale per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.' 
---
= Panoramica della manutenzione dei moduli I/O: AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi di storage AFF A20, AFF A30 e AFF A50 offrono flessibilità nell'espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L'aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O è essenziale per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
È possibile aggiungere moduli I/O per migliorare la ridondanza, contribuendo a garantire che il sistema storage rimanga operativo anche in caso di guasto di un modulo I/O. È possibile aggiungere moduli I/O quando ci sono slot disponibili o quando tutti gli slot sono completamente occupati.

* link:io-module-hotswap.html["Eseguire lo swap a caldo di un modulo I/O"]
+
È possibile eseguire lo swap a caldo di determinati moduli I/O con un modulo I/O equivalente per ripristinare il sistema storage al suo stato operativo ottimale. Lo swap a caldo viene eseguito senza dover eseguire un takeover manuale.

+
Per utilizzare questa procedura, il sistema storage deve eseguire ONTAP 9.17.1 o versioni successive e soddisfare i requisiti specifici per la versione di ONTAP in esecuzione sul sistema.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
È possibile sostituire un modulo I/O guasto per ripristinare il sistema storage allo stato operativo ottimale. Questa procedura richiede un takeover manuale del controller con il modulo I/O guasto.


