---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: 'I sistemi di storage AFF A20, AFF A30 e AFF A50 offrono flessibilità nell"espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L"aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O è essenziale per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.' 
---
= Panoramica della manutenzione dei moduli I/O: AFF A20, AFF A30 e AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi di storage AFF A20, AFF A30 e AFF A50 offrono flessibilità nell'espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L'aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O è essenziale per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.

È possibile sostituire un modulo I/O guasto nel sistema di storage con un modulo I/O dello stesso tipo o con un modulo I/O diverso. È possibile sostituire a caldo un cluster e un modulo I/O HA quando il sistema di storage soddisfa requisiti specifici. È inoltre possibile aggiungere un modulo I/O a un sistema di storage con slot disponibili.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di ulteriori moduli di i/o può migliorare la ridondanza, contribuendo a garantire che il sistema di storage rimanga operativo anche in caso di guasto di un modulo di i/O.

* link:io-module-hotswap-ha-slot4.html["Sostituzione a caldo di un cluster e di un modulo I/O HA"]
+
La sostituzione a caldo di un cluster guasto e di un modulo I/O HA può ripristinare il sistema di storage al suo stato operativo ottimale. La sostituzione a caldo viene eseguita senza dover intervenire manualmente sul controller danneggiato.

+
Per utilizzare questa procedura, il sistema di archiviazione deve eseguire ONTAP 9.17.1 o versione successiva e soddisfare requisiti specifici del sistema di archiviazione.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema di storage allo stato operativo ottimale.


