---
permalink: c250/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: aff c250, post boot media replacement steps for okm, nse, and nve 
summary: 'Una volta controllate le variabili di ambiente, è necessario completare i passaggi specifici per i sistemi che hanno attivato Onboard Key Manager (OKM), NetApp Storage Encryption (NSE) o NetApp Volume Encryption (NVE).' 
---
= Ripristinare la crittografia - AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ripristinare la crittografia sul supporto di avvio sostitutivo.

È necessario completare i passaggi specifici per i sistemi che hanno attivato Gestione chiavi integrato (OKM), crittografia storage NetApp (NSE) o crittografia del volume NetApp (NVE) utilizzando le impostazioni acquisite all'inizio della procedura di sostituzione dei supporti di avvio.

A seconda di quale gestore di chiavi è configurato sul sistema, selezionare una delle seguenti opzioni per ripristinarlo dal menu di avvio.

* link:["Opzione 1: Ripristinare la configurazione di Onboard Key Manager"]
* link:["Opzione 2: Ripristinare la configurazione di External Key Manager"]




== Opzione 1: Ripristinare la configurazione di Onboard Key Manager

Ripristinare la configurazione di Onboard Key Manager (OKM) dal menu di avvio di ONTAP.

.Prima di iniziare
* Durante il ripristino della configurazione OKM, assicurarsi di disporre delle seguenti informazioni:
+
** Passphrase a livello di cluster immessa https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html["consentendo la gestione delle chiavi integrata"].
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/backup-key-management-information-manual-task.html["Informazioni di backup per il Key Manager integrato"].


* Eseguire la https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_verify_onboard_key_management_backup_and_cluster-wide_passphrase["Come verificare il backup della gestione delle chiavi integrata e la passphrase a livello del cluster"] procedura prima di procedere.


.Fasi
. Collegare il cavo della console al controller di destinazione.
. Dal menu di avvio di ONTAP, selezionare l'opzione appropriata dal menu di avvio.
+
[cols="1a,2a"]
|===
| Versione di ONTAP | Selezionare questa opzione 


 a| 
ONTAP 9.8 o versione successiva
 a| 
Selezionare l'opzione 10.

.Mostra un esempio di menu di avvio
[%collapsible]
====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 10

....
====


 a| 
ONTAP 9.7 e versioni precedenti
 a| 
Selezionare l'opzione nascosta `recover_onboard_keymanager`

.Mostra un esempio di menu di avvio
[%collapsible]
====
....

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
Selection (1-19)? recover_onboard_keymanager

....
====
|===
. Confermare che si desidera continuare il processo di ripristino.
+
.Mostra prompt di esempio
[%collapsible]
====
`This option must be used only in disaster recovery procedures. Are you sure? (y or n):`

====
. Inserire due volte la passphrase a livello di cluster.
+
Quando si inserisce la passphrase, la console non visualizza alcun input.

+
.Mostra prompt di esempio
[%collapsible]
====
`Enter the passphrase for onboard key management:`

`Enter the passphrase again to confirm:`

====
. Immettere le informazioni di backup.
+
.. Incollare l'intero contenuto dalla riga DI BACKUP BEGIN attraverso la riga di BACKUP FINALE.
+
.Mostra prompt di esempio
[%collapsible]
====
....
Enter the backup data:

--------------------------BEGIN BACKUP--------------------------
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
3456789012345678901234567890123456789012345678901234567890123456
4567890123456789012345678901234567890123456789012345678901234567
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
0123456789012345678901234567890123456789012345678901234567890123
1234567890123456789012345678901234567890123456789012345678901234
2345678901234567890123456789012345678901234567890123456789012345
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

---------------------------END BACKUP---------------------------

....
====
.. Premere due volte il tasto invio alla fine dell'immissione.
+
Il processo di ripristino è stato completato.

+
.Mostra prompt di esempio
[%collapsible]
====
....

Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.

***********************************************************************************
* Select option "(1) Normal Boot." to complete recovery process.
*
* Run the "security key-manager onboard sync" command to synchronize the key database after the node reboots.
***********************************************************************************

....
====


+

WARNING: Non procedere se l'output visualizzato è diverso da `Successfully recovered keymanager secrets`. Eseguire la risoluzione dei problemi per correggere l'errore.

. Selezionare l'opzione 1 dal menu di avvio per continuare l'avvio in ONTAP.
+
.Mostra prompt di esempio
[%collapsible]
====
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
====
. Verificare che la console del controller visualizzi il seguente messaggio.
+
`Waiting for giveback...(Press Ctrl-C to abort wait)`

. Dal nodo partner, eseguire un giveback per il controller partner immettendo il seguente comando.
+
`storage failover giveback -fromnode local -only-cfo-aggregates true`.

. Dopo l'avvio con solo l'aggregato CFO, eseguire il comando seguente.
+
`security key-manager onboard sync`

. Immettere la passphrase a livello di cluster per Onboard Key Manager.
+
.Mostra prompt di esempio
[%collapsible]
====
....

Enter the cluster-wide passphrase for the Onboard Key Manager:

All offline encrypted volumes will be brought online and the corresponding volume encryption keys (VEKs) will be restored automatically within 10 minutes. If any offline encrypted volumes are not brought online automatically, they can be brought online manually using the "volume online -vserver <vserver> -volume <volume_name>" command.

....
====
+

NOTE: Se la sincronizzazione ha esito positivo, il prompt del cluster viene restituito senza messaggi aggiuntivi. Se la sincronizzazione non riesce, viene visualizzato un messaggio di errore prima di tornare al prompt del cluster. Non continuare fino a quando l'errore non viene corretto e la sincronizzazione non viene eseguita correttamente.

. Assicurarsi che tutte le chiavi siano sincronizzate immettendo il seguente comando.
+
`security key-manager key query -restored false`.

+
`There are no entries matching your query.`

+

NOTE: Nessun risultato dovrebbe comparire quando si filtra per false nel parametro ripristinato.

. Eseguire il giveback del nodo dal partner immettendo il seguente comando.
+
`storage failover giveback -fromnode local`

. Ripristinare il giveback automatico, se è stato disattivato, immettendo il seguente comando.
+
`storage failover modify -node local -auto-giveback true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi immettendo il seguente comando.
+
`system node autosupport invoke -node * -type all -message MAINT=END`





== Opzione 2: Ripristinare la configurazione di External Key Manager

Ripristinare la configurazione del gestore chiavi esterno dal menu di avvio di ONTAP.

.Prima di iniziare
Per ripristinare la configurazione di EKM (External Key Manager) sono necessarie le seguenti informazioni.

* Una copia del file /cfcard/kmip/servers.cfg da un altro nodo del cluster o le seguenti informazioni:
+
** L'indirizzo del server KMIP.
** Porta KMIP.


* Una copia del `/cfcard/kmip/certs/client.crt` file da un altro nodo cluster o dal certificato client.
* Una copia del `/cfcard/kmip/certs/client.key` file da un altro nodo cluster o dalla chiave client.
* Una copia del `/cfcard/kmip/certs/CA.pem` file da un altro nodo cluster o dalle CA del server KMIP.


.Fasi
. Collegare il cavo della console al controller di destinazione.
. Selezionare l'opzione 11 dal menu di avvio di ONTAP.
+
.Mostra un esempio di menu di avvio
[%collapsible]
====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
====
. Quando richiesto, confermare di aver raccolto le informazioni richieste.
+
.Mostra prompt di esempio
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
====
. Quando richiesto, immettere le informazioni relative al client e al server.
+
.Mostra prompt
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
====
+
.Mostra esempio
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
====
+
Dopo aver immesso le informazioni sul client e sul server, il processo di ripristino viene completato.

+
.Mostra esempio
[%collapsible]
====
....
System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.
....
====
. Selezionare l'opzione 1 dal menu di avvio per continuare l'avvio in ONTAP.
+
.Mostra prompt di esempio
[%collapsible]
====
....

***************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***************************************************************************

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....
====
. Ripristinare lo sconto automatico se è stato disattivato.
+
`storage failover modify -node local -auto-giveback true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi immettendo il seguente comando.
+
`system node autosupport invoke -node * -type all -message MAINT=END`


