---
permalink: c250/install-setup.html 
sidebar: sidebar 
keywords: aff c250, install, setup, initial configuration 
summary: Scegli tra istruzioni rapide, istruzioni dettagliate o video per installare e configurare un sistema storage AFF C250. 
---
= Flusso di lavoro per l'installazione e la configurazione di AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scegli tra procedure rapide, procedure dettagliate o istruzioni video per installare e configurare un sistema storage AFF C250, a seconda del formato preferito e del tuo livello di esperienza.

* link:../c250/install-quick-guide.html["Passaggi rapidi"]
+
Un PDF stampabile con istruzioni dettagliate con collegamenti in tempo reale a contenuti aggiuntivi.

* link:../c250/install-videos.html["Video fasi"]
+
Video istruzioni dettagliate.

* link:../c250/install-detailed-guide.html["Passaggi dettagliati"]
+
Istruzioni passo-passo online con collegamenti in tempo reale a contenuti aggiuntivi.



Se il sistema si trova in una configurazione MetroCluster IP, consultare https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installare la configurazione IP di MetroCluster"^] istruzioni.
