---
permalink: asa-r2-a1k/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, overview, the boot media 
summary: 'Il ripristino del supporto di avvio utilizza l"immagine di avvio dal nodo partner ed esegue automaticamente l"opzione appropriata del menu di avvio per installare l"immagine di avvio sul supporto di avvio sostitutivo.' 
---
= Panoramica del ripristino dei supporti di avvio - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ripristino del supporto di avvio per il sistema di storage ASA A1K utilizza l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione appropriata del menu di avvio per installare l'immagine di avvio sul supporto di avvio sostitutivo.

Quando vengono visualizzati messaggi di errore di avvio, è necessario sostituire il supporto di avvio e ripristinare l'immagine ONTAP dal nodo partner.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....