---
permalink: asa-r2-a1k/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa r2 a1k, prerequisite, replace the controller module 
summary: 'Prima di sostituire il controller nel sistema ASA A1K, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ad esempio disporre del controller sostitutivo corretto, di un backup della configurazione del sistema e dell"accesso agli strumenti e al firmware necessari.' 
---
= Requisiti per la sostituzione della centralina - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il controller nel sistema ASA A1K, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ad esempio disporre del controller sostitutivo corretto, di un backup della configurazione del sistema e dell'accesso agli strumenti e al firmware necessari.

Esaminare i requisiti.

* Tutti gli shelf di dischi devono funzionare correttamente.
* Il controller integro deve essere in grado di assumere il controllo del controller da sostituire (indicato in questa procedura come "`controller alterato`").
* È necessario sostituire il componente guasto con un componente sostitutivo ricevuto da NetApp.
* Non utilizzare questa procedura per gli upgrade dei controller, ma fare riferimento a https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Scegliere la procedura di aggiornamento dell'hardware del controller"] per le relative indicazioni.
* È necessario sostituire un modulo controller con un modulo controller dello stesso tipo di modello. Non è possibile aggiornare il sistema semplicemente sostituendo il modulo controller.
* Non è possibile modificare dischi o shelf di dischi come parte di questa procedura.
* Poiché il dispositivo di avvio si trova nel modulo di gestione del sistema installato sul retro del sistema, non è necessario spostare il dispositivo di avvio quando si sostituisce un modulo controller.
* È importante applicare i comandi descritti di seguito ai sistemi corretti:
+
** Il controller _alterato_ è il controller che viene sostituito.
** Il controller _replacement_ è il nuovo controller che sostituisce il controller compromesso.
** Il controller _healthy_ è il controller sopravvissuto.


* È sempre necessario acquisire l'output della console del controller in un file di registro di testo.
+
In questo modo è possibile registrare la procedura per risolvere eventuali problemi riscontrati durante il processo di sostituzione.



.Quali sono le prossime novità?
Dopo aver esaminato i requisiti per sostituire il controller ASA A1K, è necessario link:controller-replace-shutdown-nomcc.html["spegnere i controller"].
