---
permalink: asa-r2-a1k/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a1k, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Verifica che le interfacce logiche (LIF) riportino la porta home, esegui un controllo dello stato di salute del cluster e invia il componente guasto a NetApp per completare l"ultimo passaggio della procedura di sostituzione del controller ASA A1K.' 
---
= Sostituzione completa della centralina - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica che le interfacce logiche (LIF) riportino la porta home, esegui un controllo dello stato di salute del cluster e invia il componente guasto a NetApp per completare l'ultimo passaggio della procedura di sostituzione del controller ASA A1K.



== Fase 1: Verifica delle LIF e verifica dello stato del cluster

Prima di riportare in servizio il nodo sostitutivo, verifica che le interfacce logiche siano sulle porte home, verifica lo stato del cluster e ripristina il giveback automatico.

.Fasi
. Verificare che le interfacce logiche stiano segnalando al server principale e alle porte: `network interface show -is-home false`
+
Se alcune interfacce logiche sono elencate come false, riportarle alle porte principali: `network interface revert -vserver * -lif *`

. Controllare lo stato di salute del cluster. Per ulteriori informazioni, consultare l' https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Come eseguire un controllo dello stato del cluster con uno script in ONTAP"^] articolo della KB.
. Se il giveback automatico è stato disattivato, riabilitarlo: `storage failover modify -node local -auto-giveback true`




== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
