---
permalink: asa-r2-a1k/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: asa r2 a1k, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: Verifica che la configurazione ha del controller sia attiva e funzioni correttamente nel sistema di storage ASA A1K e conferma che gli adattatori del sistema elencano tutti i percorsi dei dischi. 
---
= Ripristinare e verificare la configurazione di sistema - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica che la configurazione ha del controller sia attiva e funzioni correttamente nel sistema di storage ASA A1K e conferma che gli adattatori del sistema elencano tutti i percorsi dei dischi.



== Fase 1: Verificare le impostazioni di configurazione ha

Verificare `HA` stato del modulo controller e, se necessario, aggiornare lo stato in modo che corrisponda alla configurazione del sistema.

. Avvio in modalità di manutenzione: `boot_ontap maint`
+
.. Immettere `y` quando viene visualizzato _continuare con boot?_.
+
Se viene visualizzato il messaggio di avviso _System ID mismatch_, immettere `y`.



. Immettere `sysconfig -v` e acquisire il contenuto del display.
+

NOTE: Se viene visualizzato _PERSONALITY MISMATCH_, contattare l'assistenza clienti.

. Dall' `sysconfig -v`uscita, confrontare le informazioni della scheda adattatore con le schede e le posizioni nella centralina sostitutiva.
. Verificare che tutti i componenti visualizzino lo stesso `HA` stato: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato del modulo controller non corrisponde alla configurazione del sistema, impostare `HA` lo stato per il modulo controller: `ha-config modify controller ha`
+
Il valore dello stato ha può essere uno dei seguenti:

+
** `ha`
** `mcc` (non supportato)
** `mccip` (Non supportato nei sistemi ASA)
** `non-ha` (non supportato)


. Verificare che l'impostazione sia stata modificata: `ha-config show`




== Passo 2: Verifica dell'elenco dei dischi

. Verificare che la scheda di rete elenchi i percorsi verso tutti i dischi con `storage show disk -p` .
+
In caso di problemi, controllare il cablaggio e riposizionare i cavi.

. Uscire dalla modalità di manutenzione: `halt`.


.Quali sono le prossime novità?
Dopo aver ripristinato e verificato la configurazione di sistema per il sistema ASA A1K, è necessario link:controller-replace-recable-reassign-disks.html["restituire il controller"].
