---
permalink: asa-r2-a1k/dimm-replace.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace a dimm 
summary: 'È necessario sostituire un modulo DIMM nel modulo controller quando il sistema registra un numero crescente di codici di correzione degli errori correggibili (ECC); in caso contrario, si verifica un errore di sistema.' 
---
= Sostituire un modulo DIMM - ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario sostituire un modulo DIMM nel modulo controller quando il sistema registra un numero crescente di codici di correzione degli errori correggibili (ECC); in caso contrario, si verifica un errore di sistema.

.Prima di iniziare
Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.



== Fase 1: Spegnere il controller compromesso

Spegnere o sostituire il controller compromesso.

Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso.

.A proposito di questa attività
* Se si dispone di un sistema SAN, è necessario aver controllato i messaggi di evento  `cluster kernel-service show`) per il blade SCSI del controller danneggiato. Il `cluster kernel-service show` comando (dalla modalità avanzata precedente) visualizza il nome del nodo, lo stato del quorum di quel nodo, lo stato di disponibilità di quel nodo e lo stato operativo di quel nodo.
+
Ogni processo SCSI-blade deve essere in quorum con gli altri nodi del cluster. Eventuali problemi devono essere risolti prima di procedere con la sostituzione.

* Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].


.Fasi
. Se AutoSupport è attivato, sospendere la creazione automatica dei casi richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattivare il giveback automatico dalla console del controller integro: `storage failover modify –node local -auto-giveback false`
+

NOTE: Quando viene visualizzato _Vuoi disattivare il giveback automatico?_, inserisci `y`.

. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Passare alla fase successiva.



 a| 
In attesa di un giveback...
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode _impaired_node_name_`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===




== Fase 2: Rimuovere il modulo controller

È necessario rimuovere il modulo controller dal contenitore quando si sostituisce il modulo controller o un componente all'interno del modulo controller.

. Controllare il LED di stato NVRAM situato nello slot 4/5 del sistema. Sul pannello anteriore del modulo controller è presente anche un LED NVRAM. Cercare l'icona NV:
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[Grafico della posizione dei LED di stato e di attenzione NVRAM]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Numero di didascalia 1, larghezza=30px"]
 a| 
LED di stato NVRAM



 a| 
image:../media/legend_icon_02.svg["Numero di didascalia 1, larghezza=30px"]
 a| 
LED di attenzione NVRAM

|===
+

NOTE: Se il LED di stato NVRAM lampeggia, il modulo controller potrebbe non essere stato rilevato o arrestato correttamente (dati non registrati). Se il modulo del controller associato non è stato rilevato correttamente, contattare prima di continuare con https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] questa procedura.

+
Il comportamento generale del LED di stato NVRAM sul modulo controller danneggiato è il seguente:

+
** Il LED di stato NVRAM lampeggia quando l'alimentazione viene interrotta dal modulo controller e il modulo controller si trova nello stato "in attesa di giveback" oppure il modulo controller non viene rilevato o arrestato correttamente (dati non impegnati).
** Il LED di stato NVRAM lampeggia quando il modulo controller viene rimosso dal contenitore e potrebbe indicare che il modulo controller non è stato rilevato o arrestato correttamente (dati non registrati). Verificare che il modulo controller sia stato acquisito in modo corretto dal modulo controller partner o che il modulo controller danneggiato mostri `waiting for giveback`. Quindi, il LED lampeggiante può essere ignorato (e il controller può essere rimosso dal contenitore).


. Se non si è già collegati a terra, mettere a terra l'utente.
. Sulla parte anteriore dell'unità, agganciare le dita nei fori delle camme di bloccaggio, premere le linguette sulle leve a camma e ruotare delicatamente, ma con decisione, entrambi i fermi verso di sé contemporaneamente.
+
Il modulo controller si sposta leggermente all'esterno del contenitore.

+
image::../media/drw_a1k_pcm_remove_replace_ieops-1375.svg[Immagine di rimozione della centralina]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Numero di didascalia 1, larghezza=30px"]
| Una camma di bloccaggio si blocca 
|===
. Estrarre il modulo controller dal contenitore e collocarlo su una superficie piana e stabile.
+
Assicurarsi di sostenere la parte inferiore del modulo controller mentre lo si estrae dal contenitore.





== Fase 3: Sostituire un DIMM

È necessario sostituire un DIMM quando il sistema segnala una condizione di errore permanente per tale DIMM.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Aprire il condotto dell'aria della centralina sulla parte superiore della centralina.
+
.. Inserire le dita nelle cavità alle estremità più lontane del condotto dell'aria.
.. Sollevare il condotto dell'aria e ruotarlo verso l'alto fino in fondo.


. Individuare i moduli DIMM sul modulo controller e identificare il modulo DIMM da sostituire.
. Estrarre il modulo DIMM dal relativo slot spingendo lentamente verso l'esterno le due linguette di espulsione dei moduli DIMM su entrambi i lati del modulo, quindi estrarre il modulo DIMM dallo slot.
+

IMPORTANT: Tenere il modulo DIMM per i bordi in modo da evitare di esercitare pressione sui componenti della scheda a circuiti stampati del modulo DIMM.

+
image::../media/drw_a1k_dimms_ieops-1512.svg[DIMM sostituire]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Numero di didascalia 1, larghezza=30px"]
 a| 
Schede di espulsione DIMM e DIMM

|===
. Rimuovere il modulo DIMM di ricambio dalla confezione antistatica, tenerlo per gli angoli e allinearlo allo slot.
+
La tacca tra i pin del DIMM deve allinearsi con la linguetta dello zoccolo.

. Assicurarsi che le linguette di espulsione del modulo DIMM sul connettore siano aperte, quindi inserire il modulo DIMM correttamente nello slot.
+
Il DIMM si inserisce saldamente nello slot, ma dovrebbe essere inserito facilmente. In caso contrario, riallineare il DIMM con lo slot e reinserirlo.

+

IMPORTANT: Esaminare visivamente il DIMM per verificare che sia allineato in modo uniforme e inserito completamente nello slot.

. Spingere con cautela, ma con decisione, il bordo superiore del DIMM fino a quando le linguette dell'espulsore non scattano in posizione sulle tacche alle estremità del DIMM.
. Chiudere il condotto dell'aria della centralina.




== Fase 4: Installare il controller

Reinstallare il modulo controller e avviarlo.

. In caso contrario, chiudere il condotto dell'aria.
. Allineare l'estremità del modulo controller con l'apertura nel contenitore, quindi far scorrere il modulo controller nel telaio con le leve ruotate lontano dalla parte anteriore del sistema.
. Una volta che il modulo controller non riesce a farlo scorrere ulteriormente, ruotare le maniglie della camma verso l'interno fino a quando non si bloccano sotto le ventole
+

NOTE: Non esercitare una forza eccessiva quando si fa scorrere il modulo controller nel contenitore per evitare di danneggiare i connettori.

+
Il modulo controller inizia ad avviarsi non appena viene inserito completamente nel contenitore.

. Ripristinare il giveback automatico se è stato disattivato utilizzando `storage failover modify -node local -auto-giveback true` comando.
. Se AutoSupport è abilitato, ripristinare/riattivare la creazione automatica dei casi utilizzando il `system node autosupport invoke -node * -type all -message MAINT=END` comando.




== Fase 5: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
