= 
:allow-uri-read: 


In una configurazione MetroCluster a due nodi che esegue ONTAP, è necessario riassegnare manualmente i dischi all'ID di sistema del nuovo controller prima di riportare il sistema alla normale condizione operativa.

.A proposito di questa attività
Questa procedura si applica solo ai sistemi in una configurazione MetroCluster a due nodi che esegue ONTAP.

Assicurarsi di eseguire i comandi di questa procedura sul nodo corretto:

* Il nodo _alterato_ è il nodo su cui si esegue la manutenzione.
* Il nodo _replacement_ è il nuovo nodo che ha sostituito il nodo compromesso come parte di questa procedura.
* Il nodo _healthy_ è il partner DR del nodo compromesso.


.Fasi
. Se non lo si è già fatto, riavviare il nodo _replacement_ e interrompere il processo di avvio immettendo `Ctrl-C`, Quindi selezionare l'opzione per avviare la modalità di manutenzione dal menu visualizzato.
+
È necessario immettere `Y` Quando viene richiesto di sostituire l'ID di sistema a causa di una mancata corrispondenza dell'ID di sistema.

. Visualizzare i vecchi ID di sistema dal nodo integro: ``metrocluster node show -fields node-systemid`,dr-partner-systemid`
+
In questo esempio, Node_B_1 è il nodo precedente, con il vecchio ID di sistema 118073209:

+
[listing]
----
dr-group-id cluster         node                 node-systemid dr-partner-systemid
 ----------- --------------------- -------------------- ------------- -------------------
 1           Cluster_A             Node_A_1             536872914     118073209
 1           Cluster_B             Node_B_1             118073209     536872914
 2 entries were displayed.
----
. Visualizzare il nuovo ID di sistema al prompt della modalità di manutenzione sul nodo non valido: `disk show`
+
In questo esempio, il nuovo ID di sistema è 118065481:

+
[listing]
----
Local System ID: 118065481
    ...
    ...
----
. Riassegnare la proprietà del disco (per i sistemi FAS) o la proprietà del LUN (per i sistemi FlexArray), utilizzando le informazioni sull'ID di sistema ottenute dal comando disk show: `disk reassign -s old system ID`
+
Nel caso dell'esempio precedente, il comando è: `disk reassign -s 118073209`

+
Puoi rispondere `Y` quando viene richiesto di continuare.

. Verificare che i dischi (o LUN FlexArray) siano stati assegnati correttamente: `disk show -a`
+
Verificare che i dischi appartenenti al nodo _replacement_ mostrino il nuovo ID di sistema per il nodo _replacement_. Nell'esempio seguente, i dischi di proprietà del sistema-1 ora mostrano il nuovo ID di sistema, 118065481:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK     OWNER                 POOL   SERIAL NUMBER  HOME
-------    -------------         -----  -------------  -------------
disk_name   system-1  (118065481) Pool0  J8Y0TDZC       system-1  (118065481)
disk_name   system-1  (118065481) Pool0  J8Y09DXC       system-1  (118065481)
.
.
.
----
. Dal nodo integro, verificare che tutti i coredump siano salvati:
+
.. Passare al livello di privilegio avanzato: `set -privilege advanced`
+
Puoi rispondere `Y` quando viene richiesto di passare alla modalità avanzata. Viene visualizzato il prompt della modalità avanzata (*>).

.. Verificare che i coredump siano salvati: `system node run -node _local-node-name_ partner savecore`
+
Se l'output del comando indica che il salvataggio è in corso, attendere il completamento del salvataggio prima di emettere il giveback. È possibile monitorare l'avanzamento del salvataggio utilizzando `system node run -node _local-node-name_ partner savecore -s command`</info>.

.. Tornare al livello di privilegio admin: `set -privilege admin`


. Se il nodo _replacement_ è in modalità Maintenance (con il prompt *>), uscire dalla modalità Maintenance (manutenzione) e passare al prompt DEL CARICATORE: `halt`
. Avviare il nodo _replacement_: `boot_ontap`
. Una volta avviato il nodo _replacement_, eseguire uno switchback: `metrocluster switchback`
. Verificare la configurazione di MetroCluster: `metrocluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. Verificare il funzionamento della configurazione MetroCluster in Data ONTAP:
+
.. Verificare la presenza di eventuali avvisi sullo stato di salute su entrambi i cluster: `system health alert show`
.. Verificare che MetroCluster sia configurato e in modalità normale: `metrocluster show`
.. Eseguire un controllo MetroCluster: `metrocluster check run`
.. Visualizzare i risultati del controllo MetroCluster: `metrocluster check show`
.. Eseguire Config Advisor. Accedere alla pagina Config Advisor sul sito del supporto NetApp all'indirizzo https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor/["support.netapp.com/NOW/download/tools/config_advisor/"].
+
Dopo aver eseguito Config Advisor, esaminare l'output dello strumento e seguire le raccomandazioni nell'output per risolvere eventuali problemi rilevati.



. Simulare un'operazione di switchover:
+
.. Dal prompt di qualsiasi nodo, passare al livello di privilegio avanzato: `set -privilege advanced`
+
Devi rispondere con `y` quando viene richiesto di passare alla modalità avanzata e di visualizzare il prompt della modalità avanzata (*>).

.. Eseguire l'operazione di switchback con il parametro -simulate: `metrocluster switchover -simulate`
.. Tornare al livello di privilegio admin: `set -privilege admin`



