= 
:allow-uri-read: 


Esaminare i requisiti per la sostituzione del modulo controller.

[NOTE]
====
NetApp raccomanda vivamente di abilitare la registrazione della console sui dispositivi con cui si sta lavorando e di adottare le seguenti misure durante l'esecuzione di questa procedura:

* Lascia AutoSupport abilitato durante la manutenzione. Questo consente al supporto NetApp di ricevere informazioni diagnostiche in caso di problemi.
* Abilita la registrazione delle sessioni per tutte le sessioni CLI. Questo crea una registrazione completa di tutti i comandi e dell'output di sistema durante l'attività di manutenzione. Per istruzioni su come abilitare la registrazione delle sessioni, vedere  https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["Come configurare PuTTY per una connettività ottimale ai sistemi ONTAP"^].


====
* Tutti gli shelf di dischi devono funzionare correttamente.
* Il controller sano deve essere in grado di subentrare al controller sostituito (definito in questa procedura come controller danneggiato).
* Non utilizzare questa procedura per gli aggiornamenti del controller.  Fare riferimento a https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Scegliere la procedura di aggiornamento dell'hardware del controller"] per avere una guida.
* Se il sistema è in una configurazione MetroCluster , rivedere https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Scelta della procedura di ripristino corretta"] per determinare se utilizzare questa procedura.
* Sostituisci il componente guasto con l'unità sostituibile sul campo (FRU) ricevuta da NetApp.
* Sostituire il modulo controller con un modulo controller dello stesso tipo di modello.  Non è possibile aggiornare il sistema sostituendo il modulo controller.
* Non è possibile modificare le unità o gli scaffali delle unità durante questa procedura.
* Il dispositivo di avvio si trova sul modulo System Management installato nella parte posteriore del sistema.  Non è necessario spostare il dispositivo di avvio quando si sostituisce un modulo controller.
* Comprendere la terminologia del controller utilizzata in questa procedura:
+
** Il controller _danneggiato_ è il controller che viene sostituito.
** Il controller _sostitutivo_ è il nuovo controller che sostituisce quello difettoso.
** Il controller _healthy_ è il controller sopravvissuto.



