= 
:allow-uri-read: 


.Prima di iniziare
* Per OKM, sono necessari la passphrase dell'intero cluster e i dati di backup.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** file /cfcard/kmip/servers.cfg.
** file /cfcard/kmip/certs/client.crt.
** file /cfcard/kmip/certs/client.key.
** File /cfcard/kmip/certs/CA.pem.




.Fasi
. Al prompt di Loader, immettere il comando:
+
`boot_recovery -partner`

+
Sullo schermo viene visualizzato il seguente messaggio:

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Monitorare il processo di ripristino dell'installazione dei supporti di avvio.
+
Il processo viene completato e viene visualizzato il `Installation complete` messaggio.

. Il sistema controlla il tipo di crittografia e di crittografia e visualizza uno dei due messaggi. A seconda del messaggio visualizzato, eseguire una delle seguenti operazioni:
+

IMPORTANT: A volte, il processo potrebbe non essere in grado di identificare se il gestore delle chiavi è configurato sul sistema. Viene visualizzato un messaggio di errore, viene chiesto se il gestore delle chiavi è configurato per il sistema e viene chiesto quale tipo di gestore delle chiavi è configurato. Il processo riprenderà dopo aver risolto il problema.

+
.Mostrare un esempio di messaggi di errore di configurazione per la ricerca
[%collapsible]
====
....
Error when fetching key manager config from partner ${partner_ip}: ${status}

Has key manager been configured on this system

Is the key manager onboard

....
====
+
[cols="1,2"]
|===
| Se viene visualizzato questo messaggio... | Eseguire questa operazione... 


 a| 
`key manager is not configured. Exiting.`
 a| 
La crittografia non è configurata sul sistema. Completare i seguenti passaggi:

.. Premere <enter> quando i messaggi della console si interrompono.
+
*** Se viene visualizzato il prompt di accesso, procedere al passaggio 4.
*** Se non viene visualizzato il prompt di accesso, accedi al nodo partner e procedi al passaggio 4.


.. Passare al passaggio 6 per abilitare la restituzione automatica se era disabilitata.




 a| 
`key manager is configured.`
 a| 
Passare al passaggio 5 per ripristinare il gestore chiavi appropriato.

Il nodo accede al menu di avvio ed esegue:

** Opzione 10 per sistemi con Onboard Key Manager (OKM).
** Opzione 11 per i sistemi con EKM (External Key Manager).


|===
. Se la crittografia non è installata sul sistema e il prompt di accesso non viene visualizzato. Completare i seguenti passaggi:
+
.. Restituisci solo la radice con l'opzione override-destination-checks:
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: Questo comando è disponibile solo in modalità Diagnostica. Per maggiori dettagli, vedere link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["Livelli di privilegio per i comandi ONTAP CLI"^] .

+
In caso di errori, contattare https://support.netapp.com["Supporto NetApp"].

.. Attendere 5 minuti dopo il completamento del report di sconto e verificare lo stato di failover e dello stato dello sconto:
+
`storage failover show`E `storage failover show-giveback`

+

NOTE: Il seguente comando è disponibile solo nel livello di privilegio Modalità diagnostica.

.. Se si utilizza ONTAP 9.17.1 e i collegamenti interconnessione HA sono stati interrotti, ripristinarli:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

+

NOTE: Se stai utilizzando la versione 9.18.1 o successiva, salta il passaggio precedente e vai al passaggio successivo.

.. Riportare la centralina guasta al normale funzionamento restituendo la memoria:
+
`storage failover giveback -ofnode _impaired_node_name_`



. Per i sistemi con gestore chiavi configurato, selezionare il processo di ripristino del gestore chiavi appropriato.
+
[role="tabbed-block"]
====
.Onboard Key Manager (OKM)
--
Se viene rilevato un OKM, il sistema visualizza il seguente messaggio e inizia a eseguire l'opzione 10 del menu di avvio.

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. Immettere `Y` quando richiesto per confermare che si desidera avviare il processo di ripristino OKM.
.. Quando richiesto, immettere quanto segue:
+
... La frase segreta
... La passphrase di nuovo quando viene richiesto di confermare
... Dati di backup per il gestore delle chiavi di bordo
+
.Mostra un esempio di richiesta di passphrase e dati di backup
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END ACKUP-----
....
=====


.. Continuare a monitorare il processo di ripristino durante il ripristino dei file appropriati dal nodo partner.
+
Al termine del processo di ripristino, il nodo viene riavviato. I seguenti messaggi indicano che il ripristino è stato eseguito correttamente:

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.

Successfully recovered keymanager secrets.
....
.. Quando il nodo viene riavviato, verificare che il ripristino del supporto di avvio sia stato eseguito correttamente confermando che il sistema è nuovamente in linea e operativo.
.. Riportare la centralina guasta al normale funzionamento restituendo la memoria:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
... Se i collegamenti di interconnessione HA sono stati interrotti, ripristinarli per riprendere il giveback automatico:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



.. Una volta che il nodo partner è completamente attivo e fornisce i dati, sincronizzare le chiavi OKM nel cluster.
+
`security key-manager onboard sync`



--
.Gestore chiavi esterno (EKM)
--
Se viene rilevato EKM, il sistema visualizza il seguente messaggio e inizia a eseguire l'opzione 11 del menu di avvio.

....
key manager is configured.
Entering Bootmenu Option 11...
....
.. A seconda che la chiave sia stata ripristinata correttamente, eseguire una delle seguenti operazioni:
+
*** Se vedi `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696` nell'output, la configurazione EKM è stata ripristinata correttamente.
+
Il processo tenta di ripristinare i file appropriati dal nodo partner e riavvia il nodo.  Vai al passaggio d.

*** Se il ripristino della chiave non riesce, il sistema si arresta e indica che non è stato possibile ripristinarla.  Vengono visualizzati i messaggi di errore e di avviso.  È necessario eseguire nuovamente il processo di ripristino:
+
`boot_recovery -partner`

+
.Mostrare un esempio di messaggi di errore e di avvertenza relativi al ripristino della chiave
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>
....
=====


.. Quando il nodo viene riavviato, verificare che il ripristino del supporto di avvio sia stato eseguito correttamente confermando che il sistema è nuovamente online e operativo.
.. Riportare il controller al funzionamento normale restituendo lo storage:
+
`storage failover giveback -ofnode _impaired_node_name_`

+
... Se i collegamenti di interconnessione HA sono stati interrotti, ripristinarli per riprendere il giveback automatico:
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`





--
====


. Se il giveback automatico è stato disattivato, riabilitarlo:
+
`storage failover modify -node local auto-giveback-of true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


