= 
:allow-uri-read: 


È possibile ripristinare l'immagine ONTAP (boot media recovery) dal nodo partner utilizzando il `boot_recovery -partner` comando con le piattaforme ASA R2 che eseguono ONTAP 9.16,0 e versioni successive.

.Prima di iniziare
Quando si avvia un nodo e il supporto di avvio su quel nodo è danneggiato, al prompt di Loader vengono visualizzati i seguenti messaggi e il processo di avvio con stop:

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
Se viene visualizzato questo messaggio, è necessario ripristinare l'immagine ONTAP

.Fasi
. Dal prompt DI Loader, immettere il comando _boot_recovery -partner_.
+
La schermata visualizza il messaggio `Starting boot media recovery (BMR) process press Ctrl-C to abort...` e avvia i controlli iniziali.

. Monitorare il processo mentre Loader configura le porte del cluster locale ed esegue netboot tramite `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`.
+
Una volta eseguito netboot, `Starting BMR ...` viene visualizzato sullo schermo e il processo completa il processo di installazione.

+
.. Se Key Manager non è configurato, viene visualizzato il seguente messaggio:
+
....
key manager is not configured. Exiting.
....
.. Se viene visualizzato il seguente messaggio, Onboard Key Manager (OKM) è configurato:
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
Andare a per completare il processo di ripristino.

.. Se viene visualizzato il seguente messaggio, EKM (External Key Manager) è configurato. Andare all'argomento EKM e completare il processo di ripristino:
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. Monitorare il processo BMR mentre esegue il ripristino della configurazione di backup, del file env, di mdb e di rdb dal partner.
. Il nodo si riavvia e il BMR è completo quando viene visualizzato quanto segue:


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....