= 
:allow-uri-read: 


È necessario avviare l'immagine ONTAP dall'unità USB, ripristinare il file system e verificare le variabili ambientali.

.Fasi
. Dal prompt DEL CARICATORE, avviare l'immagine di ripristino dall'unità flash USB: `boot_recovery`
+
L'immagine viene scaricata dall'unità flash USB.

. Quando richiesto, inserire il nome dell'immagine o accettare l'immagine predefinita visualizzata tra parentesi sullo schermo.
. Ripristinare il file system var:
+
[role="tabbed-block"]
====
.Opzione 1: ONTAP 9.16,0 o versione precedente
--
.. Sul controller con problemi, premere `Y` quando viene visualizzato `Do you want to restore the backup configuration now?`
.. Sul controller danneggiato, premere `Y` quando viene richiesto di sovrascrivere _/etc/ssh/ssh_host_ecdsa_key_.
.. Sul controller partner sano, impostare il controller con problemi sul livello di privilegi avanzato: `set -privilege advanced`.
.. Sul controller partner integro, eseguire il comando di ripristino del backup: `system node restore-backup -node local -target-address impaired_node_IP_address` .
+
*NOTA:* se viene visualizzato un messaggio diverso da un ripristino riuscito, contattare https://support.netapp.com["Supporto NetApp"].

.. Sul controller partner sano, riportare il controller danneggiato al livello di amministratore: `set -privilege admin`.
.. Sul controller con problemi, premere `Y` quando viene visualizzato `Was the restore backup procedure successful?`.
.. Sul controller con problemi, premere `Y` quando viene visualizzato `...would you like to use this restored copy now?`.
.. Sul controller danneggiato, premere `Y` quando richiesto per riavviare il controller danneggiato e premere `ctrl-c` per il menu di avvio.
.. Se il sistema non utilizza la crittografia, selezionare _opzione 1 Avvio normale._, altrimenti andare a link:bootmedia-encryption-restore.html["Ripristino della crittografia"].


--
.Opzione 2: ONTAP 9.16,1 o versione successiva
--
.. Al prompt Loader sul controller danneggiato, configurare l'indirizzo IP del modulo controller danneggiato:
+
`ifconfig e0M - auto`

.. Al prompt di Loader, netboot del nodo danneggiato:
+
`netboot \http://_web_server_ip/path_to_web-accessible_directory_/<ontap_version>_image.tgz`

.. Dal menu di avvio, selezionare opzione `7`.
.. Immettere `n` quando viene richiesto di ripristinare la configurazione di backup.
.. Immettere `y` quando viene richiesto di riavviare il nodo.
.. Premere `ctrl-c` per tornare al menu di avvio.
+
Se la crittografia è attivata, è necessario ripristinarla prima di continuare a ripristinare l'immagine di avvio. Andare a link:bootmedia-encryption-restore.html["Ripristino della crittografia"].

.. Sul controller danneggiato, premere `Y` quando richiesto per riavviare il controller danneggiato e premere `ctrl-c` per il menu di avvio.
.. Selezionare opzione `6`.
.. Sul controller danneggiato, premere `Y` quando richiesto per confermare se il backup di ripristino è stato eseguito correttamente.
.. Sul controller danneggiato, premere `Y` quando viene richiesto di utilizzare la configurazione ripristinata.
.. Sul controller danneggiato, premere `Y` quando viene richiesto di riavviare il nodo.
.. Premere `Y` quando viene richiesto di ripristinare la configurazione di backup.
+
Una volta completata la procedura di ripristino, questo messaggio viene visualizzato sulla console - `syncflash_partner: Restore from partner complete`.



--
====


. Collegare il cavo della console al controller partner.
. Restituire il controller utilizzando `storage failover giveback -fromnode local` comando.
. Ripristinare il giveback automatico se è stato disattivato utilizzando `storage failover modify -node local -auto-giveback true` comando.
. Se AutoSupport è abilitato, ripristinare/riattivare la creazione automatica dei casi utilizzando il `system node autosupport invoke -node * -type all -message MAINT=END` comando.
+
*NOTA:* se il processo non riesce, contattare https://support.netapp.com["Supporto NetApp"].


