= Fase 1: Verificare e impostare lo stato ha del telaio
:allow-uri-read: 




== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornare lo stato in modo che corrisponda alla configurazione del sistema di storage.

. In modalità di manutenzione, da uno dei controller, viene visualizzato lo stato ha del controller locale e dello chassis:
+
`ha-config show`

+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema di archiviazione:
+
.. Impostare lo stato ha per lo chassis:
+
`ha-config modify chassis _HA-state_`

+
Il valore per ha-state deve essere _ha_. Il valore per ha-state può essere uno dei seguenti: _Ha_ _mcc_ (non supportato in ASA)

.. Verificare che l'impostazione sia stata modificata:
+
`ha-config show`



. Se non l'hai ancora fatto, puoi recuperare il resto del tuo sistema storage.




== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
