= Requisiti
:allow-uri-read: 


Esaminare i seguenti requisiti e considerazioni.



== Requisiti

* Il telaio di ricambio deve essere dello stesso modello del telaio danneggiato. Questa procedura si riferisce a una sostituzione simile a quella di un prodotto, non a un aggiornamento.
* Tutti gli altri componenti del sistema di stoccaggio devono funzionare correttamente; in caso contrario, contattare https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] prima di continuare con questa procedura.




== Considerazioni

* La procedura di sostituzione dello chassis provoca interruzioni. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.
* Puoi utilizzare la procedura di sostituzione dello chassis con tutte le versioni di ONTAP supportate dal tuo sistema storage.
* La procedura di sostituzione dello chassis viene scritta presupponendo che il pannello, le unità, gli eventuali alloggiamenti e i controller vengano spostati nel nuovo chassis.

