= Requisiti
:allow-uri-read: 


È necessario rivedere i requisiti e le considerazioni per la procedura di sostituzione della centralina.



== Requisiti

* Tutti i ripiani devono funzionare correttamente.
* Il controller integro deve essere in grado di assumere il controllo del controller da sostituire (indicato in questa procedura come "`controller alterato`").
* È necessario sostituire un controller con un controller dello stesso tipo di modello. Non è possibile aggiornare il sistema semplicemente sostituendo il controller.
* Non è possibile sostituire dischi o shelf nell'ambito di questa procedura.
* È sempre necessario acquisire l'output della console del controller in un file di registro di testo.
+
L'output della console fornisce una registrazione della procedura che è possibile utilizzare per risolvere i problemi che potrebbero verificarsi durante il processo di sostituzione.





== Considerazioni

* È importante applicare i comandi di questa procedura al controller corretto:
+
** Il controller _alterato_ è il controller che viene sostituito.
** Il controller _replacement_ è il nuovo controller che sostituisce il controller compromesso.
** Il controller _healthy_ è il controller sopravvissuto.



