= 
:allow-uri-read: 


È possibile sostituire un disco guasto senza interruzioni mentre l'i/o è in corso.

.Prima di iniziare
* L'unità che si sta installando deve essere supportata dal sistema di archiviazione.
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* Se l'autenticazione SED (self-Encrypting Drive) è attivata, è necessario utilizzare le istruzioni per la sostituzione SED contenute nella documentazione ONTAP.
+
Le istruzioni contenute nella documentazione di ONTAP descrivono i passaggi aggiuntivi da eseguire prima e dopo la sostituzione di un SED.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Panoramica della crittografia NetApp con CLI"^]

* Tutti gli altri componenti del sistema di stoccaggio devono funzionare correttamente; in caso contrario, è necessario contattare https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] prima di continuare con questa procedura.
* Verificare che l'unità che si sta rimuovendo non sia funzionante.
+
È possibile verificare che il disco non funzioni correttamente eseguendo `storage disk show -broken` comando. Il disco guasto viene visualizzato nell'elenco dei dischi guasti. In caso contrario, attendere ed eseguire nuovamente il comando.

+

NOTE: A seconda del tipo e della capacità del disco, potrebbero essere necessarie diverse ore prima che il disco venga visualizzato nell'elenco dei dischi guasti.



.A proposito di questa attività
* Quando si sostituisce un'unità guasta, è necessario attendere 70 secondi tra la rimozione dell'unità e l'inserimento dell'unità sostitutiva per consentire al sistema di archiviazione di riconoscere che un'unità è stata rimossa.
* Si consiglia di installare la versione corrente del Disk Qualification Package (DQP) prima di eseguire lo hot-swap di un'unità.
+
L'installazione della versione corrente di DQP consente al sistema di riconoscere e utilizzare dischi appena qualificati. In questo modo si evitano messaggi di eventi di sistema relativi alla presenza di informazioni non aggiornate sui dischi e alla prevenzione della partizione dei dischi perché i dischi non vengono riconosciuti. Inoltre, il DQP notifica la presenza di firmware del disco non aggiornato.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["Download NetApp: Pacchetto di qualificazione dei dischi"^]

* Prima di sostituire i componenti FRU, si consiglia di disporre delle versioni attuali del firmware del disco e del firmware del modulo shelf NVMe (NSM) sul sistema.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Download NetApp: Firmware shelf di dischi"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Download NetApp: Firmware del disco"^]

+
[NOTE]
====
Non riportare il firmware a una versione che non supporta lo shelf e i relativi componenti.

====
* Il firmware del disco viene aggiornato automaticamente (senza interruzioni) sui nuovi dischi con versioni firmware non aggiornate.
+

NOTE: I controlli del firmware del disco vengono eseguiti ogni due minuti.

* Se necessario, è possibile attivare i LED di posizione del sistema di archiviazione (blu) per agevolare l'individuazione fisica del sistema di archiviazione interessato. Accedere a BMC utilizzando SSH e immettere il `system location-led _on_` comando.
+
Un sistema di archiviazione ha tre LED di posizione: Uno sul pannello del display dell'operatore e uno su ciascun controller. I LED di posizione rimangono accesi per 30 minuti.

+
È possibile disattivarle immettendo il `system location-led _off_` comando. Se non si è certi che i LED siano accesi o spenti, è possibile controllarne lo stato digitando il `system location-led show` comando.


