= 
:allow-uri-read: 


Prepara il sistema storage e lo slot del modulo I/O in modo che sia sicuro rimuovere il modulo I/O guasto:

.Fasi
. Mettere a terra l'utente.
. Scollegare i cavi dal modulo I/O guasto.
+
Assicuratevi di etichettare i cavi in modo da poterli ricollegare alle stesse porte più avanti in questa procedura.

+
[NOTE]
====
Il modulo I/O dovrebbe essere guasto (le porte dovrebbero essere nello stato di collegamento inattivo); tuttavia, se i collegamenti sono ancora attivi e contengono l'ultima porta cluster funzionante, scollegando i cavi si attiva un takeover automatico.

Attendere cinque minuti dopo aver scollegato i cavi per assicurarsi che eventuali takeover o failover LIF siano completati prima di continuare con questa procedura.

====
. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
Ad esempio, il seguente messaggio AutoSupport sopprime la creazione automatica dei casi per due ore:

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. A seconda della versione di ONTAP in esecuzione sul sistema storage e dello stato dei controller, disabilitare il giveback automatico:
+
[cols="1,2,3"]
|===
| Versione di ONTAP | Se... | Quindi... 


 a| 
9.17.1 o 9.18.1RC
 a| 
Se il controller compromesso ha effettuato il takeover automatico del controller sano
 a| 
Disattiva la restituzione automatica:

.. Immettere il seguente comando dalla console del controller non funzionante
+
`storage failover modify -node local -auto-giveback false`

.. Entra `y` quando vedi il messaggio _Vuoi disattivare la restituzione automatica?_




 a| 
9.18.1GA o versioni successive
 a| 
Se uno dei due controller ha effettuato il takeover automatico del partner controller
 a| 
Disattiva la restituzione automatica:

.. Immettere il seguente comando dalla console del controller che ha effettuato il takeover del partner controller:
+
`storage failover modify -node local -auto-giveback false`

.. Entra `y` quando vedi il messaggio _Vuoi disattivare la restituzione automatica?_




 a| 
9.18.1GA o versioni successive
 a| 
Entrambi i controller sono attivi e in esecuzione I/O (servendo dati)
 a| 
Passare alla fase successiva.

|===
. Prepara il modulo I/O guasto per la rimozione rimuovendolo dal servizio e spegnendolo:
+
.. Immettere il seguente comando:
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. Entra `y` quando vedi il messaggio _Vuoi continuare?_
+
Ad esempio, il seguente comando prepara il modulo guasto nello slot 4 sul nodo 2 (il controller danneggiato) per la rimozione e visualizza un messaggio che indica che è sicuro rimuoverlo:

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----


. Verificare che il modulo I/O guasto sia spento:
+
`system controller slot module show`

+
L'output dovrebbe mostrare  `_powered-off_` nella  `_status_` colonna per il modulo guasto e il suo numero di slot.


