= 
:allow-uri-read: 


Preparare il sistema di storage e lo slot 4 del modulo I/O in modo da poter rimuovere in sicurezza il cluster guasto e il modulo I/O HA:

. Mettere a terra l'utente.
. Scollegare i cavi dal cluster guasto e dal modulo I/O HA.
+
Assicuratevi di etichettare i cavi in modo che più avanti in questa procedura sia possibile ricollegarli alle stesse porte.

. Se AutoSupport è attivato, eliminare la creazione automatica del caso richiamando un messaggio AutoSupport:
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
Ad esempio, il seguente messaggio AutoSupport sopprime la creazione automatica dei casi per due ore:

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattiva la restituzione automatica:
+
.. Immettere il seguente comando dalla console del controller non funzionante:
+
`storage failover modify -node local -auto-giveback false`

.. Entra `y` quando vedi il messaggio _Vuoi disattivare la restituzione automatica?_


. Preparare il cluster guasto e il modulo HA nello slot 4 per la rimozione, rimuovendoli dal servizio e spegnendoli:
+
.. Immettere il seguente comando:
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. Entra `y` quando vedi il messaggio _Vuoi continuare?_
+
Ad esempio, il seguente comando prepara il modulo nello slot 4 sul nodo 2 (il controller danneggiato) per la rimozione e visualizza un messaggio che indica che è possibile rimuoverlo in sicurezza:

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----


. Verificare che il cluster non funzionante e il modulo HA nello slot 4 siano spenti:
+
`system controller slot module show`

+
L'output dovrebbe mostrare  `_powered-off_` nella colonna di stato del modulo guasto nello slot 4.


