= 
:allow-uri-read: 


Per utilizzare questa procedura, il sistema storage deve eseguire ONTAP 9.17.1 o una versione successiva e il sistema storage deve soddisfare tutti i requisiti per la versione di ONTAP che il sistema storage sta eseguendo.


NOTE: Se il sistema storage non esegue ONTAP 9.17.1 o una versione successiva, oppure non soddisfa tutti i requisiti per la versione di ONTAP in esecuzione sul sistema storage, non è possibile utilizzare questa procedura, è necessario utilizzare il link:io-module-replace.html["sostituire una procedura del modulo I/O"].

[role="tabbed-block"]
====
.ONTAP 9.17.1 o 9.18.1RC
--
* Si sta eseguendo lo swap a caldo di un cluster guasto e di un modulo I/O HA nello slot 4 con un modulo I/O equivalente. Non è possibile modificare il tipo di modulo I/O.
* Il controller con il cluster e il modulo I/O HA guasti (il controller danneggiato) deve aver già effettuato il takeover del partner controller. Il takeover dovrebbe essere avvenuto automaticamente se il modulo I/O si è guastato.
+
Per i cluster a due nodi, il sistema storage non è in grado di distinguere quale controller abbia il modulo I/O guasto, quindi uno dei due controller potrebbe avviare il takeover. Lo swap a caldo è supportato solo quando il controller con il modulo I/O guasto (il controller compromesso) ha effettuato il takeover del controller funzionante. Lo swap a caldo del modulo I/O è l'unico modo per ripristinare senza interruzioni.

+
È possibile verificare che il controller non funzionante abbia preso il controllo del controller sano immettendo  `storage failover show` comando.

+
Se non si è sicuri di quale controller abbia il modulo I/O guasto, contattare  https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] .

* La configurazione del sistema di storage deve avere un solo cluster e modulo I/O HA nello slot 4, non due cluster e moduli I/O HA.
* Il sistema di archiviazione deve essere una configurazione cluster a due nodi (switchless o switching).
* Tutti gli altri componenti del sistema di stoccaggio devono funzionare correttamente; in caso contrario, contattare https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] prima di continuare con questa procedura.


--
.ONTAP 9.18.1GA o versioni successive
--
* Si sta eseguendo lo swap a caldo di un modulo I/O Ethernet in uno slot con qualsiasi combinazione di porte utilizzate per cluster, HA e client con un modulo I/O equivalente. Non è possibile modificare il tipo di modulo I/O.
+
I moduli I/O Ethernet con porte utilizzate per lo storage o MetroCluster non sono hot-swappable.

* Il tuo sistema storage (configurazione cluster switchless o cluster commutato) può avere qualsiasi numero di nodi supportati per il tuo sistema storage.
* Tutti i nodi del cluster devono eseguire la stessa versione di ONTAP (ONTAP 9.18.1GA o successiva) oppure diversi livelli di patch della stessa versione di ONTAP.
+
Se i nodi del tuo cluster eseguono versioni di ONTAP diverse, questo è considerato un cluster a versioni miste e lo swap a caldo di un modulo I/O non è supportato.



* I controller nel tuo sistema storage possono trovarsi in uno dei seguenti stati:
+
** Entrambi i controller possono essere attivi e in esecuzione I/O (servendo dati).
** Entrambi i controller possono trovarsi in uno stato di takeover se il takeover è stato causato dal modulo I/O guasto e i controller funzionano correttamente.
+
In determinate situazioni, ONTAP può eseguire automaticamente un takeover di uno dei controller a causa del guasto del modulo I/O. Ad esempio, se il modulo I/O guasto conteneva tutte le porte del cluster (tutti i collegamenti del cluster su quel controller si interrompono), ONTAP esegue automaticamente un takeover.





* Tutti gli altri componenti del sistema di stoccaggio devono funzionare correttamente; in caso contrario, contattare https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"] prima di continuare con questa procedura.


--
====