= Fase 1: Collegare i controller di archiviazione alla rete
:allow-uri-read: 


.Prima di iniziare
Per l'orientamento corretto della linguetta di estrazione del connettore del cavo, consultare la freccia degli schemi dei cavi.

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[Esempio di orientamento della linguetta di estrazione del cavo]

* Quando si inserisce il connettore, si dovrebbe avvertire uno scatto in posizione; se non si sente uno scatto, rimuoverlo, capovolgere la testa del cavo e riprovare.
* Se si effettua il collegamento a uno switch ottico, inserire il ricetrasmettitore SFP (Small Form-factor pluggable) nella porta del controller prima di collegare il cavo alla porta.




== Fase 1: Collegare i controller di archiviazione alla rete

Collegare i controller direttamente l'uno all'altro e alla rete host.

.Prima di iniziare
Contattare l'amministratore di rete per informazioni sulla connessione del sistema di archiviazione agli switch di rete host.

.A proposito di questa attività
Queste procedure mostrano le configurazioni comuni. Il cablaggio specifico dipende dai componenti ordinati per il sistema di storage in uso. Per informazioni dettagliate sulla configurazione e la priorità degli slot, vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^].

[role="tabbed-block"]
====
.Sistema di storage ASA A1K
--
Connetti gli storage controller per creare connessioni cluster ONTAP e collegare le porte Ethernet di ciascun controller alla rete host.

.Fasi
. Utilizzare il cavo di interconnessione Cluster/ha per collegare le porte da E1a a E1a e le porte da e7a a e7a.
+

NOTE: Il traffico di cluster Interconnect e quello di ha condividono le stesse porte fisiche.

+
.. Collegare la porta E1a del controller A alla porta E1a del controller B.
.. Collegare la porta e7a del controller A alla porta E1a del controller B.
+
*Cavi di interconnessione cluster/ha*

+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cavo ha del cluster]

+
image::../media/drw_a1k_tnsc_cluster_cabling_ieops-1648.svg[Schema di cablaggio del cluster senza switch a due nodi]



. Collegare le porte del modulo Ethernet alla rete host.
+
Di seguito sono riportati alcuni esempi tipici di cablaggio della rete host. Per informazioni sulla configurazione specifica del sistema, vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^] .

+
.. Collegare le porte e9a e e9b allo switch di rete dati Ethernet, come illustrato.
+

NOTE: Per ottenere le massime performance di sistema per il traffico cluster e ha, si consiglia di non utilizzare le porte e1b e e7b per le connessioni di rete host. Utilizzare una scheda host separata per ottimizzare le prestazioni.

+
*Cavo 100 GbE*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100GB cavo Ethernet]

+
image::../media/drw_a1k_network_cabling1_ieops-1649.svg[Cavo alla rete Ethernet 100GB]

.. Collegare gli switch di rete host 10/25 GbE.
+
*Host 10/25 GbE*

+
image::../media/oie_cable_sfp_gbe_copper.svg[Cavo Ethernet 10/25GB]

+
image::../media/drw_a1k_network_cabling2_ieops-1650.svg[Cavo alla rete Ethernet 10/25GB]



. Utilizzare i cavi RJ-45 1000BASE-T per collegare le porte di gestione del controller (chiave inglese) agli switch della rete di gestione.
+
image::../media/oie_cable_rj45.svg[Cavi RJ-45]

+
*CAVI RJ-45 1000BASE-T.

+
image::../media/drw_a1k_management_connection_ieops-1651.svg[Connettersi alla rete di gestione]




IMPORTANT: Non collegare ancora i cavi di alimentazione.

--
.Sistemi storage ASA A70 e ASA A90
--
Connetti gli storage controller per creare connessioni cluster ONTAP e collegare le porte Ethernet di ciascun controller alla rete host.

.Fasi
. Utilizzare il cavo di interconnessione Cluster/ha per collegare le porte da E1a a E1a e le porte da e7a a e7a.
+

NOTE: Il traffico di cluster Interconnect e quello di ha condividono le stesse porte fisiche.

+
.. Collegare la porta E1a del controller A alla porta E1a del controller B.
.. Collegare la porta e7a del controller A alla porta E1a del controller B.
+
*Cavi di interconnessione cluster/ha*

+
image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[Cavo ha del cluster]



+
image::../media/drw_70-90_tnsc_cluster_cabling_ieops-1653.svg[Schema di cablaggio del cluster senza switch a due nodi]

. Collegare le porte del modulo Ethernet alla rete host.
+
Di seguito sono riportati alcuni esempi tipici di cablaggio della rete host. Per informazioni sulla configurazione specifica del sistema, vedere link:https://hwu.netapp.com["NetApp Hardware Universe"^] .

+
.. Collegare le porte e9a e e9b allo switch di rete dati Ethernet, come illustrato.
+

NOTE: Per ottenere le massime performance di sistema per il traffico cluster e ha, si consiglia di non utilizzare le porte e1b e e7b per le connessioni di rete host. Utilizzare una scheda host separata per ottimizzare le prestazioni.

+
*Cavo 100 GbE*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100GB cavo Ethernet]

+
image::../media/drw_70-90_network_cabling1_ieops-1654.svg[Cavo alla rete Ethernet da 100 GB]

.. Collegare gli switch di rete host 10/25 GbE.
+
*4 porte, 10/25 GbE host*

+
image::../media/oie_cable_sfp_gbe_copper.svg[Cavo da 10/25 GB]

+
image::../media/drw_70-90_network_cabling2_ieops-1655.svg[Cavo alla rete Ethernet 100GB]



. Utilizzare i cavi RJ-45 1000BASE-T per collegare le porte di gestione del controller (chiave inglese) agli switch della rete di gestione.
+
image::../media/oie_cable_rj45.svg[RJ45 cavi]

+
*CAVI RJ-45 1000BASE-T.

+
image::../media/drw_70-90_management_connection_ieops-1656.svg[Connettersi alla rete di gestione]




IMPORTANT: Non collegare ancora i cavi di alimentazione.

--
====


== Fase 2: Connettere gli storage controller agli shelf di storage

Le seguenti procedure di cablaggio mostrano come collegare i controller a uno shelf e a due shelf. Puoi connettere direttamente fino a quattro shelf ai tuoi controller.

[role="tabbed-block"]
====
.Sistema ASA A1K
--
Scegliere una delle seguenti opzioni di cablaggio che corrisponda alla propria configurazione.

.Opzione 1: Cavo i controller a uno shelf storage NS224
[%collapsible]
=====
Collegare ciascun controller ai moduli NSM sullo shelf NS224. La grafica mostra il cablaggio di ciascuno dei controller: Il cablaggio del controller A è mostrato in blu e il cablaggio del controller B è mostrato in giallo.

.Fasi
. Sul controller A, collegare le seguenti porte:
+
.. Collegare la porta e11a alla porta NSM A e0a.
.. Collegare la porta e11b alla porta NSM B e0b.
+
image:../media/drw_a1k_1shelf_cabling_a_ieops-1703.svg["Controller A e11a e e11b su un singolo shelf NS224"]



. Sul controller B, collegare le seguenti porte:
+
.. Collegare la porta e11a alla porta NSM B e0a.
.. Collegare la porta e11b alla porta NSM A e0b.
+
image:../media/drw_a1k_1shelf_cabling_b_ieops-1704.svg["Collegare le porte B del controller e11a e e11b a un singolo shelf NS224"]





=====
.Opzione 2: Cavo dei controller a due shelf storage NS224
[%collapsible]
=====
Collegare ciascun controller ai moduli NSM su entrambi gli shelf NS224. La grafica mostra il cablaggio di ciascuno dei controller: Il cablaggio del controller A è mostrato in blu e il cablaggio del controller B è mostrato in giallo.

.Fasi
. Sul controller A, collegare le seguenti porte:
+
.. Collegare la porta e11a alla porta e0a NSM A dello shelf 1.
.. Collegare la porta e11b alla porta NSM B e0b dello shelf 2.
.. Collegare la porta E10A alla porta e0a NSM A dello shelf 2.
.. Collegare la porta e10b alla porta e0b NSM A dello shelf 1.
+
image:../media/drw_a1k_2shelf_cabling_a_ieops-1705.svg["Connessioni da controller a shelf per il controller A"]



. Sul controller B, collegare le seguenti porte:
+
.. Collegare la porta e11a alla porta NSM B e0a dello shelf 1.
.. Collegare la porta e11b alla porta e0b NSM A dello shelf 2.
.. Collegare la porta E10A alla porta NSM B e0a dello shelf 2.
.. Collegare la porta e10b alla porta e0b NSM A dello shelf 1.
+
image:../media/drw_a1k_2shelf_cabling_b_ieops-1706.svg["Connessioni da controller a shelf per il controller B"]





=====
--
.Sistemi ASA A70 e A90
--
Scegliere una delle seguenti opzioni di cablaggio che corrisponda alla propria configurazione.

.Opzione 1: Connessione dei controller a uno shelf storage NS224
[%collapsible]
=====
Collegare ciascun controller ai moduli NSM sullo shelf NS224. La grafica mostra il cablaggio di ciascuno dei controller: Il cablaggio del controller A è mostrato in blu e il cablaggio del controller B è mostrato in giallo.

*Cavi in rame 100 GbE QSFP28*

image::../media/oie_cable100_gbe_qsfp28.svg[Cavo in rame da 100 GbE QSFP28]

.Fasi
. Collegare la porta e11a del controller A alla porta NSM A e0a.
. Collegare la porta e11b del controller A alla porta NSM B e0b.
+
image:../media/drw_a70-90_1shelf_cabling_a_ieops-1731.svg["Controller A e11a e e11b su un singolo shelf NS224"]

. Collegare la porta e11a del controller B alla porta NSM B e0a.
. Collegare la porta e11b del controller B alla porta NSM A e0b.
+
image:../media/drw_a70-90_1shelf_cabling_b_ieops-1732.svg["Controller B e11a e e11b su un singolo shelf NS224"]



=====
.Opzione 2: Connettere i controller a due shelf storage NS224
[%collapsible]
=====
Collegare ciascun controller ai moduli NSM su entrambi gli shelf NS224. La grafica mostra il cablaggio di ciascuno dei controller: Il cablaggio del controller A è mostrato in blu e il cablaggio del controller B è mostrato in giallo.

*Cavi in rame 100 GbE QSFP28*

image::../media/oie_cable100_gbe_qsfp28.svg[Cavo in rame da 100 GbE QSFP28]

.Fasi
. Sul controller A, collegare le seguenti porte:
+
.. Collegare la porta e11a allo shelf 1, la porta NSM A e0a.
.. Collegare la porta e11b allo shelf 2, la porta NSM B e0b.
.. Collegare la porta E8a allo shelf 2, la porta NSM A e0a.
.. Collegare la porta e8b allo shelf 1, la porta NSM B e0b.
+
image:../media/drw_a70-90_2shelf_cabling_a_ieops-1733.svg["Connessioni da controller a shelf per il controller A"]



. Sul controller B, collegare le seguenti porte:
+
.. Collegare la porta e11a allo shelf 1, la porta NSM B e0a.
.. Collegare la porta e11b allo shelf 2, la porta NSM A e0b.
.. Collegare la porta E8a allo shelf 2, la porta NSM B e0a.
.. Collegare la porta e8b allo shelf 1, la porta NSM A e0b.
+
image:../media/drw_a70-90_2shelf_cabling_b_ieops-1734.svg["Connessioni da controller a shelf per il controller B"]





=====
--
====