= Attrezzatura necessaria per l'installazione
:allow-uri-read: 




== Attrezzatura necessaria per l'installazione

Per installare il sistema di storage sono necessari i seguenti strumenti e attrezzature.

* Accesso a un browser Web per configurare il sistema di archiviazione
* Cinturino da scariche elettrostatiche (ESD)
* Torcia
* Computer portatile o console con connessione USB/seriale
* Graffetta o penna a sfera con punta stretta per l'impostazione di NS224 ID scaffali
* Cacciavite Phillips n. 2




== Precauzioni per il sollevamento

I sistemi di storage e gli shelf di storage sono pesanti. Prestare attenzione durante il sollevamento e lo spostamento di questi elementi.



=== Pesi del sistema di archiviazione

Prendere le precauzioni necessarie durante lo spostamento o il sollevamento del sistema di stoccaggio.

[role="tabbed-block"]
====
.A1K
--
Un sistema di stoccaggio A1K può pesare fino a 28,5 kg (62,83 lb). Per sollevare l'impianto, utilizzare due persone o un sollevatore idraulico.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[Icona di avvertenza sollevamento AFF A1K]

--
.A70 e A90
--
Un sistema di storage A70 o A90 può pesare fino a 68,8 kg (151,68 libbre). Per sollevare l'impianto, utilizzare quattro persone o un sollevatore idraulico.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[Icona di attenzione peso AFF A90 e AFF A70]

--
====


=== Pesi dei ripiani

Un ripiano di stoccaggio NS224 può pesare fino a 30,29 kg (66,78 lb). Per sollevare il ripiano portaoggetti, utilizzare due persone o un sollevatore idraulico. Tenere tutti i componenti nel ripiano portaoggetti (anteriore e posteriore) per evitare di sbilanciare il peso del ripiano.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 attenzione al sollevamento]

.Informazioni correlate
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["Informazioni sulla sicurezza e avvisi normativi"^]

