= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Sistemi AFF
--
I modelli AFF A-Series e C-Series sono una solida piattaforma scale-out costruita per ambienti virtualizzati ed è implementabile come un sistema indipendente o un Tier dalle performance elevate in una configurazione NetApp ONTAP. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["Ulteriori informazioni sui sistemi AFF"].

.AFF A20, AFF A30, AFF A50
Disponibile a partire da ONTAP 9.16.1

.AFF C30, AFF C60
Disponibile a partire da ONTAP 9.16.1

.AFF A1K, AFF A70 e AFF A90
Disponibile a partire da ONTAP 9.15.1

.AFF A150
Disponibile a partire da ONTAP 9.13.1, ONTAP 9.12.1P1, ONTAP 9.11.1P8, ONTAP 9.10.1P12

.AFF A900
Disponibile a partire da ONTAP 9.10.1

.AFF A250 e AFF A800
Disponibile a partire da ONTAP 9,8

.AFF A400
Disponibile a partire da ONTAP 9,7

.AFF C250, AFF C400, AFF C800
Disponibile a partire da ONTAP 9.12.1P1, ONTAP 9.13.1 GA

--
.Sistemi ASA r2
--
I sistemi ASA R2 forniscono una soluzione hardware e software unificata che crea un'esperienza semplificata specifica delle esigenze dei clienti SAN. link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Ulteriori informazioni sui sistemi ASA R2"].

.ASA A1K, ASA A70, ASA A90
Disponibile a partire da ONTAP 9.16.0

--
.Sistemi ASA
--
I modelli ASA A-Series e C-Series offrono un'esperienza SAN semplificata e dedicata che fornisce una disponibilità continua dei dati per database Enterprise mission-critical e altri carichi di lavoro SAN utilizzando il protocollo FCP o iSCSI. link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["Ulteriori informazioni sui sistemi ASA"].

.ASA A150, ASA A250, ASA A400, ASA A900
Disponibile a partire da ONTAP 9.13.1

.ASA C250, C400, C800
Disponibile a partire da ONTAP 9.13.1P1

--
.Sistemi FAS
--
I sistemi FAS offrono uno storage secondario efficiente e sicuro, la soluzione definitiva per tiering, backup e disaster recovery. link:https:://www.netapp.com/data-storage/fas/["Scopri di più sui sistemi FAS"].

.FAS70 e FAS90
Disponibile a partire da ONTAP 9.15.1

.FAS9500
Disponibile a partire da ONTAP 9.11.1, ONTAP 9.10.1P3

.FAS8300 e FAS700
Disponibile a partire da ONTAP 9,7

.FAS2820
Disponibile a partire da ONTAP 9.13.1

.FAS2700
Disponibile a partire da ONTAP 9.13.1

--
====