= 
:allow-uri-read: 


Ripristinare la configurazione di External Key Manager dal menu di avvio ONATP.

.Prima di iniziare
Per ripristinare la configurazione del gestore chiavi esterno (EKM) sono necessarie le seguenti informazioni:

* Una copia del file /cfcard/kmip/servers.cfg da un altro nodo del cluster o le seguenti informazioni:
+
** L'indirizzo del server KMIP.
** Porta KMIP.
** Una copia del file /cfcard/kmip/certs/client.crt da un altro nodo cluster o dal certificato client.
** Una copia del file /cfcard/kmip/certs/client.key da un altro nodo del cluster o dalla chiave del client.
** Una copia del file /cfcard/kmip/certs/CA.pem da un altro nodo del cluster o dalle CA del server KMIP.




.Fasi
. Collegare il cavo della console al controller di destinazione.
. Selezionare l'opzione 11 dal menu di avvio di ONTAP.
+
.Mostra un esempio di menu di avvio
[%collapsible]
====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
====
. Quando richiesto, confermare di aver raccolto le informazioni richieste.
+
.Mostra prompt di esempio
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
====
+
.In alternativa, è possibile che vengano visualizzati questi messaggi
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
====
. Quando richiesto, immettere le informazioni relative al client e al server.
+
.Mostra prompt
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
====
+
.Mostra esempio
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
====
. Il processo di ripristino è stato completato.
+
.Mostra prompt di esempio
[%collapsible]
====
....


System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.

....
.. Selezionare l'opzione 1 dal menu di avvio per continuare l'avvio in ONTAP.
+
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....


====
. Ripristinare lo sconto automatico se è stato disattivato:
+
`storage failover modify -node local -auto-giveback true`

. Se AutoSupport è attivato, ripristinare la creazione automatica dei casi immettendo il seguente comando:
+
`system node autosupport invoke -node * -type all -message MAINT=END`


