= 
:allow-uri-read: 


In un sistema standalone, è necessario riassegnare manualmente i dischi all'ID di sistema del nuovo controller prima di riportare il sistema alle normali condizioni operative.

.A proposito di questa attività

NOTE: Questa procedura si applica solo ai sistemi che si trovano in una configurazione standalone.

.Fasi
. Se non lo si è già fatto, riavviare il nodo _replacement_, interrompere il processo di avvio premendo Ctrl-C, quindi selezionare l'opzione per l'avvio in modalità manutenzione dal menu visualizzato.
. È necessario immettere `Y` Quando viene richiesto di sostituire l'ID di sistema a causa di una mancata corrispondenza dell'ID di sistema.
. Visualizzare gli ID di sistema: `disk show -a`
. Prendere nota dell'ID di sistema precedente, visualizzato come parte della colonna del proprietario del disco.
+
L'esempio seguente mostra il vecchio ID di sistema 118073209:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118073209)  Pool0  J8XJE9LC       system-1  (118073209)
disk_name    system-1  (118073209)  Pool0  J8Y478RC       system-1  (118073209)
.
.
.

----
. Riassegnare la proprietà del disco utilizzando le informazioni sull'ID di sistema ottenute dal comando disk show: `disk reassign -s old system ID disk reassign -s 118073209`
. Verificare che i dischi siano stati assegnati correttamente: `disk show -a`
+
I dischi appartenenti al nodo sostitutivo dovrebbero mostrare il nuovo ID di sistema. L'esempio seguente mostra ora i dischi di proprietà del sistema 1, il nuovo ID di sistema, 118065481:

+
[listing]
----
*> disk show -a
Local System ID: 118065481

  DISK      OWNER                  POOL   SERIAL NUMBER  HOME
--------    -------------          -----  -------------  -------------
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
disk_name    system-1  (118065481)  Pool0  J8Y0TDZC       system-1  (118065481)
.
.
.

----
. Se il sistema di storage ha configurato Storage o Volume Encryption, è necessario ripristinare la funzionalità Storage o Volume Encryption utilizzando una delle seguenti procedure, a seconda che si utilizzi la gestione delle chiavi integrata o esterna:
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["Ripristinare le chiavi di crittografia integrate per la gestione delle chiavi"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["Ripristinare le chiavi di crittografia esterne per la gestione delle chiavi"^]


. Avviare il nodo: `boot_ontap`

