---
permalink: c190/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: Scopri come sostituire il supporto di avvio su un sistema AFF C190 e scopri i diversi metodi di sostituzione. Il sistema AFF C190 supporta solo procedure di ripristino manuale tramite supporti di avvio. Il ripristino automatico del supporto di avvio non è supportato. 
---
= Panoramica della sostituzione dei supporti di avvio - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri come sostituire il supporto di avvio su un sistema AFF C190 e scopri i diversi metodi di sostituzione. Il supporto di avvio memorizza i file immagine di avvio primari e secondari utilizzati dal sistema durante l'avvio. A seconda della configurazione della rete, è possibile eseguire una sostituzione non distruttiva (coppia HA connessa alla rete) o una sostituzione distruttiva (richiede due riavvii).

Il sistema AFF C190 supporta solo procedure di ripristino manuale tramite supporti di avvio. Il ripristino automatico del supporto di avvio non è supportato.

È necessario disporre di un'unità flash USB, formattata in FAT32, con la quantità di storage appropriata per contenere `image_xxx.tgz` file.

* I metodi senza interruzioni e senza interruzioni per la sostituzione di un supporto di avvio richiedono entrambi il ripristino del file system var:
+
** Per la sostituzione senza interruzioni, la coppia ha deve essere connessa a una rete per ripristinare il file system var.
** Per la sostituzione delle interruzioni, non è necessaria una connessione di rete per ripristinare il file system var, ma il processo richiede due riavvii.


* È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.
* È importante applicare i comandi descritti di seguito al controller corretto:
+
** Il controller _alterato_ è il controller su cui si esegue la manutenzione.
** Il controller _healthy_ è il partner ha del controller compromesso.



