---
permalink: c190/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff c190, replace the chassis 
summary: Il nuovo telaio dello stesso modello del telaio compromesso viene sostituito da un telaio non valido. 
---
= Controlla i requisiti per la sostituzione di uno chassis in un sistema AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire lo chassis nel tuo sistema AFF C190, verifica i requisiti per una sostituzione corretta. La procedura di sostituzione dello chassis richiede di spostare tutti i dischi, gli alimentatori e i moduli controller dallo chassis guasto a quello di ricambio ed è un'operazione che comporta interruzioni.

Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura si basa sul presupposto che si stiano spostando tutti i dischi e i moduli controller nel nuovo chassis e che lo chassis sia un nuovo componente di NetApp.
* Questa procedura ha un'interruzione. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

