---
permalink: a700/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, chassis replacement 
summary: Il nuovo telaio dello stesso modello del telaio compromesso viene sostituito da un telaio non valido. 
---
= Esamina i requisiti per la sostituzione di uno chassis in un sistema AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire lo chassis nel tuo sistema AFF A700, verifica i requisiti per una sostituzione corretta. La procedura di sostituzione dello chassis prevede lo spostamento di tutti i componenti dallo chassis guasto a quello di ricambio ed è un'operazione che comporta interruzioni.

Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura ha un'interruzione. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

