---
permalink: fas-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the boot media 
summary: Prima di sostituire il supporto di avvio nel sistema di archiviazione FAS70 o FAS90, accertarsi di soddisfare i requisiti necessari per una sostituzione corretta. 
---
= Requisiti per il ripristino automatico dei supporti di avvio - FAS70 e FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema di storage FAS70 o FAS90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma del corretto funzionamento delle porte del cluster sul controller danneggiato e la verifica dell'abilitazione di Onboard Key Manager (OKM) o External Key Manager (EKM).

Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .

Esaminare i seguenti requisiti.

* È necessario sostituire il supporto di avvio guasto con un supporto di avvio sostitutivo ricevuto da NetApp.
* Le porte del cluster vengono utilizzate per comunicare tra i due controller durante il processo di ripristino automatico dell'avvio. Assicurarsi che le porte del cluster sul controller danneggiato funzionino correttamente.
* Per OKM, è necessaria la passphrase dell'intero cluster e anche i dati di backup.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* Comprendere la terminologia del controller utilizzata in questa procedura:
+
** Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
** Il _controllore sano_ è il partner HA del controllore compromesso.




.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, si link:bootmedia-shutdown-bmr.html["spegnere il controller"].
