---
permalink: fas-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: fas70, fas90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: Verificare che le interfacce logiche LIF stiano segnalando alla loro porta home, eseguire un controllo dello stato del cluster e quindi restituire la parte guasta a NetApp per completare il passaggio finale della procedura di sostituzione del controller FAS70 o FAS90. 
---
= Completa la sostituzione del controller per un sistema FAS70 o FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per completare la sostituzione del controller per il tuo sistema FAS70 o FAS90, prima ripristina la configurazione di NetApp Storage Encryption (se necessario). Successivamente, conferma che le interfacce logiche (LIF) stiano riportando alle loro porte home ed esegui un controllo dello stato del cluster. Infine, restituisci la parte guasta a NetApp.



[[step-1-verify-lifs-and-check-cluster-health]]
== Fase 1: Verifica delle LIF e verifica dello stato del cluster

Prima di riportare in servizio il nodo sostitutivo, verifica che le interfacce logiche siano sulle porte home, verifica lo stato del cluster e ripristina il giveback automatico.

.Fasi
. Verificare che le interfacce logiche segnalino il proprio server di origine e le porte:
+
`network interface show -is-home false`

+
Se alcune interfacce logiche sono elencate come false, ripristinarle alle rispettive porte home:

+
`network interface revert -vserver * -lif *`

. Controlla lo stato del tuo cluster.  Vedi il https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Come eseguire un controllo dello stato del cluster con uno script in ONTAP"^] Articolo della Knowledge Base.
. Se il giveback automatico è stato disattivato, riabilitarlo:
+
`storage failover modify -node local -auto-giveback true`





[[step-2-return-the-failed-part-to-netapp]]
== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
