---
permalink: fas-70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas70, fas90, how to recable the system, how to reassign disks 
summary: Ripristina il controllo delle risorse di storage sul controller sostitutivo, in modo che il sistema FAS70 o FAS90 possa riprendere il normale funzionamento. 
---
= Restituisci il controller nel tuo sistema FAS70 o FAS90 per riprendere le normali operazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ripristina il controllo delle risorse di storage sul controller sostitutivo, in modo che il sistema FAS70 o FAS90 possa riprendere il normale funzionamento. La procedura di restituzione varia in base al tipo di crittografia utilizzato dal sistema: nessuna crittografia o crittografia Onboard Key Manager (OKM).

[role="tabbed-block"]
====
.Nessuna crittografia o gestore di chiavi esterno (EKM)
--
Riportare il controller danneggiato al normale funzionamento restituendo il relativo spazio di archiviazione.

.Fasi
. Dal prompt DI Loader, immettere `boot_ontap`.
. Premere <enter> quando i messaggi della console si interrompono.
+
** Se viene visualizzato il prompt _login_, andare al passo successivo alla fine di questa sezione.
** Se viene visualizzato _Waiting for giveback_, premere il tasto <enter>, accedere al nodo partner, quindi passare alla fase successiva alla fine di questa sezione.


. Riportare la centralina guasta al normale funzionamento restituendo la memoria: `storage failover giveback -ofnode _impaired_node_name_`
. Se lo sconto automatico è stato disattivato, riattivarlo: `storage failover modify -node local -auto-giveback _true_`
. Se AutoSupport è attivato, ripristinare/riattivare la creazione automatica dei casi: `system node autosupport invoke -node * -type all -message MAINT=END`


--
.Crittografia integrata (OKM)
--
Ripristinare e sigillare le chiavi di crittografia integrate per OKM e riportare il controller al normale funzionamento.

.Prima di iniziare
Prima di iniziare, rivedi  https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"]o contatta il supporto NetApp.

.Fasi
. Avviare il menu ONTAP dal prompt di Loader `boot_ontap menu` e selezionare l'opzione 10.
. Visualizza le informazioni di backup della gestione delle chiavi per il cluster.
+
.. Esegui il seguente comando per visualizzare le informazioni di backup della gestione delle chiavi per il cluster:
+
`security key-manager onboard show-backup`

.. Esegui il seguente comando per verificare il backup del key manager integrato:
+
`security key-manager onboard verify-backup`



. Inserisci la passphrase OKM e conferma l'avvenuta verifica.
+

NOTE: La passphrase viene richiesta due volte.

. Immettere i dati della chiave di backup quando richiesto.
. Nel menu di avvio, inserire l'opzione `1` per l'avvio normale.
. Premere <enter> quando viene visualizzato _Waiting for giveback_.
. Spostare il cavo della console sul nodo partner e accedere come `admin`.
. Fornire solo gli aggregati CFO (l'aggregato root): `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** In caso di errori, contattare https://support.netapp.com["Supporto NetApp"].


. Attendere 5 minuti dopo il completamento del report di sconto e controllare lo stato di failover e di sconto: `storage failover show` E `storage failover show-giveback`.
. Sincronizzare e verificare lo stato dei tasti:
+
.. Riportare il cavo della console nella centralina sostitutiva.
.. Sincronizza chiavi mancanti: `security key-manager onboard sync`
+

NOTE: Viene richiesta la passphrase a livello di cluster di OKM per il cluster.

.. Verificare lo stato delle chiavi: `security key-manager key query -restored false`
+
L'output non dovrebbe mostrare alcun risultato se la sincronizzazione è corretta.

+
Se l'output mostra i risultati (gli ID chiave delle chiavi che non sono presenti nella tabella delle chiavi interna del sistema), contattare https://support.netapp.com["Supporto NetApp"].



. Riportare la centralina guasta al normale funzionamento restituendo la memoria: `storage failover giveback -ofnode _impaired_node_name_`
. Se lo sconto automatico è stato disattivato, riattivarlo: `storage failover modify -node local -auto-giveback _true_`
+

NOTE: Non ignorare il veto sulla restituzione per chiavi mancanti. Contatta il Supporto NetApp.

. Se AutoSupport è attivato, ripristinare/riattivare la creazione automatica dei casi: `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.Quali sono le prossime novità?
Dopo aver ritrasferito la proprietà delle risorse di storage al controller sostitutivo, occorre seguire link:controller-replace-restore-system-rma.html["completare la sostituzione della centralina"] la procedura.
