---
permalink: fas-70-90/maintain-overview.html 
sidebar: sidebar 
keywords: fas70, fas90 maintenance, maintenance, repairing a1k, repairing fas70, fas90, replace fas70, fas90 components, replace fas70, fas90 components 
summary: 'Conserva l"hardware del tuo sistema storage FAS70 o FAS90 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.' 
---
= Panoramica delle procedure di manutenzione - FAS70 e FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conserva l'hardware del tuo sistema storage FAS70 o FAS90 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.

Le procedure di manutenzione presuppongono che il sistema di archiviazione FAS70 o FAS90 sia già stato distribuito come nodo di archiviazione nell'ambiente ONTAP .



== Componenti del sistema

Per i sistemi di archiviazione FAS70 e FAS90, è possibile eseguire le procedure di manutenzione sui seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Supporto di avvio - ripristino automatico"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio.  Durante il ripristino automatico, il sistema recupera l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione di menu di avvio appropriata per installare l'immagine sul supporto di avvio sostitutivo. Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .



 a| 
link:bootmedia-replace-workflow.html["Supporto di avvio - ripristino manuale"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per avviare l'immagine da un'unità USB e ripristinare la configurazione dal nodo partner



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla le unità ed esegue il software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un modulo DIMM (Dual in-line Memory Module) è un tipo di memoria per computer. Vengono installati per aggiungere memoria di sistema a una scheda madre del controller.



 a| 
link:fan-replace.html["Ventola"]
 a| 
Una ventola raffredda la centralina.



 a| 
link:caching-module-hot-swap.html["Flash cache"]
 a| 
Flash cache accelera l'accesso ai dati attraverso il caching intelligente in tempo reale dei dati utente recentemente letti e dei metadati NetApp. È efficace per i carichi di lavoro a lettura intensiva, inclusi database, e-mail e file service.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
La NVRAM (non-volatile Random Access Memory) è un modulo che consente al controller di proteggere e salvare i dati in-flight in caso di interruzione dell'alimentazione del sistema. L'ID di sistema risiede nel modulo NVRAM. Una volta sostituito, il controller presuppone il nuovo ID di sistema dal modulo NVRAM sostitutivo.



 a| 
link:nvdimm-battery-replace.html["Batteria NV"]
 a| 
La batteria NV è responsabile dell'alimentazione al modulo NVRAM mentre i dati in-flight vengono trasferiti alla memoria flash dopo un'interruzione dell'alimentazione.



 a| 
link:io-module-overview.html["Modulo i/O."]
 a| 
Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



 a| 
link:power-supply-replace.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc-battery-replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria dell'orologio in tempo reale conserva le informazioni relative alla data e all'ora del sistema se l'alimentazione è spenta.



 a| 
link:system-management-replace.html["Modulo di gestione del sistema"]
 a| 
Il modulo di gestione del sistema fornisce l'interfaccia tra il controller e una console o un computer portatile per scopi di manutenzione del controller o del sistema. Il modulo di gestione del sistema contiene il supporto di avvio e memorizza il numero di serie del sistema (SSN).

|===