---
permalink: asa900/bootmedia_recovery_image.html 
sidebar: sidebar 
keywords:  
summary: 'La procedura per avviare il controller compromesso dall"immagine di ripristino dipende dalla configurazione MetroCluster a due nodi del sistema.' 
---
= Avviare l'immagine di ripristino - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario avviare l'immagine ONTAP dall'unità USB, ripristinare il file system e verificare le variabili ambientali.

. Dal prompt DEL CARICATORE, avviare l'immagine di ripristino dall'unità flash USB: `boot_recovery`
+
L'immagine viene scaricata dall'unità flash USB.

. Quando richiesto, inserire il nome dell'immagine o accettare l'immagine predefinita visualizzata tra parentesi sullo schermo.
. Ripristinare il file system var:
+
[cols="1,2"]
|===
| Se il sistema dispone di... | Quindi... 


 a| 
Una connessione di rete
 a| 
.. Premere `y` quando viene richiesto di ripristinare la configurazione di backup.
.. Premere `y` quando viene richiesto di sovrascrivere `/etc/ssh/ssh_host_ecdsa_key`.
.. Premere `y` quando viene richiesto di confermare se il backup di ripristino è stato eseguito correttamente.
.. Premere `Y` quando viene richiesto di ripristinare la copia della configurazione.
.. Impostare il controller compromesso sul livello di privilegio avanzato: `set -privilege advanced`
.. Eseguire il comando di ripristino del backup: `system node restore-backup -node local -target-address impaired_node_IP_address`
.. Riportare il controller compromesso al livello di amministrazione: `set -privilege admin`
.. Premere `y` quando viene richiesto di utilizzare la configurazione ripristinata.
.. Premere `y` quando viene richiesto di riavviare il controller compromesso.




 a| 
Nessuna connessione di rete
 a| 
.. Premere `n` quando viene richiesto di ripristinare la configurazione di backup.
.. Riavviare il sistema quando richiesto dal sistema.
.. Selezionare l'opzione *Update flash from backup config* (Sync flash) dal menu visualizzato.
+
Se viene richiesto di continuare con l'aggiornamento, premere `y`.





 a| 
Nessuna connessione di rete e si trova in una configurazione MetroCluster IP
 a| 
.. Premere `n` quando viene richiesto di ripristinare la configurazione di backup.
.. Riavviare il sistema quando richiesto dal sistema.
.. Attendere che le connessioni dello storage iSCSI si connettano.
+
È possibile procedere dopo aver visualizzato i seguenti messaggi:

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Selezionare l'opzione *Update flash from backup config* (Sync flash) dal menu visualizzato.
+
Se viene richiesto di continuare con l'aggiornamento, premere `y`.



|===
. Assicurarsi che le variabili ambientali siano impostate come previsto:
+
.. Portare la centralina danneggiata al prompt DEL CARICATORE.
.. Controllare le impostazioni delle variabili di ambiente con il comando printenv.
.. Se una variabile di ambiente non è impostata come previsto, modificarla con il comando setenventment_variable_name changed_value.
.. Salvare le modifiche utilizzando il comando saveenv.


. Il successivo dipende dalla configurazione del sistema:
+
** Se il sistema dispone di onboard keymanager, NSE o NVE configurati, visitare il sito xref:bootmedia_encryption_restore.adoc[Fasi di sostituzione dei supporti post-boot per OKM, NSE e NVE]
** Se il sistema non dispone di onboard keymanager, NSE o NVE configurati, completare la procedura descritta in questa sezione.


. Dal prompt DEL CARICATORE, immettere il comando boot_ontap.
+
[cols="1,2"]
|===
| Se viene visualizzato... | Quindi... 


 a| 
Prompt di login
 a| 
Passare alla fase successiva.



 a| 
In attesa di un giveback...
 a| 
.. Accedere al controller partner.
.. Verificare che il destinatario sia pronto per il giveback con `storage failover show` comando.


|===
. Collegare il cavo della console al controller partner.
. Restituire il controller utilizzando il comando giveback -fromnode local di failover dello storage.
. Al prompt del cluster, controllare le interfacce logiche con il comando net int -is-home false.
+
Se le interfacce sono elencate come "false", ripristinarle nella porta home utilizzando il comando net int revert.

. Spostare il cavo della console sul dispositivo riparato spegnere o sostituire il controller con problemi utilizzando la procedura appropriata per la configurazione. Ed eseguire il comando version -v per controllare le versioni di ONTAP.
. Ripristinare il giveback automatico se è stato disattivato utilizzando il comando storage failover modify -node local -auto-giveback true.

