---
permalink: asa900/bootmedia_recovery_image.html 
sidebar: sidebar 
keywords:  
summary: 'La procedura per avviare il controller compromesso dall"immagine di ripristino dipende dalla configurazione MetroCluster a due nodi del sistema.' 
---
= Avviare l'immagine di ripristino - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario avviare l'immagine ONTAP dall'unità USB, ripristinare il file system e verificare le variabili ambientali.

. Dal prompt DEL CARICATORE, avviare l'immagine di ripristino dall'unità flash USB: `boot_recovery`
+
L'immagine viene scaricata dall'unità flash USB.

. Quando richiesto, inserire il nome dell'immagine o accettare l'immagine predefinita visualizzata tra parentesi sullo schermo.
. Ripristinare il file system var:
+
[cols="1,2"]
|===
| Se il sistema è in esecuzione... | Quindi... 


 a| 
ONTAP 9.16.0 o versioni precedenti
 a| 
.. Sul controller danneggiato, premere _Y_ quando viene visualizzato `Do you want to restore the backup configuration now?`
.. Sul controller danneggiato, premere _Y_ quando viene richiesto di sovrascrivere `/etc/ssh/ssh_host_ecdsa_key`.
.. Sul controller partner sano, impostare il controller con problemi sul livello di privilegi avanzato: `set -privilege admin`.
.. Sul controller partner integro, eseguire il comando di ripristino del backup: `system node restore-backup -node local -target-address impaired_node_IP_address`.
+
*NOTA:* se viene visualizzato un messaggio diverso da un ripristino riuscito, contattare https://support.netapp.com["Supporto NetApp"].

.. Sul controller partner sano, riportare il controller danneggiato al livello di amministratore: `set -privilege admin`.
.. Sul controller danneggiato, premere _y_ quando viene visualizzato `Was the restore backup procedure successful?`.
.. Sul controller danneggiato, premere _y_ quando viene visualizzato `...would you like to use this restored copy now?`.
.. Sul controller danneggiato, premere _y_ quando viene richiesto di riavviare il controller danneggiato e premere _ctrl-c_ per il menu di avvio.
.. Se il sistema non utilizza la crittografia, selezionare _opzione 1 Avvio normale._, altrimenti andare a link:bootmedia_encryption_restore.html["Ripristinare i gestori delle chiavi"].
.. Collegare il cavo della console al controller partner.
.. Restituire il controller utilizzando il comando _storage failover giveback -fromnode local_.
.. Ripristinare il giveback automatico se è stato disattivato utilizzando il comando _storage failover modify -node local -auto-giveback true_.
.. Se AutoSupport è abilitato, ripristinare/riattivare la creazione automatica dei casi utilizzando il comando _system node AutoSupport Invoke -node * -type all -message MAINT=END_.
+
*NOTA:* se il processo non riesce, contattare https://support.netapp.com["Supporto NetApp"].



|===

