---
permalink: asa900/install_videos.html 
sidebar: sidebar 
keywords: ASA A900 
summary: 'Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.' 
---
= Video fasi - ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.



== Video uno di due: Installazione hardware e cablaggio

Il seguente video mostra come installare e collegare il nuovo sistema.

.Animazione - istruzioni per l'installazione e la configurazione di AFF A900
video::4c222e90-864b-4435-9405-adf200112f3e[panopto]

NOTE: Il sistema ASA A900 utilizza la stessa procedura di installazione del sistema AFF A900.



== Video due di due: Esecuzione della configurazione software end-to-end

Il seguente video mostra la configurazione software end-to-end per i sistemi che eseguono ONTAP 9.2 e versioni successive.

video::WAE0afWhj1c?[youtube]