---
permalink: asa900/maintain-overview.html 
sidebar: sidebar 
keywords: asa A900 maintenance, maintenance, repairing asa A900, repairing asa A900, replace asa A900 components, replace asa A900 components 
summary: 'Manutenzione dell"hardware ASA A900' 
---
= Manutenzione dell'hardware ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema storage ASA A900, è possibile eseguire le procedure di manutenzione dei seguenti componenti.



== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



== DCPM

Il DCPM (destage controller power module) contiene la batteria NVRAM11.



== Ventola

La ventola raffredda il controller.



== Modulo i/O.

Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



== USB LED

Il modulo LED USB fornisce connettività alle porte della console e allo stato del sistema.



== NVRAM

 The NVRAM module (Non-Volatile Random Access Memory) allows the controller to retain data across power cycles or system reboots.


== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
