---
permalink: asa900/maintain-overview.html 
sidebar: sidebar 
keywords: asa A900 maintenance, maintenance, repairing asa A900, repairing asa A900, replace asa A900 components, replace asa A900 components 
summary: 'Manutenzione dell"hardware ASA A900' 
---
= Manutenzione dell'hardware ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantieni l'hardware del tuo sistema di archiviazione ASA A900 per garantire affidabilità a lungo termine e prestazioni ottimali. Eseguite regolarmente attività di manutenzione, come la sostituzione di componenti difettosi, per prevenire tempi di inattività e perdite di dati.

Le procedure di manutenzione presuppongono che il sistema di archiviazione ASA A900 sia già stato distribuito come nodo di archiviazione nell'ambiente ONTAP .



== Componenti del sistema

Per il sistema storage ASA A900, è possibile eseguire le procedure di manutenzione dei seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Supporto di avvio - ripristino automatico"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio.  Durante il ripristino automatico, il sistema recupera l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione di menu di avvio appropriata per installare l'immagine sul supporto di avvio sostitutivo. Il processo di ripristino automatico del supporto di avvio è supportato solo in ONTAP 9.17.1 e versioni successive. Se il sistema di storage esegue una versione precedente di ONTAP, utilizzare link:bootmedia-replace-workflow.html["procedura di ripristino manuale dell'avvio"] .



 a| 
link:bootmedia-replace-workflow.html["Supporto di avvio - ripristino manuale"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio. Durante il ripristino manuale, si avvia il sistema di archiviazione da un'unità USB e si ripristina manualmente l'immagine e la configurazione del file system.  Se il sistema di archiviazione esegue ONTAP 9.17.1 e versioni successive, utilizzarelink:bootmedia-replace-workflow-bmr.html["procedura di ripristino automatico dell'avvio"] .



 a| 
link:chassis_replace_overview.html["Chassis"]
 a| 
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



 a| 
link:controller_replace_overview.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



 a| 
link:dimm_replace.html["DIMM"]
 a| 
È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



 a| 
link:dcpm-nvram11-battery-replace.html["DCPM"]
 a| 
Il DCPM (destage controller power module) contiene la batteria NVRAM11.



 a| 
link:fan_swap_out.html["Ventola"]
 a| 
La ventola raffredda il controller.



 a| 
link:pci_cards_and_risers_replace.html["Modulo i/O."]
 a| 
Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



 a| 
link:led_module_replace.html["USB LED"]
 a| 
Il modulo LED USB fornisce connettività alle porte della console e allo stato del sistema.



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
Il modulo NVRAM (Non-Volatile Random Access Memory) consente al controller di conservare i dati durante i cicli di accensione e spegnimento o i riavvii del sistema, mentre il modulo NVRAM DIMM mantiene le impostazioni NVRAM .



 a| 
link:power_supply_swap_out.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc_battery_replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.

|===