---
permalink: a150/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a150, a150, aff, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: È necessario verificare lo stato ha dello chassis ed eseguire la diagnostica a livello di sistema, eseguire gli aggregati di back-switch e restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. 
---
= Ripristinare e verificare la configurazione - AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario verificare lo stato ha dello chassis ed eseguire la diagnostica a livello di sistema, eseguire gli aggregati di back-switch e restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit.



== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _HA-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mccip`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.
. Il passaggio successivo dipende dalla configurazione del sistema.
+
[cols="1,2"]
|===
| Se il sistema è in... | Quindi... 


 a| 
Una configurazione standalone
 a| 
.. Uscire dalla modalità di manutenzione: `halt`
.. Passare a. link:chassis_replace.html[""Completamento del processo di sostituzione"].




 a| 
Una coppia ha con un secondo modulo controller
 a| 
Uscire dalla modalità di manutenzione: `halt` Viene visualizzato il prompt DEL CARICATORE.

|===




== Fase 2: Eseguire la diagnostica a livello di sistema

Dopo aver installato un nuovo chassis, eseguire la diagnostica di interconnessione.

Per avviare la diagnostica a livello di sistema, il sistema deve essere al prompt DEL CARICATORE.

Tutti i comandi delle procedure diagnostiche vengono emessi dalla centralina in cui viene sostituito il componente.

. Se il controller da sottoporre a manutenzione non viene visualizzato al prompt DEL CARICATORE, attenersi alla seguente procedura:
+
.. Selezionare l'opzione Maintenance mode (modalità manutenzione) dal menu visualizzato.
.. Una volta avviato il controller in modalità di manutenzione, arrestare il controller: `halt`
+
Dopo aver eseguito il comando, attendere che il sistema si arresti al prompt DEL CARICATORE.

+

NOTE: Durante il processo di avvio, è possibile rispondere in modo sicuro `y` a prompt:



. Ripetere il passaggio precedente sul secondo controller se si è in una configurazione ha.
+

NOTE: Per eseguire il test di interconnessione, entrambi i controller devono essere in modalità di manutenzione.

. Al prompt DEL CARICATORE, accedere ai driver speciali progettati appositamente per la diagnostica a livello di sistema per funzionare correttamente: `boot_diags`
+
Durante il processo di avvio, è possibile rispondere in modo sicuro `y` Fino a visualizzare il prompt della modalità di manutenzione (*>).

. Attivare i test di diagnostica di interconnessione dal prompt della modalità di manutenzione: `sldiag device modify -dev interconnect -sel enable`
+
I test di interconnessione sono disattivati per impostazione predefinita e devono essere attivati per essere eseguiti separatamente.

. Eseguire il test di diagnostica di interconnessione dal prompt della modalità di manutenzione: `sldiag device run -dev interconnect`
+
È sufficiente eseguire il test di interconnessione da un solo controller.

. Verificare che non vi siano problemi hardware dovuti alla sostituzione dello chassis: `sldiag device status -dev interconnect -long -state failed`
+
La diagnostica a livello di sistema riporta al prompt se non ci sono errori di test o elenca lo stato completo degli errori risultanti dal test del componente.

. Procedere in base al risultato del passaggio precedente.
+
[cols="1,2"]
|===
| Se il test di diagnostica a livello di sistema... | Quindi... 


 a| 
Sono stati completati senza guasti
 a| 
.. Cancellare i registri di stato: `sldiag device clearstatus`
.. Verificare che il registro sia stato cancellato: `sldiag device status`
+
Viene visualizzata la seguente risposta predefinita:

+
[listing]
----
SLDIAG: No log messages are present.
----
.. Uscire dalla modalità di manutenzione su entrambi i controller: `halt`
+
Il sistema visualizza il prompt DEL CARICATORE.

+

NOTE: Prima di procedere, uscire dalla modalità di manutenzione su entrambi i controller.

.. Immettere il seguente comando su entrambi i controller al prompt DEL CARICATORE: `bye`
.. Riportare il controller al funzionamento normale:


|===
+
[cols="1,2"]
|===
| Se sul sistema è in esecuzione ONTAP... | Quindi... 


 a| 
Con due nodi nel cluster
 a| 
Eseguire questi comandi: `node::> cluster ha modify -configured true``node::> storage failover modify -node node0 -enabled true`



 a| 
Con più di due nodi nel cluster
 a| 
Eseguire questo comando:``node::> storage failover modify -node node0 -enabled true``



 a| 
In una configurazione MetroCluster a due nodi
 a| 
Passare alla fase successiva. La procedura di switchback MetroCluster viene eseguita nell'attività successiva del processo di sostituzione.



 a| 
In una configurazione standalone
 a| 
Non hai ulteriori passaggi in questa specifica attività.

La diagnostica a livello di sistema è stata completata.



 a| 
Ha causato alcuni errori di test
 a| 
Determinare la causa del problema.

.. Uscire dalla modalità di manutenzione: `halt`
.. Eseguire un arresto pulito, quindi scollegare gli alimentatori.
.. Verificare di aver osservato tutte le considerazioni identificate per l'esecuzione della diagnostica a livello di sistema, che i cavi siano collegati saldamente e che i componenti hardware siano installati correttamente nel sistema di storage.
.. Ricollegare gli alimentatori, quindi accendere il sistema storage.
.. Eseguire nuovamente il test di diagnostica a livello di sistema.


|===




== Fase 3: Switch back aggregates in una configurazione MetroCluster a due nodi

Una volta completata la sostituzione dell'unità FRU in una configurazione MetroCluster a due nodi, è possibile eseguire l'operazione di switchback dell'unità MetroCluster. In questo modo, la configurazione torna al suo normale stato operativo, con le macchine virtuali dello storage di origine sincronizzata (SVM) sul sito precedentemente compromesso ora attive e che forniscono i dati dai pool di dischi locali.

Questa attività si applica solo alle configurazioni MetroCluster a due nodi.

.Fasi
. Verificare che tutti i nodi si trovino in `enabled` stato: `metrocluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. Verificare che la risincronizzazione sia completa su tutte le SVM: `metrocluster vserver show`
. Verificare che tutte le migrazioni LIF automatiche eseguite dalle operazioni di riparazione siano state completate correttamente: `metrocluster check lif show`
. Eseguire lo switchback utilizzando `metrocluster switchback` comando da qualsiasi nodo del cluster esistente.
. Verificare che l'operazione di switchback sia stata completata: `metrocluster show`
+
L'operazione di switchback è ancora in esecuzione quando un cluster si trova in `waiting-for-switchback` stato:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
L'operazione di switchback è completa quando i cluster si trovano in `normal` stato:

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
Se il completamento di uno switchback richiede molto tempo, è possibile verificare lo stato delle linee di base in corso utilizzando `metrocluster config-replication resync-status show` comando.

. Ripristinare le configurazioni SnapMirror o SnapVault.




== Fase 4: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma["Parti restituita  sostituzioni"] per ulteriori informazioni.
