---
permalink: a150/maintain-overview.html 
sidebar: sidebar 
keywords: aff A150 maintenance, maintenance, repairing a150, repairing aff a150, replace aff a150 components, replace aff a150 components 
summary: 'Mantieni l"hardware AFF A150' 
---
= Scopri come effettuare la manutenzione di un sistema storage AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantieni l'hardware del tuo sistema storage AFF A150 per garantire affidabilità a lungo termine e prestazioni ottimali. Esegui regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, per aiutare a prevenire downtime e perdita di dati.



[[boot-media]]
== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



[[chassis]]
== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



[[controller]]
== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



[[dimm]]
== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



[[drive]]
== Disco

Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



[[nvram-battery]]
== Batteria NVRAM

Una batteria è inclusa in un controller e conserva i dati memorizzati nella cache in caso di interruzione dell'alimentazione CA.



[[power-supply]]
== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



[[real-time-clock-battery]]
== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
