---
permalink: a150/overview.html 
sidebar: sidebar 
keywords: AFF A150 specifications, AFF A150 specs, NetApp AFF A150, AFF A150 hardware 
summary: Specifiche chiave per il sistema di archiviazione AFF A150 
---
= Specifiche chiave per AFF A150
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' AFF A150.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche AFF A150 .  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per AFF A150

Configurazione della piattaforma: coppia HA a telaio singolo AFF A150 UTA2

Capacità massima grezza: 0,5472 PB

Memoria: 64.0000 GB

Fattore di forma: chassis 2U con 2 controller HA e 24 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe:

Versione minima ONTAP : ONTAP 9.10.1P12



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS | 12 | 6,6 PB / 5,8 PiB | 768 GB 


| SAN | 6 | 3,3 PB / 2,9 PiB | 384 GB 


| Coppia HA |  | 0,5 PB / 0,5 PiB | 64,0000 
|===


=== Io



==== IO di bordo

|===


| Protocollo | porti 


| Ethernet 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== IO totale

|===


| Protocollo | porti 


| Ethernet 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 2 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2 
|===


=== Rete di archiviazione supportata

CIFS; FC; FCoE; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 1209 BTU/ora
* Potenza nel caso peggiore: 1676 BTU/ora
* Peso: 60,8 libbre 27,6 kg
* Altezza: 2U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 19,0" (24,1" con staffa di gestione dei cavi)
* Temperatura/altitudine/umidità di funzionamento: da 5°C a 45°C (da 41°F a 113°F) fino a 3048 m (10000 piedi) di altitudine; umidità relativa dall'8% al 90%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: potenza sonora dichiarata (LwAd): 6,9; pressione sonora (LpAm) (posizioni degli astanti): 51,0 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo; Gestione in banda SAS tramite connessioni SAS;
