---
permalink: asa-c400/overview.html 
sidebar: sidebar 
keywords: ASA C400 specifications, ASA C400 specs, NetApp ASA C400, ASA C400 hardware 
summary: Specifiche chiave per il gruppo di piattaforme ASA-C400 
---
= Specifiche chiave per ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione ASA C400 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche chiave per ASA C400

* Configurazione della piattaforma: coppia HA a chassis singolo ASA C400A, bundle Ethernet
* Capacità massima grezza: 2,9472 PB
* Memoria: 256.0000 GB
* Fattore di forma: chassis 4U con 2 controller HA
* Versione ONTAP : ONTAP: 9.16.1P2
* Slot di espansione PCIe: 10
* Versione minima ONTAP : ONTAP 9.13.1P1 == Massimi di scalabilità
* Tipo: NAS
* Tipo: SAN; Coppie HA: 6; Capacità grezza: 17,7 PB / 15,7 PiB; Memoria massima: 1536 GB
* Tipo: coppia HA; capacità grezza: 2,9 PB / 2,6 PiB; memoria massima: 256.0000




== I/O



=== I/O integrato

* Protocollo: Ethernet 100 Gbps; Porte: 4
* Protocollo: Ethernet 25 Gbps; Porte: 12




=== Totale I/O

* Protocollo: Ethernet 100 Gbps; Porte: 24
* Protocollo: Ethernet 25 Gbps; Porte: 28
* Protocollo: Ethernet 10 Gbps; Porte: 32
* Protocollo: FC 32 Gbps; Porte: 40
* Protocollo: NVMe/FC 32 Gbps; Porte: 40
* Porte: 0




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 12 Mbps; Porte: 4




== Rete di archiviazione supportata

* FC
* iSCSI
* NVMe/FC == Specifiche dell'ambiente di sistema
* Potenza tipica: 4209 BTU/ora
* Potenza nel caso peggiore: 5215 BTU/ora
* Peso: 110,0 libbre 49,9 kg
* Altezza: 4U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 32,6" (34,7" con staffa per la gestione dei cavi)
* Temperatura/altitudine/umidità di esercizio: da 10°C a 35°C (da 50°F a 95°F) a = 3048 m = 10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 8,5 Pressione sonora (LpAm) (posizioni degli astanti): 67,2 dB




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo
* Gestione in banda SAS su connessioni SAS

