---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, replace the boot media 
summary: Prima di sostituire il supporto di avvio nel sistema ASA A70 o A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. 
---
= Necessità di sostituire i supporti di avvio - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema ASA A70 o ASA A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. È necessario verificare di disporre dei supporti di avvio sostitutivi corretti, confermare l'assenza di porte cluster difettose sul controller e determinare se il gestore delle chiavi integrato (OKM) o il gestore delle chiavi esterno (EKM) sono abilitati.

Esaminare i seguenti requisiti.

* È necessario sostituire il supporto di avvio guasto con un supporto di avvio sostitutivo ricevuto da NetApp.
* Non devono essere presenti porte del quadro strumenti difettose sulla centralina guasta.
* Per OKM, è necessario il contenuto del file della passphrase OKM.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** file /cfcard/kmip/servers.cfg.
** file /cfcard/kmip/certs/client.crt.
** file /cfcard/kmip/certs/client.key.
** File /cfcard/kmip/certs/CA.pem.




.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, si link:bootmedia-shutdown-bmr.html["spegnere il controller"].
