---
permalink: asa-r2-70-90/bootmedia-replace-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, replace the boot media 
summary: È possibile individuare il supporto di avvio non riuscito rimuovendo il modulo di gestione del sistema prima di sostituire il supporto di avvio. 
---
= Sostituire i supporti di avvio - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sostituire il supporto di avvio, è necessario rimuovere il modulo di gestione del sistema dal retro del sistema, rimuovere il supporto di avvio danneggiato e installare il supporto di avvio sostitutivo nel modulo di gestione del sistema.

.Fasi
Il supporto di avvio si trova all'interno del modulo di gestione del sistema ed è accessibile rimuovendo il modulo dal sistema.

image::../media/drw_a70-90_boot_media_remove_replace_ieops-1367.svg[I supporti di avvio sostituiscono l'immagine]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[Numero di didascalia 1]
 a| 
Dispositivo di chiusura della camma del modulo di gestione del sistema



 a| 
image::../media/legend_icon_02.svg[Numero di didascalia 2]
 a| 
Pulsante di blocco dei supporti di avvio



 a| 
image::../media/legend_icon_03.svg[Numero di didascalia 3]
 a| 
Supporto di boot

|===
. Nella parte anteriore dello chassis, premere con decisione ciascun disco fino a quando non si avverte un arresto positivo. In questo modo, i dischi sono posizionati saldamente sulla scheda intermedia dello chassis.
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[Disco drw a800 installato IEOPS 960]

. Andare sul retro del telaio. Se non si è già collegati a terra, mettere a terra l'utente.
. Scollegare l'alimentazione al modulo controller estraendo il modulo controller di circa tre pollici:
+
.. Premere verso il basso entrambi i fermi di bloccaggio del modulo controller, quindi ruotare entrambi i fermi contemporaneamente verso il basso.
.. Estrarre il modulo controller di circa 3 pollici dal telaio per disinserire l'alimentazione.
.. Rimuovere tutti i cavi collegati al modulo di gestione del sistema. Assicurarsi di etichettare il punto in cui sono stati collegati i cavi, in modo da poterli collegare alle porte corrette quando si reinstalla il modulo.
.. Ruotare il vassoio di gestione dei cavi verso il basso tirando i pulsanti su entrambi i lati all'interno del vassoio di gestione dei cavi, quindi ruotare il vassoio verso il basso.
.. Premere il pulsante della camma di gestione del sistema. La leva della camma si allontana dal telaio.
.. Ruotare la leva della camma completamente verso il basso e rimuovere il modulo di gestione del sistema dal modulo controller.
.. Posizionare il modulo di gestione del sistema su un tappetino antistatico, in modo che il supporto di avvio sia accessibile.


. Rimuovere il supporto di avvio dal modulo di gestione:
+
.. Premere il pulsante di bloccaggio blu.
.. Ruotare il supporto di avvio verso l'alto, farlo scorrere fuori dallo zoccolo e metterlo da parte.


. Installare il supporto di avvio sostitutivo nel modulo di gestione del sistema:
+
.. Allineare i bordi del supporto di avvio con l'alloggiamento dello zoccolo, quindi spingerlo delicatamente a squadra nello zoccolo.
.. Ruotare il supporto di avvio verso il basso verso il pulsante di bloccaggio.
.. Premere il pulsante di bloccaggio, ruotare completamente il supporto di avvio e rilasciare il pulsante di bloccaggio.


. Reinstallare il modulo di gestione del sistema:
+
.. Ruotare il vassoio di gestione dei cavi verso l'alto fino alla posizione di chiusura.
.. Eseguire il richiamo del modulo Gestione del sistema.



