---
permalink: asa-r2-70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, prepare to replace the chassis 
summary: Prepararsi a sostituire lo chassis danneggiato del sistema ASA A70 o ASA A90 identificando lo chassis danneggiato, verificando i componenti di ricambio ed etichettando i cavi e i moduli del controller. 
---
= Preparazione alla sostituzione del telaio - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Preparatevi a sostituire lo chassis danneggiato nel vostro sistema ASA A70 o ASA A90 identificando lo chassis danneggiato, verificando i componenti sostitutivi ed etichettando i cavi e i moduli del controller.

.Fasi
. Collegare alla porta seriale della console per interfacciarsi con il sistema e monitorarlo.
. Accendere il LED di posizione del controller:
+
.. Utilizzare il `system controller location-led show` comando per visualizzare lo stato corrente del LED di posizione.
.. Accendere il LED di posizione:
+
`system controller location-led modify -node _node1_ -state on`

+
Il LED posizione rimane acceso per 30 minuti.



. Prima di aprire la confezione, esaminare l'etichetta sulla confezione e verificare quanto segue:
+
** Numero di parte del componente
** Descrizione della parte
** Quantità nella scatola


. Rimuovere il contenuto dalla confezione e conservare l'imballaggio per restituire il componente guasto a NetApp.
. Etichettare tutti i cavi collegati al sistema di archiviazione.  Ciò garantisce un corretto cablaggio più avanti nella procedura.
. Collegati alla terra se non lo sei già.


.Quali sono le prossime novità?
Dopo aver preparato la sostituzione del telaio ASA A70 o ASA A90,link:chassis-replace-shutdown.html["spegnere i controller"] .
