---
permalink: asa-r2-70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, prerequisite, replace the controller module 
summary: È necessario esaminare i prerequisiti per la procedura di sostituzione e selezionare quello corretto per la versione del sistema operativo ONTAP in uso. 
---
= Requisiti per sostituire la centralina - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il controller nel sistema ASA A70 o ASA A90, assicurarsi di soddisfare i requisiti necessari per una sostituzione corretta. Ad esempio disporre del controller sostitutivo corretto, di un backup della configurazione del sistema e dell'accesso agli strumenti e al firmware necessari.

Esaminare i requisiti per la sostituzione del modulo controller.

* Tutti gli shelf di dischi devono funzionare correttamente.
* Il controller integro deve essere in grado di assumere il controllo del controller da sostituire (indicato in questa procedura come "`controller alterato`").
* Non utilizzare questa procedura per gli upgrade dei controller, ma fare riferimento a https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Scegliere la procedura di aggiornamento dell'hardware del controller"] per le relative indicazioni.
* Se il sistema è in una configurazione MetroCluster, è necessario verificare se è https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["Scelta della procedura di ripristino corretta"] necessario utilizzare questa procedura.
* È necessario sostituire il componente guasto con l'unità FRU (Field-Replaceable Unit) ricevuta da NetApp.
* È necessario sostituire un modulo controller con un modulo controller dello stesso tipo di modello. Non è possibile aggiornare il sistema semplicemente sostituendo il modulo controller.
* Non è possibile modificare dischi o shelf di dischi come parte di questa procedura.
* Poiché il dispositivo di avvio si trova nel modulo di gestione del sistema installato sul retro del sistema, non è necessario spostare il dispositivo di avvio quando si sostituisce un modulo controller.
* È importante applicare i comandi descritti di seguito ai sistemi corretti:
+
** Il controller _alterato_ è il controller che viene sostituito.
** Il controller _replacement_ è il nuovo controller che sostituisce il controller compromesso.
** Il controller _healthy_ è il controller sopravvissuto.


* È sempre necessario acquisire l'output della console del controller in un file di registro di testo.
+
In questo modo è possibile registrare la procedura per risolvere eventuali problemi riscontrati durante il processo di sostituzione.


