---
permalink: asa-r2-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'Per ripristinare il funzionamento completo del sistema, devi verificare le LIF, controllare lo stato di salute del cluster e restituire la parte guasta a NetApp. Contattare il supporto tecnico al https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"]numero , 888-463-8277 (Nord America), 00-800-44-638277 (Europa) o +800-800-80-800 (Asia/Pacifico) se si necessita del numero RMA o di ulteriore assistenza per la procedura di sostituzione.' 
---
= Ripristino completo del sistema - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per ripristinare il funzionamento completo del sistema, devi verificare le LIF, controllare lo stato di salute del cluster e restituire la parte guasta a NetApp.



== Fase 1: Verifica delle LIF e verifica dello stato del cluster

Prima di riportare in servizio il nodo _replacement_, occorre verificare che le LIF si trovino nelle loro porte home, verificare lo stato del cluster e reimpostare il giveback automatico.

.Fasi
. Verificare che le interfacce logiche stiano segnalando al server principale e alle porte: `network interface show -is-home false`
+
Se alcuni LIF sono elencati come falsi, ripristinarli alle porte home: `network interface revert -vserver * -lif *`

. Controllare lo stato di salute del cluster. Per ulteriori informazioni, consultare l' https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["Come eseguire un controllo dello stato del cluster con uno script in ONTAP"^] articolo della KB.
. Se il giveback automatico è stato disattivato, riabilitarlo: `storage failover modify -node local -auto-giveback true`




== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
