---
permalink: asa-r2-70-90/io-module-overview.html 
sidebar: sidebar 
keywords: ASA A90,  ASA A70, replace io module 
summary: 'I sistemi ASA A70 e ASA A90 offrono la massima flessibilità nell"espansione o sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L"aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.' 
---
= Panoramica sull'aggiunta e la sostituzione di un modulo i/o - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi ASA A70 e ASA A90 offrono la massima flessibilità nell'espansione o sostituzione dei moduli i/o per migliorare la connettività e le prestazioni della rete. L'aggiunta o la sostituzione di un modulo i/o è essenziale quando si aggiornano le funzionalità di rete o si risolve un problema di un modulo.

È possibile sostituire un modulo i/o guasto nel sistema storage ASA A70 o ASA A90 con uno stesso tipo di modulo i/o o o con un altro tipo di modulo i/O. È inoltre possibile aggiungere un modulo i/o in un sistema con slot vuoti.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di moduli aggiuntivi può migliorare la ridondanza, contribuendo a garantire che il sistema rimanga operativo anche in caso di guasto di un modulo.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema allo stato operativo ottimale.



.Numerazione degli slot i/O.
Gli slot i/o sui controller ASA A70 e ASA A90 sono numerati da 1 a 11, come illustrato nella figura seguente.

image::../media/drw_a1K_back_slots_labeled_ieops-2162.svg[Numerazione degli slot sui controller ASA A70 e AFF A90]
