---
permalink: asa-r2-70-90/io-module-replace.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, replace a pcie card 
summary: Per sostituire una scheda PCIe, scollegare i cavi dalle schede, rimuovere i moduli SFP e QSFP dalle schede prima di rimuovere il riser, reinstallare il riser, quindi reinstallare i moduli SFP e QSFP prima di collegare le schede. 
---
= Sostituire il modulo i/o - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare questa procedura per sostituire un modulo i/o guasto.

* Puoi utilizzare questa procedura con tutte le versioni di ONTAP supportate dal tuo sistema storage.
* Tutti gli altri componenti del sistema di storage devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.




== Fase 1: Spegnere il controller compromesso

Spegnere o sostituire il controller compromesso.

Per spegnere il controller compromesso, è necessario determinare lo stato del controller e, se necessario, assumere il controllo del controller in modo che il controller integro continui a servire i dati provenienti dallo storage del controller compromesso.

.A proposito di questa attività
* Se si dispone di un sistema SAN, è necessario aver controllato i messaggi di evento  `cluster kernel-service show`) per il blade SCSI del controller danneggiato. Il `cluster kernel-service show` comando (dalla modalità avanzata precedente) visualizza il nome del nodo, lo stato del quorum di quel nodo, lo stato di disponibilità di quel nodo e lo stato operativo di quel nodo.
+
Ogni processo SCSI-blade deve essere in quorum con gli altri nodi del cluster. Eventuali problemi devono essere risolti prima di procedere con la sostituzione.

* Se si dispone di un cluster con più di due nodi, questo deve trovarsi in quorum. Se il cluster non è in quorum o un controller integro mostra false per idoneità e salute, è necessario correggere il problema prima di spegnere il controller compromesso; vedere link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["Sincronizzare un nodo con il cluster"^].


.Fasi
. Se AutoSupport è attivato, sospendere la creazione automatica dei casi richiamando un messaggio AutoSupport: `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
Il seguente messaggio AutoSupport elimina la creazione automatica del caso per due ore: `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. Disattivare il giveback automatico dalla console del controller integro: `storage failover modify –node local -auto-giveback false`
+

NOTE: Quando viene visualizzato _Vuoi disattivare il giveback automatico?_, inserisci `y`.

. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Passare alla fase successiva.



 a| 
In attesa di un giveback...
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode _impaired_node_name_`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===




== Fase 2: Sostituire un modulo i/o guasto

Per sostituire un modulo i/o, individuarlo all'interno del modulo controller e seguire la sequenza specifica di passi.

. Se non si è già collegati a terra, mettere a terra l'utente.
. Scollegare eventuali cavi dal modulo i/o di destinazione.
+
Accertarsi di etichettare i cavi in modo da sapere da dove provengono.

. Ruotare il vassoio di gestione dei cavi verso il basso tirando i pulsanti all'interno del vassoio di gestione dei cavi e ruotandolo verso il basso.
. Rimuovere il modulo i/o dal modulo controller:
+

NOTE: La figura seguente mostra la rimozione di un modulo i/o orizzontale e verticale. In genere, si rimuoverà un solo modulo i/O.

+
image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[Rimuovere il modulo di i/O.]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["Numero didascalia 1,larghezza=30px"]
 a| 
Pulsante di bloccaggio della camma

|===
+
.. Premere il pulsante del dispositivo di chiusura a camma.
.. Ruotare il dispositivo di chiusura della camma allontanandolo completamente dal modulo.
.. Rimuovere il modulo dal modulo controller agganciando il dito nell'apertura della leva a camme ed estraendo il modulo dal modulo controller.
+
Assicurarsi di tenere traccia dello slot in cui si trovava il modulo i/O.



. Mettere da parte il modulo i/O.
. Installare il modulo i/o sostitutivo nello slot di destinazione:
+
.. Allineare il modulo i/o con i bordi dello slot.
.. Far scorrere delicatamente il modulo nello slot fino in fondo nel modulo controller, quindi ruotare il dispositivo di chiusura della camma completamente verso l'alto per bloccare il modulo in posizione.


. Collegare il modulo i/O.
. Ripetere i passi di rimozione e installazione per sostituire i moduli aggiuntivi per la centralina.
. Ruotare il vassoio di gestione dei cavi in posizione di blocco.




== Fase 3: Riavviare il controller

Dopo aver sostituito un modulo i/o, è necessario riavviare il modulo controller.


NOTE: Se il nuovo modulo i/o non è lo stesso modello del modulo guasto, è necessario prima riavviare il BMC.

.Fasi
. Riavviare il BMC se il modulo sostitutivo non è lo stesso modello del modulo precedente:
+
.. Dal prompt del CARICATORE, passare alla modalità privilegi avanzata: _Set Privilege Advanced_
.. Riavviare BMC: _Sp reboot_


. Dal prompt del CARICATORE, riavviare il nodo: _Bye_
+

NOTE: In questo modo, vengono reinizializzate le schede i/o e altri componenti e viene riavviato il nodo.

+

NOTE: Assicurarsi di uscire dalla modalità di manutenzione dopo aver completato la conversione.

. Riportare il nodo al normale funzionamento: _Failover giveback dello storage -ofnode inedito_node_name_
. Se il giveback automatico è stato disattivato, riabilitarlo: _Storage failover modify -node local -auto-giveback true_




== Fase 4: Restituire la parte guasta a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
