---
permalink: asa-r2-70-90/maintain-overview.html 
sidebar: sidebar 
keywords: asa r2 a70 asa r2 a90 maintenance, maintenance, repairing asa r2 a70 asa r2 a90, repairing a70 asa r2 a90, replace a70 asa r2 a90 components 
summary: 'Eseguire la manutenzione dell"hardware ASA R2 A70 e ASA R2 A90' 
---
= Panoramica delle procedure di manutenzione - ASA A70 e ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mantieni l'hardware dei tuoi sistemi storage ASA A70 e ASA A90 per garantire affidabilità a lungo termine e performance ottimali. Eseguire regolarmente attività di manutenzione, come la sostituzione dei componenti difettosi, in quanto ciò consente di evitare tempi di inattività e perdite di dati.

Le procedure di manutenzione presumono che i sistemi ASA A70 e ASA A90 siano già stati implementati come nodo storage nell'ambiente ONTAP.



== Componenti del sistema

Per i sistemi di storage ASA A70 e ASA A90, è possibile eseguire le procedure di manutenzione sui seguenti componenti.

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["Supporto di boot"]
 a| 
Il supporto di avvio memorizza un set primario e secondario di file immagine ONTAP che il sistema di archiviazione utilizza per l'avvio.  Durante il ripristino automatico, il sistema recupera l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione di menu di avvio appropriata per installare l'immagine sul supporto di avvio sostitutivo.



 a| 
link:chassis-replace-workflow.html["Chassis"]
 a| 
Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



 a| 
link:controller-replace-workflow.html["Controller"]
 a| 
Un controller è costituito da una scheda, firmware e software. Controlla lo storage, le schede i/o e esegue il software del sistema operativo ONTAP.



 a| 
link:dimm-replace.html["DIMM"]
 a| 
Un modulo DIMM (Dual in-line Memory Module) è un tipo di memoria per computer. Vengono installati per aggiungere memoria di sistema a una scheda madre del controller.



 a| 
link:drive-replace.html["Disco"]
 a| 
Un'unità è un dispositivo che fornisce l'archiviazione fisica necessaria per i dati.



 a| 
link:fan-swap-out.html["Ventola"]
 a| 
Una ventola raffredda la centralina.



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
La NVRAM (non-volatile Random Access Memory) è un modulo che consente al controller di proteggere e salvare i dati in-flight in caso di interruzione dell'alimentazione del sistema. L'ID di sistema risiede nel modulo NVRAM. Una volta sostituito, il controller presuppone il nuovo ID di sistema dal modulo NVRAM sostitutivo.



 a| 
link:nvdimm-battery-replace.html["Batteria NV"]
 a| 
La batteria NV è responsabile dell'alimentazione al modulo NVRAM mentre i dati in-flight vengono trasferiti alla memoria flash dopo un'interruzione dell'alimentazione.



 a| 
link:io-module-overview.html["Modulo i/O."]
 a| 
Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



 a| 
link:power-supply-replace.html["Alimentatore"]
 a| 
Un alimentatore fornisce una fonte di alimentazione ridondante in un controller.



 a| 
link:rtc-battery-replace.html["Batteria con orologio in tempo reale"]
 a| 
Una batteria dell'orologio in tempo reale conserva le informazioni relative alla data e all'ora del sistema se l'alimentazione è spenta.



 a| 
link:system-management-replace.html["Modulo di gestione del sistema"]
 a| 
Il modulo di gestione del sistema fornisce l'interfaccia tra il controller e una console o un laptop per scopi di manutenzione del controller o del sistema. Il modulo di gestione del sistema contiene il supporto di avvio e memorizza il numero di serie del sistema (SSN).

|===