---
permalink: c800/install-videos.html 
sidebar: sidebar 
keywords: aff c800, hardware installation and cabling video, perform end-to-end software configuration video 
summary: 'Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.' 
---
= Video - AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sono disponibili due video: Uno che mostra come installare e collegare il sistema in rack e uno che mostra un esempio di utilizzo della configurazione guidata di System Manager per eseguire la configurazione iniziale del sistema.

Se si dispone di una configurazione MetroCluster, utilizzare il contenuto dell'installazione di MetroCluster.

https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentazione MetroCluster"^]



== Video uno di due: Installazione hardware e cablaggio

Il seguente video mostra come installare e collegare il nuovo sistema.

.Animazione - Installazione e configurazione di un AFF C800
video::db9f506c-b08e-4b66-b781-afc40187b639[panopto]


== Video due di due: Esecuzione della configurazione software end-to-end

Il seguente video mostra la configurazione software end-to-end per i sistemi che eseguono ONTAP 9.2 e versioni successive.

video::WAE0afWhj1c?[youtube]