---
permalink: c800/overview.html 
sidebar: sidebar 
keywords: AFF C800 specifications, AFF C800 specs, NetApp AFF C800, AFF C800 hardware 
summary: Specifiche chiave per il sistema di archiviazione AFF C800 
---
= Specifiche chiave per AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche selezionate per l' AFF C800.  Visita https://hwu.netapp.com["NetApp Hardware Universe"^] (HWU) per un elenco completo delle specifiche AFF C800 .  Questa pagina riflette una singola coppia ad alta disponibilità.



=== Specifiche chiave per AFF C800

Configurazione della piattaforma: coppia HA a telaio singolo AFF C800

Capacità massima grezza: 7,3680 PB

Memoria: 1280.0000 GB

Fattore di forma: chassis 4U con 2 controller HA e 48 slot per unità

Versione ONTAP : b_startONTAP: 9.16.1P2b_end

Slot di espansione PCIe: 10

Versione minima ONTAP : ONTAP 9.10.1P15



=== Massimi di scalabilità

|===


| Tipo | Coppie HA | Capacità grezza | Memoria massima 


| NAS | 12 | 88,4 PB / 78,5 PiB | 15360 GB 


| SAN | 6 | 44,2 PB / 39,3 PiB | 7680 GB 


| Coppia HA |  | 7,4 PB / 6,5 PiB | 1280,0000 
|===


=== Io



==== IO di bordo

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 4 
|===


==== IO totale

|===


| Protocollo | porti 


| Ethernet 100 Gbps | 20 


| Ethernet 25 Gbps | 16 


| Ethernet 10 Gbps | 32 


| FC 32 Gbps | 32 


| NVMe/FC 32 Gbps | 32 


|  | 0 


|  | 0 
|===


==== Porte di gestione

|===


| Protocollo | porti 


| Ethernet 1 Gbps | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== Rete di archiviazione supportata

CIFS; FC; iSCSI; NFS v3; NFS v4.0; NFS v4.1; NFS v4.2; NFSv3/RDMA; NFSv4/RDMA; NVMe/FC; NVMe/TCP; S3; S3 con NAS; SMB 2.0; SMB 2.1; SMB 2.x; SMB 3.0; SMB 3.1; SMB 3.1.1;



=== Specifiche dell'ambiente di sistema

* Potenza tipica: 6626 BTU/ora
* Potenza nel caso peggiore: 8417 BTU/ora
* Peso: 132,5 libbre/60,1 kg
* Altezza: 4U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 34,5" (36,6" con staffa per la gestione dei cavi)
* Temperatura/altitudine/umidità di esercizio: da 5°C a 40°C (da 41°F a 104°F) a 3048 m (da 10000 piedi) di altitudine; umidità relativa dall'8% al 90%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi)<br/>Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 8,0;br/Pressione sonora (LpAm) (posizioni degli astanti): 62,8 dB




=== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55024, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 14336, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




=== Alta disponibilità

Controller di gestione della scheda madre (BMC) basato su Ethernet e interfaccia di gestione ONTAP ; Controller ridondanti sostituibili a caldo; Alimentatori ridondanti sostituibili a caldo;

 [//] 2025-10-15 ontap-systems-internal/issues/1357