---
permalink: fas2600/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas2600, verify and set HA state, complete the replacement process 
summary: Completa la sostituzione dello chassis per il tuo sistema FAS2600 verificando lo stato HA dello chassis e restituendo il componente guasto a NetApp. 
---
= Completa la sostituzione dello chassis del tuo sistema FAS2600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Completa la sostituzione dello chassis del tuo sistema FAS2600 verificando lo stato HA dello chassis e restituendo il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit.



[[step-1-verify-and-set-the-ha-state-of-the-chassis]]
== Fase 1: Verificare e impostare lo stato ha del telaio

È necessario verificare lo stato ha dello chassis e, se necessario, aggiornarlo in modo che corrisponda alla configurazione del sistema.

. In modalità Maintenance (manutenzione), da uno dei moduli controller, visualizzare lo stato ha del modulo controller locale e dello chassis: `ha-config show`
+
Lo stato ha deve essere lo stesso per tutti i componenti.

. Se lo stato del sistema visualizzato per lo chassis non corrisponde alla configurazione del sistema:
+
.. Impostare lo stato ha per lo chassis: `ha-config modify chassis _HA-state_`
+
Il valore dello stato ha può essere uno dei seguenti:

+
*** `ha`
*** `non-ha`


.. Verificare che l'impostazione sia stata modificata: `ha-config show`


. Se non lo si è già fatto, recuperare il resto del sistema.
. Il passaggio successivo dipende dalla configurazione del sistema.
+
[cols="1,2"]
|===
| Se il sistema è in... | Quindi... 


 a| 
Una configurazione standalone
 a| 
.. Uscire dalla modalità di manutenzione: `halt`
.. Passare a. link:chassis-replace-move-hardware.html["Completamento del processo di sostituzione"].




 a| 
Una coppia ha con un secondo modulo controller
 a| 
Uscire dalla modalità di manutenzione: `halt`

Viene visualizzato il prompt DEL CARICATORE.

|===




[[step-2-return-the-failed-part-to-netapp]]
== Fase 2: Restituire il componente guasto a NetApp

Restituire la parte guasta a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere la https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione delle parti"] pagina per ulteriori informazioni.
