---
permalink: fas9000/bootmedia-recovery-image-boot-options.html 
sidebar: sidebar 
keywords: aff a700, fas9000, boot, recovery, image, two, node, metrocluster, configuration 
summary: 'La procedura per avviare il nodo con problemi dall"immagine di ripristino dipende dal fatto che il sistema si trovi in una configurazione MetroCluster a due nodi.' 
---
= Avviare l'immagine di ripristino - AFF A700 e FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La procedura per avviare il nodo con problemi dall'immagine di ripristino dipende dal fatto che il sistema si trovi in una configurazione MetroCluster a due nodi.



== Opzione 1 avviare l'immagine di ripristino nella maggior parte dei sistemi

È necessario avviare l'immagine ONTAP dall'unità USB, ripristinare il file system e verificare le variabili ambientali.

Questa procedura si applica ai sistemi che non si trovano in una configurazione MetroCluster a due nodi.

.Fasi
. Dal prompt DEL CARICATORE, avviare l'immagine di ripristino dall'unità flash USB: `boot_recovery`
+
L'immagine viene scaricata dall'unità flash USB.

. Quando richiesto, inserire il nome dell'immagine o accettare l'immagine predefinita visualizzata tra parentesi sullo schermo.
. Ripristinare `var` file system:
+
[cols="1,2"]
|===
| Se il sistema dispone di... | Quindi... 


 a| 
Una connessione di rete
 a| 
.. Premere `y` quando viene richiesto di ripristinare la configurazione di backup.
.. Impostare il nodo integro sul livello di privilegio avanzato: `set -privilege advanced`
.. Eseguire il comando di ripristino del backup: `system node restore-backup -node local -target-address _impaired_node_IP_address_`
.. Riportare il nodo al livello admin: `set -privilege admin`
.. Premere `y` quando viene richiesto di utilizzare la configurazione ripristinata.
.. Premere `y` quando viene richiesto di riavviare il nodo.




 a| 
Nessuna connessione di rete
 a| 
.. Premere `n` quando viene richiesto di ripristinare la configurazione di backup.
.. Riavviare il sistema quando richiesto dal sistema.
.. Selezionare l'opzione *Update flash from backup config* (Sync flash) dal menu visualizzato.
+
Se viene richiesto di continuare con l'aggiornamento, premere `y`.





 a| 
Nessuna connessione di rete e si trova in una configurazione MetroCluster IP
 a| 
.. Premere `n` quando viene richiesto di ripristinare la configurazione di backup.
.. Riavviare il sistema quando richiesto dal sistema.
.. Attendere che le connessioni dello storage iSCSI si connettano.
+
È possibile procedere dopo aver visualizzato i seguenti messaggi:

+
[listing]
----
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_auxiliary, address: ip-address).
date-and-time [node-name:iscsi.session.stateChanged:notice]: iSCSI session state is changed to Connected for the target iSCSI-target (type: dr_partner, address: ip-address).
----
.. Selezionare l'opzione *Update flash from backup config* (Sync flash) dal menu visualizzato.
+
Se viene richiesto di continuare con l'aggiornamento, premere `y`.



|===
. Assicurarsi che le variabili ambientali siano impostate come previsto:
+
.. Portare il nodo al prompt DEL CARICATORE.
.. Controllare le impostazioni delle variabili di ambiente con `printenv` comando.
.. Se una variabile di ambiente non è impostata come previsto, modificarla con `setenv __environment-variable-name__ __changed-value__` comando.
.. Salvare le modifiche utilizzando `savenv` comando.


. Il successivo dipende dalla configurazione del sistema:
+
** Se il sistema dispone di onboard keymanager, NSE o NVE configurati, visitare il sito xref:bootmedia-encryption-restore.adoc[Ripristinare OKM, NSE e NVE secondo necessità]
** Se il sistema non dispone di onboard keymanager, NSE o NVE configurati, completare la procedura descritta in questa sezione.


. Dal prompt DEL CARICATORE, immettere `boot_ontap` comando.
+
[cols="1,2"]
|===
| *Se vedi... | Quindi...* 


 a| 
Prompt di login
 a| 
Passare alla fase successiva.



 a| 
In attesa di un giveback...
 a| 
.. Accedere al nodo partner.
.. Verificare che il nodo di destinazione sia pronto per il giveback con `storage failover show` comando.


|===
. Collegare il cavo della console al nodo partner.
. Restituire il nodo utilizzando `storage failover giveback -fromnode local` comando.
. Al prompt del cluster, controllare le interfacce logiche con `net int -is-home false` comando.
+
Se le interfacce sono elencate come "false", ripristinarle alla porta home utilizzando `net int revert` comando.

. Spostare il cavo della console sul nodo riparato ed eseguire `version -v` Per controllare le versioni di ONTAP.
. Ripristinare il giveback automatico se è stato disattivato utilizzando `storage failover modify -node local -auto-giveback true` comando.




== Opzione 2: Avviare l'immagine di ripristino in una configurazione MetroCluster a due nodi

È necessario avviare l'immagine ONTAP dall'unità USB e verificare le variabili ambientali.

Questa procedura si applica ai sistemi in una configurazione MetroCluster a due nodi.

.Fasi
. Dal prompt DEL CARICATORE, avviare l'immagine di ripristino dall'unità flash USB: `boot_recovery`
+
L'immagine viene scaricata dall'unità flash USB.

. Quando richiesto, inserire il nome dell'immagine o accettare l'immagine predefinita visualizzata tra parentesi sullo schermo.
. Una volta installata l'immagine, avviare il processo di ripristino:
+
.. Premere `n` quando viene richiesto di ripristinare la configurazione di backup.
.. Premere `y` quando viene richiesto di riavviare per iniziare a utilizzare il software appena installato.
+
Quando richiesto, si dovrebbe essere pronti ad interrompere il processo di avvio.



. All'avvio del sistema, premere `Ctrl-C` dopo aver visualizzato `Press Ctrl-C for Boot Menu` E quando viene visualizzato il menu di avvio, selezionare l'opzione 6.
. Verificare che le variabili ambientali siano impostate come previsto.
+
.. Portare il nodo al prompt DEL CARICATORE.
.. Controllare le impostazioni delle variabili di ambiente con `printenv` comando.
.. Se una variabile di ambiente non è impostata come previsto, modificarla con `setenv __environment-variable-name__ __changed-value__` comando.
.. Salvare le modifiche utilizzando `savenv` comando.
.. Riavviare il nodo.



