---
permalink: fas9000/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, chassis replacement 
summary: Prima di sostituire lo chassis in un sistema FAS9000, verifica che tutti gli altri componenti funzionino correttamente e che lo chassis di ricambio sia dello stesso modello dello chassis guasto. 
---
= Esamina i requisiti per la sostituzione di uno chassis in un sistema FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire lo chassis in un sistema FAS9000, verifica che tutti gli altri componenti funzionino correttamente e che lo chassis di ricambio sia dello stesso modello dello chassis guasto. La procedura è invasiva e causa un'interruzione completa del servizio in un cluster a due nodi o un'interruzione parziale in un cluster multi-nodo.

Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura ha un'interruzione. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

