---
permalink: fas9000/install-setup.html 
sidebar: sidebar 
keywords: fas9000, aff a700, install, setup, initial, configuration 
summary: Installare e configurare il sistema. 
---
= Scegli la tua esperienza di installazione e configurazione FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per la maggior parte delle configurazioni FAS9000, puoi scegliere il formato di installazione e configurazione che meglio si adatta alle tue esigenze: passaggi rapidi, passaggi video o passaggi dettagliati.

* link:../fas9000/install-quick-guide.html["Passaggi rapidi"]
+
Un PDF stampabile con istruzioni dettagliate con collegamenti in tempo reale a contenuti aggiuntivi.

* link:../fas9000/install-videos.html["Video fasi"]
+
Video istruzioni dettagliate.

* link:../fas9000/install-detailed-guide.html["Passaggi dettagliati"]
+
Istruzioni passo-passo online con collegamenti in tempo reale a contenuti aggiuntivi.



Per le configurazioni MetroCluster, vedere:

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installare la configurazione IP di MetroCluster"]
* https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html["Installare la configurazione MetroCluster Fabric-Attached"]

