---
permalink: fas9000/maintain-overview.html 
sidebar: sidebar 
keywords: fas9000 maintenance, maintenance, repairing fas9000, repairing fas9000, replace fas9000 components, replace fas9000 components 
summary: 'Manutenzione dell"hardware ASA A700' 
---
= Manutenzione dell'hardware FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema storage FAS9000, è possibile eseguire le procedure di manutenzione sui seguenti componenti.



[[boot-media]]
== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



[[caching-module]]
== Modulo di caching

È necessario sostituire il modulo di caching del controller quando il sistema registra un singolo messaggio ASUP (AutoSupport) che indica che il modulo è offline.



[[chassis]]
== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



[[controller]]
== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



[[dcpm]]
== DCPM

Il DCPM (destage controller power module) contiene la batteria NVRAM11.



[[dimm]]
== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



[[fan]]
== Ventola

La ventola raffredda il controller.



[[io-module]]
== Modulo i/O.

Il modulo i/o (modulo Input/Output) è un componente hardware che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.



[[led-usb]]
== USB LED

Il modulo LED USB fornisce connettività alle porte della console e allo stato del sistema.



[[nvram]]
== NVRAM

Il modulo NVRAM (non-volatile Random Access Memory) consente al controller di conservare i dati durante i cicli di alimentazione o il riavvio del sistema.



[[power-supply]]
== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



[[real-time-clock-battery]]
== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.



[[x91148a-module]]
== Modulo X91148A

Il modulo X91148A è un modulo i/o che funge da intermediario tra il controller e vari dispositivi o sistemi che devono scambiare dati con il controller.
