---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: Informazioni sui requisiti per la sostituzione dei supporti di avvio. 
---
= Requisiti - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio, verificare i seguenti requisiti e considerazioni.



== Requisiti

* È necessario sostituire il componente guasto con un componente FRU sostitutivo della stessa capacità ricevuta da NetApp.
* La porta e0S (chiave da e0M mm) sulla centralina guasta non può essere guasta.
+
La porta e0S viene utilizzata per il ripristino automatico dell'avvio.

* Determinare se OKM (Onboard Key Manager) o EKM (Eternal Key Manager) è configurato utilizzando uno dei seguenti metodi:
+
** È possibile chiedere all'amministratore di sistema se OKM o EKM sono abilitati.
** Per verificare se OKM è abilitato, è possibile utilizzare `security key-manager onboard show` .
** Per verificare se EKM è abilitato, è possibile utilizzare `security key-manager external show` .


* Per OKM, è necessario il contenuto del file della passphrase OKM.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** file /cfcard/kmip/servers.cfg.
** file /cfcard/kmip/certs/client.crt.
** file /cfcard/kmip/certs/client.key.
** File /cfcard/kmip/certs/CA.pem.






== Considerazioni

* È importante applicare i comandi descritti di seguito al controller corretto:
+
** Il controller _alterato_ è il controller su cui si esegue la manutenzione.
** Il controller _healthy_ è il partner ha del controller compromesso.


* Se necessario, è possibile attivare i LED di posizione del telaio della piattaforma (blu) per facilitare l'individuazione fisica della piattaforma interessata. Accedere a BMC utilizzando SSH e immettere il `system location-led _on_` comando.
+
Un telaio della piattaforma ha tre LED di posizione: Uno sul pannello del display dell'operatore e uno su ogni controller. I LED di posizione rimangono accesi per 30 minuti.

+
È possibile disattivarle immettendo il `system location-led _off_` comando. Se non si è certi che i LED siano accesi o spenti, è possibile controllarne lo stato digitando il `system location-led show` comando.



.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, link:bootmedia-shutdown-bmr.html["spegnere il controller danneggiato"].
