---
permalink: asa-r2-a20-30-50/bootmedia-overview-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, overview, automatic recovery, boot media 
summary: Informazioni sul metodo automatico per la sostituzione dei supporti di avvio. 
---
= Panoramica sul ripristino dei supporti di avvio - ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ripristino del supporto di avvio per il sistema di storage ASA A20, ASA A30 o ASA A50 utilizza l'immagine di avvio dal nodo partner ed esegue automaticamente l'opzione appropriata del menu di avvio per installare l'immagine di avvio sul supporto di avvio sostitutivo.

Quando si verificano messaggi di errore di avvio simili a quelli illustrati di seguito, è necessario sostituire il supporto di avvio e ripristinare l'immagine ONTAP dal nodo partner.

....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....