---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the boot media 
summary: 'Prima di sostituire il supporto di avvio nel sistema di storage ASA A20, ASA A30 o ASA A50, assicurarsi di soddisfare i requisiti e le considerazioni necessari per una sostituzione corretta. Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma del corretto funzionamento della porta e0S (chiave e0M) del controller danneggiato e la verifica dell"abilitazione di Onboard Key Manager (OKM) o External Key Manager (EKM).' 
---
= Requisiti per sostituire i supporti di avvio: ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di sostituire il supporto di avvio nel sistema di storage ASA A20, ASA A30 o ASA A50, assicurarsi di soddisfare i requisiti e le considerazioni necessari per una sostituzione corretta. Ciò include la verifica di disporre del supporto di avvio sostitutivo corretto, la conferma del corretto funzionamento della porta e0S (chiave e0M) del controller danneggiato e la verifica dell'abilitazione di Onboard Key Manager (OKM) o External Key Manager (EKM).

Esaminare i seguenti requisiti.

* È necessario sostituire il componente guasto con un componente FRU sostitutivo della stessa capacità ricevuta da NetApp.
* La porta e0S (chiave e0M) viene utilizzata per comunicare tra i due controller durante il processo di ripristino automatico dell'avvio. Assicurarsi che la porta e0S del controller in questione funzioni correttamente.
* Per OKM, è necessario il contenuto del file della passphrase OKM.
* Per EKM, è necessario copiare i seguenti file dal nodo partner:
+
** file /cfcard/kmip/servers.cfg.
** file /cfcard/kmip/certs/client.crt.
** file /cfcard/kmip/certs/client.key.
** File /cfcard/kmip/certs/CA.pem.


* Quando si sostituisce il supporto di avvio danneggiato, è fondamentale applicare i comandi al controller corretto:
+
** Il _controller non funzionante_ è il controller su cui si sta eseguendo la manutenzione.
** Il _controllore sano_ è il partner HA del controllore compromesso.




.Cosa succederà
Dopo aver esaminato i requisiti dei supporti di avvio, si link:bootmedia-shutdown-bmr.html["spegnere il controller danneggiato"].
