---
permalink: asa-r2-a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace io module, io module add, io module hotswap 
summary: 'I sistemi di storage ASA A20, ASA A30 e ASA A50 offrono flessibilità nell"espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L"aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O è essenziale per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.' 
---
= Panoramica della manutenzione dei moduli I/O: ASA A20, ASA A30 e ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I sistemi di storage ASA A20, ASA A30 e ASA A50 offrono flessibilità nell'espansione o nella sostituzione dei moduli I/O per migliorare la connettività e le prestazioni di rete. L'aggiunta, la sostituzione a caldo o la sostituzione di un modulo I/O è essenziale per aggiornare le funzionalità di rete o risolvere un problema relativo a un modulo guasto.

È possibile sostituire un modulo I/O guasto nel sistema di storage con un modulo I/O dello stesso tipo o con un modulo I/O diverso. È possibile sostituire a caldo un cluster e un modulo I/O HA quando il sistema di storage soddisfa requisiti specifici. È inoltre possibile aggiungere un modulo I/O a un sistema di storage con slot disponibili.

* link:io-module-add.html["Aggiungere un modulo i/O."]
+
L'aggiunta di ulteriori moduli di i/o può migliorare la ridondanza, contribuendo a garantire che il sistema di storage rimanga operativo anche in caso di guasto di un modulo di i/O.

* link:io-module-hotswap.html["Eseguire lo swap a caldo di un modulo I/O"]
+
È possibile eseguire lo swap a caldo di determinati moduli I/O con un modulo I/O equivalente per ripristinare il sistema storage al suo stato operativo ottimale. Lo swap a caldo viene eseguito senza dover eseguire un takeover manuale.

+
Per utilizzare questa procedura, il sistema di archiviazione deve eseguire ONTAP 9.17.1 o versione successiva e soddisfare requisiti di sistema specifici.

* link:io-module-replace.html["Sostituire un modulo i/O."]
+
La sostituzione di un modulo i/o guasto può ripristinare il sistema di storage allo stato operativo ottimale.


