---
permalink: asa-r2-key-specifications/asa-a90-key-specifications.html 
sidebar: sidebar 
keywords: ASA A90 specifications, ASA A90 specs, ASA A90 capacity, ASA A90 memory, ASA A90 I/O, ASA A90 compliance 
summary: Specifiche chiave per ASA A90 
---
= Specifiche chiave per ASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Di seguito sono riportate alcune specifiche per il sistema di archiviazione ASA A90 in una singola coppia ad alta disponibilità.  Per le specifiche complete di questo sistema di storage, visitare NetApp Hardware Universe (HWU).



== Specifiche chiave di capacità, memoria, fattore di forma e versione ONTAP

* Configurazione della piattaforma: coppia HA a telaio singolo ASA A90
* Capacità massima grezza: 2,6622 PB
* Memoria: 2048.0000 GB
* Fattore di forma: chassis 4U con 2 controller HA e 48 slot per unità
* Versione ONTAP : ONTAP: 9.16.1P2
* Slot di espansione PCIe: 18
* Versione minima ONTAP : ONTAP 9.16.0 == Massimi di scalabilità
* Tipo: NAS
* Tipo: SAN; Coppie HA: 6; Capacità grezza: 16,0 PB / 14,2 PiB; Memoria massima: 12288 GB
* Tipo: coppia HA; capacità grezza: 2,7 PB / 2,4 PiB; memoria massima: 2048.0000




== I/O



=== I/O integrato

Nessun dato I/O integrato.



=== Totale I/O

* Protocollo: Ethernet 200 Gbps; Porte: 24
* Protocollo: Ethernet 100 Gbps; Porte: 36
* Protocollo: Ethernet 25 Gbps; Porte: 56
* Protocollo: Ethernet 10 Gbps; Porte: 56
* Protocollo: FC 64 Gbps; Porte: 56
* Protocollo: NVMe/FC 64 Gbps; Porte: 56
* Porte: 0




=== Porte di gestione

* Protocollo: Ethernet 1 Gbps; Porte: 2
* Protocollo: RS-232 115 Kbps; Porte: 4
* Protocollo: USB 600 Mbps; Porte: 2




== Rete di archiviazione supportata

* FC
* iSCSI
* NVMe/FC
* NVMe/TCP == Specifiche dell'ambiente di sistema
* Potenza tipica: 8304 BTU/ora
* Potenza nel caso peggiore: 10948 BTU/ora
* Peso: 170,4 libbre 77,3 kg
* Altezza: 4U
* Larghezza: 19" conforme allo standard IEC per rack (17,6" 44,7 cm)
* Profondità: 34,5" (36,6" con staffa per la gestione dei cavi)
* Temperatura/altitudine/umidità di esercizio: da 10°C a 35°C (da 50°F a 95°F) a = 3048 m = 10000 piedi) di altitudine; umidità relativa dall'8% all'80%, senza condensa
* Temperatura/umidità non operativa: da -40°C a 70°C (da -40°F a 158°F) fino a 12192 m (40000 piedi) Umidità relativa dal 10% al 95%, senza condensa, nel contenitore originale
* Rumore acustico: Potenza sonora dichiarata (LwAd): 8,6 Pressione sonora (LpAm) (posizioni degli astanti): 71,6 dB




== Conformità

* Certificazioni EMC/EMI: AMCA, FCC, ICES, KC, Marocco, VCCI
* Certificazioni sicurezza: BIS, CB, CSA, G_K_U-SoR, IRAM, NOM, NRCS, SONCAP, TBS
* Certificazioni Sicurezza/EMC/EMI: EAC, UKRSEPRO
* Certificazioni Sicurezza/EMC/EMI/RoHS: BSMI, CE DoC, UKCA DoC
* Standard EMC/EMI: BS-EN-55032, BS-EN55035, CISPR 32, EN55022, EN55024, EN55032, EN55035, EN61000-3-2, EN61000-3-3, FCC Parte 15 Classe A, ICES-003, KS C 9832, KS C 9835
* Standard di sicurezza: ANSI/UL60950-1, ANSI/UL62368-1, BS-EN62368-1, CAN/CSA C22.2 n. 60950-1, CAN/CSA C22.2 n. 62368-1, CNS 15598-1, EN60825-1, EN62368-1, IEC 62368-1, IEC60950-1, IS 13252 (parte 1)




== Alta disponibilità

* Controller di gestione della scheda madre basato su Ethernet (BMC) e interfaccia di gestione ONTAP
* Controller ridondanti sostituibili a caldo
* Alimentatori ridondanti sostituibili a caldo
* Gestione in banda SAS su connessioni SAS per scaffali esterni

