---
permalink: afx/afx-install-setup.html 
sidebar: sidebar 
keywords: afx, afx 1k, install, setup, initial configuration 
summary: Installare e configurare il sistema. 
---
= Installa e configura il tuo sistema di archiviazione AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vai al https://docs.netapp.com/us-en/ontap-afx/index.html["Documentazione AFX"^] per imparare come installare, utilizzare e gestire il tuo sistema AFX.

IL https://docs.netapp.com/us-en/ontap-afx/index.html["Documentazione AFX"^] include informazioni quali:

* Istruzioni per l'installazione e la configurazione
* Istruzioni amministrative per la configurazione del sistema, ad esempio il provisioning dell'archiviazione NAS, la clonazione dei dati e il ridimensionamento dell'archiviazione locale.
* Istruzioni per la gestione del sistema, tra cui la gestione dell'accesso client, la protezione dei dati e la protezione dei dati.
* Istruzioni per il monitoraggio e la risoluzione dei problemi, comprese informazioni su avvisi, eventi del cluster e registri di sistema.


Le procedure di manutenzione specifiche per ogni tipo di sistema AFX sono riportate nellink:../afx-landing-maintain/index.html["Sezione di manutenzione del sistema AFX"] .
