---
permalink: ns224/cable-as-switch-attached.html 
sidebar: sidebar 
keywords: ns224 nvme drive shelf cabling guide, ns224 drive shelf cabling guide, ns224 shelf cabling guide, ns224 cabling guide, switch-attach, switch-attached, switch-attached storage, cable ns224 drive shelves as switch-attached storage 
summary: 'Se si dispone di un sistema in cui gli shelf di dischi NS224 devono essere cablati come storage collegato allo switch (non direct-attached storage), utilizzare le informazioni fornite.' 
---
= Shelf di cavi come storage collegato allo switch - shelf NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dispone di un sistema in cui gli shelf di dischi NS224 devono essere cablati come storage collegato allo switch (non come storage collegato direttamente), utilizzare le informazioni fornite.

* Per collegare gli shelf di dischi NS224 attraverso switch di storage, fare riferimento alla https://hwu.netapp.com["NetApp Hardware Universe"^] per ulteriori informazioni. Per i modelli hardware meno recenti, le informazioni sul cablaggio degli interruttori sono disponibili anche nella https://library.netapp.com/ecm/ecm_download_file/ECMLP2876580["NS224 NVMe Drive Shelf Cabining Guide"^] .
* Per installare gli switch di archiviazione, fare riferimento alla https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentazione switch AFF e FAS"^].
* Per verificare l'hardware supportato per il modello di piattaforma in uso, ad esempio switch di archiviazione e cavi, fare riferimento alla https://hwu.netapp.com["NetApp Hardware Universe"^] .

