---
permalink: ns224/hot-add-asa-complete.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa systems, complete, drive 
summary: 'Se hai disabilitato l"assegnazione automatica delle unità, assegna manualmente la proprietà delle unità e riattiva l"assegnazione automatica delle unità per il tuo sistema ASA.' 
---
= Completa l'aggiunta a caldo dello shelf NS224 per il tuo sistema ASA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se hai disattivato l'assegnazione automatica dei dischi come parte della preparazione per l'aggiunta a caldo dello shelf NS224, devi assegnare manualmente la proprietà dei dischi e riattivare l'assegnazione automatica dei dischi, se necessario.

.Prima di iniziare
Devi aver già cablato la mensola come indicato nelle istruzioni per la tua coppia HA.

.Fasi
. Visualizzare tutti i dischi non posseduti: `storage disk show -container-type unassigned`
+
È possibile immettere il comando su uno dei controller.

. Assegnare ciascun disco: `storage disk assign -disk _disk_name_ -owner _owner_name_`
+
È possibile immettere il comando su uno dei controller.

+
È possibile utilizzare il carattere jolly per assegnare più di un disco alla volta.

. Se necessario, riabilitare l'assegnazione automatica del disco: `storage disk option modify -node _node_name_ -autoassign on`
+
È necessario riattivare l'assegnazione automatica della guida su entrambi i controller.


