---
permalink: ns224/hot-add-aff-cable-a250-c250.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, aff a250, aff c250, cable 
summary: Collega il tuo shelf NS224 al sistema AFF A250 o AFF C250 in modo che ogni shelf abbia due connessioni a ciascun controller della coppia HA. 
---
= Collega un shelf NS224 al tuo sistema AFF A250 o AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Collega il tuo shelf NS224 al sistema AFF A250 o AFF C250 in modo che ogni shelf abbia due connessioni a ciascun controller della coppia HA.

.A proposito di questa attività
Vista dal retro dello chassis della piattaforma, la porta della scheda compatibile con RoCE a sinistra è la porta "a" (e1a) e la porta a destra è la porta "b" (e1b).

.Fasi
. Cablare i collegamenti dello shelf:
+
.. Shelf di cavi NSM Porta A e0a per controller Slot A porta a (e1a).
.. Porta NSM A del ripiano per cavi e0b allo slot controller B 1 porta b (e1b).
.. Porta NSM B dello shelf per cavi e0a allo slot controller B 1 porta a (e1a).
.. Porta NSM B del ripiano per cavi e0b allo slot a del controller 1 porta b (e1b). + la seguente illustrazione mostra il cablaggio dello shelf una volta completato.
+
image::../media/drw_ns224_a250_c250_f500f_1shelf_ieops-1824.svg[Cablaggio per AFF/ASA A250 C250 o FAS500f con uno shelf NS224 e un set di porte per schede PCIe]



. Verificare che il ripiano aggiunto a caldo sia collegato correttamente utilizzando https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^].
+
Se vengono generati errori di cablaggio, seguire le azioni correttive fornite.



.Cosa succederà
Se hai disabilitato l'assegnazione automatica delle unità durante la preparazione di questa procedura, devi assegnare manualmente la proprietà dell'unità e quindi riattivare l'assegnazione automatica delle unità, se necessario. Vai a link:hot-add-aff-complete.html["Completare l'aggiunta a caldo"].

In caso contrario, la procedura di aggiunta a caldo dello shelf è terminata.
