---
permalink: ns224/service-replace-nsm100.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, impair, nvme, module, nsm, nondisruptive, drive, i/o, nsm, replace an nsm module 
summary: 'È possibile sostituire senza interruzioni un modulo shelf NVMe non alterato in uno shelf di dischi NS224 acceso e mentre l"i/o è in corso.' 
---
= Sostituire un modulo NSM - shelf NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire un modulo shelf NVMe (NSM) non compromesso senza interruzioni in uno shelf di dischi NS224 acceso e mentre l'i/o è in corso.

.Prima di iniziare
* Il modulo NSM del partner dello shelf deve essere attivo e funzionante ed essere cablato correttamente in modo che lo shelf mantenga la connettività quando si rimuove il modulo NSM guasto.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]

* Tutti gli altri componenti del sistema devono funzionare correttamente.


.A proposito di questa attività
* La sostituzione del modulo NSM comporta lo spostamento dei moduli DIMM, delle ventole e dell'alimentatore dal modulo NSM guasto al modulo NSM sostitutivo.
+
Non spostare la batteria dell'orologio in tempo reale (RTC) o il supporto di avvio. Vengono forniti preinstallati nel modulo NSM sostitutivo.

* Attendere almeno 70 secondi tra la rimozione e l'installazione del modulo NVMe shelf (NSM).
+
Ciò consente a ONTAP di elaborare l'evento di rimozione NSM.

* *Best practice:* la Best practice consiste nel disporre delle versioni correnti del firmware NVMe shelf module (NSM) e del firmware del disco sul sistema prima di sostituire i componenti FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Download NetApp: Firmware shelf di dischi"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Download NetApp: Firmware del disco"^]

+
[NOTE]
====
Non riportare il firmware a una versione che non supporta lo shelf e i relativi componenti.

====
* Il firmware shelf (NSM) viene aggiornato automaticamente (senza interruzioni) su un nuovo modulo NSM con una versione del firmware non corrente.
+
I controlli del firmware del modulo NSM avvengono ogni 10 minuti. L'aggiornamento del firmware di un modulo NSM può richiedere fino a 30 minuti.

* Se necessario, è possibile attivare i LED di posizione (blu) dello shelf per individuare fisicamente lo shelf interessato: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se non si conosce `shelf_name` dello shelf interessato, eseguire `storage shelf show` comando.

+
Uno shelf ha tre LED di posizione: Uno sul display operatore e uno su ciascun modulo NSM. I LED di posizione rimangono accesi per 30 minuti. È possibile disattivarle immettendo lo stesso comando, ma utilizzando `off` opzione.

* Quando si disimballa il modulo NSM sostitutivo, conservare tutto il materiale di imballaggio per utilizzarlo quando si restituisce il modulo NSM guasto.
+
Per ottenere il numero RMA o ulteriore assistenza per la procedura di sostituzione, contattare il supporto tecnico all'indirizzo https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^], 888-463-8277 (Nord America), 00-800-44-638277 (Europa) o +800-800-80-800 (Asia/Pacifico).

* Per sostituire un modulo NSM, è possibile utilizzare la seguente animazione o i passaggi scritti.
+
.Animazione - Sostituisci un modulo NSM in uno shelf di dischi NS224
video::f57693b3-b164-4014-a827-aa86002f4b34[panopto]


.Fasi
. Mettere a terra l'utente.
. Identificare fisicamente il modulo NSM con problemi.
+
Il sistema registra un messaggio di avviso alla console di sistema che indica quale modulo è guasto. Inoltre, il LED attenzione (ambra) sul display operatore dello shelf di dischi e il modulo per problemi si illuminano.

. Scollegare il cablaggio dal modulo NSM guasto:
+
.. Scollegare il cavo di alimentazione dall'alimentatore aprendo il fermo del cavo di alimentazione, se si tratta di un alimentatore CA, oppure svitando le due viti pollici, se si tratta di un alimentatore CC, quindi scollegare il cavo di alimentazione dall'alimentatore.
+
Gli alimentatori non dispongono di un interruttore di alimentazione.

.. Scollegare il cablaggio dello storage dalle porte del modulo NSM.
+
Prendere nota delle porte del modulo NSM a cui ciascun cavo è collegato. Ricollegare i cavi alle stesse porte del modulo NSM sostitutivo, più avanti in questa procedura.



. Rimuovere il modulo NSM dallo shelf:
+
.. Far passare le dita di indice attraverso i fori dei meccanismi di blocco su entrambi i lati del modulo NSM.
+

NOTE: Se si rimuove il modulo NSM inferiore e la guida inferiore impedisce l'accesso ai meccanismi di blocco, posizionare le dita di riferimento attraverso i fori all'interno (incrociando le braccia).

.. Con i pollici, tenere premuti le linguette arancioni sulla parte superiore dei meccanismi di blocco.
+
I meccanismi di chiusura si sollevano, liberando i perni di chiusura sullo scaffale.

.. Tirare delicatamente fino a quando il modulo NSM non si trova a circa un terzo del percorso di uscita dallo scaffale, afferrare i lati del modulo NSM con entrambe le mani per sostenerne il peso, quindi posizionarlo su una superficie piana e stabile.
+
Quando si inizia a tirare, i bracci del meccanismo di chiusura si estendono dal modulo NSM e si bloccano in posizione completamente estesa.



. Disimballare il modulo NSM sostitutivo e impostarlo su una superficie piana vicino al modulo NSM compromesso.
. Aprire il coperchio del modulo NSM guasto e il modulo NSM sostitutivo allentando la vite a testa zigrinata su ciascun coperchio.
+

NOTE: L'etichetta FRU sul coperchio del modulo NSM indica la posizione dei DIMM e delle ventole.

. Spostare i DIMM dal modulo NSM guasto al modulo NSM sostitutivo:
+
.. Prendere nota dell'orientamento dei DIMM negli slot in modo da poter inserire i DIMM nel modulo NSM sostitutivo con lo stesso orientamento.
.. Estrarre un modulo DIMM dal relativo slot spingendo lentamente le linguette di espulsione su entrambe le estremità dello slot, quindi estrarre il modulo DIMM dallo slot.
+

NOTE: Tenere il modulo DIMM per gli angoli o i bordi per evitare di esercitare pressione sui componenti della scheda a circuiti stampati del modulo DIMM. Le linguette dell'espulsore rimangono in posizione aperta.

.. Tenere il modulo DIMM per gli angoli, quindi inserirlo perpendicolarmente in uno slot del modulo NSM sostitutivo.
+
La tacca sulla parte inferiore del DIMM, tra i pin, deve allinearsi con la linguetta nello slot.

+
Una volta inserito correttamente, il DIMM dovrebbe essere inserito facilmente ma saldamente nello slot. In caso contrario, reinserire il DIMM.

.. Spingere con cautela, ma con decisione, il bordo superiore del modulo DIMM fino a quando le linguette di espulsione non scattano in posizione sulle tacche di entrambe le estremità del modulo DIMM.
.. Ripetere i passaggi da 7a a 7d per i DIMM rimanenti.


. Spostare le ventole dal modulo NSM guasto al modulo NSM sostitutivo:
+
.. Afferrare saldamente una ventola dai lati, dove si trovano i punti di contatto blu, quindi sollevarla verticalmente per scollegarla dalla presa.
+
Potrebbe essere necessario far oscillare delicatamente la ventola avanti e indietro per scollegarla prima di sollevarla.

.. Allineare la ventola alle guide del modulo NSM sostitutivo, quindi spingere verso il basso fino a inserire completamente il connettore del modulo della ventola nello zoccolo.
.. Ripetere i passaggi secondari 8a e 8b per le ventole rimanenti.


. Chiudere il coperchio di ciascun modulo NSM, quindi serrare ciascuna vite a testa zigrinata.
. Spostare l'alimentatore dal modulo NSM guasto al modulo NSM sostitutivo:
+
.. Ruotare la maniglia verso l'alto, in posizione orizzontale, quindi afferrarla.
.. Con il pollice, premere la linguetta blu per rilasciare il meccanismo di bloccaggio.
.. Estrarre l'alimentatore dal modulo NSM utilizzando l'altra mano per sostenerne il peso.
.. Con entrambe le mani, sostenere e allineare i bordi dell'alimentatore con l'apertura del modulo NSM sostitutivo.
.. Spingere delicatamente l'alimentatore nel modulo NSM fino a quando il meccanismo di blocco non scatta in posizione.
+

NOTE: Non esercitare una forza eccessiva per evitare di danneggiare il connettore interno.

.. Ruotare la maniglia verso il basso, in modo che non sia di intralcio alle normali operazioni.


. Inserire il modulo NSM sostitutivo nello shelf:
+
.. Assicurarsi che i bracci del meccanismo di chiusura siano bloccati in posizione completamente estesa.
.. Con entrambe le mani, far scorrere delicatamente il modulo NSM nello shelf fino a quando il peso del modulo NSM non è completamente supportato dallo shelf.
.. Spingere il modulo NSM nello shelf fino a quando non si ferma (circa mezzo pollice dal retro dello shelf).
+
È possibile posizionare i pollici sulle linguette arancioni sulla parte anteriore di ciascun gancio per le dita (dei bracci del meccanismo di chiusura) per inserire il modulo NSM.

.. Far passare le dita di indice attraverso i fori dei meccanismi di blocco su entrambi i lati del modulo NSM.
+

NOTE: Se si inserisce il modulo NSM inferiore e la guida inferiore ostruisce l'accesso ai meccanismi di blocco, posizionare le dita di riferimento attraverso i fori all'interno (incrociando le braccia).

.. Con i pollici, tenere premuti le linguette arancioni sulla parte superiore dei meccanismi di blocco.
.. Spingere delicatamente in avanti i fermi fino al punto di arresto.
.. Rilasciare i pollici dalla parte superiore dei meccanismi di blocco, quindi continuare a spingere fino a quando i meccanismi di blocco non scattano in posizione.
+
Il modulo NSM deve essere inserito completamente nello shelf e a filo con i bordi dello shelf.



. Ricollegare il cablaggio al modulo NSM:
+
.. Ricollegare il cablaggio dello storage alle stesse due porte del modulo NSM.
+
I cavi devono essere inseriti con la linguetta di estrazione del connettore rivolta verso l'alto. Quando un cavo è inserito correttamente, scatta in posizione.

.. Ricollegare il cavo di alimentazione all'alimentatore, quindi fissare il cavo di alimentazione con il relativo fermo, se si tratta di un alimentatore CA, oppure serrare le due viti ad alette, se si tratta di un alimentatore CC.
+
Quando funziona correttamente, il LED bicolore di un alimentatore si illumina di verde.

+
Inoltre, entrambi i LED LNK (verde) della porta del modulo NSM si illuminano. Se il LED LNK non si accende, ricollegare il cavo.



. Verificare che il LED attenzione (ambra) sul display operatore dello scaffale non sia più acceso.
+
Il LED attenzione del display operatore si spegne dopo il riavvio del modulo NSM. Questa operazione può richiedere da tre a cinque minuti.

. Verificare che il modulo NSM sia cablato correttamente eseguendo Active IQ Config Advisor.
+
Se vengono generati errori di cablaggio, seguire le azioni correttive fornite.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]

. Assicurarsi che entrambi i moduli NSM nello shelf eseguano la stessa versione del firmware: Versione 0200 o successiva.

