---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 'È possibile sostituire un disco guasto senza interruzioni in uno shelf di dischi NS224 acceso e mentre l"i/o è in corso.' 
---
= Disco hot-swap: Shelf NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire un disco guasto senza interruzioni in uno shelf di dischi NS224 acceso e mentre l'i/o è in corso.

.Prima di iniziare
* L'unità che si sta installando deve essere supportata dallo shelf NS224.
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* Se l'autenticazione SED è attivata, è necessario utilizzare le istruzioni per la sostituzione SED nella documentazione di ONTAP.
+
Le istruzioni contenute nella documentazione di ONTAP descrivono i passaggi aggiuntivi da eseguire prima e dopo la sostituzione di un SED.

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["Panoramica della crittografia NetApp con CLI"^]

* Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.
* Verificare che l'unità che si sta rimuovendo non sia funzionante.
+
È possibile verificare che il disco non funzioni correttamente eseguendo `storage disk show -broken` comando. Il disco guasto viene visualizzato nell'elenco dei dischi guasti. In caso contrario, attendere ed eseguire nuovamente il comando.

+

NOTE: A seconda del tipo e della capacità del disco, potrebbero essere necessarie diverse ore prima che il disco venga visualizzato nell'elenco dei dischi guasti.



.A proposito di questa attività
* *Best practice:* la Best practice consiste nell'installare la versione corrente del Disk Qualification Package (DQP) prima di sostituire a caldo un disco.
+
L'installazione della versione corrente di DQP consente al sistema di riconoscere e utilizzare dischi appena qualificati. In questo modo si evitano messaggi di eventi di sistema relativi alla presenza di informazioni non aggiornate sui dischi e alla prevenzione della partizione dei dischi perché i dischi non vengono riconosciuti. Inoltre, il DQP notifica la presenza di firmware del disco non aggiornato.

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["Download NetApp: Pacchetto di qualificazione dei dischi"^]

* *Best practice:* la Best practice consiste nel disporre delle versioni correnti del firmware NVMe shelf module (NSM) e del firmware del disco sul sistema prima di sostituire i componenti FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Download NetApp: Firmware shelf di dischi"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Download NetApp: Firmware del disco"^]

+
[NOTE]
====
Non riportare il firmware a una versione che non supporta lo shelf e i relativi componenti.

====
* Il firmware del disco viene aggiornato automaticamente (senza interruzioni) sui nuovi dischi con versioni firmware non aggiornate.
+

NOTE: I controlli del firmware del disco vengono eseguiti ogni due minuti.

* Se necessario, è possibile attivare i LED di posizione (blu) dello shelf per individuare fisicamente lo shelf interessato: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se non si conosce `_shelf_name_` dello shelf interessato, eseguire `storage shelf show` comando.

+
Uno shelf ha tre LED di posizione: Uno sul display operatore e uno su ciascun modulo NSM. I LED di posizione rimangono accesi per 30 minuti. È possibile disattivarle immettendo lo stesso comando, ma utilizzando `off` opzione.

* Quando si disimballa l'unità sostitutiva, conservare tutti i materiali di imballaggio per l'utilizzo quando si restituisce l'unità guasta.
+
Per ottenere il numero RMA o ulteriore assistenza per la procedura di sostituzione, contattare il supporto tecnico all'indirizzo https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^], 888-463-8277 (Nord America), 00-800-44-638277 (Europa) o +800-800-80-800 (Asia/Pacifico).

* La seguente animazione fornisce una panoramica delle parti fisiche di rimozione e inserimento della procedura di hot-swap del disco.
+
video::733011a7-e03a-41b0-8723-aa840133bf25[Animation,width=Hot-swapping a drive in an NS224 shelf"]
+
.Fasi
.. Se si desidera assegnare manualmente la proprietà del disco per l'unità sostitutiva, è necessario disattivare l'assegnazione automatica del disco, se attivata.
+

NOTE: È necessario assegnare manualmente la proprietà del disco se i dischi nello shelf sono di proprietà di entrambi i moduli controller della coppia ha.

+

NOTE: Assegnare manualmente la proprietà del disco e riabilitare l'assegnazione automatica del disco più avanti in questa procedura.

+
... Verificare se l'assegnazione automatica dei dischi è abilitata: `storage disk option show`
+
È possibile immettere il comando su entrambi i moduli controller.

+
Se l'assegnazione automatica dei dischi è attivata, viene visualizzato l'output `on` in `Auto Assign` (per ciascun modulo controller).

... Se l'assegnazione automatica dei dischi è attivata, disattivarla: `storage disk option modify -node node_name -autoassign off`
+
È necessario disattivare l'assegnazione automatica dei dischi su entrambi i moduli controller.



.. Mettere a terra l'utente.
.. Identificare fisicamente il disco guasto.
+
In caso di guasto di un disco, il sistema registra un messaggio di avviso alla console di sistema che indica quale disco si è guastato. Inoltre, il LED di attenzione (ambra) sul display operatore dello shelf di dischi e il disco guasto si illuminano.

+

NOTE: Il LED di attività (verde) su un disco guasto può essere acceso (fisso), che indica che il disco è alimentato, ma non deve lampeggiare, il che indica l'attività i/O. Un disco guasto non ha attività i/O.

.. Rimuovere il disco guasto:
+
... Premere il pulsante di rilascio sulla superficie dell'unità per aprire la maniglia della camma.
... Estrarre l'unità dallo scaffale utilizzando la maniglia della camma e supportarla con l'altra mano.


.. Attendere almeno 70 secondi prima di inserire l'unità sostitutiva.
+
Questo consente al sistema di riconoscere che un disco è stato rimosso.

.. Inserire l'unità sostitutiva:
+
... Con la maniglia della camma in posizione aperta, inserire l'unità sostitutiva con entrambe le mani.
... Premere fino all'arresto del disco.
... Chiudere la maniglia della camma in modo che l'unità sia completamente inserita nel piano intermedio e la maniglia scatti in posizione.
+
Chiudere lentamente la maniglia della camma in modo che sia allineata correttamente con la superficie dell'unità.



.. Verificare che il LED di attività del disco (verde) sia acceso.
+
Quando il LED di attività del disco è acceso, significa che il disco è alimentato. Quando il LED di attività del disco lampeggia, significa che il disco è alimentato e che l'i/o è in corso. Se il firmware del disco viene aggiornato automaticamente, il LED lampeggia.

.. Se si sta sostituendo un'altra unità, ripetere i passi da 3 a 7.
.. Se l'assegnazione automatica del disco è stata disattivata nel passaggio 1, assegnare manualmente la proprietà del disco e, se necessario, riabilitare l'assegnazione automatica del disco:
+
... Visualizzare tutti i dischi non posseduti: `storage disk show -container-type unassigned`
+
È possibile immettere il comando su entrambi i moduli controller.

... Assegnare ciascun disco: `storage disk assign -disk disk_name -owner owner_name`
+
È possibile immettere il comando su entrambi i moduli controller.

+
È possibile utilizzare il carattere jolly per assegnare più di un disco alla volta.

... Se necessario, riabilitare l'assegnazione automatica del disco: `storage disk option modify -node node_name -autoassign on`
+
È necessario riabilitare l'assegnazione automatica dei dischi su entrambi i moduli controller.






