---
permalink: ns224/service-replace-fan.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, fan, nondisruptive, power, i/o, progress, replace, replace a fan 
summary: 'È possibile sostituire una ventola guasta senza interruzioni in uno shelf di dischi NS224 acceso e mentre l"i/o è in corso.' 
---
= Sostituire una ventola - shelf NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile sostituire una ventola guasta senza interruzioni in uno shelf di dischi NS224 acceso e mentre l'i/o è in corso.

.Prima di iniziare
* Il modulo NSM del partner dello shelf deve essere attivo e funzionante ed essere cablato correttamente in modo che lo shelf mantenga la connettività quando si rimuove il modulo NSM con la FRU (modulo NSM di destinazione) guasta.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]

* Tutti gli altri componenti del sistema, comprese le altre quattro ventole, devono funzionare correttamente.


.A proposito di questa attività
* Attendere almeno 70 secondi tra la rimozione e l'installazione del modulo NVMe shelf (NSM).
+
Ciò consente a ONTAP di elaborare l'evento di rimozione NSM.

* *Best practice:* la Best practice consiste nel disporre delle versioni correnti del firmware NVMe shelf module (NSM) e del firmware del disco sul sistema prima di sostituire i componenti FRU.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Download NetApp: Firmware shelf di dischi"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Download NetApp: Firmware del disco"^]

+
[NOTE]
====
Non riportare il firmware a una versione che non supporta lo shelf e i relativi componenti.

====
* Se necessario, è possibile attivare i LED di posizione (blu) dello shelf per individuare fisicamente lo shelf interessato: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se non si conosce `_shelf_name_` dello shelf interessato, eseguire `storage shelf show` comando.

+
Uno shelf ha tre LED di posizione: Uno sul display operatore e uno su ciascun modulo NSM. I LED di posizione rimangono accesi per 30 minuti. È possibile disattivarle immettendo lo stesso comando, ma utilizzando `off` opzione.

* Quando si disimballano le ventole sostitutive, conservare tutti i materiali di imballaggio da utilizzare quando si restituisce la ventola guasta.
+
Per ottenere il numero RMA o ulteriore assistenza per la procedura di sostituzione, contattare il supporto tecnico all'indirizzo https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^], 888-463-8277 (Nord America), 00-800-44-638277 (Europa) o +800-800-80-800 (Asia/Pacifico).

* Per sostituire una ventola, è possibile utilizzare la seguente animazione o la procedura scritta.
+
.Animazione - Sostituisci una ventola in uno shelf di dischi NS224
video::29635ff8-ae86-4a48-ab2a-aa86002f3b66[panopto]


.Fasi
. Mettere a terra l'utente.
. Scollegare il cablaggio dal modulo NSM che contiene la FRU che si sta sostituendo:
+
.. Scollegare il cavo di alimentazione dall'alimentatore aprendo il fermo del cavo di alimentazione, se si tratta di un alimentatore CA, oppure svitando le due viti ad alette, se si tratta di un alimentatore CC, quindi scollegare il cavo di alimentazione dall'alimentatore.
+
Gli alimentatori non dispongono di un interruttore di alimentazione.

.. Scollegare il cablaggio dello storage dalle porte del modulo NSM.
+
Prendere nota delle porte del modulo NSM a cui ciascun cavo è collegato. Ricollegare i cavi alle stesse porte quando si reinserisce il modulo NSM, più avanti in questa procedura.



. Rimuovere il modulo NSM dallo shelf:
+
.. Far passare le dita di indice attraverso i fori dei meccanismi di blocco su entrambi i lati del modulo NSM.
+

NOTE: Se si rimuove il modulo NSM inferiore e la guida inferiore impedisce l'accesso ai meccanismi di blocco, posizionare le dita di riferimento attraverso i fori all'interno (incrociando le braccia).

.. Con i pollici, tenere premuti le linguette arancioni sulla parte superiore dei meccanismi di blocco.
+
I meccanismi di chiusura si sollevano, liberando i perni di chiusura sullo scaffale.

.. Tirare delicatamente fino a quando il modulo NSM non si trova a circa un terzo del percorso di uscita dallo scaffale, afferrare i lati del modulo NSM con entrambe le mani per sostenerne il peso, quindi posizionarlo su una superficie piana e stabile.
+
Quando si inizia a tirare, i bracci del meccanismo di chiusura si estendono dal modulo NSM e si bloccano in posizione completamente estesa.



. Allentare la vite ad alette del coperchio del modulo NSM e aprire il coperchio.
+

NOTE: L'etichetta FRU sul coperchio del modulo NSM indica la posizione delle cinque ventole, lungo la parete posteriore del modulo NSM.

. Identificare fisicamente la ventola guasta.
+
In caso di guasto di una ventola, il sistema registra un messaggio di avviso alla console di sistema che indica quale ventola si è guastata.

. Sostituire la ventola guasta:
+
.. Rimuovere la ventola guasta afferrando con decisione i lati, dove si trovano i punti di contatto blu, quindi sollevarla verticalmente per scollegarla dalla presa.
.. Inserire la ventola di ricambio allineandola nelle guide, quindi spingere verso il basso fino a quando il connettore del modulo della ventola non è inserito completamente nella presa.


. Chiudere il coperchio del modulo NSM, quindi serrare la vite ad alette.
. Reinserire il modulo NSM nello shelf:
+
.. Assicurarsi che i bracci del meccanismo di chiusura siano bloccati in posizione completamente estesa.
.. Con entrambe le mani, far scorrere delicatamente il modulo NSM nello shelf fino a quando il peso del modulo NSM non è completamente supportato dallo shelf.
.. Spingere il modulo NSM nello shelf fino a quando non si ferma (circa mezzo pollice dal retro dello shelf).
+
È possibile posizionare i pollici sulle linguette arancioni sulla parte anteriore di ciascun gancio per le dita (dei bracci del meccanismo di chiusura) per inserire il modulo NSM.

.. Far passare le dita di indice attraverso i fori dei meccanismi di blocco su entrambi i lati del modulo NSM.
+

NOTE: Se si inserisce il modulo NSM inferiore e la guida inferiore ostruisce l'accesso ai meccanismi di blocco, posizionare le dita di riferimento attraverso i fori all'interno (incrociando le braccia).

.. Con i pollici, tenere premuti le linguette arancioni sulla parte superiore dei meccanismi di blocco.
.. Spingere delicatamente in avanti i fermi fino al punto di arresto.
.. Rilasciare i pollici dalla parte superiore dei meccanismi di blocco, quindi continuare a spingere fino a quando i meccanismi di blocco non scattano in posizione.
+
Il modulo NSM deve essere inserito completamente nello shelf e a filo con i bordi dello shelf.



. Ricollegare il cablaggio al modulo NSM:
+
.. Ricollegare il cablaggio dello storage alle stesse due porte del modulo NSM.
+
I cavi devono essere inseriti con la linguetta di estrazione del connettore rivolta verso l'alto. Quando un cavo è inserito correttamente, scatta in posizione.

.. Ricollegare il cavo di alimentazione all'alimentatore, quindi fissare il cavo di alimentazione con il relativo fermo, se si tratta di un alimentatore CA, oppure serrare le due viti ad alette, se si tratta di un alimentatore CC, quindi scollegare il cavo di alimentazione dall'alimentatore.
+
Quando funziona correttamente, il LED bicolore di un alimentatore si illumina di verde.

+
Inoltre, entrambi i LED LNK (verde) della porta del modulo NSM si illuminano. Se il LED LNK non si accende, ricollegare il cavo.



. Verificare che i LED di attenzione (ambra) sul modulo NSM contenente la ventola guasta e il pannello del display operatore dello scaffale non siano più accesi.
+
I LED attenzione del modulo NSM si spengono dopo il riavvio del modulo NSM e non rilevano più un problema relativo alla ventola. Questa operazione può richiedere da tre a cinque minuti.

. Verificare che il modulo NSM sia cablato correttamente eseguendo Active IQ Config Advisor.
+
Se vengono generati errori di cablaggio, seguire le azioni correttive fornite.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]


