---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 'Se il supporto di avvio si guasta su uno shelf di dischi NS224 in una coppia ha che esegue ONTAP 9.7 o versione successiva, o se lo shelf sta eseguendo il firmware NVMe shelf module (NSM) versione 1.1x o successiva, è possibile sostituire il supporto di avvio. La sostituzione del supporto di avvio può essere eseguita senza interruzioni, mentre lo shelf del disco è acceso e l"i/o è in corso.' 
---
= Sostituire i supporti di avvio - shelf NS224
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se il supporto di avvio si guasta su uno shelf di dischi NS224 in una coppia ha che esegue ONTAP 9.7 o versione successiva, o se lo shelf sta eseguendo NVMe shelf module (NSM) versione 0111 o successiva, è possibile sostituire il supporto di avvio. La sostituzione del supporto di avvio può essere eseguita senza interruzioni, mentre lo shelf del disco è acceso e l'i/o è in corso.

.Prima di iniziare
* La coppia ha deve già eseguire ONTAP 9.7 o versione successiva, che dispone della versione minima supportata del firmware NSM, oppure la coppia ha deve già eseguire una versione di ONTAP 9.6 con firmware NSM versione 0111 o successiva.
+
È possibile immettere il `storage shelf show -module` Comando sulla console di uno dei controller per verificare la versione del firmware NSM sullo shelf.

+
[NOTE]
====
Se lo shelf non utilizza il firmware NSM versione 0111 o successiva, non è possibile sostituire il supporto di avvio, è necessario sostituire il modulo NSM.

link:service-replace-nsm100.html["Sostituire un modulo NSM - shelf NS224"^]

====
* È necessario un cacciavite Phillips n. 1.
+
La vite utilizzata per fissare il supporto di avvio alla scheda richiede un cacciavite Phillips n. 1; l'utilizzo di un altro tipo di cacciavite potrebbe rimuovere la vite.

* Il modulo NSM del partner dello shelf deve essere attivo e funzionante ed essere cablato correttamente in modo che lo shelf mantenga la connettività quando si rimuove il modulo NSM con la FRU (modulo NSM di destinazione) guasta.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]

* Tutti gli altri componenti del sistema devono funzionare correttamente.


.A proposito di questa attività
* Una volta sostituito il supporto di avvio, l'immagine di avvio dal modulo NSM del partner dello shelf viene automaticamente copiata nel supporto di avvio sostitutivo.
+
Questa operazione può richiedere fino a cinque minuti.

* Attendere almeno 70 secondi tra la rimozione e l'installazione del modulo NVMe shelf (NSM).
+
Ciò consente a ONTAP di elaborare l'evento di rimozione NSM.

* Se necessario, è possibile attivare i LED di posizione (blu) dello shelf per individuare fisicamente lo shelf interessato: `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
Se non si conosce `_shelf_name_` dello shelf interessato, eseguire `storage shelf show` comando.

+
Uno shelf ha tre LED di posizione: Uno sul display operatore e uno su ciascun modulo NSM. I LED di posizione rimangono accesi per 30 minuti. È possibile disattivarle immettendo lo stesso comando, ma utilizzando `off` opzione.

* Dopo aver sostituito il supporto di avvio, è possibile restituire il componente guasto a NetApp come descritto nelle istruzioni RMA fornite con il kit.
+
Per ottenere il numero RMA o ulteriore assistenza per la procedura di sostituzione, contattare il supporto tecnico all'indirizzo https://mysupport.netapp.com/site/global/dashboard["Supporto NetApp"^], 888-463-8277 (Nord America), 00-800-44-638277 (Europa) o +800-800-80-800 (Asia/Pacifico).

* Per sostituire il supporto di avvio, è possibile utilizzare la seguente animazione o i passaggi scritti.
+
.Animazione - sostituire il supporto di avvio in uno shelf di dischi NS224
video::20ed85f9-1f80-4e0e-9219-ab4600070d8a[panopto]


.Fasi
. Assicurarsi che entrambi i moduli NSM nello shelf eseguano la stessa versione del firmware: Versione 0200 o successiva.
. Mettere a terra l'utente.
. Scollegare il cablaggio dal modulo NSM che contiene la FRU che si sta sostituendo:
+
.. Scollegare il cavo di alimentazione dall'alimentatore aprendo il fermo del cavo di alimentazione, se si tratta di un alimentatore CA, oppure svitando le due viti ad alette, se si tratta di un alimentatore CC, quindi scollegare il cavo di alimentazione dall'alimentatore.
+
Gli alimentatori non dispongono di un interruttore di alimentazione.

.. Scollegare il cablaggio dello storage dalle porte del modulo NSM.
+
Prendere nota delle porte del modulo NSM a cui ciascun cavo è collegato. Ricollegare i cavi alle stesse porte quando si reinserisce il modulo NSM, più avanti in questa procedura.



. Rimuovere il modulo NSM dallo shelf:
+
.. Far passare le dita di indice attraverso i fori dei meccanismi di blocco su entrambi i lati del modulo NSM.
+

NOTE: Se si rimuove il modulo NSM inferiore e la guida inferiore impedisce l'accesso ai meccanismi di blocco, posizionare le dita di riferimento attraverso i fori all'interno (incrociando le braccia).

.. Con i pollici, tenere premuti le linguette arancioni sulla parte superiore dei meccanismi di blocco.
+
I meccanismi di chiusura si sollevano, liberando i perni di chiusura sullo scaffale.

.. Tirare delicatamente fino a quando il modulo NSM non si trova a circa un terzo del percorso di uscita dallo scaffale, afferrare i lati del modulo NSM con entrambe le mani per sostenerne il peso, quindi posizionarlo su una superficie piana e stabile.
+
Quando si inizia a tirare, i bracci del meccanismo di chiusura si estendono dal modulo NSM e si bloccano in posizione completamente estesa.



. Allentare la vite ad alette del coperchio del modulo NSM e aprire il coperchio.
. Individuare fisicamente il supporto di avvio guasto.
+
Il supporto di avvio si trova lungo la parete del telaio del ripiano, di fronte all'alimentatore.

. Sostituire il supporto di avvio:
+
.. Utilizzando il cacciavite Phillips n. 1, rimuovere con cautela la vite che fissa l'estremità inferiore (dentellata) del supporto di avvio alla scheda.
.. Rimuovere il supporto di avvio ruotando leggermente l'estremità con tacche verso l'alto, quindi tirarlo delicatamente verso di sé fino a sganciarlo dallo zoccolo.
+
È possibile tenere il supporto di avvio posizionando il pollice e l'indice sui bordi laterali, all'estremità con tacche

.. Estrarre il supporto di avvio dalla confezione antistatica.
.. Inserire il supporto di avvio sostitutivo spingendolo delicatamente nello zoccolo fino a inserirlo completamente nello zoccolo.
+
È possibile tenere il supporto di avvio posizionando il pollice e l'indice sui bordi laterali, all'estremità con tacche Assicurarsi che il lato con il dissipatore di calore sia rivolto verso l'alto.

+
Una volta posizionato correttamente e lasciato andare il supporto di avvio, l'estremità con tacche del supporto di avvio è inclinata verso l'alto, lontano dalla scheda, perché non è ancora fissata con la vite.

.. Tenere delicatamente l'estremità dentellata del supporto di avvio mentre si inserisce e serrare la vite con il cacciavite per fissare il supporto di avvio in posizione.
+

NOTE: Stringere la vite quanto basta per mantenere saldamente in posizione il supporto di avvio, ma non serrarlo eccessivamente.



. Chiudere il coperchio del modulo NSM, quindi serrare la vite ad alette.
. Reinserire il modulo NSM nello shelf:
+
.. Assicurarsi che i bracci del meccanismo di chiusura siano bloccati in posizione completamente estesa.
.. Con entrambe le mani, far scorrere delicatamente il modulo NSM nello shelf fino a quando il peso del modulo NSM non è completamente supportato dallo shelf.
.. Spingere il modulo NSM nello shelf fino a quando non si ferma (circa mezzo pollice dal retro dello shelf).
+
È possibile posizionare i pollici sulle linguette arancioni sulla parte anteriore di ciascun gancio per le dita (dei bracci del meccanismo di chiusura) per inserire il modulo NSM.

.. Far passare le dita di indice attraverso i fori dei meccanismi di blocco su entrambi i lati del modulo NSM.
+

NOTE: Se si inserisce il modulo NSM inferiore e la guida inferiore ostruisce l'accesso ai meccanismi di blocco, posizionare le dita di riferimento attraverso i fori all'interno (incrociando le braccia).

.. Con i pollici, tenere premuti le linguette arancioni sulla parte superiore dei meccanismi di blocco.
.. Spingere delicatamente in avanti i fermi fino al punto di arresto.
.. Rilasciare i pollici dalla parte superiore dei meccanismi di blocco, quindi continuare a spingere fino a quando i meccanismi di blocco non scattano in posizione.
+
Il modulo NSM deve essere inserito completamente nello shelf e a filo con i bordi dello shelf.



. Ricollegare il cablaggio al modulo NSM:
+
.. Ricollegare il cablaggio dello storage alle stesse due porte del modulo NSM.
+
I cavi devono essere inseriti con la linguetta di estrazione del connettore rivolta verso l'alto. Quando un cavo è inserito correttamente, scatta in posizione.

.. Ricollegare il cavo di alimentazione all'alimentatore, quindi fissare il cavo di alimentazione con il relativo fermo, se si tratta di un alimentatore CA, oppure serrare le due viti ad alette, se si tratta di un alimentatore CC.
+
Quando funziona correttamente, il LED bicolore di un alimentatore si illumina di verde.

+
Inoltre, entrambi i LED LNK (verde) della porta del modulo NSM si illuminano. Se il LED LNK non si accende, ricollegare il cavo.



. Verificare che i LED di attenzione (ambra) sul modulo NSM contenente il supporto di avvio guasto e il pannello di visualizzazione operatore dello shelf non siano più accesi.
+
I LED di attenzione possono impiegare da 5 a 10 minuti per spegnersi. Si tratta del tempo necessario al riavvio del modulo NSM e al completamento della copia dell'immagine del supporto di avvio.

+
Se i LED di errore rimangono accesi, il supporto di avvio potrebbe non essere inserito correttamente oppure potrebbe esserci un altro problema e contattare il supporto tecnico per assistenza.

. Verificare che il modulo NSM sia cablato correttamente eseguendo Active IQ Config Advisor.
+
Se vengono generati errori di cablaggio, seguire le azioni correttive fornite.

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Download NetApp: Config Advisor"^]


