---
permalink: a700s/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, aff, a700s, primary, boot, media, store, ontap, image, system, restore, primary, media, secondary, usb, flash, drive, replace, replace the boot media, manual, manual boot recovery 
summary: Scopri come sostituire il supporto di avvio su un sistema AFF A700s e impara i metodi di ripristino. Il sistema AFF A700s supporta solo procedure di ripristino manuale tramite supporti di avvio. Il ripristino automatico del supporto di avvio non è supportato. 
---
= Panoramica della sostituzione dei supporti di avvio - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri come sostituire il supporto di avvio su un sistema AFF A700s e scopri i metodi di ripristino. Il supporto di avvio primario memorizza l'immagine di avvio ONTAP utilizzata dal sistema durante l'avvio. È possibile ripristinare l'immagine del supporto di avvio primario utilizzando l'immagine ONTAP dal supporto di avvio secondario o, se necessario, da un'unità flash USB formattata in FAT32.

Il sistema AFF A700s supporta solo procedure di ripristino manuale tramite supporti di avvio. Il ripristino automatico del supporto di avvio non è supportato.

Se il supporto di avvio secondario non funziona o manca il file image.tgz, è necessario ripristinare il supporto di avvio primario utilizzando un'unità flash USB. Il disco deve essere formattato in FAT32 e disporre della quantità di storage appropriata per contenere il file image_xxx.tgz.

* Il processo di sostituzione ripristina il file system var dal supporto di avvio secondario o dall'unità flash USB al supporto di avvio primario.
* È necessario sostituire il componente guasto con un componente FRU sostitutivo ricevuto dal provider.
* È importante applicare i comandi descritti di seguito al controller corretto:
+
** Il controller _alterato_ è il controller su cui si esegue la manutenzione.
** Il controller _healthy_ è il partner ha del controller compromesso.




Se è necessario sostituire il supporto di avvio secondario mentre il supporto di avvio primario è installato e integro, contattare il supporto NetApp e citare l' https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s["Come sostituire il dispositivo di avvio secondario di un AFF A700s"^] articolo della Knowledge base.
