---
permalink: a700s/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a700s, aff, a700s, completing, complete, nve, nse, shutdown, impair, controller, shut down the controller 
summary: 'Dopo aver completato le attività NVE o NSE, è necessario completare l"arresto del controller compromesso.' 
---
= Spegnere il controller - AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato le attività NVE o NSE, è necessario completare l'arresto del controller compromesso.

.Fasi
. Portare la centralina danneggiata al prompt DEL CARICATORE:
+
[cols="1,2"]
|===
| Se il controller non utilizzato visualizza... | Quindi... 


 a| 
Il prompt DEL CARICATORE
 a| 
Andare a Rimozione del modulo controller.



 a| 
`Waiting for giveback...`
 a| 
Premere Ctrl-C, quindi rispondere `y` quando richiesto.



 a| 
Prompt di sistema o prompt della password (inserire la password di sistema)
 a| 
Assumere il controllo o arrestare il controller compromesso dal controller integro: `storage failover takeover -ofnode impaired_node_name`

Quando il controller non utilizzato visualizza Waiting for giveback... (in attesa di giveback...), premere Ctrl-C e rispondere `y`.

|===
. Dal prompt DEL CARICATORE, immettere: `printenv` per acquisire tutte le variabili ambientali di avvio. Salvare l'output nel file di log.
+

NOTE: Questo comando potrebbe non funzionare se il dispositivo di boot è corrotto o non funzionante.


