---
permalink: a700s/chassis-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, replace the chassis 
summary: Il nuovo telaio dello stesso modello del telaio compromesso viene sostituito da un telaio non valido. 
---
= Panoramica della sostituzione dello chassis - AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per sostituire lo chassis, è necessario spostare i moduli controller e le unità SSD dallo chassis compromesso allo chassis sostitutivo, quindi rimuovere lo chassis compromesso dal rack dell'apparecchiatura o dall'armadietto del sistema e installare lo chassis sostitutivo al suo posto.

Tutti gli altri componenti del sistema devono funzionare correttamente; in caso contrario, contattare il supporto tecnico.

* È possibile utilizzare questa procedura con tutte le versioni di ONTAP supportate dal sistema.
* Questa procedura si basa sul presupposto che si stiano spostando gli SSD e i moduli controller nel nuovo chassis e che lo chassis sostitutivo sia un nuovo componente di NetApp.
* Questa procedura ha un'interruzione. Per un cluster a due nodi, si avrà un'interruzione completa del servizio e un'interruzione parziale in un cluster a più nodi.

