---
permalink: a700s/maintain-overview.html 
sidebar: sidebar 
keywords: a700s maintenance, maintenance, repairing a700s, repairing a700s, replace a700s components, replace a700s components 
summary: 'Manutenzione dell"hardware del AFF A700s' 
---
= Manutenzione dell'hardware AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per il sistema storage AFF A700s, è possibile eseguire le procedure di manutenzione sui seguenti componenti.



== Supporto di boot

Il supporto di avvio memorizza un set primario e secondario di file immagine di avvio che il sistema utilizza al momento dell'avvio.



== Chassis

Lo chassis è l'enclosure fisica in cui sono alloggiati tutti i componenti del controller, ad esempio l'unità controller/CPU, l'alimentatore e i/O.



== Controller

Un controller è costituito da una scheda, firmware e software. Controlla i dischi e implementa le funzioni ONTAP.



== DIMM

È necessario sostituire un modulo DIMM (Dual in-line Memory Module) quando è presente una mancata corrispondenza di memoria o se si verifica un guasto al modulo DIMM.



== Disco

Un disco è un dispositivo che fornisce i supporti di storage fisici per i dati.



== Ventola

La ventola raffredda il controller.



== Batteria NVRAM

Una batteria è inclusa nel controller e fornisce l'alimentazione di backup in caso di interruzione dell'alimentazione CA.



== Modulo NVRAM

Il modulo NVRAM (memoria ad accesso casuale non volatile) conserva i dati memorizzati nella cache in caso di interruzione dell'alimentazione.



== Scheda PCIe

Una scheda PCIe (Peripheral Component Interconnect Express) è una scheda di espansione che si inserisce nello slot PCIe della scheda madre.



== Alimentatore

Un alimentatore fornisce una fonte di alimentazione ridondante in uno shelf di controller.



== Batteria con orologio in tempo reale

Una batteria con orologio in tempo reale conserva le informazioni di data e ora del sistema se l'alimentazione è spenta.
