---
permalink: asa-r2/asa-r2-install-setup.html 
sidebar: sidebar 
keywords: asa r2 a1k, a70, a90, install, setup, initial configuration 
summary: Installare e configurare il sistema. 
---
= Installazione e configurazione dei sistemi ASA R2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Accedere alla https://docs.netapp.com/us-en/asa-r2/index.html["Documentazione dei sistemi ASA R2"^] per informazioni su come installare, utilizzare e gestire il sistema ASA R2.

La https://docs.netapp.com/us-en/asa-r2/index.html["Documentazione dei sistemi ASA R2"^] include informazioni quali:

* Istruzioni per l'installazione e la configurazione
* Istruzioni amministrative per la configurazione del sistema, ad esempio il provisioning dello storage SAN, la clonazione dei dati e il ridimensionamento dello storage locale.
* Istruzioni per la gestione del sistema, tra cui la gestione dell'accesso client, la protezione dei dati e la protezione dei dati.
* Istruzioni per il monitoraggio e la risoluzione dei problemi, comprese informazioni su avvisi, eventi del cluster e registri di sistema.


Le procedure di manutenzione specifiche per ciascun tipo di sistema ASA R2 sono disponibili in link:../asa-r2-landing-maintain/index.html["Sezione di manutenzione dei sistemi ASA R2"].
